### ISSUE TITLE
OwnerReferences must be in the same namespace as object

### ISSUE THREAD

**Issue by calind** [kubernetes-sigs/controller-runtime#100]
https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#OwnerReference
> OwnerReference contains enough information to let you identify an owning object. Currently, an owning object must be in the same namespace, so there is no namespace field

The admission controller secret writer sets the webhook as owner for the generated secret even if they are in different namespaces. I don't know if it's by design but it looks like a bug.
https://github.com/kubernetes-sigs/controller-runtime/blob/5a961ac0b8b06ac0409fd9de027d0ea9ecbc6730/pkg/admission/cert/writer/secret.go#L136-L151

I found it by #99 which enforces a check between owner and object.

**Comment by DirectXMan12** [comment]
cc @mengqiy

**Comment by calind** [comment]
@mengqiy do you see a major issue if we don't set OwnerReferences for the created secrets?

**Comment by mengqiy** [comment]
@calind I just confirmed with sig api machinery people that setting a cluster-scoped object to be the ownerRef for a namespaced object is supported.
https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/types.go#L287-L289 is out-of-date, they will update it shortly.

**Comment by calind** [comment]
Great. I’ll update #99 to take this into account. I guess we can close this now.
