### ISSUE TITLE
event predicates logic optimization

### ISSUE THREAD

**Issue by cuisongliu** [kubernetes-sigs/controller-runtime#1013]
https://github.com/kubernetes-sigs/controller-runtime/blob/4836ec28374c2692ba8e1a21a8840b9becddcd64/pkg/source/internal/eventsource.go#L117

this code design is  “and” logic。  but I think  "or" logic is better?

```golang
       var flag bool
       for _, p := range e.Predicates {
		if p.Create(c) {
			flag = true
                        break
		} 
	}
       
        if flag{
             // Invoke create handler
	     e.EventHandler.Create(c, e.Queue)
        }
```

- all false result  is false;
- has one true result is true

**Comment by cuisongliu** [comment]
/kind/kind feature

**Comment by vincepri** [comment]
Can we rely on the `Or` functionality that we now have in #1043 

/milestone Next
/priority awaiting-more-evidence

**Comment by cuisongliu** [comment]
yes, I want this  logic. thank.
