### ISSUE TITLE
How can I get resource composed by controller like sample-controller?

### ISSUE THREAD

**Issue by dongwangdw** [kubernetes-sigs/controller-runtime#1017]
I am writing an operator, which uses this api. When I try to get resource of an controller, the return value is always empty. The controller is as the form of sample-controller.

Is there anything I missed or should I compose a clientset of the controller to get the resource? Please advise, thanks.

**Comment by vincepri** [comment]
/triage support
/milestone Next
/priority awaiting-more-evidence

Do you have code sample we can look somewhere?

**Comment by dongwangdw** [comment]
https://github.com/IBM/ibm-monitoring-grafana-operator/blob/1.9.2-beta/pkg/controller/grafana/grafana_reconcile.go#L209

The code is here.

The dashboard is our controller which is not public, but as the same structure with sample-controller.
Here when I try to get the resource, but the returned value is empty, I mean when the resource exists.
The return value is supposed to be the dashboard resource. But always empty. So the logic got buggy here.

**Comment by vincepri** [comment]
Does the `Get` call return an error, or is that also empty?

**Comment by vincepri** [comment]
I'd expect if `Get` returns a NotFound or any other error that the code afterwards fails trying to create it

**Comment by dongwangdw** [comment]
when the resource exists, I got a empty with `Get`.
Then we try to create it, error will be raised.

I expect the `Get` can return the existing resource. Does that make sense ?
