### ISSUE TITLE
Default webhook port (443) is problematic for operators running as non-root

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/controller-runtime#1018]
If left unset, the manager [defaults to running the webhook server on port 443](https://github.com/kubernetes-sigs/controller-runtime/blob/add0b6444f5091f56824b070d28f930090d8deab/pkg/webhook/server.go#L39-L40).

Since it is a security best practice to run pods as a non-root user, this default can cause unexpected problems for developers using controller-runtime directly (nonroot users typically can't open listeners on low-numbered ports).

In Kubebuilder, the default `main.go` scaffold hardcodes this value to `9443`, which solves the problem for users of Kubebuilder that scaffolded their project somewhat recently, but all other users are left figuring this out on their own.

I'm wondering if we should change the default value to `9443` to match Kubebuilder's current scaffold configuration? 

**This _would_ be a breaking change.**

**Comment by vincepri** [comment]
+1, we should change the port to 9443 or similar, let's do this in the next milestone. Anyone tackling this issue, you should title your PR as ⚠️, given that's a breaking change and it'll probably need release notes.

/milestone v0.7.x
/priority important-soon
/kind cleanup
/help
/good-first-issue
