### ISSUE TITLE
Provide Custom resource metrics as default.

### ISSUE THREAD

**Issue by bharathi-tenneti** [kubernetes-sigs/controller-runtime#1023]
/kind feature
Description: Currently, `operator-sdk` provides default custom resource info [metrics](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/cmd/manager/main.go#L145), as part of its scaffold. We are looking for options to re-design more generic approach, one that may be achieved from controller-runtime itself. Please see [here](https://github.com/kubernetes-sigs/controller-runtime/compare/master...joelanford:resource-metric?expand=1) , for an idea of the proposed change by @joelanford . This gives possibility of an option to enable some metrics on the informer cache to give us presence metrics  on the primary CR instances.
We are also in process incorporating the same approach in SDK as well, Please see [here](https://github.com/operator-framework/operator-sdk/pull/3436/files) for draft PR.

Motivation:
As of now, operator developers may choose one of the three options outlined in below controller examples,  to get these metrics, using Kubebuilder scaffold.
An example has been hosted [here](https://github.com/bharathi-tenneti/memcached-operator-metrics). 
[Option](https://github.com/bharathi-tenneti/memcached-operator-metrics/blob/master/main.go#L97) 1: Predicate based, where we let the metrics populated by the event handlers on the CRs.
[Option](https://github.com/bharathi-tenneti/memcached-operator-metrics/blob/master/controllers/memcached_controller.go#L84) 2: Let Reconciler set up metrics each time an active Reconcile is called.
[Option](https://github.com/bharathi-tenneti/memcached-operator-metrics/blob/master/controllers/memcached_metrics_controller.go) 3: Same logic as Option 2, using separate reconciler for metrics , and setting up two watches on the CR.

We would like open discussion on controller-runtime approach, for keeping it simple.

/cc @joelanford

**Comment by camilamacedo86** [comment]
IMO it should be a design proposal. E.g https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/component-config.md

**Comment by bharathi-tenneti** [comment]
As per the community discussion, will follow adding wrapper on existing handler from controller-runtime, in our own project.
Closing this issue for now.

**Comment by bharathi-tenneti** [comment]
Closing.
