### ISSUE TITLE
Remove "master" word from our codebase

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-runtime#1028]
- https://github.com/kubernetes-sigs/controller-runtime/blob/add0b6444f5091f56824b070d28f930090d8deab/pkg/client/config/config.go#L43
- https://github.com/kubernetes-sigs/controller-runtime/blob/add0b6444f5091f56824b070d28f930090d8deab/pkg/manager/manager.go#L147
- https://github.com/kubernetes-sigs/controller-runtime/blob/add0b6444f5091f56824b070d28f930090d8deab/pkg/manager/internal.go#L158

/milestone Next
/wg naming

**Comment by fabriziopandini** [comment]
I checked the codebase and it seems everything in this issue is already addressed. Is there something else I should take care of?

**Comment by vincepri** [comment]
/close

This can be closed, the only thing left to do is #1026
