### ISSUE TITLE
Question about scheme comment in CRD example

### ISSUE THREAD

**Issue by eddycharly** [kubernetes-sigs/controller-runtime#1030]
What does the comment below means ?
What should the correct implementation look like ?

https://github.com/kubernetes-sigs/controller-runtime/blob/add0b6444f5091f56824b070d28f930090d8deab/examples/crd/main.go#L114-L115

Thanks.

**Comment by vincepri** [comment]
/triage support
/milestone Next
/priority awaiting-more-evidence

Using Cluster API project as an example, you can create a new custom runtime.Scheme object https://github.com/kubernetes-sigs/cluster-api/blob/7d92339fffd475d39a3ffc168b00f90ad7ad1aba/main.go#L50, and then add all the type you'll be using at runtime like https://github.com/kubernetes-sigs/cluster-api/blob/7d92339fffd475d39a3ffc168b00f90ad7ad1aba/main.go#L76-L81
