### ISSUE TITLE
Add option to disable stack traces for zap logs `--zap-stacktrace-level`

### ISSUE THREAD

**Issue by bharathi-tenneti** [kubernetes-sigs/controller-runtime#1035]
Description:
Allow users to disable stacktraces , using `--zap-stacktrace-level`, when running the operator.

**Comment by vincepri** [comment]
You should be able to register the flag in your controller, like we do for `klog`. I'm not sure if there is anything for controller-runtime to do in this case.

**Comment by camilamacedo86** [comment]
@vincepri it is related to : https://github.com/kubernetes-sigs/controller-runtime/pull/915  after merge this one we would be nice be allowed to disable/enable it.

**Comment by camilamacedo86** [comment]
Hi @vincepri, 

For we  `You should be able to register the flag in your controller, like we do for klog. I'm not sure if there is anything for controller-runtime to do in this case.` the user requires to do the change in the code, Am I right? If yes, I understand that the flag allows disable/enable the logs on the cluster where the project is running without code changes. 

if I am wrong here, I think we can just add an example here how to do your suggestion and then close this one.

**Comment by croomes** [comment]
I had the same issue but I couldn't find a good way to disable stack traces completely.  I checked klog but couldn't find anything relevant.  Allowing the user to set `panic` as the `--zap-stacktrace-level` seems like a simple solution.
