### ISSUE TITLE
Detail standardised fields that can be used in the status block to indicate status uniformly

### ISSUE THREAD

**Issue by philbrookes** [kubernetes-sigs/controller-runtime#1036]
### Problem Statement
When provisioning a product via it’s operator, the most common flow is:
- Install the operator
- Create a CR
- Wait for the product to be ready

Currently, the final step is performed in a unique way for each operator, this could be as low-tech as checking if an end-point is responding correctly, or as automated as watching the status of the CR for something like “Status: Ready”.

### Goal
Define a best-practices format for the status block, which details "recommended fields and values". An operator choosing to use these fields in the recommended manner, will make it simple and uniform for a user of the operator to see what the status of the operand is.

### Non-Goal
Standardising the entire status block for all operators; It is worth noting, that these recommended fields may not be applicable for all operators, and these recommended fields are not a hard requirement for all operators.

### Proposal
Recommend fields to communicate information about the operand service, which can otherwise be quite difficult to locate.

For example:
- The version of the service that is running.
- Whether the service is ready for consumpton.
- What is the operator currently enacting upon the service.

Define a set of fields to help communicate this information in a standardised way:
**version**: This field should be a map of string string, where the first value is service name, and the second is a semver for that service.
**Ready**: This field is likely best to be a condition, and only when the product is fit for use should this value be true and false otherwise.
**Message**: This can be added to the ready condition, and help users to understand why the ready condition is false, and what the operator is currently trying to do, in an effort to bring the service to ready.

### References
I have also discussed this with the operator-sdk team, please find notes from that conversation below:
- https://github.com/operator-framework/operator-sdk/issues/3310

**Comment by matskiv** [comment]
IMHO, having a set of recommended fields would be nice for UI/TUI k8s projects as well.
Values of the recommended fields could be shown in a more user friendly way.

**Comment by merlante** [comment]
It's hard to believe that there is no standard way to get the version of the service that is running or whether the service is ready for consumption. I think we need this.
