### ISSUE TITLE
[Question]What is the difference between the For(), Own() and Watch() in `controller-runtime/builder`?

### ISSUE THREAD

**Issue by Miss-you** [kubernetes-sigs/controller-runtime#1049]
Hi, I'm new to Kubernetes and kubebuilder and these days I'm implementing the APISIX Operator based on the kubebuilder framework.

I went through the interface documentation and the kubebuilder-book and learned that if I want to configure listening to Ingress objects, then I need to do it in the `SetupWithManager` method, e.g. the following code is the default using the For method to listen to `ApisixRoutes` objects (automatically generated by kubebuilder)

```
func (r *ApisixRoutesReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&githubcomv1.ApisixRoutes{}).
		Complete(r).
}
```
I understand that I can use methods such as For() to listen to the desired object, so what is the difference between the For, Own and Watch interfaces in `controller-runtime/builder`?

Taking it one step further, I want to listen to the ingress object and generate the ApisixRoutesReconciler object's data; on the other hand, I also needed to check the If the ApisixRoutesReconciler object has changed, find out if it was previously matched. It's Ingress, for reconciliation. How should it be done?

**Comment by jiachengxu** [comment]
Hi,
If you check the code of For, Owns, and Watch here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L72-L123
`Watch` is the low-level ControllerManagedBy Watches functions through the builder. `Owns` and `For` can be replaced by `Watch` with some enqueue handlers. (Also mentioned in the above link).
For use cases, controller-runtime contains an example_test.go file in almost package to demonstrate use cases, which is supper helpful, please check here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/example_test.go to see the use cases of `For` `Watch` and `Own`.

**Comment by sunnoy** [comment]
> Hi,
> If you check the code of For, Owns, and Watch here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L72-L123
> `Watch` is the low-level ControllerManagedBy Watches functions through the builder. `Owns` and `For` can be replaced by `Watch` with some enqueue handlers. (Also mentioned in the above link).
> For use cases, controller-runtime contains an example_test.go file in almost package to demonstrate use cases, which is supper helpful, please check here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/example_test.go to see the use cases of `For` `Watch` and `Own`.

How to obtain pod resource events and handle them through the handler ？

**Comment by DmitriGekhtman** [comment]
I think the relevant piece of documentation (generated from the code linked above) is
https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/builder#Builder.Owns
