### ISSUE TITLE
Why is a Logger not injected by the Controller Manager?

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/controller-runtime#1056]
Hi there,

Along with the other injector-style interfaces, there is `InjectLogger`, https://github.com/kubernetes-sigs/controller-runtime/blob/57ed2a3ccc943a6a3a07300771326a7e930a9671/pkg/runtime/inject/inject.go#L149-L153

However, the only place this seems to be used is [with respect to webhooks](https://github.com/kubernetes-sigs/controller-runtime/search?q=InjectLogger&unscoped_q=InjectLogger).

Why is `InjectLogger` not part of the `SetFields` function in the Controller Manager so loggers are added to components added to the manager at https://github.com/kubernetes-sigs/controller-runtime/blob/ea795f6400dc064dce43c0aa6a065f47e0633077/pkg/manager/internal.go#L244-L270

**Comment by alvaroaleman** [comment]
Looks like an oversight

**Comment by vincepri** [comment]
/milestone v0.6.x
/kind bug

Can/Should also be backported.

**Comment by jiachengxu** [comment]
Would like to work on this :) 
/assign
