### ISSUE TITLE
[Question] What's the difference between patching vs updating an object's status?

### ISSUE THREAD

**Issue by chardch** [kubernetes-sigs/controller-runtime#1064]
This is a general question. I was running into resourceVersion issues during status updates, similar to this: https://github.com/kubernetes/kubernetes/issues/8625.

I saw patch was mentioned elsewhere as something to get around running into mismatched resourceVersions. However, what's the difference between patching vs updating in regards to the status? Is one suggested over the other (I don't see uses of patching the status anywhere)?

**Comment by coderanger** [comment]
Hi there, this issue tracker is for things like bug reports. If you're looking for user support you can email the mailing list, or ask in either the #kubebuilder or #kubernetes-operators channels on Slack.

**Comment by chardch** [comment]
ok, will ask in the channel

**Comment by vadasambar** [comment]
Link to the question in the slack channel if anyone is interested: https://kubernetes.slack.com/archives/CAR30FCJZ/p1595473693168700

**Comment by lorenzoiuri** [comment]
> Link to the question in the slack channel if anyone is interested: https://kubernetes.slack.com/archives/CAR30FCJZ/p1595473693168700

The channel seems to be private.

**Comment by sbueringer** [comment]
> > Link to the question in the slack channel if anyone is interested: https://kubernetes.slack.com/archives/CAR30FCJZ/p1595473693168700
> 
> The channel seems to be private.

No the linked channel is "kubebuilder" which is not private.
