### ISSUE TITLE
client delete job,but pod not delete

### ISSUE THREAD

**Issue by lovebaby979** [kubernetes-sigs/controller-runtime#1079]
delete job created by ctx, but pod created by job was not deleted.
delete job code:
        getJob := &batchv1.Job{}
	myErr := r.Get(ctx, types.NamespacedName{Namespace: "csf", Name: jobName}, getJob)
	if myErr != nil && !api_errors.IsNotFound(myErr) {
		r.Log.WithValues("Reconcile CsfTemplate get job fail!")
		return false, myErr
	} else if api_errors.IsNotFound(myErr) {
		return  true, nil
	}
	errDel := r.Delete(ctx, getJob)
	if errDel != nil {
		r.Log.Error(errDel, " deleteJob fail! Namespace["+"csf"+"],JobName["+jobName+"]\n", errDel.Error())
	}else{
		r.Log.Info(" deleteJob success! Namespace["+"csf"+"],JobName["+jobName+"]\n")
	}

**Comment by coderanger** [comment]
This is unfortunately a limitation of Kubernetes. The Job object does not own the resulting pod. Kubectl does a secndary clean up for you during `kubectl delete job`.
