### ISSUE TITLE
Manual operations needed with fake client

### ISSUE THREAD

**Issue by cscetbon** [kubernetes-sigs/controller-runtime#1084]
Trying to write unit tests for an operator I get issues when the operator's code expects the status of a StatefulSet to be updated. Instead the fake client does not update it and I get something like below in my StatefulSet status which unfortunately triggers a different branch of my code when it shouldn't. 
```
Replicas = {int32} 0
ReadyReplicas = {int32} 0
CurrentReplicas = {int32} 0
UpdatedReplicas = {int32} 0
```

Similarly, why do I have to also manage the pods underneath instead of the fake client itself ? For now, I have to create the StatefulSets and their pods using different fake client calls. My operator checks that the version of the StatefulSet is identical to what it was before the last reconcile loop, but as I have to manually do things the fake client doesn't (like updating the status) it causes troubles during unit tests.

**Comment by senorhesles** [comment]
Sorry to piggback off of your issue @cscetbon, but looking at the docs [here](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake), it says:
```
 Deprecated: please use pkg/envtest for testing. This package will be dropped before the v1.0.0 release.
```

Is this a mistake? I looked at the pkg/envtest, and...it doesn't seem relevant.

**Comment by alvaroaleman** [comment]
You are expecting the fake client to behave like a real Kubernetes cluster, which is an unrealitic expectation and far above its scope. If you need to test against a real Kubernetes cluster, I recommend kind: https://kind.sigs.k8s.io/

/triage support

**Comment by cscetbon** [comment]
@alvaroaleman im trying to avoid it as much as possible because of the time tests take. What’s the purpose of the fake client then ? You’re talking about a scope, what is it ? Can you elaborate on this ?

**Comment by alvaroaleman** [comment]
As the godoc states, it's scope is limited to do object tracking and some minimal parts of what the kube api does, like increasing `ResourceVersion` on Update operations.

**Comment by cscetbon** [comment]
Okay cause I also looked into envtest which uses an etcd + an api server but are you saying I should still use a k8s cluster ?

**Comment by alvaroaleman** [comment]
@cscetbon if you expect pods to appear after you create a Statefulset then yes, envtest won't be sufficient and you need a real cluster

**Comment by cscetbon** [comment]
Thanks @alvaroaleman. I'll stop using fakeClient for unit tests that involved the creation of k8s objects then. It's a bit frustrating but if that's what it is 🤷‍♂️
