### ISSUE TITLE
Implement a fake RESTMapper for fake client

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-runtime#1110]
After #1109 merges, we'll have a `RESTMapper()` function on client.Client interface that returns the RESTMapper that's used for a given Client. To support the same functionality in the fake client, we'd have to implement a fake rest mapper that's integrated in our fake package. Currently we're returning `nil` https://github.com/kubernetes-sigs/controller-runtime/pull/1109/files#diff-62fbcb10a0dc0bc5b0a1bba07b8eefb0R232-R233

/milestone v0.7.x
/help

**Comment by rahulchheda** [comment]
Is somebody is still working on this issue?

**Comment by rahulchheda** [comment]
@wfernandes Are you currently working on this issue? I would like to work to this too.

**Comment by wfernandes** [comment]
@rahulchheda Go for it. 
/unassign

**Comment by varshaprasad96** [comment]
@vincepri RestMapper is going to map the GroupVersionKinds to Resources passed. Can the [DefaultRestMapper](https://github.com/kubernetes/apimachinery/blob/2456ebdaba229616fab2161a615148884b46644b/pkg/api/meta/restmapper.go#L57) serve this purpose? It would expose the mappings between the types defined in the scheme which is passed while creating the fakeclient.

**Comment by EronWright** [comment]
Note that the fake client now uses `DefaultRestMapper` as suggested above.
https://github.com/kubernetes-sigs/controller-runtime/blob/b88ed7a3602b85b6cfd0acfe9c25033b978bdb83/pkg/client/fake/client.go#L211-L213
