### ISSUE TITLE
it will list all resources when use special label

### ISSUE THREAD

**Issue by tskdsb** [kubernetes-sigs/controller-runtime#1115]
when I use `List(ctx context.Context, list runtime.Object, opts ...ListOption) error` with `client.MatchingLabels(LABEL)`, the LABEL is something like(a normal k-v and a k-v with value==`""`):
```
{
    "key1": "value1",
    "key2": "\"\""
}
```
I will get full list of resources, it seems like the LABEL is empty.

**Comment by alvaroaleman** [comment]
@tskdsb that query gives you items that do not have `"key1": "value1", "key2": ""` in their labels?

**Comment by tskdsb** [comment]
> @tskdsb that query gives you items that do not have `"key1": "value1", "key2": ""` in their labels?

do not have

**Comment by tskdsb** [comment]
version used in go.mod: `sigs.k8s.io/controller-runtime v0.2.2`

**Comment by gaocegege** [comment]
> @tskdsb that query gives you items that do not have `"key1": "value1", "key2": ""` in their labels?

Yeah, we got the items that do not have these two labels.

**Comment by gaocegege** [comment]
To be precise, we got all the items instead of items contains these two labels.

**Comment by vincepri** [comment]
Are you able to update to a later version of controller runtime? v0.2.x series has been deprecated a long time ago

**Comment by alvaroaleman** [comment]
The described behavior looks like https://github.com/kubernetes-sigs/controller-runtime/issues/740 which was fixed in https://github.com/kubernetes-sigs/controller-runtime/pull/882 and is available in 0.5.3+ and 0.6.0+

**Comment by tskdsb** [comment]
thanks @vincepri @alvaroaleman
