### ISSUE TITLE
pkg/webhook: k8s.io/api/admission/v1beta1 is deprecated in v1.19

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/controller-runtime#1123]
See https://github.com/kubernetes/kubernetes/pull/90300. Bumping to v1 is a breaking change.

/cc @vincepri @DirectXMan12

**Comment by estroz** [comment]
v1beta1 `{Mutating,Validating}WebhookConfiguration`s have been deprecated for awhile now (v1.16), see https://github.com/kubernetes/kubernetes/pull/90301. Perhaps it's worth removing support for them as well.

**Comment by alvaroaleman** [comment]
I don't think we can remove support for v1beta1 webhooksconfigurations because the major cloudproviders lack so severly behind in versions. GKE does support 1.16, but its not the default. Not sure about AKS and EKS.

**Comment by estroz** [comment]
Right. I think v1 and v1beta1 can coexist, with v1beta1 types/methods having a `Legacy` suffix. This would still be a breaking change, but probably should be to notify users that webhook defaults are changing and that they should upgrade if possible. Thoughts?

**Comment by alvaroaleman** [comment]
sgtm. Maybe also add a comment telling users the minimum version needed (I believe its v1.16 for v1)

**Comment by vincepri** [comment]
SGTM, let's do it :)

**Comment by adrianludwin** [comment]
Was this fixed by #1284 ?

**Comment by estroz** [comment]
@adrianludwin yes!

/close

**Comment by adrianludwin** [comment]
Thanks!
