### ISSUE TITLE
Leader election is unsafe if the binary isn't stopped when the Manager returns

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/controller-runtime#1132]
With this change: https://github.com/alvaroaleman/controller-runtime/blob/93e6db8d5f04222e42accaa91af027e8bc4ec52b/pkg/manager/internal.go#L647

users can now call releaseOnCancel.  This was previously not the case.  When the leader's context is canceled, the lease will be released.

We call cancel the leader's context here: https://github.com/alvaroaleman/controller-runtime/blob/93e6db8d5f04222e42accaa91af027e8bc4ec52b/pkg/manager/internal.go#L548

If a user doesn't specify a long enough timeout (default 30 seconds) and processes are still running leader election is now invalidated.

We should wait indefinitely if using releaseOnCancel or call os.Exit(1) here when using releaseOnCancel and hit the timeout.

**Comment by DirectXMan12** [comment]
is there any reason not to do a panic instead of `os.Exit(1)`?  That's testable, and while you can technically catch the panic, then you have to be *really* trying to mess things up, and I think it becomes a case of "if you ignore the warning sign *and* wrestle past the giant laser-sharks, it's on you".

**Comment by DirectXMan12** [comment]
could also put an option in the context to explicitly *not* panic if you need to for some reason, to have an extra escape hatch

**Comment by michaelgugino** [comment]
Panic perhaps does seem like a good solution to this problem as well.  Either os.Exit(1) or panic I think is suitable, probably each have their own merits.
