### ISSUE TITLE
how to get all resource by controller-runtime?

### ISSUE THREAD

**Issue by FreeZhang61** [kubernetes-sigs/controller-runtime#1158]
I want to get all resource by controller-runtime just like `kubectl get all  -A` ,  can anyone me a demo?  thanks

**Comment by ncdc** [comment]
I'd do something like this (assuming you have a `Manager`):

```go
restConfig := mgr.GetConfig()

```

**Comment by camilamacedo86** [comment]
Hi @FreeZhang61, 

Shows that what you are looking for is: 

```
// Get a config to talk to the apiserver
	cfg, err := config.GetConfig()
	if err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	// Create the discoveryClient
	discoveryClient, err := discovery.NewDiscoveryClientForConfig(cfg)
	if err != nil {
		log.Error(err, "Unable to create discovery client")
		os.Exit(1)
	}

	discoveryClient.ServerGroupsAndResources()
```

So, I am closing this one as sorted out. However, please feel free to raise a new issue if you still needing help with.
