### ISSUE TITLE
Dependency Failing

### ISSUE THREAD

**Issue by jsing157** [kubernetes-sigs/controller-runtime#1168]
Hello Team, Thank you for all the work you have done! I wish to bring attention to errors I have in my current golang repo: 
```
sigs.k8s.io/controller-runtime@v0.5.0 requires
        gomodules.xyz/jsonpatch/v2@v2.0.1: unrecognized import path "gomodules.xyz/jsonpatch/v2": reading https://gomodules.xyz/jsonpatch/v2?go-get=1: 404 Not Found
```
```
go: sigs.k8s.io/controller-runtime@v0.5.11 requires
	gomodules.xyz/jsonpatch/v2@v2.0.1: unrecognized import path "gomodules.xyz/jsonpatch/v2": reading https://gomodules.xyz/jsonpatch/v2?go-get=1: 404 Not Found
	server response: 404 page not found
```
Regardless of the version, it seems I cannot get jsonpatch. I have noticed `https://gomodules.xyz/` has changed its URL paths so maybe it is something to do with that. 
Various `replace` in go.mod have prove ineffective. Have you experienced any jsonpatch issues on your end?
Thanks!

**Comment by cjhpaul** [comment]
Yeah same here, made a pr #1167 for that. I'm fine with any fix, but hopefully this gets resolved asap.

**Comment by jsing157** [comment]
Try: `export GOPROXY=https://proxy.golang.org` in your go env. It seems to work for my development team.

**Comment by jaypipes** [comment]
https://github.com/gomodules/jsonpatch/issues/28

**Comment by tamalsaha** [comment]
Sorry, looks like I fat fingered `gcloud app deploy --project gomodules` to `gcloud app deploy --project kmodules` and made the problem. Should be fixed now.
