### ISSUE TITLE
Fix thread safety issue in controller-runtime v0.6

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/controller-runtime#1172]
This is a request to fix #1148 in the v0.6 branch by cherry-picking #1155. I tried this out myself in github.com/adrianludwin/controller-runtime v0.6.3-ts-fix and it works perfectly with HNC - in fact, we're patching HNC with that right now (https://github.com/kubernetes-sigs/multi-tenancy/pull/1127) since we don't want to wait for the official fix, but I'd like to get back onto the official `controller-runtime` releases ASAP.

Thanks!

/assign @DirectXMan12

**Comment by adrianludwin** [comment]
Hi, any chance we'll be able to get a fix for this on the v0.6 branch? Thanks!

**Comment by vincepri** [comment]
Feel free to open a PR to cherry pick PR to the `release-0.6` branch

**Comment by adrianludwin** [comment]
Done, PTAL

**Comment by yiqigao217** [comment]
Can this issue be closed with https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.6.4? @adrianludwin

**Comment by adrianludwin** [comment]
Yup! Thanks all.
