### ISSUE TITLE
Builder causes panics when For isn't called

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#1181]
Currently the causes builder panics when `For` isn't called, because it constructs a `Kind` source with a nil `Type` field.  We should detect this in the builder's `doWatch` method and return an actual error instead.

/kind bug
/priority important-longterm
/good-first-issue

**Comment by prafull01** [comment]
The panic happens on the `doController()` function itself before the `doWatch()` is called.
```
func (blder *Builder) doController(r reconcile.Reconciler) error {
	ctrlOptions := blder.ctrlOptions
	if ctrlOptions.Reconciler == nil {
		ctrlOptions.Reconciler = r
	}


	// Retrieve the GVK from the object we're reconciling
	// to prepopulate logger information, and to optionally generate a default name.
	gvk, err := getGvk(blder.forInput.object, blder.mgr.GetScheme())
        ....
}
```
IMO we need to check the reconcile type present in the Build() function itself where we do all types of error checking already.
