### ISSUE TITLE
Builder.For should panic when called twice

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/controller-runtime#1184]
I know that a Controller should just control for a single Resource kind, this is an edgy-case.

With the following said

https://github.com/kubernetes-sigs/controller-runtime/blob/fdc6658a141b99a3fcb733c8a8000f98e6666f48/pkg/builder/controller.go#L65-L68

I'm considering `For` a shorthand for `Watches` that allows multiple inputs

https://github.com/kubernetes-sigs/controller-runtime/blob/fdc6658a141b99a3fcb733c8a8000f98e6666f48/pkg/builder/controller.go#L89-L100

but that's not true, because I got a single `ForInput`

https://github.com/kubernetes-sigs/controller-runtime/blob/fdc6658a141b99a3fcb733c8a8000f98e6666f48/pkg/builder/controller.go#L69-L81

Returning an error would be easier, although breaking the method chaining that is a de-facto standard with the Builder pattern: maybe is better to panic rather than making this non-predictable.

WDYT?

**Comment by dsbrng25b** [comment]
I just ran into the problem that the builder fails if `Builder.For` is not used. See the following example:
https://github.com/dsbrng25b/controller-runtime/commit/766c2441427d0d11012114003dd5faf3a533a21b

I think it would be the best if `Builder.For` would behave in the same way as `Watches` and `Owns` (so define `forInput` as slice `[]ForInput`). This would fix the case when `For` is not used and would make it more predictable if it is used multiple times. Probably in most of the cases using `Builder.For` multiple times does not make sense but I don't think that a user should be stopped of doing that.

**Comment by dsbrng25b** [comment]
Just found #1173 and #1176 which adds en error if For is called multiple times.
But as said before: To me it would make more sense to allow multiple calls to For and not artificially restrict users.

**Comment by vincepri** [comment]
@alvaroaleman What do you think here? I'm ok having it panic given that's definitely a user error

**Comment by alvaroaleman** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/1176 already added an error that is returned on `Build`, that sounds good enough to me? (The error could probably be a bit more helpful and tell what was the pre-existing type and whats the new one, but thats nitpicking)

> But as said before: To me it would make more sense to allow multiple calls to For and not artificially restrict users.

No. There is only one root type per controller. You have `Watches` to watch subordinate types.

**Comment by dsbrng25b** [comment]
Ok, but can we change the builder that it is possible to use it without `For`?
https://github.com/dsbrng25b/controller-runtime/commit/766c2441427d0d11012114003dd5faf3a533a21b
