### ISSUE TITLE
Fix typo in comments of manager.go

### ISSUE THREAD

**Issue by qu1queee** [kubernetes-sigs/controller-runtime#1185]
I was just reading some enhancements around the leader election, and I found a small typo, please see [delta](https://github.com/kubernetes-sigs/controller-runtime/compare/master...qu1queee:qu1queee/fix_typo_comment?expand=1) , wondering if you want me to fix this with a pr @alvaroaleman ?

**Comment by christopherhein** [comment]
I'd say submit the PR @qu1queee the doc bug is still there after about a month.

**Comment by qu1queee** [comment]
@christopherhein will do, thanks

**Comment by camilamacedo86** [comment]
It shows done already. 
So, I am closing this one. However, please feel free to ping if it requires to be re-open.
