### ISSUE TITLE
Healthz logs are not enough

### ISSUE THREAD

**Issue by iammuho** [kubernetes-sigs/controller-runtime#1188]
As a user of the controller-runtime project in a critical application, we have found that if healthz cannot pass, it's just logging as below;

```
{"level":"info","ts":1600177017.8146179,"logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
{"level":"info","ts":1600177027.8145843,"logger":"controller-runtime.healthz","caller":"healthz/healthz.go:128","msg":"healthz check failed","statuses":[{},{}]}
```

And as you can see, this is not enough to understand the error at first. What I have in my mind is to improve logs by reflecting which component is failed.

**Comment by camilamacedo86** [comment]
Hi @iammuho, 

Could you please check if it is not done for the latest release of the project already? Also, could you please let us know how can we reproduce your scenario?
