### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by JoelSpeed** [kubernetes-sigs/controller-runtime#119]
I would like to add prometheus metrics to the controllers I'm building using kubebuilder.

It would be good to have information both from the controller internals themselves as well as from the reconciler loops I'm implementing.

My initial idea is to add a [prometheus metric registry](https://godoc.org/github.com/prometheus/client_golang/prometheus#Registry) to the controller manager that it can use itself and can be used by `reconcil.Reconciler`s to register their own metrics. Then have the controller manager start the metrics server when `Start` is called.

Does this seem reasonable or should people just handle metrics on their own? PR welcome?

**Comment by DirectXMan12** [comment]
PRs definitely welcome.  We already have some metrics that we inherit from the underlying apimachinery, but PRs are definitely welcome to improve this!

/kind feature
