### ISSUE TITLE
cannot easily differentiate between stop proccesing and no-op when returning reconcile.Result

### ISSUE THREAD

**Issue by georgettica** [kubernetes-sigs/controller-runtime#1190]
it seems that for indicating to stop processing (because an operation updated a resource and that triggered another reconcile) cannot be communicated to the controller, can we add a bool for `StopProccesing` so we can handle this case inside the code better?

https://github.com/kubernetes-sigs/controller-runtime/blob/dba75e5c7c5d39c6926307c01e402c0747bdc7ee/pkg/reconcile/reconcile.go#L29

**Comment by dsbrng25b** [comment]
I think that is not the idea. You run the reconcile until all resources are in the desired state. If the resources are in the desired you don't perform an update and thus no further reconcile is triggered.

**Comment by georgettica** [comment]
/remove-lifeycle-stale
Adding more eyes from my team, who have stronger opinions on the subject

**Comment by georgettica** [comment]
After discussion, the signal is for internal operator work.

This way we can signal "skip this step, no-op" and not break the whole loop.

Maybe an intermediary object for it?
This internal paradigm might be useful for other operators

**Comment by camilamacedo86** [comment]
Hi @georgettica, 

If you want to stop the reconcile you can just return null and it will stop and no longer do any operation. 
As @dvob described the idea is that is idempotent which means that it works like a loop until the desired state is achieved. 

Is it make sense? WDYT about we close this one?

**Comment by georgettica** [comment]
I am fine with that. Understood it's not relevant to others and no need for it to upstream so yes
