### ISSUE TITLE
Write a migration guide for 0.7

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#1208]
There is a big chunk of breaking changes in 0.7, we should write a migration guide that enumerates them and has an "if you did this before, you now need to do that" explanation for all of them

**Comment by akutz** [comment]
Chatting with @ncdc, and just noting a few things that have changed:

* Many functions take a Go context
* Removed top-level error log message when a call to `Reconcile` fails
* The Go context that CR passes around now has a Logger that can be extracted

**Comment by alvaroaleman** [comment]
The release notes contain a pretty comprehensive description of the breaking changes, that should hopefully do it: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0
