### ISSUE TITLE
fetch-envtest script should verify integrity of download 

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#1210]
As pointed out in recent meeting, we should be verifying the integrity of downloaded files in the `hack/setup-envtest.sh` script, since it's now going to be used in kubebuilder.  I think we should probably also consider cleaning up that script -- not hardcoding `/tmp`, etc, since it'll be used externally (or having a separate kubebuilder script).

**Comment by DirectXMan12** [comment]
we'll need to also have our cloudbuild scripts over in the kubebuilder repo sign the tarballs and upload the signature

**Comment by camilamacedo86** [comment]
It was requested in the Controller-runtime meeting in order to address security concerns.

**Comment by sbueringer** [comment]
setup-envtest.sh doesn't exist anymore and setup-envtest verifies the hash of the downloaded binaries

/close
