### ISSUE TITLE
Support controller history management via ControllerRevision for the feautres such as rollback and revision change.

### ISSUE THREAD

**Issue by elanv** [kubernetes-sigs/controller-runtime#1221]
Several native k8s controllers such as `DaemonSet` and `StatefulSet` manage its resource revision history via `ControllerRevision`. It would also be useful for custom resources if history management feature could be applied easily. I have implemented history management with `ControllerRevision` in flink-operator for `FlinkCluster` custom resource [(link)](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/master/controllers/history/controller_history.go). History management feature has been ported from `controller_history.go` in kubernetes repository [(link)](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/history/controller_history.go).

The history management code via `ControllerRevison` can be applied to any CR, so I think it woud be nice if it is provided as a utility of controller-runtime. What do you think about this idea?

**Comment by elanv** [comment]
@DirectXMan12 What do you think about this feature?

**Comment by pigletfly** [comment]
can we reopen this issue ?

**Comment by coderanger** [comment]
@pigletfly I don't think there's anything generic we could do. I would recommend building the feature as a library to prove out the API and if it looks useful to a wide enough range of use cases we can look at moving it upstream.

**Comment by pigletfly** [comment]
Agreed.It requires a `RevisionHistoryLimit` in a CRD.Could we add these ControllerRevision related functions in `controllerutil`?

**Comment by elanv** [comment]
Work on this issue is almost done with the Flink operator. 
I think we just need to port the code to controller-runtime.
If you think it's okay, I'll make a PR with the code added to controllerutil.

**Comment by coderanger** [comment]
I don’t think this is broadly applicable enough to land in controllerutil without getting it in the wild first and seeing how people like it. So I would make your own separate library with the related code and let the API evolve a bit there before we consider it for a util module here.
