### ISSUE TITLE
question: getting pod logs and execute command in pod

### ISSUE THREAD

**Issue by phin1x** [kubernetes-sigs/controller-runtime#1229]
Currently the controller-runtime unstructed client does not have support for executing commands in pods or gathering logs from pods.
what is the currently recommended procedure? Should i instantiate a separate kubernetes client and pass it as a client interface to my controllers or is there a better way to do this? personally I don't like to have two different clients in one controller.
is planned to implement this in the controller runtime?

**Comment by coderanger** [comment]
Yep, you need to use client-go directly. There is not particularly much overhead from this other than just having to also learn to use client-go but in terms of memory or CPU it's not a big thing. I can't comment on future plans for c-r's client library but it seems like it's a ways off regardless so probably just use client-go for now.

**Comment by anders-swanson** [comment]
Is there any update or interest in this issue? If you are using the controller-runtime client and want to run a command on a pod, managing two clients adds a certain degree of complexity/cludge to your code.

**Comment by coderanger** [comment]
@anders-swanson Both of these are very rarely used and even then most of those times are incorrect so I would say the update is "we're not worrying about it".
