### ISSUE TITLE
Support for v1 Ingress in envtest

### ISSUE THREAD

**Issue by LCaparelli** [kubernetes-sigs/controller-runtime#1230]
When attempting to make use of `k8s.io/api/networking/v1` Ingresses within `envtest`-based tests I'm running into:

`2020-10-27T18:38:49.428-0300  ERROR  controller  Reconciler error  {"reconcilerGroup": "apps.m88i.io", "reconcilerKind": "Nexus", "controller": "nexus", "name": "nexus3", "namespace": "default", "error": "could not fetch Ingress (default/nexus3): no matches for kind \"Ingress\" in version \"networking.k8s.io/v1\""}`

This log message was taken from an Operator scaffolded with the Go operator-sdk. If I run the tests with `USE_EXISTING_CLUSTER=TRUE` using minikube v1.13.0 I do not run into this issue and all tests complete successfully.

```
╰─ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Are `k8s.io/api/networking/v1` Ingresses currently supported? Am I doing something wrong?

**Comment by coderanger** [comment]
The default build of envtest control plane binaries is from before v1 existed. You can either get a newer build of those (specifically kube-apiserver) or use an external control plane as you noted.

**Comment by LCaparelli** [comment]
Ah, I see @coderanger, thank you very much for the quick reply! Closing the issue :-)
