### ISSUE TITLE
Install and looking for envtest bins in the $GOBIN/ by default

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#1234]
**Description**

Currently, the default path where controller-runtime is looking for the binaries which are required for the env tests is `"/usr/local/kubebuilder/bin"`. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/server.go#L57

This issue is to purpose the idea of:
- Change the default path for $GOBIN/ (e.g $GOBIN/kubectl-1.15.6) 
- Change the scripts to looking for and use the $GOBIN instead of this path. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/hack/setup-envtest.sh

**Motivation**

- Do not require sudo permissions to install the required binaries 
- Simplifies its installation and usage 
- Issue raised in Kubebuilder: https://github.com/kubernetes-sigs/kubebuilder/issues/1732

**Comment by estroz** [comment]
Expanding on this: it would be nice to have
- a set of simple loading rules (like with kubeconfigs)
- a helper to install envtest binaries to one of those locations
- a helper to compare binary versions

**Comment by camilamacedo86** [comment]
We might consider addressing these requirements toghether with https://github.com/kubernetes-sigs/controller-runtime/issues/1300.

**Comment by DirectXMan12** [comment]
I think this is likely to be subsumed by #1488, closing for now
