### ISSUE TITLE
Add ComponentConfig helper alias

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/controller-runtime#1243]
When implementing https://github.com/kubernetes-sigs/kubebuilder/issues/722 I'm noticing that it would help to reduce the amount of dependencies that need to be imported to mutate `main.go` to support scaffolding. 

```golang
// alias.go

import (
         // ... other imports
	cfg "sigs.k8s.io/controller-runtime/pkg/config"
)

var (
         // ... other aliases

  	// ConfigFile returns the cfg.File function for deferred config file loading,
	// this is passed into Options{}.From() to populate the Options fields for
	// the manager.
	ConfigFile = cfg.File
)
```

Ref #895

**Comment by vincepri** [comment]
+1 having the helper, seems it could be useful to reduce the amount of imports
