### ISSUE TITLE
EnvTest: Tests randomly fail with watch error

### ISSUE THREAD

**Issue by kushthedude** [kubernetes-sigs/controller-runtime#1246]
Hello Team,

We are experience a very frequent and irritating error in our operator tests written using Env_Test and Ginkgo. The tests randomly fail with the error 
```sh
2020-11-04T18:11:21.764Z	INFO	controller-runtime.controller	Starting EventSource	{"controller": "federation", "source": "kind source: /, Kind="}
68
2020-11-04T18:11:21.764Z	INFO	controller-runtime.controller	Starting Controller	{"controller": "federation"}
69
2020-11-04T18:11:21.867Z	INFO	controller-runtime.controller	Starting workers	{"controller": "federation", "worker count": 1}
70
2020-11-04T18:11:21.867Z	INFO	controller-runtime.controller	Starting workers	{"controller": "federationgroup", "worker count": 1}
71
W1104 18:11:21.962044   14029 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.Federation ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received
72
W1104 18:11:21.962411   14029 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.FederationGroup ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received
73
W1104 18:11:21.962794   14029 reflector.go:326] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: watch of *v1.FederationTemplate ended with: very short watch: pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Unexpected watch close - watch lasted less than a second and no items received
74
E1104 18:11:21.971143   14029 event.go:272] Unable to write event: 'Post "http://127.0.0.1:34333/api/v1/namespaces/default/events": dial tcp 127.0.0.1:34333: connect: connection refused' (may retry after sleeping)
```

It would be great if there is any fix or workaround for this occasional yet irritating error 😄 .

**Comment by vincepri** [comment]
This seems a problem with a local api-server, not sure if controller runtime can do anything about this. Are you running in a constrained environment?

**Comment by kushthedude** [comment]
> This seems a problem with a local api-server, not sure if controller runtime can do anything about this. Are you running in a constrained environment?

Nope, we are not running the tests in a constrained environment, moreover, the same issue occurs in our CI and the machines of others working on the same project.

**Comment by vincepri** [comment]
Not totally sure, I've seen in the past similar errors when the api server wasn't able to get enough resources on a machine. It seems from the logs that there are connection issues, which usually suggest an overloaded api-server.

Are you using cached clients in your code?

**Comment by kushthedude** [comment]
No, we are not using cached k8sClient. Even this is an error new to us which didn't occur in our past project which was using ginkgo + envtest. Is there any way to debug it that what might be wrong?

**Comment by vincepri** [comment]
Closing this due lack of updates

/close
