### ISSUE TITLE
Rename GetControllerManagerConfiguration to Complete for ComponentConfig

### ISSUE THREAD

**Issue by christopherhein** [kubernetes-sigs/controller-runtime#1252]
I'd like to make a change to `pkg/config/config.go` which will register as a breaking change, when I was implementing the ComponentConfig `DeferredFileLoader` I setup a func called `GetControllerManagerConfiguration()` while this name is factually correct it's quite long and couple be replaced by a simpler sounding name like `Complete()`. 

Links: 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/config/config.go#L36
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L419

Changing this would make the calls:

```golang
newObj, err := loader.Complete()
// error handling
```

If I were to implement this the PR Checks specifically the `go-apidiff` will fail since it's a breaking change. Is there a path around this without adding a new `func Complete()` and supporting both given that this is an alpha feature and it's fully implemented?

Ref #895

**Comment by vincepri** [comment]
This is fine, the go-apidiff bot checks the diff from the last commit, not the last released version. Given that we haven't released v0.7.0 yet, breaking changes are ok for now. Usually though, we'd hold breaking changes to the next minor release

**Comment by christopherhein** [comment]
Thanks @vincepri ! I'm going to rename this and put in a PR to rename that then.
