### ISSUE TITLE
Patch applied but still getting an old version

### ISSUE THREAD

**Issue by cscetbon** [kubernetes-sigs/controller-runtime#1257]
I'm using controller-runtime v0.6.0 from operator-sdk v0.18.0 and I get a weird behavior. You can check the logs at https://pastebin.com/TRLFeCCk
In short, I have a controller that monitors a custom object that I patch. As soon as it gets patched (with no error) I see that my update predicate function gets called. However the new values of the object are still the old values. It doesn't happen 100% of the time but it happens most of the time. Is there a bug in the version I'm using ? Do I need to do something else to prevent something like that from happening ? of course when I try to debug it I get the new values and not the old one as opposed to when it runs in non debug mode.

FYI, this is the type I'm patching https://github.com/Orange-OpenSource/casskop/blob/backup-diagnostic/pkg/apis/db/v1alpha1/backrest.go#L29-L42, where I'm doing it https://github.com/Orange-OpenSource/casskop/blob/backup-diagnostic/pkg/controller/cassandrarestore/status.go#L54-L57 and how I build the patch https://github.com/Orange-OpenSource/casskop/blob/backup-diagnostic/pkg/controller/common/common_controller.go#L44-L53

**Comment by cscetbon** [comment]
@DirectXMan12 any idea ? I’m suck because of that error.

**Comment by cscetbon** [comment]
I stopped building my own patch and use client.MergeFrom instead. I also had to ensure to get the latest version of the object prior of patching it

**Comment by DirectXMan12** [comment]
are you all good here then, or is something still up? (sorry, just saw this issue)

**Comment by cscetbon** [comment]
Yes but if you have an explanation, I would love to read it.

**Comment by foriequal0** [comment]
I have the same issue!

**Comment by coderanger** [comment]
This sounds like its just the async nature of the read cache?
