### ISSUE TITLE
Can't Watch for `apiextensions.CustomResourceDefinition`

### ISSUE THREAD

**Issue by gmrodgers** [kubernetes-sigs/controller-runtime#1262]
Hey folks,

We're using the kubebuilder project which utilises controller-runtime.  We are trying to build a controller that will reconcile on the CRUD of `apiextensions.CustomResourceDefinition`s i.e. if there is a new CRD, then trigger this controller. Explicitly this is not a new CR for a CRD. 

To do so we have added the following to our controller:

```go
func (r *CRDReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&apiextensions.CustomResourceDefinition{}).
		Complete(r)
}
```

When trying to run this, we got the following error:
```
 ERROR   setup   unable to create controller     {"controller": "CRDRelation", "error": "no kind is registered for the type apiextensions.CustomResourceDefinition in scheme \"pkg/runtime/scheme.go:101\""}
```

We were surprised by this as we thought the schema for this would already be present since it is a standard kube resource.
But we added the `apiextensions` to the manager Scheme anyways as follows:

```go
import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
)
...
	_ = apiextensions.AddToScheme(scheme)
```

And got the following error:
```
E1112 10:50:12.399176   28530 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *apiextensions.CustomResourceDefinition: v1.ListOptions is not suitable for converting to "apiextensions.k8s.io/__internal" in scheme "pkg/runtime/scheme.go:101"
```

We have found this issue: https://github.com/operator-framework/operator-sdk/issues/2633 where they also experience the same error.  We agree with https://github.com/operator-framework/operator-sdk/issues/2633#issuecomment-601696813 that metrics does not seem to be the issue here.

Is there any obvious error with what we're doing above?  If not, is there a workaround/fix for this?

Thanks
Glen && @edwardecook

**Comment by alvaroaleman** [comment]
@gmrodgers that is because you are using the internal version of the api: https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions

You must use one of the external versions (https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1 or https://godoc.org/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1).

Closing this issue for now, but feel free to re-open if the above comment doesn't address your issue.
/close
