### ISSUE TITLE
use go-logr context functions

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/controller-runtime#1275]
go-logr 0.3.0 added support for storing and retrieving a logger in a context: https://github.com/go-logr/logr/blob/4fa77cb7175ca349567983fd9cc9fd94462f41fa/logr.go#L197-L222

It would be good to implement https://github.com/kubernetes-sigs/controller-runtime/blob/f3831c24e5e99c242f993fde8aad18047ca47570/pkg/log/log.go#L56-L73 as wrapper around those functions because then code using the controller-runtime methods and code using go-logr directly become interoperable.

As it stands now, the loggers are different because the context keys are different.

**Comment by alvaroaleman** [comment]
Sounds like a good idea
/good-first-issue
