### ISSUE TITLE
webhook for delete verb is broken

### ISSUE THREAD

**Issue by felipeweb** [kubernetes-sigs/controller-runtime#1278]
when I run `kubectl delete -f config/samples/app_v1alpha1_helmrelease.yaml ` I receive response below
               
`Error from server: error when deleting "config/samples/app_v1alpha1_helmrelease.yaml": admission webhook "mhelmrelease.undistro.io" denied the request: there is no content to decode` running on `kind v0.9.0 go1.15.2 linux/amd64` , using `sigs.k8s.io/controller-runtime v0.7.0-alpha.6` and `controller-gen v0.4.1` with `CRD v1`

**Comment by klzsysy** [comment]
same here

- v1.19.2-1008
- kubebuilder@2.3.1
- controller-gen@v0.4.1

go.mod:

```
	k8s.io/apimachinery v0.18.6
	k8s.io/client-go v0.18.6
	k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29 // indirect
	sigs.k8s.io/controller-runtime v0.6.3
	sigs.k8s.io/controller-tools v0.4.1 // indirect
	sigs.k8s.io/structured-merge-diff v1.0.1-0.20191108220359-b1b620dd3f06 // indirect
```


`Error from server: admission webhook "mmodule.kb.io" denied the request: there is no content to decode`

**Comment by christopherhein** [comment]
Did you all work around this? It seems like it's just that the decoder package only looks at `req.Object` not `req.OldObject` as is present with admission deletes.

**Comment by grzesuav** [comment]
I hit that recently and needed to navigate to solution - use `DecodeRaw` method and passing just `oldObject`
