### ISSUE TITLE
Export the certwatcher package

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/controller-runtime#1292]
Consumers might want to react to externally-managed + rotated certificates, and the certwatcher package handles this, but it is an internal package. Could we consider exporting it?

**Comment by christopherhein** [comment]
@vincepri is this something controller-runtime would be interested in?

**Comment by vincepri** [comment]
The code was originally proposed by @bison in https://github.com/kubernetes-sigs/controller-runtime/commit/2d952ac877fcb86923cb38a7925ed872cade374c — I don't see anything in there that particularly worries me to expose it as non-internal package.

@alvaroaleman @DirectXMan12 thoughts?

**Comment by alvaroaleman** [comment]
yeah sgtm (looking at the code makes me want to replace the mutex with a RW mutex though).

**Comment by christopherhein** [comment]
Awesome, I was thinking this would be nice to be able to use this with the `Runnable` interfaces in the manager you could configure reloading like we have with internal webhooks.
