### ISSUE TITLE
How to watch a custom object outside the controller

### ISSUE THREAD

**Issue by 27149chen** [kubernetes-sigs/controller-runtime#1296]
Sometimes we need to wait for a certain situation of a object in a funciton/request/stream, we can use a watcher for k8s native objects, but it is hard for a custom object since it requires a client, with the help of controller-runtime, is it possible to watch a custom object changes from lcoal cache?

**Comment by jay-rob** [comment]
Is the object in question referring to a CRD or aggregated API resource?

**Comment by 27149chen** [comment]
@jay-rob  a CRD

**Comment by jay-rob** [comment]
So to make sure I understand your usecase, you want to Watch a CRD managed resource without needing the go types? Are you using Go for the client code?

**Comment by 27149chen** [comment]
@jay-rob , I think you misunderstand my words, what I want is watching an crd object in a normal function, just like a watcher which implementing:
```
import (
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
)

type Watcher interface {
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}
```

**Comment by 27149chen** [comment]
@jay-rob , do you understand my usecase now?

**Comment by jay-rob** [comment]
@27149chen 

https://github.com/kubernetes-sigs/controller-runtime/blob/cf7ac887d082b481ec1389ddcd576f4140b15595/pkg/source/source.go#L45

May be what you are looking for. A reconciler with a `predicate` to filter down the criteria in which `reconcile` is called only when the object meets your desired criteria.

[More on predicates](https://github.com/kubernetes-sigs/controller-runtime/blob/cf7ac887d082b481ec1389ddcd576f4140b15595/pkg/predicate/predicate.go#L54)
[Example of a reconciler using a predicate filter](https://github.com/kubernetes-sigs/controller-runtime/blob/cf7ac887d082b481ec1389ddcd576f4140b15595/pkg/builder/example_test.go#L38)

**Comment by 27149chen** [comment]
@jay-rob 

Suppose I need to create a pod inside my function, and return it when the pod is running.
If I understand correctly, to watch the single pod, I need a seprated manager, add the pod (filtered by predicates), and register my wait logic as a reconciler, and then start the manage. Then before the function returns, I also need to stop the manager. Am I right? is it too complex?

**Comment by jay-rob** [comment]
You can use the same manager. Also checkout kubebuilder-declarative. [These libraries might be closer to what you are looking for](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/b731a62175207a3d8343d318e72ddc13896bcb3f/pkg/patterns/declarative/watch.go#L41)

**Comment by camilamacedo86** [comment]
Hi @27149chen, 

So, you are looking for how to watch a CRD that is not managed by the controller. See that the watch func has an attribute for you to set if the Kind is or not managed by the controller. Then, the implementation looks like the same you just need to inform this arg like as: 
```go
	// controller is a controller.controller
	err := c.Watch(
		&source.Kind{Type: &appsv1.ReplicaSet{}},
		&handler.EnqueueRequestForOwner{
			OwnerType:    &appsv1.Deployment{},
			IsController: false, // See here that we are setting it as false. 
		},
	)
	if err != nil {
		// handle it
	}
```

For further information see the controller-runtime docs https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.7.0/pkg/handler#EnqueueRequestForOwner. 

I am closing this one as sorted out. However, please feel free to ping us to re-open if you think that it is required or to raise new issues as well.

**Comment by 27149chen** [comment]
Hi, @camilamacedo86 ,

Thank you for your reply, that really helps.

Since I can not find a good example for watching a single object, I write one myself.
Here is part of the snippet, please point out if it is the right way, thank you very much.
Please note that I did not put my main logic to Reconciler, I wonder if it is a good practice here.

```
type ActionFunc func(obj runtime.Object) (done bool, err error)

func WatchObject(ctx context.Context, ns, name string, mgr manager.Manager, action ActionFunc) error {
	watchCtx, cancelFunc := context.WithCancel(ctx)
	defer cancelFunc()

	c, err := controller.NewUnmanaged(name, mgr, controller.Options{Reconciler: &noopReconciler{}})
	if err != nil {
		return err
	}

	err = c.Watch(
		&source.Kind{Type: &corev1.Pod{}},
		&ActionForObject{Action: action, Done: cancelFunc},
		singleObjectPredicate{Namespace: ns, Name: name},
	)

	if err != nil {
		return err
	}

	go func() {
		if err := c.Start(watchCtx.Done()); err != nil {
			logger.WithError(err).Error("Failed to start watcher")
		}
		cancelFunc()
	}()

	<-watchCtx.Done()

	return nil
}

type ActionForObject struct {
	Action ActionFunc
	Done   func()
	Logger *logrus.Entry
}

func (e *ActionForObject) Create(evt event.CreateEvent, _ workqueue.RateLimitingInterface) {
	if evt.Meta == nil {
		return
	}
	done, err := e.Action(evt.Object)
	if err != nil || done {
		e.Done()
	}
}

func (e *ActionForObject) Update(evt event.UpdateEvent, q workqueue.RateLimitingInterface) {
	if evt.MetaNew == nil {
		return
	}
	done, err := e.Action(evt.ObjectNew)
	if err != nil || done {
		e.Done()
	}
}

func (e *ActionForObject) Delete(evt event.DeleteEvent, q workqueue.RateLimitingInterface) {
	if evt.Meta == nil {
		return
	}
	_, _ = e.Action(evt.Object)
	e.Done()
}

func (e *ActionForObject) Generic(evt event.GenericEvent, q workqueue.RateLimitingInterface) {}
```

**Comment by 27149chen** [comment]
please reopen this issue, I want to continue this discussion. Thanks.

**Comment by mtrbpr** [comment]
> So to make sure I understand your usecase, you want to Watch a CRD managed resource without needing the go types? Are you using Go for the client code?

That's my usecase. I'm using Go for the client code. is there a way to achieve this?
I connot import the external library containing the external type because it would break my go dependencies.

**Comment by h-abinaya28** [comment]
Hi @27149chen : I have a similar use case where I need to watch the status if an object and create new CRs based on that. Does your logic implement that? And could you perhaps provide an example to how and where you would call the Watch function?
