### ISSUE TITLE
Configurable annotation change predicate

### ISSUE THREAD

**Issue by hiddeco** [kubernetes-sigs/controller-runtime#1301]
In `v0.7.0` a `AnnotationChangedPredicate` was introduced that skips update events that have no change in the object's annotation. In the [Flux project](https://github.com/fluxcd) controllers we are making use of _specific_ annotations to trigger reconciliations per user's request to re-observe state, a pattern that I have seen other controllers use as well.

Hereby polling interest for a predicate that would accept a configurable string slice of annotations, and only skip update events if none of the given annotations have a change in values.

**Comment by alvaroaleman** [comment]
Any good reason to not simply use [`predicate.Funcs`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/predicate#Funcs.Update)?

I don't think we should be adding a `Predicate` implementation for each possible way an object can change.

**Comment by coderanger** [comment]
Going to close this out from lack of uptake. If someone wants to tackle a bigger library of reusable predicates, that can also be its own Go package :)

/close
