### ISSUE TITLE
Support for pod bind sub resource

### ISSUE THREAD

**Issue by hrishin** [kubernetes-sigs/controller-runtime#1305]
### Feature Request

**Describe the problem you need a feature to resolve.**
It appears like controller-runtime client don't have any support for creating the `Pod` `Binding` sub-resource. If that is the case how can I confirm? Consider it as a feature request

I'm sorry to say, however, I couldn't found anything for the `Binding` sub-resource.

**Comment by coderanger** [comment]
Only the standardized subresources for custom resources would be easy to support, and of those only /status is so far. I would recommend using client-go for these requests. From-scratch schedulers are a very niche thing, so not really a priority in a controller support library, even if they are technically a kind of controller.

**Comment by alvaroaleman** [comment]
The canonical issue for the problem of arbitrary CRUD subresources is https://github.com/kubernetes-sigs/controller-runtime/issues/1305

/close

**Comment by hrishin** [comment]
@alvaroaleman did you mean some other issue than #1305 ?

**Comment by alvaroaleman** [comment]
@hrishin err yes, sorry, I meant https://github.com/kubernetes-sigs/controller-runtime/issues/452
