### ISSUE TITLE
A handler for controller is required to do something in a regular cycle.

### ISSUE THREAD

**Issue by shyung** [kubernetes-sigs/controller-runtime#1308]
For example, it is assumed that there is a controller for crd named 'Foo' with phase in its Status. After manager started, 'Foo' will be reconciled on CREATE/UPDATE/DELETE operation on it. It is expected for me, however, that the number of 'Foo's in each phase need to be counted in a regular cycle rather than counted in one reconcile for some 'Foo'. And another controller for crd named 'Bar' may be also need such a handler to do something else in a regular cycle.

**Comment by coderanger** [comment]
You will need to write the code for this yourself, check all the objects, write some kind of locking, etc. There's no specific support for special singleton objects.

**Comment by shyung** [comment]
> You will need to write the code for this yourself, check all the objects, write some kind of locking, etc. There's no specific support for special singleton objects.

As far as I am concerned, however, there is no place for the code. Actually, I want to register a handler for controller, which will execute in a regular cycle and its period is also supported to be configured. Specifically, the handler will start to execute in Start Function of Controller Interface as followed.

> // Controller implements a Kubernetes API.  A Controller manages a work queue fed reconcile.Requests
> // from source.Sources.  Work is performed through the reconcile.Reconciler for each enqueued item.
> // Work typically is reads and writes Kubernetes objects to make the system state match the state specified
> // in the object Spec.
> type Controller interface {
> 	// Reconciler is called to reconcile an object by Namespace/Name
> 	reconcile.Reconciler
> 
> 	// Watch takes events provided by a Source and uses the EventHandler to
> 	// enqueue reconcile.Requests in response to the events.
> 	//
> 	// Watch may be provided one or more Predicates to filter events before
> 	// they are given to the EventHandler.  Events will be passed to the
> 	// EventHandler if all provided Predicates evaluate to true.
> 	Watch(src source.Source, eventhandler handler.EventHandler, predicates ...predicate.Predicate) error
> 
> 	// Start starts the controller.  Start blocks until the context is closed or a
> 	// controller has an error starting.
> 	Start(ctx context.Context) error
> 
> 	// GetLogger returns this controller logger prefilled with basic information.
> 	GetLogger() logr.Logger
> }
