### ISSUE TITLE
Can not pass value to Predicates

### ISSUE THREAD

**Issue by zackzhangkai** [kubernetes-sigs/controller-runtime#1310]
When use Predicates, it will failed with "Cannot assign value to unexported field 'predicates' "

Such as I defined below. I will pass a value to the predicates.
```bash
//pkg/controller/application/application_controller.go
var pp []predicate.Funcs
var p = builder.Predicates{[]predicate.Predicate{pp}}
```

predicates is defined as below:

```bash
// vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go:55
// Predicates filters events before enqueuing the keys.
type Predicates struct {
	predicates []predicate.Predicate
}
```

I think it is a bug. May be should be as follows:

```bash
// vendor/sigs.k8s.io/controller-runtime/pkg/builder/options.go:55
// Predicates filters events before enqueuing the keys.
type Predicates struct {
	Predicates []predicate.Predicate  # should be Upper
}
```

**Comment by coderanger** [comment]
What is your end goal? Per-source predicates in the builder syntax are declared like this: `.Owns(whatever, builder.WithPredicates(myPredicate))`

**Comment by zackzhangkai** [comment]
@coderanger Thanks a lot. You are right. It solved my problem as what you said.
