### ISSUE TITLE
Client retrieved from controller-runtime NewManager seems to be missing updates

### ISSUE THREAD

**Issue by tmjd** [kubernetes-sigs/controller-runtime#1316]
In testing the tigera/operator, I have found that sometimes controllers in this operator are not tiggered when a particular resource is added. The controllers should be triggered because they have watches (this is wrong, see comment below for update) for the resource. One detail to be aware of is that the watched resources are backed by an aggregated API server and the server starts after the operator controllers start.
This could be an issue in the watch code or the client cache code but I have found that if I don't use the cache in the client by setting the `NewClient` (as done [here](https://github.com/tigera/operator/pull/1049)) then I do not see this error so makes me think it is due to the default client read caching.

If there is something I should try or look into please let me know. I hope there isn't a similar issue but didn't find one when I looked.

**Comment by tmjd** [comment]
I was looking again today and was wrong about the resources being watched. The controllers do not watch the resource but instead do a Get for the resource with a requeue delay of 10 seconds (and no error so the requeue is never dropped). With that info it is definitely not a watch issue.

**Comment by Brian-McM** [comment]
/reopen

Can somebody respond to this issue please? This stops us from upgrading our libraries to the latest k8s versions.

**Comment by sbueringer** [comment]
@Brian-McM Can you open a new issue, describe your problem there and ideally a way to reproduce it (otherwise it could be hard for us to investigate). I would prefer not re-opening an issue from 2 years ago.
