### ISSUE TITLE
Inconsistent return value of client.create for object status between 0.7.0-alpha.4 and 0.7.0

### ISSUE THREAD

**Issue by vishnukarthikl** [kubernetes-sigs/controller-runtime#1319]
In 0.7.0-alpha.4
Calling client.create of an object (e.g. Deployment) with status set preserves the status in the original object passed.

In 0.7.0
Calling client.create of an object (e.g. Deployment) with some status set removes the status of the original object passed. But if a Custom Resource object is passed, the status is preserved in the original object. This seems inconsistent either it should preserve original status for both kinds of objects or update the status from the k8s API.

```
cl, err := client.New(config.GetConfigOrDie(), client.Options{})
if err != nil {
	fmt.Println("failed to create client")
	os.Exit(1)
}

d := appsv1.Deployment{
	ObjectMeta: metav1.ObjectMeta{
		Name:      "test",
		Namespace: "default",
	},
	Spec: appsv1.DeploymentSpec{
		Selector: &metav1.LabelSelector{
			MatchLabels: map[string]string{
				"app": "test",
			},
		},
		Template: corev1.PodTemplateSpec{
			ObjectMeta: metav1.ObjectMeta{
				Labels: map[string]string{
					"app": "test",
				},
			},
			Spec: corev1.PodSpec{
				Containers: []corev1.Container{{Name: "test", Image: "test"}},
			},
		},
	},
	Status: appsv1.DeploymentStatus{
		Conditions: []appsv1.DeploymentCondition{
			{
				Type:   appsv1.DeploymentProgressing,
				Status: corev1.ConditionTrue,
			},
		},
	},
}
fmt.Println(d.Status.Conditions)
if err = cl.Create(context.Background(), &d, &client.CreateOptions{}); err != nil {
	log.Fatalf("Unable to create: %v", err)
}
fmt.Println(d.Status.Conditions)
```

Output in 0.7.0
```
[{Progressing True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]
[]
```

Output in 0.7.0-alpha.4
```
[{Progressing True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]
[{Progressing True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }]
```

In 0.7.0, the passed object's status is reset. 

I would like to understand if this change was intended or not. Also note that for CR objects the behavior is same for 0.7.0-alpha.4 and 0.7.0

**Comment by mattysweeps** [comment]
/remove-lifecycle stale

We're looking for an answer if this is intentional or not.
