### ISSUE TITLE
Cached client doesn't support Get for cluster scoped resources if namespace is given

### ISSUE THREAD

**Issue by jmrodri** [kubernetes-sigs/controller-runtime#1323]
cached client `Get` returns not found when looking for cluster-scoped object and passing in a namespace.
client.Get should ignore the namespace for cluster scoped objects and return the object. Logging a
warning is probably a good idea that we are ignoring the namespace.

The APIReader ignores the namespace for cluster-scoped gets. The cache should behave similarly.

**Comment by joelanford** [comment]
This may be related to https://github.com/kubernetes-sigs/controller-runtime/issues/934.
