### ISSUE TITLE
MatchingFields - field label not supported: spec.Name

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/controller-runtime#1342]
Hey there,
We have crds with a spec:
Name string
Value string

When I try get a list with MatchingFields filter I'm getting this error - 
```
field label not supported: spec.Name
```

Is there anything extra needs to get done to make this work?

I use this client to connect to k8s - sigs.k8s.io/controller-runtime/pkg/client

**Comment by coderanger** [comment]
Fields always need an index created ahead of time before you can query on them. Did you create an index named `spec.Name`?

**Comment by kotyara85** [comment]
@codenrhoden No, I didn't. This query is not a part of controller.

**Comment by coderanger** [comment]
You still need to define an indexer, regardless of what you're using the client for. https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup has details on the process.

**Comment by kotyara85** [comment]
Yes, I added a new indexer to the field

```
		if err := mgr.GetFieldIndexer().IndexField(context.TODO(), &apiv1.Test{}, "spec.Name", func(rawObj runtime.Object) []string {
			test := rawObj.(*apiv1.Test)
			if test == nil {
				return nil
			}
			return []string{test.Spec.Name}
		}); err != nil {
			return err
		}
```

kubectl still returns this error - ```that match label selector "", field selector "spec.Name=www": field label not supported: spec.Name```

**Comment by coderanger** [comment]
Are you using kubectl or the controller-runtime client library?

**Comment by kotyara85** [comment]
@coderanger controller-runtime
