### ISSUE TITLE
Defaulter interface does not allow rejection, contrary to K8s

### ISSUE THREAD

**Issue by michael-db** [kubernetes-sigs/controller-runtime#1344]
"Mutating webhooks may choose to reject an object, similarly to a validating webhook." This capacity is not respected by the controller-runtime code, which imposes its own restrictions in not allowing Default() to complain. To fix this, Default() must return error.

Sample problem scenario: A mutating admission controller may fail to set a default for any one of several reasons. It has no way to report the error. A validating admission controller could return an error for the missing default value, but the reason the Defaulter failed to set it is unknown to it.

(The workaround I expect to make, unless I abandon this code generation approach, is to hack the reason into the object so the validator can extract it.)

**Comment by coderanger** [comment]
This is an intentional choice to keep the high-level interface simple. Drop down to the lower-level webhook API if you want to do fancy stuff.

/close

**Comment by michael-db** [comment]
As stated in the description, according to the documentation, "Mutating webhooks may choose to reject an object, similarly to a validating webhook." You can claim that the documentation is wrong instead of the functionality, but you cannot claim that there is nothing to fix.
https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go

/reopen

**Comment by coderanger** [comment]
There is a difference between the high-level `Default()` interface and mutating webhooks in general. You can write a low-level hook server implementation yourself which can send back any admission response it wants. See my https://github.com/coderanger/migrations-operator/blob/main/webhook/webhook.go for an example.

**Comment by michael-db** [comment]
Thank you for the pointer. In my own code I worked around it as mentioned. I still think that this is something that should be fixed: preventing a mutating webhook from returning an error doesn't really make the interface simpler, so the reason for not aligning with the expectation is not at all compelling. However, if you want to close it go ahead - at least your link will be useful to anyone else who finds this issue.

**Comment by coderanger** [comment]
/close

As I said, the high-level interfaces are intentionally kept very simple and do not cover all use cases. Notably you also can't use them with out-of-package types at all. The goal is to make the simple use cases _very_ simple not replace the actual admission webhook API.
