### ISSUE TITLE
Does it have cache when first update and then read it immediately

### ISSUE THREAD

**Issue by mjaow** [kubernetes-sigs/controller-runtime#1349]
When I'm trying to update the deployment

```
import "sigs.k8s.io/controller-runtime/pkg/client"
client client.Client
client.Update(context, deployment)
```
then I read it immediately , to check if deployment is ready, if not, requeue with several secs

```
d := &v1.Deployment{}
client.Get(ctx, nsName, d)
```
I found the annotation "deployment.kubernetes.io/revision" is not changed. It seems a stale state. As it's stale, I cannot find the right replicasSets with latest revision.

But when I try to use kubectl to see the revision of deployment, it's updated to latest

Does anyone know how it happened? Is it cache problem of client?

**Comment by coderanger** [comment]
There is indeed a delay due to the informer cache. You can either use an uncached client or just look at the post-Update object directly.

**Comment by mjaow** [comment]
@coderanger  do you know how to look at the post-update object?
