### ISSUE TITLE
context.TODO() in the example

### ISSUE THREAD

**Issue by shaikatz** [kubernetes-sigs/controller-runtime#1353]
https://github.com/kubernetes-sigs/controller-runtime/blob/5c2b42d0dfe264fe1a187dcb11f384c0d193c042/examples/builtins/controller.go#L45

Hi, why do we use `context.TODO()` instead of using the function's `ctx`?
Looks like it's a leftover from before the `Reconcile` function received a context.

**Comment by rashmigottipati** [comment]
It does look like the PR that added context w/ logger to Reconciler interface missed switching to using the function's ctx, so it has leftover from the previous Reconcile function.
