### ISSUE TITLE
Failure to create node resources with envtest

### ISSUE THREAD

**Issue by codeblooded** [kubernetes-sigs/controller-runtime#1360]
I know that envtest does not emulate real nodes, but can we create a node resource? I'm trying to test some logic of a controller that is dependent on the status of nodes with specific labels. I attempt to create nodes, like-so:

```go
var pools = map[string]int{
	"drivers":   3,
	"workers-a": 5,
	"workers-b": 7,
}

var nodes []*corev1.Node

for pool, count := range pools {
    for i := 0; i < count; i++ {
        nodes = append(nodes, &corev1.Node{
            ObjectMeta: metav1.ObjectMeta{
                Name: fmt.Sprintf("node-%s-%d", pool, i),
                Labels: map[string]string{
                    "pool": pool,
                },
            },
        })
    }
}

for _, node := range nodes {
	Expect(k8sClient.Create(context.Background(), node)).To(Succeed())
}
```

The assertion fails with the following error:

```
  Expected success, but got an error:
      <*errors.StatusError | 0xc0002d8140>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "resourceVersion should not be set on objects to be created",
              Reason: "",
              Details: nil,
              Code: 500,
          },
      }
      resourceVersion should not be set on objects to be created
```

I would expect to be able to create a node like any other resource. Am I missing something?

---

Version:

sigs.k8s.io/controller-runtime v0.5.0 h1:CbqIy5fbUX+4E9bpnBFd204YAzRYlM9SWW77BbrcDQo=
sigs.k8s.io/controller-runtime v0.5.0/go.mod h1:REiJzC7Y00U+2YkMbT8wxgrsX5USpXKGhb2sCtAXiT8=

**Comment by coderanger** [comment]
Are you sure you aren't populating `nodes` once and then using it multiple times? `Create()` puts the returned object data back into the pointer its given so you can't call it twice on the same object. If you change that to `k8sClient.Create(context.Background(), node.DeepCopy())` it will likely work.

**Comment by codeblooded** [comment]
@coderanger That makes sense. That was an id10t error on my part. Apparently somewhere else in the test suite identical nodes were created. Totally missed that. Apologies.
