### ISSUE TITLE
Start Envtest processes in parallel

### ISSUE THREAD

**Issue by crew-helper** [kubernetes-sigs/controller-runtime#1363]
Hi.

We use envtest to write integration tests and it looks great, very easy, and fast to start!
Though our resource takes considerable time to start as it waits for the external providers and update/create may take around 10 minutes. So with growing amount of tests we'll end up in long running time for the integration tests.

I sought ways to parallize this and as with ginkgo this looks quite simple as just `ginkgo -p` makes all the parallelization though this results in `BeforeSuite` run in parallel and envtest fails as apiServers don't start. I thought about setting the different ports for ApiServer and different data directories for etcd but the `ControlPlane` struct is in `controller-runtime/pkg/internal/testing/integration` so it's not available from external code. 

Questions: is it possible to start envtest environments in parallel? If not - is it something planned to be done?

thanks!

**Comment by nilsherzig** [comment]
Hi @crew-helper I'm stuck at the exact same spot you're describing, did you find a solution for this problem?
