### ISSUE TITLE
move certwatcher to k8s.io/utils?

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/controller-runtime#1370]
`certwatcher` looks useful for my use-case but I'm thinking it might be better to be used from `k8s.io/utils`. WDYT if I move it?

**Comment by alvaroaleman** [comment]
I think that is more of a question for the k8s.io/utils maintainers than for contorller-runtime?

**Comment by mythi** [comment]
@alvaroaleman I can check that too. The repo has acceptance criteria defined too so `certwatcher` would first need to be made compliant...

**Comment by mythi** [comment]
other plans came up

**Comment by miparnisari** [comment]
+1 for it to get moved 😄 

Our Go package imports `sigs.k8s.io/controller-runtime` purely because of `certwatcher` and `log`. According to https://github.com/Bevisy/goweight this is costing us 27 MB in the final binary.

**Comment by alvaroaleman** [comment]
> I think that is more of a question for the k8s.io/utils maintainers than for contorller-runtime?

This point still stands, the issue is in the wrong project.  Feel free to get in touch with the k8s.io/utils maintainers and request them to add this functionality.

**Comment by miparnisari** [comment]
Thanks @alvaroaleman. Opened https://github.com/kubernetes/utils/issues/327
