### ISSUE TITLE
Field selector filtering in fake client

### ISSUE THREAD

**Issue by imilchev** [kubernetes-sigs/controller-runtime#1376]
I am also interested in this and is quite annoying for me that I cannot even inject custom behaviour in the fake client. I am willing to work on adding this feature if someone has any suggestions how to incorporate it. I saw how the kubernetes API implements this [here](https://github.com/kubernetes/kubernetes/blob/d0439d417b0563d44c65b6e400e2070964dea7d1/pkg/registry/core/pod/strategy.go#L235-L247). I think this would mean that the `fakeClient.ClientBuilder` should get a slice of `fieldIndexers`/`fieldMappers` that are able to create a map with field name and field value for objects. This would probably mean that those indexers/mappers need to be type specific. Then we should make sure those are applied when filtering.

_Originally posted by @imilchev in https://github.com/kubernetes-sigs/controller-runtime/issues/866#issuecomment-775072419_

**Comment by invidian** [comment]
As a workaround, one can do the following in tests:
```go
      podsToCreate := []*corev1.Pod{}
      fakeClient := fake.NewSimpleClientset(pods...)

      fakeClient.PrependReactor("list", "pods", func(action k8stesting.Action) (bool, runtime.Object, error) {
        actionList, ok := action.(k8stesting.ListActionImpl)
        if !ok {
          return true, nil, fmt.Errorf("unexpected action type, expected %T, got %T", k8stesting.ListActionImpl{}, action)
        }

        listFieldsSelector := actionList.GetListRestrictions().Fields

        pods := []corev1.Pod{}

        for _, pod := range podsToCreate {
          podSpecificFieldsSet := make(fields.Set, 8)
          podSpecificFieldsSet["spec.nodeName"] = pod.Spec.NodeName

          if listFieldsSelector.Matches(podSpecificFieldsSet) {
            pods = append(pods, *pod)
          }
        }

        return true, &corev1.PodList{
          Items: pods,
        }, nil
      })
```
