### ISSUE TITLE
Duplicate cluster scoped objects while listing using MultiNamespacedCache

### ISSUE THREAD

**Issue by vinod-patil** [kubernetes-sigs/controller-runtime#1377]
I am using manager client to list and get resources from cache with below option to cache objects from multiple namespaces
```
ctrl.Options{
   NewCache: cache.MultiNamespacedCacheBuilder([]string{"ns1", "ns2", "ns3"})
}
```
But whenever I list cluster scoped resources function is returning duplicate resources after [combining resources from each namespace](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L159) map so in my case resource count is going to be 3 * actual as I used 3 namespaces in cache builder.

**Comment by alvaroaleman** [comment]
Sounds like the MultiNamespaceCache needs proper handling for cluster-scoped resources. Objections to converge this issue into https://github.com/kubernetes-sigs/controller-runtime/issues/1378 and close it?
