### ISSUE TITLE
Unknown namespace for the cache error while Getting cluster scoped for MultiNamespacedCache

### ISSUE THREAD

**Issue by vinod-patil** [kubernetes-sigs/controller-runtime#1378]
While using MultiNamespacedCache with manager, if we try to get a cluster scoped resource as 
cluster scoped resource doesn't have any namespace (empty namespace), it's returning unknown namespace error 
```
func (c *multiNamespaceCache) Get(ctx context.Context, key client.ObjectKey, obj client.Object) error {
	cache, ok := c.namespaceToCache[key.Namespace]
	if !ok {
		return fmt.Errorf("unable to get: %v because of unknown namespace for the cache", key)
	}
	return cache.Get(ctx, key, obj)
}
```

**Comment by varshaprasad96** [comment]
@alvaroaleman, would this be the right approach to solve the issue with cluster scoped objects:
1. In [`namespaceToCache`](https://github.com/kubernetes-sigs/controller-runtime/blob/e388e1e1f5a745166955442294bb8aede1f761e2/pkg/cache/multi_namespace_cache.go#L66) mapping, we add an entry for a mapping between no namespace and global cache (say an empty string as the key). When there is no namespace provided in the [object key](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L129), we call the global cache to get the cluster scoped object.
2. In case of listing the objects in multinamespace cache - if `listOptions` does provide anything, we call the global cache, without any specified namespace to list the objects. Currently, by default if namespace is not provided we are[ looking for objects across all namespaces](https://github.com/kubernetes-sigs/controller-runtime/blob/e388e1e1f5a745166955442294bb8aede1f761e2/pkg/cache/multi_namespace_cache.go#L141) and listing them.

Maybe we can have a separate const defined for [`multiNamespaceCache`](https://github.com/kubernetes-sigs/controller-runtime/blob/e388e1e1f5a745166955442294bb8aede1f761e2/pkg/cache/multi_namespace_cache.go#L65) to identify a "no namespace" condition. 

cc: @estroz

**Comment by madhurtrilio** [comment]
Having same issue. Any tentative timelines on when this will be fixed?

**Comment by alvaroaleman** [comment]
@madhurtrilio #1418 will fix this
