### ISSUE TITLE
Fake client doesn't implement delete propagation

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#138]
Code under test may expect that setting `PropagationPolicy` to `Foreground` will cause child objects to be deleted before returning. Currently the fake client doesn't implement this, nor does it offer a hook to allow this behavior to be simulated (see #72).

**Comment by DirectXMan12** [comment]
While I'd accept a PR to contribute this, for various reasons outlined before, fake client code is not a priority, since we generally try to discourage its use.
