### ISSUE TITLE
ENVTest - cannot delete PVCs 

### ISSUE THREAD

**Issue by avrahams** [kubernetes-sigs/controller-runtime#1383]
My test creates a Persistent Volume Claim but cannot delete it.
The PersistentVolumeClaim is stuck in pending status and would not delete

**Comment by coderanger** [comment]
Sounds plausible that there's some funky code in apiserver for one of the volume protection features that won't work well without the PVC controller running (which it doesn't in envtest). Unfortunately there's nothing we can do about this on our end, envtest is running an unmodified kube-apiserver just like always, the only special thing is it doesn't run any of the normal controller manager daemons.

You can use envtest's "existing cluster" mode to run against a real (if mini-sized) cluster like Kind or K3s which should handle this just fine as that's a fully-fledged setup with all the usual things.

/close
