### ISSUE TITLE
Isn't Hub and Spoke model for conversion webhooks already baked in in api-server?

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/controller-runtime#1388]
Hi folks!

I'm working on integrating conversion webhooks to Crossplane provider resources. I have read through the [Kubernetes doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning) about conversion webhooks and the [kubebuilder book](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html) on how they are implemented in controller-runtime.

One thing I couldn't figure out is the following excerpt from the kubebuilder doc:
> A simple approach to defining conversion might be to define conversion functions to convert between each of our versions. Then, whenever we need to convert, we’d look up the appropriate function, and call it to run the conversion.
This works fine when we just have two versions, but what if we had 4 types? 8 types? That’d be a lot of conversion functions.

It assumes that api-server will call the webhooks for every pair of versions that are served. However, I interpreted the following [part](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#writing-reading-and-updating-versioned-customresourcedefinition-objects) from Kubernetes doc as api-server only requests conversions from and to storage version.

So, it seems to me that the hub-and-spoke model is already there; hub is the storage version and spokes are the served versions. But when I look through the conversion code in controller-runtime, I see that conversions between served versions are [also handled](https://github.com/kubernetes-sigs/controller-runtime/blob/6a31842/pkg/webhook/conversion/conversion.go#L145). Does controller-runtime need to handle this case?

The reason I wanted to know this is that we don't want to implement the conversion logic in API type package as it's enforced by the existing layer in controller-runtime, because some conversions might require using provider SDK (like AWS Go SDK). For example, if a new field is added in the new API, we might not be able to infer its value from old CR version, so we might have to make a `Describe` call to AWS and see what the value should be. If we include SDK in API types package, then all external consumers of these API types will have to depend on AWS SDK as well, which is not desirable. So, I'm trying to see how we can implement the layer controller-runtime has in a separate package but I'm curious about whether that implementation needs to handle the conversion between served versions as well, as controller-runtime does.

**Comment by coderanger** [comment]
That section of the docs is explaining _why_ it follows a hub and spoke structure. Not suggesting that it's optional.

**Comment by muvaf** [comment]
@coderanger It's not about the docs necessarily. I am asking why the implementation exists even though the api-server already implements the hub-spoke model, i.e. calls only the endpoints that converts to and from the hub version(storage version).

**Comment by coderanger** [comment]
Not sure what implementation you mean, controller-runtime doesn't separately implement anything. This is part of explaining how conversion webhooks work. Those webhooks are called by kube-apiserver as part of the custom type API handling.
