### ISSUE TITLE
controllerutil.CreateOrPatch doesn't update not empty Status fields if Spec fields are specified

### ISSUE THREAD

**Issue by dmvolod** [kubernetes-sigs/controller-runtime#1392]
If we would like to patch custom resource with some `Spec` fields and `Status` which are not empty, the controllerutil.CreateOrPatch patches `Spec` only fields, but any `Status` keep unchanged,
`result` returns `OperationResultUpdatedStatus` which means that both `Spec` and `Status` where updated
The reason why this happens is that the original `Status` of the object is returned when the" Patch "procedure is exited and, as a result, no` Status` fields are updated

**Comment by dmvolod** [comment]
Reproducer created. See linked commit

**Comment by coderanger** [comment]
Do you have the status subresource enabled? If so, you need to specifically use a status writer call.

**Comment by dmvolod** [comment]
@coderanger are you mean `// +kubebuilder:subresource:status` instruction? Yes, we have it.
What does status writer call means. This function works fine with `Spec` and non `Status.Condtions` updates

**Comment by coderanger** [comment]
Turning on that subresource means that all changes to fields under `.status` will be blocked from calls to `client.Update()`. You must separately use `client.Status().Update()` (which in turn only applies changes under `.status`). This is the purpose of the status subresource. If you don't want that behavior, don't enable it :)

**Comment by dmvolod** [comment]
@coderanger please pay attention that,
- we are using and talking about `controller-runtime` library function called `controllerutil.CreateOrPatch` and it implementing with separate resource `Spec` and `Status` Patch https://github.com/kubernetes-sigs/controller-runtime/blob/5fd841429031b0fdb0b5cf2036f18871899d05aa/pkg/controller/controllerutil/controllerutil.go#L234
- first (empty `Status` field) and non `Status.Condtions` (probably any Array field) are works fine. Both `Status` and `Spec` fields are updated
- This case doesn't work for the next `controllerutil.CreateOrPatch` calls even if only `Status.Condtions` fields are updated
