### ISSUE TITLE
Dynamically add and remove informers from the informer cache

### ISSUE THREAD

**Issue by snorwin** [kubernetes-sigs/controller-runtime#1397]
It would be great if an informer could also be removed from the informer cache (e.g. if a dynamically managed crd is deleted). I found a great proposal for this feature in the [OPA gatekeeper](https://github.com/open-policy-agent/gatekeeper).

The proposed solution adds a additional stop `chan`  to each `MapEntry` which allows you to stop this individual informers without stopping the entire informers map:
https://github.com/open-policy-agent/gatekeeper/blob/6d99979b5eaf3e263c860694a4d64d4e1c302cf2/third_party/sigs.k8s.io/controller-runtime/pkg/dynamiccache/internal/informers_map.go

**Comment by alvaroaleman** [comment]
Dynamic add already exists, removal is tracked in https://github.com/kubernetes-sigs/controller-runtime/issues/935
