### ISSUE TITLE
envtest: etcd startup times out with etcd v3.5

### ISSUE THREAD

**Issue by schrej** [kubernetes-sigs/controller-runtime#1407]
The `envtest` package checks for a  [specific line](https://github.com/kubernetes-sigs/controller-runtime/blob/bdb3f845d6e2510d441f593fb420781e8a05f894/pkg/internal/testing/integration/internal/etcd.go#L37) when it's starting `etcd` for testing.
With etcd version 3.5 that line [gets removed](https://github.com/etcd-io/etcd/pull/11592/files#diff-22504f5e6a5f5ff5f4929b7fc571a26735f1b7746f5f143891af245e85ec4f0bL196), which causes the etcd startup to time out, as it will never detect it on startup.

I'm not entirely sure how this could be fixed in a backwards compatible way. Maybe just check for both variants?

**Comment by coderanger** [comment]
I think we can probably move etcd to a healthz check on `/health`, added in 3.3.0 according to the docs. That will cover all modes?

**Comment by vincepri** [comment]
/close

This has been fixed in v0.9
