### ISSUE TITLE
`delegatingClient` with `client.informerCache` does not respect `client.Limit` option

### ISSUE THREAD

**Issue by jpfourny** [kubernetes-sigs/controller-runtime#1422]
When listing resources, I found that `client.delegatingClient` with `client.informerCache` does not respect `client.Limit` option. Scanning the source, I could not find any provisions to apply the limit when reading from the cache. This should be trivial to implement, no? 

Also, I believe that `kubernetesfakes` suffers from the same issue (but that is less concerning to me).

**Comment by alvaroaleman** [comment]
Yeah, shouldn't be hard to add that, feel free to take a stab!

**Comment by MadhavJivrajani** [comment]
Hi! I'd like to work on this if possible 😄 

/assign
