### ISSUE TITLE
Disable rest client latency metric

### ISSUE THREAD

**Issue by suhanime** [kubernetes-sigs/controller-runtime#1423]
We vendor in `controller-runtime` and use it to expose its controller specific metrics in addition to our own.
Recently we observed that [rest_client_request_latency_seconds](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/client_go_adapter.go#L55-L60) was eating up a significant portion of Prometheus storage, as can be seen from a snapshot of the highest cardinality metrics in our codebase:
```
42765 kube_secret_type
42799 kube_secret_metadata_resource_version
461312 rest_client_request_latency_seconds_count
461312 rest_client_request_latency_seconds_sum
5074432 rest_client_request_latency_seconds_bucket
```

I understand this metric was deprecated in kube 1.14 and turned off in [1.17](https://github.com/kubernetes/kubernetes/pull/83836).
Is it possible to either disable this metric or to allow us to unregister it?

**Comment by dgoodwin** [comment]
Our situation is a bit unusual in that clients are used to talk to a substantial number of resources in a large number of clusters. In our case the prom endpoint blew up to over 300mb and prometheus pods scraping it fell over pretty quickly with massive memory use.

**Comment by alvaroaleman** [comment]
I agree that just putting the url as a label in there is too much wrt cardinality as that results in a new metric per individual gvk+object name. What did upstream replace these with?

What IMHO would be useful to still have is a request metric that contains labels for statuscode, method, apigroup, kind and namespace. WDYT?

**Comment by alvaroaleman** [comment]
> What IMHO would be useful to still have is a request metric that contains labels for statuscode, method, apigroup, kind and namespace. WDYT?

OTOH all these metrics exist on the apiserver and can be filtered by user and user agent. I personally have only ever used those. Are there cases where having request metrics clientside provides additional value and/or the apiserver metrics are not available?

**Comment by dgoodwin** [comment]
We actually implemented our own metric for this (didn't know this one existed until it blew up on us) with the labels []string{"controller", "method", "resource", "remote", "status"}. Even this is fairly verbose so I could see a case for saying it shouldn't be part of controller-runtime and users should implement their own, or alternatively offer the ability to enable/disable it.

**Comment by dgoodwin** [comment]
@suhanime added to agenda for Thursday meeting.

**Comment by suhanime** [comment]
Looks like upstream has made it possible to not register for certain metrics
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/prometheus/restclient/metrics.go#L127-L134
https://github.com/kubernetes/kubernetes/blob/5ab4b580de915cffd901c7a1304aca5fdcca88e7/staging/src/k8s.io/client-go/tools/metrics/metrics.go#L72-L105

**Comment by alvaroaleman** [comment]
I don't think that helps here, because you can not execute code before all your dependencies `init()` finished

**Comment by 2uasimojo** [comment]
/remove-lifecycle stale

I'd like to reopen this discussion. IIUC:
- The current metric is untenable for hive's use case.
- The current metric is deprecated/hidden in kube. (I'm not actually sure what that means -- does it mean that c-r is sending that data into a black hole where it's still taking up space but can't be scraped anyway?)
- It is possible to implement a similar metric that meets needs but doesn't use as much storage. Clients can do this as needed -- c-r doesn't need to.

To address specific points:

> What IMHO would be useful to still have is a request metric that contains labels for statuscode, method, apigroup, kind and namespace. WDYT?

No objection, but if so a) include a granny switch so clients can turn it off if they don't want it; and b) that's a separate issue/PR.

> Are there cases where having request metrics clientside provides additional value and/or the apiserver metrics are not available?

This is exactly why the decision needs to be left up to the consumer -- c-r shouldn't try to anticipate for every use case.

> I don't think that helps here, because you can not execute code before all your dependencies init() finished

Agree: as written, c-r's init() is going to run when hive imports it. (There's an `Unregister` method for the `Registry`, but that doesn't remove the registration from client-go. And it would be pretty lousy UX to have to do that anyway.)

For the scope of this issue -- i.e. deferring any discussions of alternatives that c-r could implement in the future -- I would like to propose we do one of the following:

1. **Remove the metric.** This is my preference. (Depending what the upstream "hiding" means, it may also be the only thing that remotely makes sense.)
2. **Make it optional.** For example, make the metric and adapter public in c-r, but don't register them, allowing consumers to do so if they wish:

```go
crmetrics.Registry.MustRegister(crmetrics.RequestLatencyMetric)
clientmetrics.Register(clientmetrics.RegisterOpts{
	RequestLatency: crmetrics.LatencyAdapter
})
```

...or just export a `RegisterLatencyMetric()` method that does :arrow_up:

**Comment by alvaroaleman** [comment]
Yeah, lets remove it for now. We don't have a good way to find out if anyone cares about it.

**Comment by 2uasimojo** [comment]
Cool, thanks @alvaroaleman: #1586.
