### ISSUE TITLE
How not to delete statefulsets created by controller when you delete controller

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/controller-runtime#1432]
We have an operator that manages CRDs, statefulsets, etc.  When the operator is deleted we do not want to have all of the resources deleted.  How do we do this?

**Comment by coderanger** [comment]
This is not a feature of Kubernetes per se but more of an emergent behavior. But when you delete a CRD it will delete all instances of the custom object, which should then delete all objects owned by your custom object. You could leave the CRD in place when uninstalling the operator, or you could manually delete the owner references.

**Comment by chrislovecnm** [comment]
Makes sense!  Closing - and much thanks
