### ISSUE TITLE
Race Condition in `controllerManager.waitForRunnable`

### ISSUE THREAD

**Issue by AliMohammadiSoumee** [kubernetes-sigs/controller-runtime#1442]
I got a race condition error when I was trying to run my tests with `-race` flag. 

The problem is with [controllerManager.waitForRunnable](https://github.com/kubernetes-sigs/controller-runtime/blob/b5065bd85190e92864522fcc85aa4f6a3cce4f82/pkg/manager/internal.go#L161). Based on this [document](https://golang.org/pkg/sync/#WaitGroup), `Add` and `Wait` methods of `WaitGroup` should be called in the same goroutine.

`controllerManager` calls the `WaitGroup.Add` method In the [controllerManager.StartRunnable](https://github.com/kubernetes-sigs/controller-runtime/blob/b5065bd85190e92864522fcc85aa4f6a3cce4f82/pkg/manager/internal.go#L686) method, and calls the `WaitGroup.Wait` method in the [controllerManager.waitForRunnableToEnd](https://github.com/kubernetes-sigs/controller-runtime/blob/b5065bd85190e92864522fcc85aa4f6a3cce4f82/pkg/manager/internal.go#L575) method, While `waitForRunnableToEnd` and `StartRunnable` are running in different goroutines.

This log may help you, It's for v0.8.3:
```
WARNING: DATA RACE
Write at 0x00c00038e6a8 by goroutine 86:
  internal/race.Write()
      /usr/local/go/src/internal/race/race.go:41 +0x125
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/sync/waitgroup.go:128 +0x126
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).waitForRunnableToEnd.func2()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:567 +0x44

Previous read at 0x00c00038e6a8 by goroutine 166:
  internal/race.Read()
      /usr/local/go/src/internal/race/race.go:37 +0x206
  sync.(*WaitGroup).Add()
      /usr/local/go/src/sync/waitgroup.go:71 +0x219
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:678 +0x4e
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).serveMetrics()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:384 +0x31b

Goroutine 86 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).waitForRunnableToEnd()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:566 +0xcb
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:548 +0x376
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start.func1()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:449 +0x46
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:499 +0x575

Goroutine 166 (running) created at:
  sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start()
      /home/ali/Developer/Go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager/internal.go:473 +0x61b
```

**Comment by jpfourny** [comment]
I am seeing this, too. The usage of `WaitGroup` is a bit sketchy - a ticking bomb. In a nutshell: `controllerManager` is failing to account for the fact that WaitGroup's `Add` and `Wait` function require synchronization on the first call to `Add`. There is a critical section on the first increment (bringing the internal count above zero) that WaitGroup expects the caller to deal with.

**Comment by jpfourny** [comment]
An interesting observation (in my case): Running with Go 1.16 consistently produces the issue. Dropping to Go 1.15 makes it go away. So ... perhaps race detection changed between Go releases? Either Go 1.16 has false positives on races, or it is picking up a legit race that 1.15 cannot see. I noticed that this project is testing with 1.15 ...

**Comment by jpfourny** [comment]
Yeah - the usage of WaitGroup is sketchy. It's true that `Wait` and `Add` are not safe to be called concurrently. This is a ticking time-bomb.

**Comment by jpfourny** [comment]
What I don't understand is why -race is detecting the problem consistently in 0.8.3, but not back in 0.6.5. The usage patterns of WaitGroup did not change drastically.

**Comment by brakthehack** [comment]
FWIW, this is still present in v0.9.5.

**Comment by clementnuss** [comment]
/remove-lifecycle stale

not to get this issue closed: the race condition is still present with v0.10.3

**Comment by clementnuss** [comment]
is this issue still valid with controller-runtime v0.11.0 ?
I tried to reproduce the bug but it never happened again so far (though it did not happen deterministically)

**Comment by FillZpp** [comment]
I think it has been solved in https://github.com/kubernetes-sigs/controller-runtime/pull/1695 .

**Comment by clementnuss** [comment]
@AliMohammadiSoumee @brakthehack can you guys try to reproduce your race condition with controller-runtime prior v0.11 and then with v0.11 ?

I cannot reproduce it with v0.11 personally, but it had only happened a few times
If not i think this issue could be closed

**Comment by AliMohammadiSoumee** [comment]
I have reproduced it with controller-runtime v0.11.0, and apparently, the issue is solved.
