### ISSUE TITLE
Not calling SetLogger() results in a memory leak

### ISSUE THREAD

**Issue by willbeason** [kubernetes-sigs/controller-runtime#1444]
Steps to reproduce:

1. Take controller code that otherwise functions normally. What matters is that you have something that either logs a lot or uses libraries which log a lot with Log.WithValues().
2. Create a main function and don't call `SetLog(glogr.New())`
3. Run the controller in a cluster
4. Wait for memory usage to spike and wait for the Pod to get OOMKilled

What we understand of the problem:
The log.Log Logger sets up a delegating logger to a Null Logger.
```
var Log = NewDelegatingLogger(NullLogger{})
```
The DelegatingLogger's default value uses the promise mechanism so any message sent prior to the logger setup will be logged once SetLogger is called.
```
func NewDelegatingLogger(initial logr.Logger) *DelegatingLogger {
  l := &DelegatingLogger{
    Logger: initial
    promis: &loggerPromis{promisesLock: sync.Mutex{}}
  }
}
```
On calls with log.Log.WithValues, it uses the promis codepath.

```
// WithValues provides a new Logger with the tags appended
func (p *loggerPromise) WithValues(l *DelegatingLogger, tags ...interface{}) *loggerPromise {
	res := &loggerPromise{
		logger:       l,
		tags:         tags,
		promisesLock: sync.Mutex{},
	}

	p.promisesLock.Lock()
	defer p.promisesLock.Unlock()
	p.childPromises = append(p.childPromises, res)
	return res
}
```

Promises are supposed to be evaluated once SetLogger is called, but we never call it so the p.childPromises slice will grow indefinitely.
```
func SetLogger(l logr.Logger) {
  Log.Fulfill(l)
}
```

**Comment by willbeason** [comment]
Thanks to @briantkennedy for the find - he uncovered the issue and I'm just reporting it!

**Comment by DirectXMan12** [comment]
IIRC this should fix the issue: https://github.com/kubernetes-sigs/controller-runtime/pull/1309

**Comment by willbeason** [comment]
Nice! That will.
