### ISSUE TITLE
Duplicate `Start` method in the `Manager` and `Cluster` interfaces

### ISSUE THREAD

**Issue by alidadar7676** [kubernetes-sigs/controller-runtime#1445]
The [Manager](https://github.com/kubernetes-sigs/controller-runtime/blob/197751df6040ec99414574e89f3fa73914ce335d/pkg/manager/manager.go#L51) interface embeds the [Cluster](https://github.com/kubernetes-sigs/controller-runtime/blob/197751df6040ec99414574e89f3fa73914ce335d/pkg/cluster/cluster.go#L39) interface and both of them contains the `Start(ctx context.Context) error` method.

Is it possible to convert the embedded `Cluster` interface to a field of `Manager`? I mean something like this:
```
type Manager interface {
    Cluster cluster.Cluster
    ....
}
```

It's OK with `Go v1.16` but it makes some problems with older versions of `Go`, For example, run the following command with `Go v1.13.5`:

```
go vet ./...
```

**Comment by alidadar7676** [comment]
It's the error of `go vet ./...` with `Go v1.13.5`:
```
                           
# sigs.k8s.io/controller-runtime/pkg/manager
pkg/manager/manager.go:53:2: duplicate method Start
note: module requires Go 1.16
# sigs.k8s.io/controller-runtime/pkg/manager [sigs.k8s.io/controller-runtime/pkg/cache.test]
pkg/manager/manager.go:53:2: duplicate method Start
note: module requires Go 1.16
# sigs.k8s.io/controller-runtime/pkg/manager [sigs.k8s.io/controller-runtime/pkg/manager.test]
pkg/manager/manager.go:53:2: duplicate method Start
pkg/manager/manager_test.go:307:14: ambiguous selector m.Start
pkg/manager/manager_test.go:337:14: ambiguous selector m.Start
pkg/manager/manager_test.go:404:15: ambiguous selector m1.Start
pkg/manager/manager_test.go:420:15: ambiguous selector m2.Start
pkg/manager/manager_test.go:579:14: ambiguous selector m.Start
pkg/manager/manager_test.go:609:13: ambiguous selector m.Start
pkg/manager/manager_test.go:626:13: ambiguous selector m.Start
pkg/manager/manager_test.go:656:14: ambiguous selector m.Start
pkg/manager/manager_test.go:700:14: ambiguous selector m.Start
pkg/manager/manager_test.go:700:14: too many errors
note: module requires Go 1.16
```

**Comment by alidadar7676** [comment]
Sorry, my bad

**Comment by joelanford** [comment]
> Is it possible to convert the embedded Cluster interface to a field of Manager?

Go interfaces contain only function signatures. It's not possible to put a field in an interface.

Go allows overlapping interfaces as of [Go 1.14](https://golang.org/doc/go1.14#language). Controller-runtime began taking advantage of this feature as of v0.8.0 (I think), and the current go.mod file [specifies go 1.16](https://github.com/kubernetes-sigs/controller-runtime/blob/197751df6040ec99414574e89f3fa73914ce335d/go.mod#L3) is the minimum supported version.

You'll need to upgrade to the version of Go required by the version of controller-runtime you're using.

**Comment by alidadar7676** [comment]
@joelanford 
Thanks for your response. I'm sorry about my mistake, I forgot that it's not possible to use an interface as a field =).
