### ISSUE TITLE
Is there a way to read even type in Reconcile function()

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/controller-runtime#1447]
Hey there,
Right now controller passes req with contains only Name & Namespace.
Is there a way to pass event type (Create, Update, Delete, Patch) to reconcile function as well out of the box?
Thanks

**Comment by coderanger** [comment]
No, the whole model is that the event type is unimportant. Multiple events are likely to get batched together even. A controller only cares about reconcile operations, the watches are just to know when to trigger one.

**Comment by coderanger** [comment]
Going to close this out since there has been no response. If you have any more questions please feel free to ask in the #kubebuilder channel in Slack.

/close
