### ISSUE TITLE
Observing concurrent reconciliation with 1 worker

### ISSUE THREAD

**Issue by Abhishek-Srivastava** [kubernetes-sigs/controller-runtime#1452]
I have a query on the reconcile logic with 1 worker for a custom controller I have, generated using kubebuilder.

In the reconciler logic for a CR, I am doing the following in sequence:
1. Update the status subresource.
2. Make a synchronous GRPC (blocking) call to a GRPC server running as a different pod.
3. Update the status subresource

What I have been observing is, with the Update in Step 1 itself, another reconciliation triggers immediately. The MAX_CONCURRENT_RECONCILE var is set to 1 (ensuring one worker only). My understanding was, updating status subresource would enqueue and once the first reconciliation is over (steps 2-3) then the next reconciliation would trigger. And for concurrent reconciliation we need to increase the worker count. What have I understood wrong?

I know, the  recommendation is to make the calls idempotent so that multiple calls wouldn't have any side effects, but can somebody please help me understand the above observation?

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-06-03T04:00:21Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Go deps:
k8s.io/api v0.17.2
k8s.io/apimachinery v0.17.2
k8s.io/client-go v0.17.2
sigs.k8s.io/controller-runtime v0.5.0
```

**Comment by vincent-pli** [comment]
@Abhishek-Srivastava 
That's correct behavior, when you update the status of resource (step1), another `request` will be enqueue to your `workqueue`(since the resource is updated), but not trigger `reconcile` since you `MAX_CONCURRENT_RECONCILE` is set to 1, when you current `reconcile` finished the new coming one will trigger a new `reconcile`.

For the scenario `MAX_CONCURRENT_RECONCILE` > 1, there will be multiple thread fetch from `workqueue`, but no worry about the conflict(I mean same `resource` handled by different reconcile in same time), the client-go will guarantee the conflict not happen.

**Comment by Abhishek-Srivastava** [comment]
@vincent-pli That's what my understand is. But what happening is little different. The next enqueued reconciliation triggers before the first has ever ended. Like, in the case I have given above, recon-1 is still blocked at step 2(grpc call) and recon-2 kicks already. 

This is consistent and I am seeing it always.
@DirectXMan12  Your expertise needed please.

**Comment by anusha-kandepu** [comment]
@Abhishek-Srivastava and @vincent-pli  I am observing the same behavior in my environment as well. Though MAX_CONCURRENT_RECONCILE var is set to 1 , if we update the subresource as part of reconciler logic another reconciliation is getting triggered. As per my understanding if the MAX_CONCURRENT_RECONCILE is set to 1 , the next reconcile should enqueue and it should get triggered only after the current one finishes. This behavior is consistent. 
Not sure any other settings we need to check to make sure only one reconciliation should happen if the MAX_CONCURRENT_RECONCILE is set to 1. 

any thoughts?.

**Comment by alexeldeib** [comment]
A minimal reproducer and/or logs showing what you see would probably be useful here. I haven’t seen this in the past when reproving similar issues, but admittedly haven’t tried recently.

**Comment by Abhishek-Srivastava** [comment]
I will probably close this bug since I have specific one for the stale read:
https://github.com/kubernetes-sigs/controller-runtime/issues/1464

**Comment by Abhishek-Srivastava** [comment]
Closing this bug as it might be a misled observation due to #1464
