### ISSUE TITLE
[Feature Request] Finalizer helper library

### ISSUE THREAD

**Issue by rashmigottipati** [kubernetes-sigs/controller-runtime#1453]
In Kubernetes garbage collection model, OwnerReferences are allowed within a namespace wherein the "dependent" object has anOwnerReference field referencing the "parent" object. If the parent object is being deleted, Kubernetes garbage collector will delete all of its dependent objects. As cross-namespace owner references are not allowed by design; a Finalizer should be used to perform cleanup.

Finalizers are more powerful and broadly applicable than owner references because they permit customizable deletion steps for a controller to define how an object is cleaned up, ex. updating a CR's status during deletion with a particular message. This gives Operator authors control over CR deletion proceeds. 

Operator projects would benefit from a finalizer helper library in controller-runtime which will make it easy for users to define their own finalizer struct implementations and use the abstractions we include to register the Finalizers and hand the Finalizers to their Reconciler and call Finalize function.

Please see @joelanford's high level thought on the implementation details: https://github.com/kubernetes-sigs/kubebuilder/issues/2010#issuecomment-785558621.

/kind feature

**Comment by Adirio** [comment]
Pinging @joelanford as he suggested this approach.

**Comment by coderanger** [comment]
https://github.com/coderanger/controller-utils/blob/main/core/reconciler.go#L277-L290 is my implementation of the general helper pattern for this. It checks on initialization (up above) for if the component implements the finalizer interface and if so, it will call Finalizer() on that component when needed.

**Comment by joelanford** [comment]
My high level thought was to have something like this:
```go
type Registerer interface {
	Register(key string, f Finalizer) error
}

type Finalizer interface {
	Finalize(client.Object) (requeue bool, err error)
}

type Finalizers interface {
	// implements Registerer and Finalizer to finalize
	// all registered finalizers if the provided object
	// has a deletion timestamp or set all registered
	// finalizers if it doesn't
	Registerer
	Finalizer
}

func NewFinalizers() Finalizers {
	return finalizers(map[string]Finalizer{})
}

type finalizers map[string]Finalizer

func (f finalizers) Register(key string, finalizer Finalizer) error {
	if _, ok := f[key]; ok {
		return fmt.Errorf("finalizer for key %q already registered")
	}
	f[key] = finalizer
	return nil
}

func (f finalizers) Finalize(obj client.Object) (bool, error) {
	requeue := false
	for key, finalizer := range f {
		if obj.GetDeletionTimestamp() == nil && !controllerutil.ContainsFinalizer(obj, key) {
			controllerutil.AddFinalizer(obj, key)
			requeue = true
		} else if controllerutil.ContainsFinalizer(obj, key) {
			_, err := finalizer.Finalize(obj)
			if err != nil {
				return true, fmt.Errorf("finalize failed for key %q: %v", key, err)
			}
			controllerutil.RemoveFinalizer(obj, key)
			requeue = true
		}
	}
	return requeue, nil
}
```

With something like this users could:

1. Define their own finalizer struct implementations
	```go
	const myFinalizerKey = "my-finalizer"
	type MyObjectFinalizer struct {
		client.Client
	}

	func (f MyObjectFinalizer) Finalize(obj client.Object) (bool, error) {
	    // use the client to delete some other stuff in the cluster, perhaps.
	}
	```

2. Register them with the Finalizers 
	```go
	func main() {
		...
		myFinalziers := finalizer.NewFinalizers()
		myFinalizers.Register(myFinalizerKey, &MyObjectFinalizer{mgr.GetClient()})
		...
	}
	```

3. Hand the Finalizers to their reconciler:
	  ```go
	  type MyReconciler struct {
		  client.Client
		  Log    logr.Logger
		  Scheme *runtime.Scheme
		  Finalizers finalizer.Finalizer
	  }
	  
	  func main() {
		  ...
		  if err = (&controllers.MyReconciler{
			  Client: mgr.GetClient(),
			  Log: ctrl.Log.WithName("controllers").WithName("My")
			  Scheme: mgr.GetScheme(),
			  Finalizers: myFinalziers,
		  }
		  ...
	  }
	  ```

4. And then the reconciler call is boiled down to something like this:
	  ```go
	  func Reconcile(req ctrl.Request) (ctrl.Result, error) {
		  obj := groupv1.MyObject
		  _ = r.Client.Get(ctx, req, &obj)
		  requeue, err := r.finalizers.Finalize(obj)
		  if requeue || err != nil {
			  r.Client.Update(ctx, &obj)
			  return ctrl.Result{Requeue: requeue}, err
		  }
	  }
	  ```


It looks like @coderanger has an actual working implementation of what the `Finalizer` function signature needs to look like to properly signal to the reconciler what it should do when the finalizer has completed. So take specifics of mine with a grain of salt.

**Comment by rashmigottipati** [comment]
Implemented and merged the finalizer helper library in https://github.com/kubernetes-sigs/controller-runtime/pull/1481.
Closing this issue.

**Comment by austince** [comment]
Are there any examples that use this? I'm giving it a try but don't understand where the business logic of the finalizer should live. It feels like the `Reconciler` knows what should be deleted, not `main`. Should I define the finalizer logic inside the `x_controller.go` file, and just register that in the main?
