### ISSUE TITLE
envtest environment does not perform cascading deletions

### ISSUE THREAD

**Issue by renan-campos** [kubernetes-sigs/controller-runtime#1459]
As the title describes, I believe that the envtest environment garbage collection behaviour does not match that defined by kubernetes.

This can be shown by doing the following:
- Create envtest environment and point k8s client to it.
- Create ConfigMaps A & B
- Set ConfigMap B's controller reference to ConfigMap A.
- Delete ConfigMap A.
- Check if ConfigMap B has also been deleted.

According to the [kubenetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents), ConfigMap B should also be deleted, but this is not the case in the envtest environment. 

Here is a go program that performs the steps described above (see sample output in README):
https://github.com/renan-campos/cr-envtest-demo

**Comment by coderanger** [comment]
Correct, this is a feature of the gc controller which does not run under envtest.

**Comment by renan-campos** [comment]
Thanks for clarifying, where does the Delete get handled within envtest? I'm not to familiar with the codebase but it looks like when a client calls delete it is makes an http DELETE that gets sent to kube-apiserver, I'm not sure where it goes from there, though.

**Comment by coderanger** [comment]
So the actual delete call you make happens normally. But the owner cascade piece is not part of kube-apiserver, that behavior lives in the gc controller loop which is part of kube-controller-manager. Envtest doesn't run k-c-m at all to keep things trimmed down. If this is important for a feature you need to test, the easiest approach is to use the `UseExistingCluster` mode and point the testing system at a local "real" cluster, usually Kind or K3s/d but there's many small cluster options these days.

**Comment by renan-campos** [comment]
Sounds good, thanks a lot for the help; much appreciated!
