### ISSUE TITLE
Got error when trying to update an object with empty spec field.

### ISSUE THREAD

**Issue by Ruminateer** [kubernetes-sigs/controller-runtime#1461]
Maybe it's a noob question, but I did my search and cannot find the answer.

I am using Kubebuilder to write a controller. When I try to update an object with an empty spec field, I got the following error.
```
2021-03-29T14:35:14.525+0800    INFO    controllers.PaddleJob   Reconcile       {"paddlejob": "default/resnet", "version": "176188"}
2021-03-29T14:35:14.553+0800    ERROR   controller-runtime.manager.controller.paddlejob Reconciler error        {"reconciler group": "batch.paddlepaddle.org", "reconciler kind": "PaddleJob", "name": "resnet", "namespace": "default", "error": "PaddleJob.batch.paddlepaddle.org \"resnet\" is invalid: spec.ps.template.spec.containers: Invalid value: \"null\": spec.ps.template.spec.containers in body must be of type array: \"null\""}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/zzy/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/zzy/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:267
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/zzy/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
        /home/zzy/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
        /home/zzy/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99
```

The spec of the object looks like this.
```go
type PaddleJobSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// CleanPodPolicy defines whether to clean pod after job finished
	CleanPodPolicy CleanPodPolicy `json:"cleanPodPolicy,omitempty"`

	// Intranet defines the communication mode inter pods: PodIP or Service
	Intranet Intranet `json:"intranet,omitempty"`

	//
	WithGloo int `json:"withGloo,omitempty"`

	// PS[erver] describes the spec of server base on pod template
	PS ResourceSpec `json:"ps,omitempty"`

	// Worker describes the spec of worker base on pod template
	Worker ResourceSpec `json:"worker"`
}

type ResourceSpec struct {
	// Replicas replica
	Replicas int `json:"replicas,omitempty"`

	// Requests set the minimal replicas of server to be run
	Requests int `json:"requests,omitempty"`

	// Requests set the maximal replicas of the server to be run, elastic is auto-enabled if the limit is set larger than 0
	Limits int `json:"limits,omitempty"`

	// Template specifies the podspec of a server
	Template corev1.PodTemplateSpec `json:"template"`
}
```

I have found out that the error is raised when I am calling the function `func (client.Writer).Update(ctx context.Context, obj client.Object, opts ...client.UpdateOption) error` with an object that I get from `func (client.Reader).Get(ctx context.Context, key types.NamespacedName, obj client.Object) error`. When the object in the cluster has specified `spec.ps` field, my code runs with no error. However, the error raises when the object in the cluster omits `spec.ps` (which is omitempty). Even if I do no change to the object that I `Get` and directly `Update` it, the error occurs. My code is at <https://github.com/Ruminateer/paddle-operator/blob/hostport/controllers/paddlejob_controller.go#L96> if that helps.

I am confused about how the omitting works here. Says an object omits the `ps` field, and I get it into a Go variable. Although the JSON tag specifies the field as `omitempty`, it is not a pointer field, so it has to be initialized with zero values in the variable. So the controller cannot tell if the field is omitted or explicitly set to zero values? Is omitting considered equivalent to zero values? Why controller-runtime rejects my update when I am just using the zero values that I got from the `Get` API? Sorry if my English is crappy. 😕

**Comment by Ruminateer** [comment]
resolved https://github.com/elastic/cloud-on-k8s/issues/1822

**Comment by FuPengCheng1** [comment]
@Ruminateer  
I have a similar problem. When function  (client.Reader).Get(ctxR, req.NamespacedName, ctxR.NodesProvisionRequest) called, the ctxR.NodesProvisionRequest.Spec is nil in  response . But  the spec  is not nil when I create a  NodesProvisionRequest ,like follow

spec:
  clusterName: "xxx"
  hostnames: ["host1","host2"]
  workers: 10

May I ask that how do you solve this?
