### ISSUE TITLE
Migrate to events.k8s.io v1

### ISSUE THREAD

**Issue by pigletfly** [kubernetes-sigs/controller-runtime#1462]
The new Event API has been promoted from v1beta1 to v1 in 1.19, should we migrate  to events.k8s.io v1 ?

Ref kubernetes/enhancements#383

**Comment by alvaroaleman** [comment]
So events v1 is beta and thus enabled since Kube 1.8?

**Comment by yastij** [comment]
@alvaroaleman - to avoid introducing a v2, the Events API had some changes but in the `events.k8s.io` apiGroup (core and `events.k8s.io` APIs are different). So to be more precise, we'd need to migrate from `core/v1` to `events.k8s.io/v1` of Events

**Comment by alvaroaleman** [comment]
So we can sure the servers have but it will need to be a breaking change as rbac changes, right?

**Comment by cndoit18** [comment]
kubernetes/kubernetes#101782
I tried to add events expansion in client-go so that we can migrate

**Comment by pigletfly** [comment]
FYI https://kubernetes.io/docs/reference/using-api/deprecation-guide/#event-v125

**Comment by alvaroaleman** [comment]
Feel free to pick this up @everyone who is interested. V1 is available since 1.8 according to the kep, so v1 should work for everyone (Modulo RBAC which will likely make this a breaking change).
