### ISSUE TITLE
options.AndFrom overriding previously set value

### ISSUE THREAD

**Issue by criscola** [kubernetes-sigs/controller-runtime#1463]
Hello everyone, I think I've found a small bug. Here's my code:

```
var err error
ctrlConfig := operatorconfigv1.OperatorConfig{}
options := ctrl.Options{
	Scheme:                 scheme,
	MetricsBindAddress:     viper.GetString(MetricsBindAddressKey),
	Port:                   viper.GetInt(WebhookPortKey),
	HealthProbeBindAddress: viper.GetString(HealthProbeBindAddressKey),
	LeaderElection:        	viper.GetBool(LeaderElectEnableKey),
}

// Build and pass the configuration file to the controller.
if cfgFile := viper.GetString(LoadConfigKey); cfgFile != "" {
	options, err = options.AndFrom(ctrl.ConfigFile().AtPath(cfgFile).OfKind(&ctrlConfig))
	if err != nil {
		setupLog.Error(err, "unable to load the config file into the controller")
		os.Exit(1)
	}
}

// Initialize manager
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), options)
if err != nil {
	setupLog.Error(err, "unable to initialize manager")
	os.Exit(1)
}
```

What I'm expecting is that `options.AndFrom` doesn't override _any_ previously set value. The problem is that the config file specified through `AtPath(cfgFile)` is overriding the field `LeaderElection` even though it is was set previously through a CLI flag, i.e. I have a config file like that:

```
[..]
leaderElection:
  leaderElect: true
[..]
```
so now if I set leaderElect to false using a CLI flag, it is still going to be set to true unlike the other fields.

The culprit seems to be located [here](https://github.com/kubernetes-sigs/controller-runtime/blob/0d84ce43073cefb813563dd7586c943fa2c97783/pkg/manager/manager.go#L423). 

```
if o.LeaderElection == false && obj.LeaderElection.LeaderElect != nil {
	o.LeaderElection = *obj.LeaderElection.LeaderElect
}
```
if the field is set to false and the value is specified in the config file, `LeaderElection` will be set to the value of the config file even though it was meant to be overridden by a flag.
A solution could be using a `*bool` type. What do you think?

**Comment by aayushrangwala** [comment]
@criscola I think the expectation of CLI flags to be given preference over the config file is valid. Considering the `AndFrom` comment
```
// AndFrom will use a supplied type and convert to Options
// any options already set on Options will be ignored, this is used to allow
// cli flags to override anything specified in the config file
```
