### ISSUE TITLE
Got error when using webhook

### ISSUE THREAD

**Issue by mrpre** [kubernetes-sigs/controller-runtime#1465]
```
Internal error occurred: failed calling webhook "mtaircluster.kb.io": webhook returned response.patchType but not response.patch
```

I'm using `helm upgrade` to upgrade my `cr` but got the error.  
Under what kind of circumstance could this happen?

controller-runtime version:
```
controller-runtime@v0.7.0
```

**Comment by mrpre** [comment]
the newer version is fixed

**Comment by yongxiu** [comment]
I also met this issue, curious which version did you upgrade to fixed this issue?
