### ISSUE TITLE
admission.NewDecoder doesn't perform nil check on scheme

### ISSUE THREAD

**Issue by wbrefvem** [kubernetes-sigs/controller-runtime#1471]
I discovered this while creating the following helper method for testing a mutating webhook. It returns no error:
```
func (mts *MutateTestSuite) injectDecoderWithNilScheme() error {
	decoder, err := admission.NewDecoder(nil)
	if err != nil {
		return err
	}
	mts.PodMutateHandler.InjectDecoder(decoder)
	return nil
}
```
which results in a panic when you try to decode an admission request:
```
err := myHandler.Decode(request, obj)
```

A nil check in `NewDecoder` would clean this up. Happy to work on it if folks are open to it.

**Comment by alvaroaleman** [comment]
I don't think we have many nilchecks of arguments and IMHO its sensible for functions to assume that no one will pass them a nil argument unless the godoc explicitly states that as valid.

**Comment by wbrefvem** [comment]
@alvaroaleman Sure, that makes sense. The problem that we're seeing here and other places is that testing error paths, both in webhooks and reconcilers, is difficult. Maybe the solution, here and elsewhere, is to use interfaces that can be easily mocked for unit tests? This would help us increase test coverage of things that can happen in the real world but currently are very difficult to test.

**Comment by nesv** [comment]
Sorry to jump in here: I'm currently experiencing a situation where my validation admission webhooks' `InjectDecoder` method are being passed a nil `*admission.Decoder`.

>I don't think we have many nilchecks of arguments and IMHO its sensible for functions to assume that no one will pass them a nil argument unless the godoc explicitly states that as valid.

I don't think the omission of stating whether a function _could_ be passed a nil value could (or should) imply the guarantee that it will never receive a nil value. I (admittedly, somewhat lazily) just assumed I would be getting a non-nil value passed to my admission handler's `InjectDecoder` method, and it's coming around to bite me after upgrading to v0.8.3.

**Comment by alvaroaleman** [comment]
> Sorry to jump in here: I'm currently experiencing a situation where my validation admission webhooks' InjectDecoder method are being passed a nil *admission.Decoder.

That sounds like a bug.

>  I (admittedly, somewhat lazily) just assumed I would be getting a non-nil value passed to my admission handler's InjectDecoder method, and it's coming around to bite me after upgrading to v0.8.3.

Yeah, that is the same assumption we want to make in controller-runtime which is why I am opposed to adding a nilcheck.
