### ISSUE TITLE
GetConfigOrDie log nothing

### ISSUE THREAD

**Issue by weilaaa** [kubernetes-sigs/controller-runtime#1475]
Hi there.

When we try to get *rest.Config if there is not kubeconfig exactly, it's supposed to log an error "no configuration has been provided, try setting KUBERNETES_MASTER environment variable" like code below:
```golang
func GetConfigOrDie() *rest.Config {
	config, err := GetConfig()
	if err != nil {
		log.Error(err, "unable to get kubeconfig")
		os.Exit(1)
	}
	return config
}
```
but I got "exit 1" directly without error log print:
**got**
```
➜  helloworld go run .   
exit status 1
```
**want**
```
2021/04/14 21:02:37 error no configuration has been provided, try setting KUBERNETES_MASTER environment variable
exit status 1
```

With permission，I'm willing to fix it.

```
Go deps:
k8s.io/api v0.20.5
k8s.io/apimachinery v0.21.0
k8s.io/client-go v0.20.5
sigs.k8s.io/controller-runtime v0.7.0
```

/kind bug

**Comment by joelanford** [comment]
@weilaaa You are likely not seeing logs because you have not set the logger before making this call. For an example, here is how the default kubebuilder scaffolding sets the logger: https://github.com/kubernetes-sigs/kubebuilder/blob/e6f3a70339b03f0509f19cd02cfa41c307d9a96c/testdata/project-v3/main.go#L66

**Comment by weilaaa** [comment]
@joelanford ctrl.SetLogger() works, but if should we initialize a default logger to avoid situation that logger not set or user forget it instead of logging nothing?

**Comment by joelanford** [comment]
Looks like this PR may be what you're after: https://github.com/kubernetes-sigs/controller-runtime/pull/1446

**Comment by weilaaa** [comment]
Thanks, that's what I want, count me in.

**Comment by shenlanse** [comment]
I think if  fail to `GetConfig`, should return error, instead of os.exit.  It requires log implementation `log.Error` method to flush in-memory log to disk or else the log would be lost. 
@joelanford @weilaaa
