### ISSUE TITLE
v0.8.3: admission.Handler is being injected with a nil admission.Decoder

### ISSUE THREAD

**Issue by nesv** [kubernetes-sigs/controller-runtime#1487]
Hi there!

Recently, I have been upgrading a code base from `sigs.k8s.io/controller-runtime` from v0.6.0 &rarr; v0.8.3. In v0.6.0, everything was working fine, but after updating to v0.8.3, our `admission.Handler`s are being injected with nil `*admission.Decoder`s. 

Nothing has changed with how we are registering any CRDs.

I am still doing some digging through the changesets between 0.6.0 and 0.8.3 to see if anything changed with regards to decoder injection, but I wanted to file this issue just to get the ball rolling. I will post a comment for anything I find along the way.

### Dependencies

As a side note about dependencies, any dependencies in the `k8s.io/` tree had already been updated to a v.20.x tag. The `k8s.io/` packages are updated separately, and when updating to controller-runtime v0.8.3, no `k8s.io/` packages were updated as a side-effect, since the `k8s.io/` packages were already at compatible version.

I felt it necessary to mention this aspect, to preempt any discussion about `k8s.io/` package versions, since the only change in dependencies that occurred before this issue started, was bumping `sigs.k8s.io/controller-runtime` from 0.6.0 &rarr; 0.8.3.

**Comment by nesv** [comment]
I'm officially stuck on where this issue could be happening.

With regards to the `runtime.Scheme` we pass when instantiating a `manager.Manager`, we are:

- Registering our CRDs with the [scheme.Builder](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/scheme#Builder) following the examples in the `scheme` package's godoc;
- Creating a [runtime.Scheme](https://pkg.go.dev/k8s.io/apimachinery/pkg/runtime#Scheme), passing it to `"k8s.io/client-go/kubernetes/scheme".AddToScheme`, as well as the `AddToScheme` functions in the packages for our CRDs;
- Creating a new [manager.Manager](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager#Manager) (via [manager.New](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager#New)), and passing the `runtime.Scheme` in via the [manager.Options](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.8.3/pkg/manager#Options).Scheme field.

So, all of the resource we want to handle in our handlers (both validating and mutating) are being added to the manager's scheme, yet the handlers are consistently getting nil decoders injected.

I have looked through the controller-runtime packages, and seen how the `runtime.Scheme` is passed around, but I'm still unable to figure out what could be causing a nil decoder to be injected.

**Comment by porridge** [comment]
Can you please post a stack trace where you see this `nil`?
Looking at the [library code](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/webhook/admission/webhook.go#L154-L162), I cannot see how a `nil` could get passed to [`InjectDecoder`](https://github.com/kubernetes-sigs/controller-runtime/blob/0d84ce43073cefb813563dd7586c943fa2c97783/pkg/webhook/admission/inject.go#L28).

Maybe in your case it simply is not passed at all, and you're observing the `nil` somewhere else?

**Comment by nesv** [comment]
Hi @porridge!

@d-honeybadger and I were working on this, and she may have found the culprit. I say "may" because although this fix works, it could indicate the code we are working with is doing something incorrectly.

In https://github.com/kubernetes-sigs/controller-runtime/pull/1307/files#diff-517abdd2f47b744e11990598de732426f33aba68600eaa9600d2ee20bc0b25dcL227-L256, the order of injection functions changes slightly, resulting in `webhook.InjectScheme` to be called _after_ `webhook.InjectFunc`. This means that [when `inject.InjectorInto` is called](https://github.com/kubernetes-sigs/controller-runtime/pull/1307/files#diff-517abdd2f47b744e11990598de732426f33aba68600eaa9600d2ee20bc0b25dcR209-R211), the scheme hasn't been set when [`cm.cluster.SetFields` is called](https://github.com/kubernetes-sigs/controller-runtime/pull/1307/files#diff-517abdd2f47b744e11990598de732426f33aba68600eaa9600d2ee20bc0b25dcR218-R220).

The "fix" in this case, is to move the call to `inject.InjectorInto` after the call to `cm.cluster.SetFields`.

**Comment by d-honeybadger** [comment]
@porridge Looking more closely, the "just-in-case" decoder injection that you [pointed out](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/webhook/admission/webhook.go#L154-L162) indeed works for most webhooks. The one case where it doesn't work is a webhook with a `multiValidating` handler (the same would be true for `multiMutating` handler`).
Since `multiValidating` handler does not implement `DecoderInjector` interface, doing `if _, err := InjectDecoderInto(w.GetDecoder(), w.Handler)` doesn't inject anything in the sub-handlers of the `multiValidating` handler.

**Comment by alvaroaleman** [comment]
FIxed in https://github.com/kubernetes-sigs/controller-runtime/pull/1502
