### ISSUE TITLE
Add RequeueReason field to reconcile.Result

### ISSUE THREAD

**Issue by bandesz** [kubernetes-sigs/controller-runtime#1489]
## What

When we requeue in our controllers, we would like to log the reason why we had to requeue.

Would you be open to add a new `RequeueReason string` field to the `reconcile.Result` struct?

**Comment by coderanger** [comment]
Why not log it from your controller code? You would have a lot more control there no matter what. Also this is commonly expressed in Events as well.

**Comment by bandesz** [comment]
@coderanger obviously we can, but we have a controller wrapper lib and we would like to handle requeue events in a single place.

E.g. we can have a common logic that:
 - logs the requeue event with the given reason
 - maybe creates an event with the reason (but I would leave this to the concrete controllers)
 - updates a field on the object's status so users see what's happening (as we have common fields on our object's statuses).
 
We could work around this by defining a custom RequeueError error type and return this information, but one can argue that a requeue event is not necessarily an error and shouldn't be returned as an error.

**Comment by coderanger** [comment]
I don't think this can be made usefully generic with a single string. There's too much context that should be managed in stuff like structured log values, Event types, etc. There just isn't much in common here.

**Comment by bandesz** [comment]
@coderanger my use case only requires a single string message. I don't need extra context, I can log that on a case-by-case basis in my controllers. The main purpose here is not logging, but getting back a single reason message to the users (either as a kubernetes event or a status message field on a status subresource).

I was making this suggestion as it's about a single string field, it requires only a single line of change and might be useful for some limited use-cases, like mine.

**Comment by coderanger** [comment]
We try to not support limited use cases unless they are overwhelmingly needed. I think the complexity savings of setting a field vs. calling log.Info is minimal enough to not really help. I'm sure it makes sense in your specific case but I don't think that's general enough for others to take advantage of.
