### ISSUE TITLE
controller-manager OOM

### ISSUE THREAD

**Issue by lazywhite** [kubernetes-sigs/controller-runtime#1491]
## project go.mod
```
require (
	github.com/go-logr/logr v0.1.0
	github.com/onsi/ginkgo v1.11.0
	github.com/onsi/gomega v1.8.1
	k8s.io/api v0.17.2
	k8s.io/apimachinery v0.17.2
	k8s.io/client-go v0.17.2
	sigs.k8s.io/controller-runtime v0.5.0
)
```

## Problem
1. I created 3 controllers to watch StatefulSet, Deployment, Service from all namespace,  when their annotation changed do something
2. I set memory limit to 200Mi
3. when in small cluster, it works fine
4.  when in a large scale cluster, there are too much resource to reconcile when booting that controller-manager got OOM Killed
5. So I can't set memory limit as a const.

Is there any solution?

**Comment by coderanger** [comment]
Yes, that is correct. It has to cache all of the objects so bigger cluster (or rather more of those objects) means bigger memory usage.

**Comment by lazywhite** [comment]
> Yes, that is correct. It has to cache all of the objects so bigger cluster (or rather more of those objects) means bigger memory usage.

but my colleague's code  use client-go to build a controller, and it consume only 30Mi on large scale cluster.  It use cache and informer inside of client-go

**Comment by coderanger** [comment]
We can't really say without seeing the code.

**Comment by lazywhite** [comment]
Problem got solved at last,  controller pod OOM is caused by in-memory configmap cache data. 
Should only watch specified configmap other than all namespace
