### ISSUE TITLE
Export interface only packages as separate module(s)?

### ISSUE THREAD

**Issue by reith** [kubernetes-sigs/controller-runtime#1495]
I will be happier if package `pkg/conversion` get exported as a separate module under controller-runtime project. This will allow me to make modules of my CRD types without pushing whole controller-runtime as dependency. This way, I can have a project that imports CRD types of different projects while those projects are using different versions of controller-runtime.

I've used this pattern and haven't see any big caveat so far. `controller-runtime`'s go.mod can still replace `pkg/conversion` with local path. Maybe having different versions of parent and child modules look confusing at first glance but I think we could make convention and document it.

**Comment by coderanger** [comment]
That imports from apimachinery which would bring in all the k/k deps and lock them, so I'm not sure that would help as much as hoped. As it stands, I don't think there is a good path to a non-dependency-hell implementation of webhooks in the types package like that. You would have to back down to the lower level webhooks API and implement them outside of the types package. Go unfortunately puts heavy limitations on making this nice :-(

**Comment by reith** [comment]
Well, as long as it's about reducing dependency depth of types modules (separated modules of CRD go types) they already import apimachinery for` ObjectMeta`, `TypeMeta` and registering CRDs. I guess I didn't understood which new limitation this approach will introduce?

**Comment by coderanger** [comment]
Which c-r dependencies are you worried about? The ones that cause problems are usually all the k/k packages since those generally get cranky if they aren't all on matching versions.

**Comment by reith** [comment]
The controller-runtime itself can be incompatible.. IIRC at some point logger constructor function has changed. It may rarely change but I guess less dependencies are better.

**Comment by coderanger** [comment]
Also true, but given that each c-r version encodes specific k/k dependency versions already, you aren't likely making things any worse by having to deal with that. It's all a package deal of dependency hell :D

**Comment by reith** [comment]
Each c-r versions add minimal versions of k/k dependencies to graph. Projects using controller-runtime can use higher versions of k/k components. If `pkg/conversion` go to a separate module, those projects needing just that package won't get locked to any specific k/k version, right? If `pkg/conversion` tend to bump to newer apimachinery very often, yes, projects using that module probably have less options of k/k to choose but I don't think we need to bump to newer versions since those interfaces are really shallow.

Do you agree depending on whole controller-runtime increase the chance of incompatibilities in dependency graph?

**Comment by coderanger** [comment]
It will get locked, that's the nature of Go modules. You can't declare a dependency without locking it AFAIK. So that apimachinery dep functionally locks your entire dep graph into a single shape. With or without c-r itself, there is only one version of things that will work together. Go lacks the functionality of other langs for "floating library deps" where a library can depend on a range of versions like "plz give client-go >= 0.17" or something. Or more specifically Go modules v1 lacks that, at least as far as I know, again might be wrong about that.

**Comment by reith** [comment]
That's not what I understood by [Minimal Version Selection](https://golang.org/ref/mod#minimal-version-selection) algorithm.

Go modules lack the functionality of saying "plz give me client-go > 0.17" for good but, a library user can still add client-go 0.18 directly as dependency and it will be used even if library added client-go 0.17 as dependency.

**Comment by reith** [comment]
While I was forking `pkg/conversion` as a sub-module of my project, I learned apimachinery doesn't pull anything from k/k, at-least if it just want to satisfy the mentioned interface and it's actually the other way round; some k/k packages import apimachinery. This is list of all packages that `pkg/conversion` depend on:

```
github.com/gogo/protobuf/proto
k8s.io/apimachinery/pkg/conversion
k8s.io/apimachinery/pkg/conversion/queryparams
k8s.io/apimachinery/pkg/runtime
k8s.io/apimachinery/pkg/runtime/schema
k8s.io/apimachinery/pkg/util/errors
k8s.io/apimachinery/pkg/util/json
k8s.io/apimachinery/pkg/util/naming
k8s.io/apimachinery/pkg/util/runtime
k8s.io/apimachinery/pkg/util/sets
k8s.io/apimachinery/third_party/forked/golang/reflect
k8s.io/klog
```

Nothing more than what is needed for a regular CRD types package.
