### ISSUE TITLE
How to pass client to the webhook implmentation?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-runtime#1505]
Our CRD validator and mutator needs additional information from the cluster to perform its task. From what I can tell from the docs, there does not seem to be a way to pass client to the validator and mutator. https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html

```
func (r *CronJob) SetupWebhookWithManager(mgr ctrl.Manager) error {
    return ctrl.NewWebhookManagedBy(mgr).
        For(r).
        Complete()
}
```

Is this possible? If not, can this be supported? It seems it can take an approach similar to the `Reconciler` where the `Complete()` is passed the implementation.

**Comment by tamalsaha** [comment]
https://github.com/coderanger/migrations-operator/blob/main/webhook/webhook.go#L44-L50

**Comment by alvaroaleman** [comment]
This isn't possible with the `Validator` and `Defaulter` and not desirable, because it would mean that your API depends on a specific controller-runtime version.

https://github.com/kubernetes-sigs/controller-runtime/tree/master/examples/builtins has examples on how to build a Mutating or Validating webhook without using the `Validator` and `Defaulter`.

**Comment by tamalsaha** [comment]
> it would mean that your API depends on a specific controller-runtime version.

Can you explain a bit more? By api, do you mean YAML format or the go code? We need access to some other object in the cluster not to the CR object itself.

**Comment by alvaroaleman** [comment]
By api I meant the go types in your code base

**Comment by alvaroaleman** [comment]
> I see what you mean but I think those dependencies already exist because k8s.io/api, k8s.io/apimachinery does not work across minor k8s releases anyway.

k8s.io/api should and k8s.io/apimachinery is not something I would expect a go package that holds the types for a CRD to depend on?

**Comment by tamalsaha** [comment]
metav1.TypeMeta, metv1.ObjectMeta those are in apimachinery. So, every k8s type depends on k8s.io/apimachinery.

**Comment by LochanRn** [comment]
@tahsinrahman I faced a similar issue, I needed the client in one of my webhook, I wrote a low level custom webhook with a very similar functionality to that of the existing one like it has the validator and defaulter interface with the client object passed in 😊

I changed the interface to something like this: https://github.com/spectrocloud/cluster-api-provider-azure/blob/d721b397f6c84d0225a6494fed4daf3c7d3b9ec1/util/webhook/validator.go#L35-L40

Integrate the webhook with the manager: https://github.com/spectrocloud/cluster-api-provider-azure/blob/d721b397f6c84d0225a6494fed4daf3c7d3b9ec1/main.go#L516-L524

The Validator and Defaulter for API/GO-TYPE: https://github.com/spectrocloud/cluster-api-provider-azure/blob/system-node-pool/exp/api/v1alpha4/azuremanagedmachinepool_webhook.go

@tamalsaha : You can implement it in your code-base in a similar way.  

@alvaroaleman If we can modify the exiting Validator or Defaulter interface something like [this](https://github.com/spectrocloud/cluster-api-provider-azure/blob/d721b397f6c84d0225a6494fed4daf3c7d3b9ec1/util/webhook/validator.go#L35-L40). Would it still depend on the 
controller runtime. If yes can you elaborate a little please. 

@alvaroaleman returning errors in defaulter interface/rejecting a mutation and expecting a client object within the webhook are some of them common needs, where many people might need it, like validate things based on cluster state and stuff. 

Extending the existing interfaces to provide client would be great actually.

**Comment by strideynet** [comment]
> @alvaroaleman If we can modify the exiting Validator or Defaulter interface something like this. Would it still depend on the
controller-runtime version. If yes can you elaborate a little please.

Including the client is exactly *what* makes it dependent on the controller-runtime version, since the client (and it's defined interface, and behaviour) is part of the controller-runtime. There isn't a way the client can be provided and it to not depend on the controller-runtime version.

In most cases, people are able to write Defaulters and Validators that do not need the Client, and this is probably the behaviour that should be encouraged in most cases. It would be unideal for the behaviour of your resources (with respect to admission/mutation) to change in a breaking way due to a change in the controller-runtime.

Users that need this additional power are free to use the hook server registration functionality to build their own validators/mutators, and this isn't particularly complex e.g https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/mutatingwebhook.go

**Comment by alvaroaleman** [comment]
> metav1.TypeMeta, metav1.ObjectMeta those are in apimachinery. So, every k8s type depends on k8s.io/apimachinery.

Sorry, what I meant was that there are certain parts of apimachinery that are extremely stable like the metav1 package and others that are not.

@LochanRn what @strideynet wrote should answer your questions.

**Comment by LochanRn** [comment]
> > metav1.TypeMeta, metav1.ObjectMeta those are in apimachinery. So, every k8s type depends on k8s.io/apimachinery.
> 
> Sorry, what I meant was that there are certain parts of apimachinery that are extremely stable like the metav1 package and others that are not.
> 
> @LochanRn what @strideynet wrote should answer your questions.

yup thanks ☺️

**Comment by LochanRn** [comment]
> > @alvaroaleman If we can modify the exiting Validator or Defaulter interface something like this. Would it still depend on the
> > controller-runtime version. If yes can you elaborate a little please.
> 
> Including the client is exactly _what_ makes it dependent on the controller-runtime version, since the client (and it's defined interface, and behaviour) is part of the controller-runtime. There isn't a way the client can be provided and it to not depend on the controller-runtime version.
> 
> In most cases, people are able to write Defaulters and Validators that do not need the Client, and this is probably the behaviour that should be encouraged in most cases. It would be unideal for the behaviour of your resources (with respect to admission/mutation) to change in a breaking way due to a change in the controller-runtime.
> 
> Users that need this additional power are free to use the hook server registration functionality to build their own validators/mutators, and this isn't particularly complex e.g https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/mutatingwebhook.go

@alvaroaleman @strideynet 
So I have a doubt is there a difference between the registering a webhook normally and registering it using hook server ?
Does hook-server implementation also make the api depend on the specific conntroller-runtime versions ?

**Comment by alvaroaleman** [comment]
> So I have a doubt is there a difference between the registering a webhook normally and registering it using hook server ?
Does hook-server implementation also make the api depend on the specific conntroller-runtime versions ?

One is defined in our api package, the other in a different package. The api package must not depend on frequently changing bits, or external consumption of it becomes a huge PITA. What the rest of your packages in the repo depend on doesn't matter, as they are not expected to be imported by others.

**Comment by pigletfly** [comment]
related discussion in  https://github.com/kubernetes-sigs/kubebuilder/issues/1216
