### ISSUE TITLE
Starting event source log for Channel contains error

### ISSUE THREAD

**Issue by shawn-hurley** [kubernetes-sigs/controller-runtime#153]
Right now I am getting this log when starting a `watch` on a source of type `Channel`

{"level":"info","ts":1537378068.766453,"logger":"kubebuilder.controller","caller":"controller/controller.go:120","msg":"Starting EventSource","Controller":"database-controller","SourceError":"json: unsupported type: <-chan event.GenericEvent"}

**Comment by DirectXMan12** [comment]
huh, I can't find where we log any field called `SourceError`.  In `pkg/internal/controller/controller.go` on line 120, we have `log.Info("Starting EventSource", "Controller", c.Name, "Source", src)`, but I'm having trouble seeing why it would log that message instead.  Do you have a simple reproducer that we can play around with?

**Comment by shawn-hurley** [comment]
It is going to log that message because of https://github.com/kubernetes-sigs/controller-runtime/blob/d4dff204bfca6035d3e189d295d9b78278bfe041/pkg/source/source.go#L105
is the source. I believe the logger is attempting to take the source struct and convert to JSON. But channels, I don't think, can be converted to JSON. does that make sense?

**Comment by DirectXMan12** [comment]
aaaah, yeah, that makes sense.  Maybe we should just implement `String()` on all the source the source types?

**Comment by shawn-hurley** [comment]
That makes sense to me, I can take this on if you have other stuff going on?

**Comment by DirectXMan12** [comment]
yeah, that'd be great :-)
