### ISSUE TITLE
Support steadily increasing `RequeueAfter`

### ISSUE THREAD

**Issue by salaxander** [kubernetes-sigs/controller-runtime#1534]
Hey folks! I've got a feature request that I'm happy to help implement! I'm opening this to discuss the design and get people's thoughts on the idea :)

Currently, the `Result` a reconcile returns looks like this.
```go
// Result contains the result of a Reconciler invocation.
type Result struct {	
    // Requeue tells the Controller to requeue the reconcile key.  Defaults to false.	
    Requeue bool
    
    // RequeueAfter if greater than 0, tells the Controller to requeue the reconcile key after the Duration.	
    // Implies that Requeue is true, there is no need to set Requeue to true at the same time as RequeueAfter.	
    RequeueAfter time.Duration
}
```

What I'm proposing is adding something to the effect of:
```go
// RequeueInterval behaves the same as RequeueAfter, but adds the RequeueInterval time for each requeue.
RequeueInterval time.Duration
```

This would be super helpful to prevent objects from getting trapped in a frequent requeue. What I haven't figured out yet is a good way to end the increase, or reset the tracked interval, but happy to discuss that!

Would love some thoughts on this :)

**Comment by coderanger** [comment]
This is already what happens when you use `Requeue: True`. There is a combo token-bucket/exponential backoff system baked into the workqueue library we use under the hood. That is activated either on `Requeue` or when returning an error.

**Comment by salaxander** [comment]
Well that's wildly cool and I had no idea! Thanks!!
