### ISSUE TITLE
Is release v0.8.3 compatible with k8s 1.21?

### ISSUE THREAD

**Issue by gohilankit** [kubernetes-sigs/controller-runtime#1538]
I'm trying to update kubernetes framework dependencies in my project to 1.21.

Here's what my go.mod looks like:
```
go 1.15

require (
	.
        .
	honnef.co/go/tools v0.1.4 // indirect
	k8s.io/api v0.21.0
	k8s.io/apiextensions-apiserver v0.21.0
	k8s.io/apimachinery v0.21.0
	k8s.io/client-go v0.21.0
	k8s.io/kubectl v0.0.0
	k8s.io/kubernetes v1.21.0
	k8s.io/mount-utils v0.21.0
	k8s.io/sample-controller v0.21.0
	k8s.io/utils v0.0.0-20210111153108-fddb29f9d009
	sigs.k8s.io/controller-runtime v0.8.3
)
```

If I try to build this, I get the below error:
```
../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/client_go_adapter.go:134:19: cannot use &(latencyAdapter literal) (value of type *latencyAdapter) as metrics.LatencyMetric value in struct literal: wrong type for method Observe (have func(verb string, u net/url.URL, latency time.Duration), want func(ctx context.Context, verb string, u net/url.URL, latency time.Duration)) (compile)
../../pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/client_go_adapter.go:135:19: cannot use &(resultAdapter literal) (value of type *resultAdapter) as metrics.ResultMetric value in struct literal: wrong type for method Increment (have func(code string, method string, host string), want func(ctx context.Context, code string, method string, host string)) (compile)
make: *** [staticcheck] Error 1
```

Please note earlier we were using 0.8.3 with k8s 0.20.5 modules. But looks like it's not compatible with 0.21.x modules for different k8s components.

But using controller-runtime [v0.9.0-beta.5](https://github.com/kubernetes-sigs/controller-runtime/tree/v0.9.0-beta.5) works fine. But we don't want to use it as it's still in pre-release.

Are there any plans to make an official release soon that's compatible with 1.21?

**Comment by gohilankit** [comment]
Looks like it's not compatible with `client-go v0.21.x`.

**Comment by alvaroaleman** [comment]
No, it is not.

**Comment by coderanger** [comment]
Just for very slight clarification, we are not compatible with client-go 0.21 however the Kubernetes API is forward as well as backward compatible so you can use controller-runtime with Kubernetes 1.21 itself.

**Comment by gohilankit** [comment]
Thanks for clarifying @alvaroaleman and @coderanger . Is there any tentative date to officially release v0.9.0 (which is compatible with client-go 0.21) ?

**Comment by RobertLucian** [comment]
@alvaroaleman @coderanger any idea when this will get fixed? Been trying to upgrade to:

```
k8s.io/api v0.22.11
k8s.io/apimachinery v0.22.11
k8s.io/client-go v0.22.11
k8s.io/metrics v0.22.11
```

But I keep getting the following error:

```
# sigs.k8s.io/controller-runtime/pkg/metrics
../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/client_go_adapter.go:134:3: cannot use &latencyAdapter{...} (type *latencyAdapter) as type metrics.LatencyMetric in field value:
        *latencyAdapter does not implement metrics.LatencyMetric (wrong type for Observe method)
                have Observe(string, url.URL, time.Duration)
                want Observe(context.Context, string, url.URL, time.Duration)
../../go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/metrics/client_go_adapter.go:135:3: cannot use &resultAdapter{...} (type *resultAdapter) as type metrics.ResultMetric in field value:
        *resultAdapter does not implement metrics.ResultMetric (wrong type for Increment method)
                have Increment(string, string, string)
                want Increment(context.Context, string, string, string)
```

Without this in, I seem to be stuck on the following versions:

```
k8s.io/api v0.20.15
k8s.io/apimachinery v0.20.15
k8s.io/client-go v0.20.15
k8s.io/metrics v0.20.8
```

**Comment by RobertLucian** [comment]
@FillZpp `github.com/prometheus/client_golang` is currently set to `v1.11.0`, so this doesn't seem to be the problem then. This is the current `go.mod` that we use:

https://github.com/cortexlabs/cortex/blob/update-versions/go.mod#L6-L47

**Comment by FillZpp** [comment]
> @FillZpp `github.com/prometheus/client_golang` is currently set to `v1.11.0`, so this doesn't seem to be the problem then. This is the current `go.mod` that we use: https://github.com/cortexlabs/cortex/blob/update-versions/go.mod#L6-L47

@RobertLucian  Sorry, my mistake. It is because controller-runtime v0.8 is not compatible with K8s 1.22.

> cannot use &latencyAdapter{...} (type *latencyAdapter) as type metrics.LatencyMetric in field value

From this case, you should use at least controller-runtime >= v0.9.x. But v0.10.x is better, which exactly matches K8s 1.22.

**Comment by RobertLucian** [comment]
@FillZpp thanks a lot! That fixed it!
