### ISSUE TITLE
[Question] Use client to instead client-go

### ISSUE THREAD

**Issue by iutx** [kubernetes-sigs/controller-runtime#1544]
I want to instead controller-runtime/client to instead client-go to operate kubernetes and crd resource.
But i can't find watch interface
How can i watch resource change
Thanks

**Comment by coderanger** [comment]
You pretty much have to use the c-r client. I guess there's nothing stopping you from setting up your own client-go client from scratch but you're not going to find any particular help, you just have to do it as if you weren't using controller-runtime in the first place (modulo maybe using the GetConfig() helper on the manager). There is no direct access to the underlying informers, those are abstracted away.

**Comment by iutx** [comment]
we use Clientset and c-r client to operator kubernetes resources.
Clinset operate kubernetes native resource.
c-r client operate CRD resource and kubernetes native resource, but doesn't provide watch.
