### ISSUE TITLE
Custom metrics dissappear

### ISSUE THREAD

**Issue by kotyara85** [kubernetes-sigs/controller-runtime#1547]
Hey there,
I do export custom metrics (registered clusters)
```
r.metrics = ctrlmetrics.NewGaugeVec("app", "controller", fmt.Sprintf("%s_connected", api.Clusters), fmt.Sprintf("Connected clusters"), []string{"cluster"})
```
I add it later during reconciliation
```
r.metrics.WithLabelValues(req.Name).Set(1)
```

Looks like after some time that metrics disappears (~120 entries). Is there some max number of lines prometheus metrics endpoint can export?

Restarting the operator fixes the problem

Thanks

**Comment by coderanger** [comment]
Without actually checking if it caps label cardinality, you definitely shouldn't be doing that anyway. Best case it is saving you from yourself :) Don't use labels that vary with user input.

**Comment by kotyara85** [comment]
Em, labels are actually static. api.Clusters is const
