### ISSUE TITLE
Redo client.List() in a backward compatible way

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/controller-runtime#155]
#106 was reverted by #146.

Redo kubernetes-sigs/controller-runtime#106 in a backward compatible way.
We can probably following the approach suggested in https://github.com/kubernetes-sigs/controller-runtime/pull/146#issuecomment-422206874.

**Comment by mengqiy** [comment]
@grantr Do you have bandwidth to work on this?

**Comment by grantr** [comment]
I could probably get to it sometime next week. If anyone else has an earlier opening, feel free to take it. :smile:

**Comment by mengqiy** [comment]
Any update?

**Comment by grantr** [comment]
Sorry! This got pushed down the priority stack and I might not get to it for a while. In the meantime, I'm curious if this work is still desired based on https://github.com/kubernetes-sigs/controller-runtime/pull/146#issuecomment-424384073comment by @DirectXMan12.

**Comment by DirectXMan12** [comment]
Still need to figure out what the policy is on this.  Haven't had a chance to discuss it yet :-)

**Comment by mengqiy** [comment]
Closed by #294.
