### ISSUE TITLE
Add interface and/or utility for Event

### ISSUE THREAD

**Issue by micnncim** [kubernetes-sigs/controller-runtime#1553]
[sigs.k8s.io/controller-runtime/pkg/event](https://github.com/kubernetes-sigs/controller-runtime/blob/fbf50b04fe17b0f091430d22557245d2aedabfd4/pkg/event/event.go) has several event types as structs, that is, `CreateEvent`, `UpdateEvent`, `DeleteEvent`, and `GenericEvent`.

It'd be helpful if the package provides some abstraction or utilities for such event types. For example, a function that returns the type of event like below.

```go
func Unwrap(evt interface{}) (ctrlclient.Object, EventType) {
	switch e := evt.(type) {
	case ctrlevent.CreateEvent:
		return e.Object, EventTypeCreate

	case ctrlevent.UpdateEvent:
		return e.ObjectNew, EventTypeUpdate

	case ctrlevent.DeleteEvent:
		return e.Object, EventTypeDelete

	case ctrlevent.GenericEvent:
		return e.Object, EventTypeGeneric

	default:
		return nil, EventTypeUnknown
	}
}
```

Or, it may be good if the package has an interface for each event type.

```go
type Event interface {
  // ...
}

// CreateEvent, UpdateEvent, DeleteEvent, and GenericEvent implements Event interface.
```

In my case, I'm developing a custom event handler that implements [(sigs.k8s.io/controller-runtime/pkg/handler).EventHandler](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/handler#EventHandler). In its logic, I need to check the event's type many times since some handler does the same process regardless of the event type.

**Comment by coderanger** [comment]
Unfortunately I don't think this is possible given that Update events get two objects. I'm also not really sure how this is useful overall? We already have EnqueueRequestsFromMapFunc which I think is similar to what you're describing.

**Comment by alvaroaleman** [comment]
>  In its logic, I need to check the event's type many times since some handler does the same process regardless of the event type.

That is pretty vague. As @coderanger mentioned if you just want a mapper that doesn't care about event types, there is `EnqueueRequestsFromMapFunc`. If you care about event types, there is Funcs. If neither of these work well for you, please describe why.

**Comment by micnncim** [comment]
Thanks, `EnqueueRequestsFromMapFunc` is suitable for my use case.

**Comment by alvaroaleman** [comment]
Closing this issue then, feel free to reopen if that is premature :)
