### ISSUE TITLE
Support one2many conversions

### ISSUE THREAD

**Issue by rpieczon** [kubernetes-sigs/controller-runtime#1554]
I am trying to convert one version of CRD to another one. As I see conversion webhook supports one2one conversion type.
In my case old asset has to be converted into one or more instances of new assets. Is there any pattern which I can follow?
If no, is there any chance to add support for mentioned converions(one2many)?

**Comment by coderanger** [comment]
This isn't related to how conversion webhooks work, nor would it make any sense given how Kubernetes versions work. It's a fully-connected hub-and-spoke model so a single conversion is all you ever need.

/close
