### ISSUE TITLE
Using envtest to start multiple control planes

### ISSUE THREAD

**Issue by akafazov** [kubernetes-sigs/controller-runtime#1557]
In my test scenario, I am creating an operator which monitors CRD on the cluster where the controller is running, but also connects to external API servers by creating additional managers and controllers, one for each new API server. I want to use envtest to simulate those API servers, but the issue I am running into is I don't know how to change the number of Nodes in the external clusters, because this is what the extra operators are watching for? Is starting multiple control planes even supported in envtest?

**Comment by woodgear** [comment]
same question.

**Comment by nikhil-nutanix** [comment]
Did anyone ever figure this out?
