### ISSUE TITLE
Retaining LGTM through squashes

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes-sigs/controller-runtime#1569]
Hi!

After https://github.com/kubernetes/kubernetes/issues/103096, `k/k` will retain `lgtm` through commit squashes. This has been brought up on contribex on slack as well and there doesn't seem to be any objection to this. Considering the process advantage that this provides, would `controller-runtime` prefer having this as well? 

Thank you!

cc @vincepri @alvaroaleman

**Comment by alvaroaleman** [comment]
I don't really care one way or another, ppl usually either know to squash or I apply the tide mergemethod label so it gets merged on squash
