### ISSUE TITLE
Timeout waiting for process kube-apiserver to stop

### ISSUE THREAD

**Issue by ysksuzuki** [kubernetes-sigs/controller-runtime#1571]
#### What happened:

`envtest.Environment.Stop()` raises the error `timeout waiting for process kube-apiserver to stop` with kube-apiserver 1.21.2 that set up using `setup-envtest use -p env`.

```
  Unexpected error:
      <errors.aggregate | len:1, cap:1>: [
          <*errors.errorString | 0xc000328c00>{
              s: "timeout waiting for process kube-apiserver to stop",
          },
      ]
      timeout waiting for process kube-apiserver to stop
  occurred
```

#### How to reproduce it (as minimally and precisely as possible):

Run [this envtest](https://github.com/cybozu-go/coil/blob/main/v2/Makefile#L36) with kube-apiserver 1.21.2.

#### Environment:

- controller-runtime: 0.9.2
- kube-apiserver: 1.21.2

**Comment by stijndehaes** [comment]
using 1.20.2 for example works fine

**Comment by varshaprasad96** [comment]
+1, hit the same issue and using 1.20 binaries works fine.

**Comment by erikgb** [comment]
+1, it would be nice if someone with the skills could take a look asap. 😉 

/priority important-soon

**Comment by joelanford** [comment]
I'm not able to reproduce this issue with the envtest 1.22.0 binaries and controller-runtime v0.9.6.

To try to reproduce, I bumped to the latest k8s, envtest, and c-r versions [here](https://github.com/operator-framework/helm-operator-plugins/pull/102)

**Comment by hickeyma** [comment]
Tested using the [cronjob-tutorial](https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project), results as follows:

- Kubernetes v1.20.2: No issue
- Kubernetes v1.21.4: Issue as stated 
- Kubernetes v1.22.0: Issue as stated

So, looks like issue in Kubernetes v1.21, v1.22.

**Comment by hickeyma** [comment]
This is what I have found  so far. From Kubernetes 1.21+, when it tries to cleanup the test environment, there is a clash if a custom controller is created during testing. It would seem that the controller is still running and `kube-apiserver` will not respond to shutdown during tear down.

I can get it to work by, changing controller goroutine:

```go
go func() {
		err = k8sManager.Start(ctrl.SetupSignalHandler())
		Expect(err).ToNot(HaveOccurred())
}()
```

to:

```go
go func() {
		defer GinkgoRecover()
		err = k8sManager.Start(ctrl.SetupSignalHandler())
		Expect(err).ToNot(HaveOccurred(), "failed to run manager")
		gexec.KillAndWait(4 * time.Second)

		// Teardown the test environment once controller is fnished.
		// Otherwise from Kubernetes 1.21+, teardon timeouts waiting on
		// kube-apiserver to return
		err := testEnv.Stop()
		Expect(err).ToNot(HaveOccurred())
}()
```

and disabling the teardown in `AfterSuite`.

**Comment by tenstad** [comment]
Is it a mistake that the `ctx` with cancel is replaced by `context.Background()`:
https://github.com/cybozu-go/coil/blob/main/v2/pkg/ipam/suite_test.go#L97

**Comment by erikgb** [comment]
Thx @tenstad! I think this issue can ble closed, as not a problem (here), ref. https://github.com/cybozu-go/coil/pull/189.

I will prepare a PR to fix the skaffolding (and doc) in kubebuilder, ref. the workaround implemented in https://github.com/kubernetes-sigs/kubebuilder/pull/2302. CC: @hickeyma

**Comment by Aisuko** [comment]
Hi, guys. Hit the same issue here with `1.22.1-darwin-amd64`

**Comment by Aisuko** [comment]
I know this is not a solution, if anyone hit same issue like me. This may work for you, I try the solution above, migrate the `testEnv.Stop` from `AfterSuite` to `BeforeSuite` may cause the `kube-apiserver` process killed failed. 

```
var _ = AfterSuite(func() {
	// https://github.com/kubernetes-sigs/controller-runtime/issues/1571
	cancel()
	By("tearing down the test environment,but I do nothing here.")
	err := testEnv.Stop()
        // Set 4 with random
	if err != nil {
		time.Sleep(4 * time.Second)
	}
	err = testEnv.Stop()
	Expect(err).NotTo(HaveOccurred())
})
```

**Comment by psaia** [comment]
> I know this is not a solution, if anyone hit same issue like me. This may work for you, I try the solution above, migrate the `testEnv.Stop` from `AfterSuite` to `BeforeSuite` may cause the `kube-apiserver` process killed failed.
> 
> ```
> var _ = AfterSuite(func() {
> 	// https://github.com/kubernetes-sigs/controller-runtime/issues/1571
> 	cancel()
> 	By("tearing down the test environment,but I do nothing here.")
> 	err := testEnv.Stop()
>         // Set 4 with random
> 	if err != nil {
> 		time.Sleep(4 * time.Second)
> 	}
> 	err = testEnv.Stop()
> 	Expect(err).NotTo(HaveOccurred())
> })
> ```

For the impatient:

```go
	err := (func() (err error) {
		// Need to sleep if the first stop fails due to a bug:
		// https://github.com/kubernetes-sigs/controller-runtime/issues/1571
		sleepTime := time.Duration(1) * time.Millisecond
		for i := 0; i < 12; i++ { // Exponentially sleep up to ~4s
			if err = testEnv.Stop(); err == nil {
				return
			}
			sleepTime *= 2
			time.Sleep(sleepTime)
		}
		return
	})()
        Expect(err).NotTo(HaveOccurred())
```

**Comment by UgurTheG** [comment]
Maybe if someone still ever encounters this problem

**Comment by UgurTheG** [comment]
Maybe if someone still encounters this problem - setting `ControlPlaneStopTimeout` manually helped me:

```go
	testEnv = &envtest.Environment{
		CRDDirectoryPaths: []string{
			filepath.Join("..", "..", "config", "crd", "bases"),
		},
		ErrorIfCRDPathMissing:   true,
		ControlPlaneStopTimeout: 1 * time.Minute, // Or any duration that suits your tests
	}
```

**Comment by KunWuLuan** [comment]
> ```go
> 	err := (func() (err error) {
> 		// Need to sleep if the first stop fails due to a bug:
> 		// https://github.com/kubernetes-sigs/controller-runtime/issues/1571
> 		sleepTime := 1 * time.Millisecond
> 		for i := 0; i < 12; i++ { // Exponentially sleep up to ~4s
> 			if err = testEnv.Stop(); err == nil {
> 				return
> 			}
> 			sleepTime *= 2
> 			time.Sleep(sleepTime)
> 		}
> 		return
> 	})()
>         Expect(err).NotTo(HaveOccurred())
> ```

This works for me.
