### ISSUE TITLE
Using client-go's fake clientset with controller-runtime

### ISSUE THREAD

**Issue by shashankram** [kubernetes-sigs/controller-runtime#1572]
I am exploring the usage of controller-runtime for the client caches and informers functionality, which provides some abstractions that allow informers for different API resources to be bootstrapped in a generic manner, using https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/cache.go.

The problem is that a lot of our code is using client-go's fake clientset for testing, and caches/informers are initialized based on the clientset. This works well because in testing, resources can be created using the fake clientset, and the informers/caches function as expected as they would with an actual clientset built using `NewForConfigOrDie()`. 

Is there a way to do the same with controller-runtime with a fake clientset to that can be used to populate the caches for testing?

**Comment by Szymongib** [comment]
Perhaps this is something you might want to look at https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/fake/client.go#L68
