### ISSUE TITLE
Filtering on metadata.deletionTimestamp with client.List and ListOptions

### ISSUE THREAD

**Issue by ClemOzil** [kubernetes-sigs/controller-runtime#1581]
Hello everybody,

I need to list every pods that are not in "Terminating". One of my problem is that those pods still have "status.Phase == Running", I need to check their deletionTimestamp to be able to detect them.

According to this thread (and my personnal experience) (https://github.com/kubernetes/kubectl/issues/450) we also can’t use the FieldSelector on the deletionTimestamp field.

This solution seems to work :

`kubectl get pods --template '{{range .items}}{{ if not .metadata.deletionTimestamp }}{{.metadata.name}}{{"\n"}}{{end}}{{end}}'`

Is there a trick to add the "template" part in my r.List ?

Right now, my code looks like : 

podList := &corev1.PodList{}
listOpts := []client.ListOption{
    client.InNamespace(req.NamespacedName.Namespace),
    client.MatchingLabels{"my-deployment": req.NamespacedName.Name},
}
err := r.List(ctx, podList, listOpts...)
if err != nil {
    return false, err
}
// Can't list "Not terminating" pods
podsNotTerminating := make([]corev1.Pod, 0)
for _, pod := range podList.Items {
    if pod.DeletionTimestamp == nil || pod.DeletionTimestamp.IsZero() {
        podsNotTerminating = append(podsNotTerminating, pod)
    }
}

I'd like to be able to just do : 

podList := &corev1.PodList{}
listOpts := []client.ListOption{
    client.InNamespace(req.NamespacedName.Namespace),
    client.MatchingLabels{"my-deployment": req.NamespacedName.Name},
    //Add a filter on "metadata.deletionTimestamp" here
}
err := r.List(ctx, podList, listOpts...)
if err != nil {
    return false, err
}

Do you have a solution for me ?

Thank you all for your time.

**Comment by coderanger** [comment]
https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup shows how to set up a field indexer which can index whatever behavior you want. You can use that with List.

**Comment by ClemOzil** [comment]
Thanks a lot, it works great ! 

Had a little bit of trouble at first since the client cache was disabled for pods. Enabling it doesn't seem to break anything right now.
