### ISSUE TITLE
Improved support for deleteFromPrimitiveList?

### ISSUE THREAD

**Issue by dee0** [kubernetes-sigs/controller-runtime#1583]
Have been looking into the right way to remove my finalizer.    Based on what I see in the kubernetes docs and testing it looks like the right way to do this if using kubectl is to run 
kubectl patch myresourcekind myresource --patch "$(cat patch-file-delete.yaml)"
where patch-file-delete.yaml is something like 
metadata:
  $deleteFromPrimitiveList/finalizers:
    - mycontroller/myfinalizer 

Searching through the controller-runtime codebase I don't see any refs to the prefix deleteFromPrimitiveList and after a cursory review of RemoveFinalizer it appears that it tries to get all of the current finalizers, remove the the specified finalizer, and then update the resource with the new list.   Obviously this has the potential for timing problems.    

Fwiw it looks like I can RawPatch if I really want to use deleteFromPrimitiveList but it would be nice if there was some built in support for it.

**Comment by varshaprasad96** [comment]
@dee0 - would the finalizer library be helpful here: https://github.com/kubernetes-sigs/controller-runtime/tree/master/pkg/finalizer

**Comment by dee0** [comment]
Thanks @varshaprasad96 for the response. 
I took a quick look and unfortunately it does not appear to help.
