### ISSUE TITLE
How to run "envtest" with provided root cert/key?

### ISSUE THREAD

**Issue by chunter0** [kubernetes-sigs/controller-runtime#1592]
I'm trying to test a service that can create admin credentials for a user within a cluster and I'm hoping to test this use case with envtest package. But so far I've been unsuccessful. Currently, when an envtest.Environment is started by default all the required certs are generated and passed to a temporary CertDir directory. Since the rootCA Key is not in that directory I was hoping I could pass in self-signed ca certs. Is this currently  possible?

Current Default Certs:
```
➜  test ls -l envcerts      
total 56
-rw-------  1 chunter  staff  5650 Jul 12 17:50 1158190149.kubecfg
-rw-r-----  1 chunter  staff  1196 Jul 12 17:49 apiserver.crt
-rw-r-----  1 chunter  staff  1704 Jul 12 17:49 apiserver.key
-rw-r-----  1 chunter  staff  1139 Jul 12 17:49 client-cert-auth-ca.crt     <--- Cluster RootCA (But no key)
-rw-r-----  1 chunter  staff  1139 Jul 12 17:49 sa-signer.crt
-rw-r-----  1 chunter  staff  1704 Jul 12 17:49 sa-signer.key
➜  test 
```

Environment:
```
➜  ~ go version    
go version go1.16.4 darwin/amd64
➜  ~ /usr/local/kubebuilder/bin/kube-apiserver --version           
Kubernetes v1.19.2
```

**Comment by coderanger** [comment]
I think this is probably out of scope for envtest. I would encourage you to use the "existing cluster" mode instead :)

**Comment by chunter0** [comment]
Is this not possible at all today? I'm hoping to use envtest because I only need a few components from k8s and envtest allows me quickly spin up just those components

**Comment by chunter0** [comment]
Seems like it would be simple to pass back the private key from the generated self-signed cert here to support this

https://github.com/kubernetes-sigs/controller-runtime/blob/8b55f85c90c3b1df1af58ddb7fe50096fdc7aa99/pkg/internal/testing/certs/tinyca.go#L94

**Comment by coderanger** [comment]
@chunter0 This is a super niche need so I don't think we would want to support it in envtest. You can use something like k3s or Kind with "existing cluster" mode to get full control over the cluster configuration.
