### ISSUE TITLE
How to find out which user created/updated an object when validating?

### ISSUE THREAD

**Issue by ccremer** [kubernetes-sigs/controller-runtime#1600]
Hi!
We are about to develop a validating admission webhook.
Whether creation and updates are allowed depends on who (which user or service account) has mutated a certain object.

How would that look with controller-runtime?
The default interface like the example below generated by Operator-SDK doesn't seem to expose possibilities to review the interacting.
```go
//+kubebuilder:webhook:path=/validate-core-my-domain-v1-namespace,mutating=false,failurePolicy=fail,sideEffects=None,groups=core.my.domain,resources=namespaces,verbs=create;update,versions=v1,name=vnamespace.kb.io,admissionReviewVersions={v1,v1beta1}

var _ webhook.Validator = &Namespace{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Namespace) ValidateCreate() error {
	namespacelog.Info("validate create", "name", r.Name)
	return nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Namespace) ValidateUpdate(old runtime.Object) error {
	namespacelog.Info("validate update", "name", r.Name)
	return nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Namespace) ValidateDelete() error {
	namespacelog.Info("validate delete", "name", r.Name)
	return nil
}
```

**Comment by bakito** [comment]
I recently also bumped into this.
UserInfo would also be useful in Defaulting webhook.
One solution would be to provide a context in these functions and add te information to it.

Something like https://github.com/bakito/controller-runtime/commit/2afa3adcffe45d25af57740d5f455b6fb4794880

**Comment by coderanger** [comment]
As with many questions about webhooks, if you want to do something Fancy™ you need to drop down to the actual webhook API rather than the high-level interfaces. We only support the high-level interfaces for the simplest and most direct of use cases because otherwise they would become a mess.

**Comment by ccremer** [comment]
I understand. This is not a feature request per se, I just want to understand my options.
Would listening/watching to `v1/AdmissionReview` make sense?
Or does anyone have an example snippet with the low-level webhook API with user information in action?

**Comment by coderanger** [comment]
https://github.com/coderanger/migrations-operator/blob/dfe518fb664e734d995b0e081a397a073fd90dda/webhook/webhook.go is an example of a low-level webhook. On the `req` object in there you can use `.UserInfo` to get all that is available, https://github.com/kubernetes/api/blob/499b6f90564cff48dc1fba56d974de2e5ec98bb4/authentication/v1/types.go#L107-L122.

**Comment by ccremer** [comment]
Thanks!
From my PoV this issue can be closed.

**Comment by snorwin** [comment]
@ccremer I recently developed a generic admission webhook (https://github.com/snorwin/k8s-generic-webhook) which provides  full access to the `AdmissionReview`.

**Comment by ccremer** [comment]
Neat! Thanks for sharing!

**Comment by zihuaweng** [comment]
Hi @bakito  I ran into the same issue and want to use req.UserInfo to block any users other than my customized controller from modifying a resource. The result of the req user info is {system:unsecured  [system:masters system:authenticated] map[]}. Do you know where this system:unsecured user comes from and how to configure a user for my controller? Thanks!

**Comment by thesuperzapper** [comment]
It seems like [`admission.RequestFromContext()`](https://github.com/kubernetes-sigs/controller-runtime/blob/3be3f1bf2b2fcc6b5c9510d55c6a9972294653d0/pkg/webhook/admission/webhook.go#L253-L260) can be used since https://github.com/kubernetes-sigs/controller-runtime/issues/1949 (PR https://github.com/kubernetes-sigs/controller-runtime/pull/1950) to retrieve the underlying [`AdmissionRequest`](https://kubernetes.io/docs/reference/config-api/apiserver-admission.v1/) in the context of a `ValidateCreate`/`ValidateUpdate`/etc.

Which should allow you to take actions based on the [`UserInfo`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.36/#userinfo-v1-authentication-k8s-io) field of `AdmissionRequest`.
