### ISSUE TITLE
Add client-go relationship to FAQ

### ISSUE THREAD

**Issue by stevenpitts** [kubernetes-sigs/controller-runtime#1610]
As someone newly hearing about controller-runtime, and how this is something I might use instead of some client-go resources, my first question is about the relationship between controller-runtime and client-go.

* Is controller-runtime a (figurative) "wrapper" for client-go? `(no)`
* Is controller-runtime an "improved" client-go? `(basically)`
* Is controller-runtime to be used alongside client-go, for helper functions and other conveniences? `(not really but you could I suppose)`
* Is controller-runtime meant to just be an alternative to client-go? `(basically)`

I could read through the documentation and examples to find my answers (as I ended up doing), but it would be much easier to get a quick answer in [the FAQ](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md).

**Comment by stevenpitts** [comment]
I definitely feel that someone will address this :)

**Comment by stevenpitts** [comment]
![image](https://github.com/user-attachments/assets/713bd825-cba5-483a-9fa2-610ab1fe0225)
I am so excited and expectant for the response to this issue :)

**Comment by sbueringer** [comment]
/close 

This was done a while ago, see https://github.com/kubernetes-sigs/controller-runtime?tab=readme-ov-file#compatibility

**Comment by sbueringer** [comment]
Okay not sure if that addresseed this issue. But if you have an idea what is missing, please just open a PR
