### ISSUE TITLE
Design pattern for immediate triggering of referrer objects when referent changes?

### ISSUE THREAD

**Issue by toumorokoshi** [kubernetes-sigs/controller-runtime#1611]
Hello,

## Problem Statement

I'm working on [Config Connector](https://cloud.google.com/config-connector/docs/overview), which is an operator for managing resources for Google Cloud. Like with any cloud, there is a need to manage a long chain of resources that depend on each other.

A strawperson example is:

- load balancer depends on a network interface
- network interface depends on a VM instance
- vm instance depends on an IAM account

Which introduces a chain of 4 objects, 3 object references. Depending on the frequency of the retries, this end up taking N x M (N is the retry period, M is the number of object references). Because cloud resources often have HTTP request quotas that prevent aggressive HTTP requests, we try to keep our retry frequency conservative.

To solve this problem, we need a mechanism to trigger reconciles of referrer objects as the referent updates. This will ensure immediate trigger of reconciliation for referrer objects, without increasing retry frequency blindly.

## Thoughts on a solution

I [authored a sketch on an approach here](https://github.com/toumorokoshi/k8s-object-refs/blob/main/DESIGN.md), but feedback from the Kubebuilder SIG and slack channel indicates that there may be a better approach.

The crux of the design, I believe, can be broken up into two parts for a referrer:

1. initializing the watch on the referent resource
2. how to identify the referent resources from a referrer, so you can trigger their reconciles.

For 1: the suggestion in the Kubebuilder SIG was to initialize an Owns call, and I believe it is [shown in Kubebuilder](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html?highlight=Owns(#setuphttps://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html?highlight=Owns(#setup).

For 2: I think it was a little less clear, but the suggestion was to maintain a IndexField that the child could use to look up the parent, and then trigger a reconcile of that parent.

There was also mention of [enqueue_mapped.go](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/handler/enqueue_mapped.go#L32https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/handler/enqueue_mapped.go#L32). 

The suggestion from the sig was to post the issue here for further discussion. I'm taking an action item of looking into the above recommendations, to see if that works for this pattern.

**Comment by coderanger** [comment]
Expanding on what I recommended on Slack (or really just restating it), there's two main options:

The more traditional approach is owned object watches as mentioned along with storing stuff like an external object version or hash of the external state/config into an annotation, so when it changes it triggers updates down the chain. This is how we do things internally within Kubernetes.

The more direct way that matches what you described but maybe not what you actually want is to use a channel watch, passing the send half of the channel to the other controller so it can trigger reconcile events at will by sending to the channel.

**Comment by alvaroaleman** [comment]
The usecase you mentioned in the meeting of parent references child and needs to be triggered on child changes while child doesn't know anything about parent can be accomplished by:
1. Parent reconciler watches child object type
2. You pass a mapping function in the watch of the child that will list all parents and enqueue the matching ones: https://github.com/kubernetes-sigs/controller-runtime/blob/0fcaa802896a5a8e45da32e4f5d6c6324409a778/pkg/handler/enqueue_mapped.go#L41
3. If you believe the "listing the parent" is too inefficient, you can optimize it through an index
    * [Index setup sample](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#setup) 
    * [Index usage sample](https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html#2-list-all-active-jobs-and-update-the-status)

I don't have a sample for where this is done with an index but without it it might look something like this: https://github.com/kubermatic/kubermatic/blob/cfe683e3b359cb46728104bd0b56b51adfa36595/pkg/controller/seed-controller-manager/kubernetes/cluster_controller.go#L213
