### ISSUE TITLE
Reconcile loops infinitely with no rate-limit once resources > X

### ISSUE THREAD

**Issue by blakebarnett** [kubernetes-sigs/controller-runtime#1613]
I have an operator that needs to handle 3 - 4 Apps which encompass a Deployment, Secret, ConfigMap, Service and potentially a PVC and/or Ingress. These groups of resources are created for each "project" which is equivalent to a namespace.

Everything works great when the operator only needs to deal with up to 2 of these Apps. When I add a third one, the Reconcile loop starts running infinitely with no rate-limit. There are no errors, it just runs super fast chewing up CPU. 

I have tried many different configurations and it doesn't seem to be a problem with a specific type of resource (as I originally thought it was: https://github.com/operator-framework/operator-sdk/issues/4906). 

It seems like controller-runtime is hitting some kind of limit on watched resources? I've started looking through the code but I'm hoping someone has a clearer view.

**Comment by coderanger** [comment]
You've managed to write a non-idempotency bug somewhere in your code. Resource A kicks off B kicks off C etc etc. You can use some code like https://github.com/coderanger/controller-utils/blob/main/predicates/update_debug.go to help diagnose exactly why, but it will be specific to your code so we can't help other than in the broad strokes.

**Comment by blakebarnett** [comment]
I thought that was the case also but I can trigger this by having App1 & App2 working fine, then adding App3. Starts misbehaving. If I remove App2, it behaves normally. So that says to me the code isn't the problem?

**Comment by coderanger** [comment]
It's a loop, if you break any link in the chain then there isn't a loop anymore.

**Comment by blakebarnett** [comment]
Thanks for your help, adding an equivalent to your `predicates.UpdateDebug()` revealed my goof. Each object was adding a status to the CRD, which triggered another update.
