### ISSUE TITLE
Is it valid to have a request object name set to empty string

### ISSUE THREAD

**Issue by skonto** [kubernetes-sigs/controller-runtime#1625]
From what I read the namespace is required. Are there any issues if request name is empty?
This could be used to signal cases where some global resource related to the Kind needs reconciliation (eg. rbac set at the ns level). How does controller runtime handle this scenario internally?

**Comment by varshaprasad96** [comment]
Do you mean while using controller-runtime clients with cluster scoped objects? That case is [handled](https://github.com/kubernetes-sigs/controller-runtime/blob/ca01f67d57d64cf1af861cea9e4403a6a599abb8/pkg/client/unstructured_client.go#L185) using RESTMapper.

**Comment by skonto** [comment]
Hi @varshaprasad96, I have this type of signature for the reconciler:
```
Reconcile(ctx context.Context, request reconcile.Request) (reconcile.Result, error) 

type Request struct {
	// NamespacedName is the name and namespace of the object to reconcile.
	types.NamespacedName
}

type NamespacedName struct {
	Namespace string
	Name      string
}
```
My question is about `Name` being empty string.

**Comment by coderanger** [comment]
That wouldn't make any sense since Name is required for all objects. Namespace is the optional one, in the specific case of cluster-scoped resources.

**Comment by skonto** [comment]
@coderanger I didnt see it failing in some way though. I just got requests without a name.

**Comment by coderanger** [comment]
I don't think it would fail specifically but it's not a case we test for and it might break in the future. It's semantically invalid so you shouldn't do it.

**Comment by skonto** [comment]
Cool thanks.
