### ISSUE TITLE
Using EnqueueRequestsFromMapFunc with a MapFunc that makes a call that can fail or takes a ctx is awkward

### ISSUE THREAD

**Issue by matthchr** [kubernetes-sigs/controller-runtime#1628]
The scenario I was solving is that I have a custom resource and a secret associated with that custom resource (referenced by a field in the CR) and I would like to reconcile the CR when the secret changes. The following code accomplishes that (with help from @coderanger) following what I understand is a common pattern.

`Watches(&source.Kind{Type: &corev1.Secret{}}, handler.EnqueueRequestsFromMapFunc(makeMapFunc(mgr))).`

```
func makeMapFunc(mgr ctrl.Manager) func(o client.Object) []reconcile.Request {
	return func(o client.Object) []reconcile.Request {
		if _, ok := o.(*corev1.Secret); !ok {
			return nil
		}

                // TODO: Don't know what ctx to use here... I guess just make one?
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		var matchingResources v1.MyCRDList
		err := mgr.GetClient().List(ctx, &matchingResources, client.MatchingFields{SecretKey: o.GetName()})
		if err != nil {
                        // TODO: Can't do anything but log here I guess
			return nil
		}

		var result []reconcile.Request

		for _, matchingResource := range matchingResources.Items {
			result = append(result, reconcile.Request{
				NamespacedName: types.NamespacedName{
					Namespace: matchingResource.GetNamespace(),
					Name:      matchingResource.GetName(),
				},
			})
		}

		return result
	}
}
```

This pattern is awkward (see the 2 TODOs in the code above) because:
1. Using `client.List` takes a `ctx` - except there is no `ctx` flowing through the standard `MapFunc` signature so we just need to make one up or use `ctx.Background` or something?
2. If the `List` call fails... what do we do with the error? Probably we just log it and return nil, but I think that means we end up missing a reconcile we should do?

There's no easy or obvious fix here because in the context that the `MapFunc` is called, there's not a `ctx` floating around to pass down, nor is there an obvious answer as to what would happen if a `MapFunc` could return an error. @coderanger suggested the same in the conversation we had on Slack.

Still, in the interest of exposing the awkwardness (and also giving others who have wondered about this pattern or ones like it someplace to find some discussion about it) I've filed this issue.

**Comment by coderanger** [comment]
Background() is indeed correct as you aren't going to cancel the context even if there is an error (other map functions might need to run too). And yeah, the issue with returning an error is it has nowhere to go. We do that in Reconcile() because that is bounced via a workqueue and can retry on failure. There is no such queue on incoming events so if it fails it just fails, there is nowhere for the error to go to make it try again. We could add a queue there, but I would worry about the overhead.

**Comment by harveyxia** [comment]
Is there a recommended approach for ensuring that a reconcile is not missed in the event of an error? One hacky approach would be to enqueue a `reconcile.Request` with a well-known name/namespace that signals a failure of the `handler.MapFunc`, so the controllers `reconcile()` invocation can retry the `handler.MapFunc` logic, but I'd like to avoid this if possible.
