### ISSUE TITLE
Examples of the Finalizer Helper Library

### ISSUE THREAD

**Issue by austince** [kubernetes-sigs/controller-runtime#1631]
Are there any examples that use the new Finalizer helper library? I'm giving it a try but don't quite understand where the business logic of the finalizer should live. It feels like the `Reconciler` knows what should be deleted, not `main`.

Should I define the finalizer logic inside the `x_controller.go` file, and just register that in the main? Should the reconciler itself actually implement the `Finalizer` interface? 

And then, does it make sense to requeue if either the obj or its status was updated? 

```go
requeue, err := r.Finalizers.Finalize(ctx, &job)
if requeue.Updated || requeue.StatusUpdated || err != nil {
  if requeue.Updated {
	r.Client.Update(ctx, &job)
  }

  if requeue.StatusUpdated {
	r.Client.Status().Update(ctx, &job)
  }
  return ctrl.Result{Requeue: requeue.Updated || requeue.StatusUpdated}, err
}
```

Thanks for the help! 

_Originally posted by @austince in https://github.com/kubernetes-sigs/controller-runtime/issues/1453#issuecomment-897955300_

**Comment by varshaprasad96** [comment]
Finalizers could be used to clean up any external resources across namespaces when the parent object is deleted. This [example](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#external-resources) maybe helpful to have an overview on where finalizers could be used inside a controller.
