### ISSUE TITLE
Ability in client.Client to observe (and intercept) write actions

### ISSUE THREAD

**Issue by arschles** [kubernetes-sigs/controller-runtime#1633]
I'm not sure from a few reads through the documentation and a brief look at the [fake client code](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.9.2/pkg/client/fake) if there is a way to observe (and react to) writes. It appears that clients created with a [ClientBuilder](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.9.2/pkg/client/fake#ClientBuilder) are read-only.

It would be useful for test code to allow folks to do two additional things with these clients:

- React to and/or intercept write operations
- View all write operations that were done to a fake `client.Writer`

I could use this functionality in the [KEDA HTTP Addon](https://github.com/kedacore/http-add-on). Are either/both of these goals possible to achieve already? If not, I propose that we make it so. I'm also happy to submit a detailed proposal if appropriate.

Thanks folks!

**Comment by alvaroaleman** [comment]
Are you talking about the fakeclient or the client in general?

Generally speaking, you can very easily build a light wrapper that overrides the method(s) you want to interecept, e.G.
```
type updateInterceptingClient struct {
    ctrl.Client
}

func (uic *updateInterceptingClient) Update(ctx context.Context, o ctrl.Object, opts ...ctrl.UpdateOption) error {
  // Do some custom stuff
  if o.GetGenerateName() != "" {
     o.SetName(o.GenerateName+"-123"
  }
  
  return uic.Client.Update(ctx, o, opts...)
}

**Comment by arschles** [comment]
@alvaroaleman I'm talking about the fake client. I'm going to end up doing something similar to the code you wrote, except that I'm just doing the recording for now (this is similar to what `client-go` does), so roughly this:

```go
type recordingClient struct {
    Updates []client.Object
    ctrl.Client
}

func (rc *recordingClient) Update(ctx context.Context, o ctrl.Object, opts ...ctrl.UpdateOption) error {
    rc.Updates = append(rc.Updates, o)
    return rc.Client.Update(cox, o, opts...)
}
// other methods here for create, patch, etc...
```

Are you interested in having something like this in the fake package? For example, the `ClientBuilder` could include a `BuildRecorder` that returns a `fake.RecordingClient` that has these fields on it.
