### ISSUE TITLE
Unsafe assumptions and leaked goroutine in logging

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#1655]
This code is problematic:
https://github.com/kubernetes-sigs/controller-runtime/blob/498ee8ae7cc1dfc414f453f98cde3114116e5442/pkg/log/log.go#L53-L70

First, it leaks a goroutine for 30s just by importing the library. Generally its assumed an import is not creating goroutines. The real world impact of this is that various projects (Istio, gRPC, etc) have tests that assert no goroutines are leaking; these fail if controller-runtime is so much as imported.

Another issue is `It is safe to assume that if this wasn't set within the first 30 seconds of a binaries`. This seems *not* safe to assert. There is certainly no reason that I cannot set a logger 31s or 30h into the process lifetime. The controller-runtime library can and is used as a small piece of larger binaries; its not always the sole thing running in the process.

**Comment by coderanger** [comment]
> The controller-runtime library can and is used as a small piece of larger binaries; its not always the sole thing running in the process

While we want to improve the use cases around this, especially because the controller-runtime client is so much nicer to work with than client-go for many use cases, we do still largely optimize for writing operators with tools like Kubebuilder and Operator-SDK where controller-runtime is indeed in overarching control of the universe. This code was added to fix some substantial memory leak issues due to dangling loggers. If you have suggestions on how to improve this without hurting the primary use cases, please do let us know.

**Comment by alvaroaleman** [comment]
Hey @howardjohn ,

The reason this logic exists is that the `DelegatingLogger` ends up consuming a huge amount of memory if no Logger gets set: https://github.com/kubernetes-sigs/controller-runtime/issues/1122

The current logic is the best we could come up with to deal with that situation and "leaking" a goroutine for 30 seconds/not allowing to set a logger after that is definitely less of an issue than the memory consumption.

If you have any ideas on how to improve things here, they are very welcome.

**Comment by ash2k** [comment]
I just found this weird goroutine in a debugging session.

> If you have any ideas on how to improve things here, they are very welcome.

Why not use klog, like Kubernetes? That would be consistent and not a surprise at all. Most apps that care about logs and use Kubernetes libraries set klog logger via [`klog.SetOutput()`](https://github.com/kubernetes/klog#how-to-use-klog).

/reopen
/remove-lifecycle rotten
