### ISSUE TITLE
Ensure idempotent when a controller has multiple workers

### ISSUE THREAD

**Issue by caohe** [kubernetes-sigs/controller-runtime#1656]
https://github.com/kubernetes-sigs/controller-runtime/blob/386c2b5b29bace1e1e0b35afd0f6c1acc38cd140/pkg/internal/controller/controller.go#L222-L230

As stated in the above comment, 
>It enforces that the reconcileHandler is never invoked concurrently with the same object.

If a controller has multiple workers, I need to ensure only one event of a certain object is reconciled at a certain moment. Do I need to ensure it in the reconcile logic, or the controller-runtime framework will do this?

**Comment by coderanger** [comment]
As the comment says, we take care of this. More specifically the workqueue layer handles it.

/close
