### ISSUE TITLE
Released version of setup-envtest

### ISSUE THREAD

**Issue by fabienmifsud** [kubernetes-sigs/controller-runtime#1659]
Hi,

Is there any released version of setup-envtest, we can't only rely on "latest" version for our CI pipeline.

Thanks !

**Comment by camilamacedo86** [comment]
@varshaprasad96 , @vincepri 
Could we add this one as a priority?

**Comment by FillZpp** [comment]
As I said in #1670,  controller-runtime does have the setup-envtest in releases. But You have to import it in your project with build tool and then you can install it with the required version.

You can follow this: https://github.com/kubernetes-sigs/controller-runtime/issues/1670#issuecomment-1010602287
