### ISSUE TITLE
How to use an existing informer with controller-runtime?

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#1668]
https://github.com/kubernetes-sigs/controller-runtime/blob/8e1263d50ea2688cf251ce745ec711dadc8846d8/pkg/builder/controller.go#L77-L81

This says it is equivalent  to `Watches(...)`. This doesn't seem to be true - when replacing with the suggested equivilent, an error 'must provide an object for reconciliation' is returned.

For context on *why* I don't want to use For is I want to pass in an existing informer.

**Comment by coderanger** [comment]
Conceptual equivalent for people used to the pre-builder-syntax days of controller-runtime. For() sets the root object type of the controller which does more than just set the watch, though it does include that.

**Comment by howardjohn** [comment]
Does that also mean its impossible to use an existing informer? Seems like `forInput` is private and only exposed in For which won't allow a custom source

**Comment by coderanger** [comment]
Probably? Or at least unrelated to this level of things. You could potentially use the manager-level hooks to try and inject your own in but I doubt it will work smoothly. C-R expects to control things if you are using caching?

**Comment by howardjohn** [comment]
I see.. that is pretty disappointing as we are interested in using c-r but cannot rewrite our entire O(100k) LOC app to use it (at least in the short term) and can't accept the overhead of 2x watches

**Comment by coderanger** [comment]
You can use an uncached client then. Or as I said, experiment with the `NewCache` option method when creating your manager. Normally the creates a Cache struct with a new informer but if you hammer on it hard enough you could maybe slip in a reference to an existing one? No idea how much that would break or confuse things though, esp if your informers run with a different config than ours.

**Comment by alvaroaleman** [comment]
@howardjohn Passing an existing informer into the cache might be difficult. The underlying reason is that they are constructed on-demand and there is a bunch of logic to make them implement client.Reader, so you would have to mimick that.

What is likely going to work though is the other way round: Get the cache from the manager, get the informer(s) for the types you care about, use them everywhere else.

**Comment by coderanger** [comment]
/title How to use an existing informer with controller-runtime?

**Comment by coderanger** [comment]
/retitle How to use an existing informer with controller-runtime?
