### ISSUE TITLE
Unable to download env test config based on the tags

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#1670]
The documentation and its usage are telling us to use the latest version, however, we need to get the version based on the release tags. See:https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest

We cannot use the latest because it can change and have breaking changes and we need to ensure what version is compatible or not.

```
 $ go install sigs.k8s.io/controller-runtime/tools/setup-envtest@0.10.0
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@0.10.0: sigs.k8s.io/controller-runtime/tools/setup-envtest@0.10.0: invalid version: unknown revision 0.10.0

```

**Comment by camilamacedo86** [comment]
c/c @varshaprasad96

**Comment by jmrodri** [comment]
@camilamacedo86 and you meant to use the actual tag value, `v0.10.0` and not `0.10.0` right? Though `v0.10.0` didn't work for me either but does give a different error:

```
$ go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.10.0
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.10.0: module sigs.k8s.io/controller-runtime@v0.10.0 found, but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
```

**Comment by camilamacedo86** [comment]
@varshaprasad96 , @vincepri
Could we add this one as a priority?

**Comment by FillZpp** [comment]
> go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.10.0: module sigs.k8s.io/controller-runtime@v0.10.0 found, but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest

Actually, this is a trick of go install with modules. It is **because your project does not import the "sigs.k8s.io/controller-runtime/tools/setup-envtest"**, rather than controller-runtime doesn't have the setup-envtest in releases.

It's easy to solve it:

1. Require the controller-runtime in your go.mod

```
    sigs.k8s.io/controller-runtime v0.10.0
```

2. Create a go file in your project with `build tools` comment and import `.../setup-envtest` in it. You may have done this if you have already imported code-generator or something else. You can see [how Kubernetes do this]. Example:

```golang
//go:build tools
// +build tools

/*
YOUR_COPYRIGHT
*/

// This package imports things required by build scripts, to force `go mod` to see them as dependencies
package tools

import (
	_ "sigs.k8s.io/controller-runtime/tools/setup-envtest"
)
```

3. [Optional] Refresh your go mod, for example `go mod vendor` if you use vendor.

4. Use `go install` without version to install setup-envtest, which will use the version you required in go.mod

```
go install sigs.k8s.io/controller-runtime/tools/setup-envtest
```

**Comment by FillZpp** [comment]
@camilamacedo86 We can add the steps above into document, so that users can install setup-envtest with controller-runtime version they required.

**Comment by camilamacedo86** [comment]
Hi @FillZpp, 

Thank you for your time and help on this. 

My concern/motivation to raise this one is that in Kubebuilder we are: ([here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L113-L116)) 

```
ENVTEST = $(shell pwd)/bin/setup-envtest
.PHONY: envtest
envtest: ## Download envtest-setup locally if necessary.
	$(call go-get-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest@latest)
```

Then, a KB user scaffolds the project today. The scaffold is done with controller-runtime version X.
Afterwards, we still producing new releases and versions and target can begin to download a version of this module that is no longer compatible. 

Kubebuilder projects are scaffold with the [go.mod](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/go.mod#L11) and with the controller-runtime dep/version already. So, if I properly understood your suggestion, we can sort it out by removing the latest and scaffolding the `build tools` import:

```
ENVTEST = $(shell pwd)/bin/setup-envtest
.PHONY: envtest
envtest: ## Download envtest-setup locally if necessary.
	$(call go-get-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest)
```

Then, it would install the setup-envtest module version accordingly to the controller-runtime version scaffold in the [go.mod](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/go.mod#L11). 

It shows to address the requirement without the need to ask for the KB users to read the doc/steps.

**Comment by camilamacedo86** [comment]
/reopen

It still an issue see: https://github.com/kubernetes-sigs/kubebuilder/issues/3715
