### ISSUE TITLE
controller-runtime: Possible to watch multiple resources with set of managers? 

### ISSUE THREAD

**Issue by Arsen-Uulu** [kubernetes-sigs/controller-runtime#1675]
Hi,

I am new to controller-runtime, but is it possible to have multiple managers and controllers to watch diff resources and have different Reconcilers? 

Thank you

**Comment by coderanger** [comment]
You would only have one manager per running process but that can host any number of controllers and other runnables.

**Comment by Arsen-Uulu** [comment]
@coderanger  Thank you. I was able to use any number of controllers.

I would like to close this issue, but  quick question came up, is possible to ignore resources that were already created and watch for only newly created resources that I wanna watch?

**Comment by coderanger** [comment]
@Arsen-Uulu No, that would break the convergent model we use. All root-level watched objects are reconciled at startup to ensure convergence.
