### ISSUE TITLE
Panic in fake client

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/controller-runtime#168]
I tried to write unit tests using the fake client and `List()` panics reliably when accessing `opts.Raw`:

https://github.com/kubernetes-sigs/controller-runtime/blob/ddf0390deebe496cb449b1b8540031da9236afa2/pkg/client/fake/client.go#L80-L82

Why `opts.Raw` must be filled (it's not necessary when using the real client) and why it's `TypeMeta` should have any value?

If I understand the code (and I probably don't), it expects `opts.Raw.TypeMeta.GroupVersionKind()` to be the kind of items in returned list, not the list itself (i.e. Pod instead of PodList). Such requirement looks very odd.

**Comment by DirectXMan12** [comment]
/kind bug

I think this is just straight-up a bug.  I seem to recall discussion a solution at some point, but can't recall what it was.

**Comment by sverrirsig** [comment]
Is anybody looking into this bug? :)

**Comment by DirectXMan12** [comment]
I don't think anyone's working on it right now.  If you want to, please let me know.  Like most bugs, we do intend to fix it eventually :-)

/priority important-longterm

**Comment by hasbro17** [comment]
@jsafrane Is this still an issue? I think this has been fixed with #213 in the v0.1.8 release.

**Comment by DirectXMan12** [comment]
closing as per above comment
