### ISSUE TITLE
CreateOr{Update,Patch} do not handle status subresource

### ISSUE THREAD

**Issue by prachik1** [kubernetes-sigs/controller-runtime#1693]
Why is this so? 
Same was the case with CreateOrUpdate. Is there any reason why do we have this logic wherein if the resource is not found on the cluster both CreateOrUpdate and CreateOrPatch create a resource but don't set the status fields.

**Comment by alvaroaleman** [comment]
They currently do not handle status subresources. In order to do that, there would need to be a mechanism to figure out if a resource has a status subresource (Can we get this info from the RESTMapper?)

/kind bug

**Comment by alvaroaleman** [comment]
/retitle CreateOr{Update,Patch} do not handle status subresource
