### ISSUE TITLE
cache.SelectorsByObject relies on internal struct

### ISSUE THREAD

**Issue by amisevsk** [kubernetes-sigs/controller-runtime#1697]
I'm trying out the `SelectorsByObject` cache option [introduced in v0.9.0](https://github.com/kubernetes-sigs/controller-runtime/pull/1435), and noticed a bit of a strange setup. The type for `SelectorsByObject` is
```go
// SelectorsByObject associate a client.Object's GVK to a field/label selector.
type SelectorsByObject map[client.Object]internal.Selector
```

This results in `SelectorsByObject` values being semi-accessible, e.g. I can create objects with the internal type `Selector` in a map initialization:
```go
selectors := cache.SelectorsByObject{
  &corev1.Pod{}: {
    Label: devworkspaceObjectSelector,
  },
}
internalSelector := selectors[&corev1.Pod{}]
```
but cannot add to `SelectorsByObject` directly (since I cannot create instances of `internal.Selector`):
```go
selectors[&corev1.Service{}] = // can't instantiate object here
```

This results in a moderately strange workaround in my use case, where I want to include OpenShift Routes in `SelectorsByObject` only when my controller is running on OpenShift:
```go
selectors := cache.SelectorsByObject{
  // ...
}

if isOpenShift {
  openShiftSelectors := cache.SelectorsByObject{
    &routev1.Route{}: {
      Label: myLabelSelector,
    },
  }
  for k, v := range openShiftSelectors {
    selectors[k] = v
  }
}
```

If the `internal.Selector` type is intended to be internal, then `cache.SelectorsByObject` should not use it. If it's intended to be used externally, it should not be in an internal package.

**Comment by FillZpp** [comment]
> If the internal.Selector type is intended to be internal, then cache.SelectorsByObject should not use it. If it's intended to be used externally, it should not be in an internal package.

Indeed. I'd like to open a PR to fix it.
/assign
