### ISSUE TITLE
Support source.Kind for unstructured objects

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/controller-runtime#17]
We should be able to watch for objects against unstructured objects from source.Kind.

- Make the client work
- Make the cache work
- Make watch work

**Comment by pwittrock** [comment]
@shawn-hurley FWIW, this might already work.  I think the first task is to try it and see if it works or not, then dig in deeper.

**Comment by shawn-hurley** [comment]
@pwittrock I think that it would work with a single unstructured type, but if you used two then the client-cache: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client_cache.go#L79-L84 will overwrite the GVK for one fo the types. 

Am I correct in that reading of the code?

I will work on getting an example to test this theory as well.

Thanks!

**Comment by DirectXMan12** [comment]
aah, yeah, we probably would need a key that's like `TypeOf(obj) unless IsUnstructured(obj) else SpecialUnstructuredKeyWithKind`.

**Comment by DirectXMan12** [comment]
or have a separate map for unstructured objects.

**Comment by shawn-hurley** [comment]
@pwittrock @DirectXMan12 I am working on getting an example of using two different unstructured types to test this theory out and to have something to test with.

Which would you prefer the second map if the type is Unstructured or some other mechanism? I would think that two maps might make it more clear?

**Comment by DirectXMan12** [comment]
Two maps is probably clearer.
