### ISSUE TITLE
It is possible to use controller runtime just for validating webhook? 

### ISSUE THREAD

**Issue by Arsen-Uulu** [kubernetes-sigs/controller-runtime#1701]
I am trying to write custom validating webhook and I was wondering if it's ok to use controller-runtime just for that purpose?

**Comment by Arsen-Uulu** [comment]
@coderanger 

```
 hookServer.Register("/validate-deployment", &webhook.Admission{Handler: &AppValidator{Client: mgr.GetClient()}})
 hookServer.Register("/validate-service", &webhook.Admission{Handler: &SvcValidator{Client: mgr.GetClient()}})
```
Is there a limit how many I can register?

**Comment by coderanger** [comment]
I'm sure there is technically a limit but it's probably like 2 billion or something. In general if you have support questions I would encourage you to use Slack, we have a `#kubebuilder` channel.

/close
