### ISSUE TITLE
Fake client should accept reactor functions to induce errors in unit tests

### ISSUE THREAD

**Issue by BlaineEXE** [kubernetes-sigs/controller-runtime#1702]
Kubernetes fake clientsets, including those built by `client-gen`, all can have reactors added to test basic failure scenarios. The Rook (github.com/rook/rook) codebase makes extensive use of reactors to induce errors in unit tests to ensure our error handling of functions is correct when they interact with the kubernetes API. 

For adding this functionality to the fake interface, is  this something that the controller-runtime team sees value in and has interest in implementing, or is it likely a lower priority item where we can have a Rook contributor make a contribution here?

**Comment by alvaroaleman** [comment]
This is unlikely to happen, we had a couple of previous discussions around this and agreed that client-gos reactor system is too complicated and thus bug-prone. So far there hasn't been an agreement on what we want instead, if anything.

A simple approach to introduce custom behavior is to embedd a client and overwrite some or all of the methods:
```
type myfakeclient struct {
    client.Client
}

func (f *myFakeClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOpts) error {
  if obj.GetName("foo"){
    return errors.New("Not allowed to create object named foo")
 }
 return f.Client.Create(ctx, obj, opts...) 
}
```

**Comment by BlaineEXE** [comment]
I suppose from a Golang developer perspective, that approach may actually be more straightforward and simple to understand than the reactor anyway. Thanks :)
