### ISSUE TITLE
Don't rate limit discovery clients by default?

### ISSUE THREAD

**Issue by negz** [kubernetes-sigs/controller-runtime#1707]
It seems per https://github.com/kubernetes/kubernetes/pull/105520#discussion_r723535829 that `kubectl` is planning to remove rate limiting of the discovery process, preferring to instead let [APF](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) handle the (often very large) slew of requests it makes.

Would it make sense for controller-runtime to do the same? I imagine this might help with issues like https://github.com/kubernetes-sigs/controller-runtime/issues/537, though it would also be nice to actually make fewer requests per https://github.com/kubernetes-sigs/controller-runtime/issues/1603.

**Comment by alvaroaleman** [comment]
When the upstream change merges it would make a lot of sense to follow suit here

**Comment by negz** [comment]
/remove-lifecycle stale

I think this will be pretty important for us going forward.

**Comment by negz** [comment]
FWIW client-go's discovery rate limits were just bumped to 300.
