### ISSUE TITLE
When update `status` , but trigger Reconcile func

### ISSUE THREAD

**Issue by cuisongliu** [kubernetes-sigs/controller-runtime#1711]
this is ok ? update status tigger reconcile func, I  think `spec` tigger reconcile, but `status` not tigger reconcile.

**Comment by alvaroaleman** [comment]
You can use a predicate to avoid this if you don't want that. Many controllers use status to report the status, so updating it generates an event for the whole object. This is part of the Kubernetes watch api and not something controller-runtime wants to express a different opinion about.
