### ISSUE TITLE
Properly exit when cert-watcher can no longer watch required file

### ISSUE THREAD

**Issue by ethernoy** [kubernetes-sigs/controller-runtime#1719]
When the TLS assets are no longer available (missing drive for example) after a webhook server is started with such TLS assets, the cert-watcher throws the following error:
https://github.com/kubernetes-sigs/controller-runtime/blob/4d10a0615b11507451ecb58bfd59f0f6ef313a29/pkg/certwatcher/certwatcher.go#L144
```
{"level":"error","ts":1636596243.6302137,"logger":"controller-runtime.certwatcher","msg":"error re-watching file","error":"no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:144\nsigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher.(*CertWatcher).handleEvent\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher/certwatcher.go:144\nsigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher.(*CertWatcher).Watch\n\t/go/src/github.com/open-policy-agent/gatekeeper/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/certwatcher/certwatcher.go:102"}
```
After throwing the following error, the cert-watcher simply stops monitoring the path without further action. The last valid certificate persists in `currentCert` even after the path becomes available again. I wonder if it is better if the cert-watcher can either:
- call `os.exit` after the path missing error occurs
- keeps monitoring the path even if it is missing

Happy to do a PR if possible.

**Comment by sbueringer** [comment]
To be honest, I would be really surprised if the certwatcher "can not handle secret mounted in container.". As far as I'm aware that is the standard case with controller-runtime and folks have running this in production for a very long time (also in combination with certificates managed by cert-manager that are rotated every few weeks).

Maybe I'm missing something. Definitely fine to investigate further and if there is evidence that we have a problem fix it.


/remove-lifecycle rotten
/reopen

**Comment by sbueringer** [comment]
Just to surface it here. With CR v0.20 we'll likely going to have a cert-watcher implementation that uses fsnoty + additionally regularly reads the files from disk (default: every 10s)
