### ISSUE TITLE
requeueAfter not working .. 

### ISSUE THREAD

**Issue by pigbrain** [kubernetes-sigs/controller-runtime#1720]
In my application, I run codes like  below.. 

```
func reconcile() {

    // create namespace 

    // update resource status 

    return ctrl.Result{
        requeueAfter  : 2 seconds
    }, nil
}
```

I expected next reconcile called after 2sec, but requeueAfter  is not working..
Next reconcile was called immediately.

**Comment by coderanger** [comment]
If another event is received, it will be processed. RequeueAfter just creates a synthetic event (kind of, technically this is all inside the workqueue) after that time period. Also `2 seconds` isn't valid Go code so I'm assuming you edited this from your actual code.

**Comment by pigbrain** [comment]
@coderanger Thanks for your reply. How do i know what event has occured ??

**Comment by jichaofdu** [comment]
I have the same issue

**Comment by leemingeer** [comment]
Ihave the same issue
$ ./bin/controller-gen --version
Version: v0.8.0

**Comment by antonengelhardt** [comment]
I have the same issue. When i return a ReconcileResult like this:
```
return ctrl.Result{
				Requeue:      true,
				RequeueAfter: 10 * time.Minute,
			}, err
```
it reconciles right away.
