### ISSUE TITLE
Support running commands on a pod with controller-runtime client

### ISSUE THREAD

**Issue by anders-swanson** [kubernetes-sigs/controller-runtime#1723]
As a user I would like to use the controller-runtime client to run commands on pods, and receive the stdin/stdout/stderr. As it is, I must create a kubernetes-go client from inside routines that use the controller-runtime client - this adds a certain amount of cludge/complexity to the code. It would be great if the controller-runtime exposed an interface for this functionality, which would abstract away the need to have a direct reference to a kubernetes-go client.

 See #1229, which was closed about a year ago - is there any update to this?

**Comment by coderanger** [comment]
Please don't open duplicates, especially when you _know_ it's a duplicate.

/close
