### ISSUE TITLE
Add Object Patcher as CAPI has in controllerutil package

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/controller-runtime#1732]
CAPI has a good [patcher utility ](https://github.com/kubernetes-sigs/cluster-api/blob/main/util/patch/patch.go)for the controlled object. But it has specific CAPI logic for CAPI conditions which is not generally used by other controllers. It would be better if controller-runtime has similar utility might be under controllerutil package with more general logic.

maybe we can adopt the old version of CAPI patcher utility from [release-0.2](https://github.com/kubernetes-sigs/cluster-api/blob/release-0.2/util/patch/patch.go) branch.

As far as I see, many of several controller-runtime adopters will invoke client.{Update/Patch} after every changing the object. The motivation for having this utility is to make the reconcile block be cleaner and help the controller developer to ensure every controlled object change is patched.

```go
// Initialize the patch helper.
pacher, err := patch.NewPatcher(obj, r.Client)
if err != nil {
	return ctrl.Result{}, err
}

defer func ()  {
	// Always patch the changes of object
	if err := patcher.Patch(ctx, obj); err != nil {
		reterr = err
	}
}()

// Do something with object
```

/kind feature

**Comment by fabriziopandini** [comment]
I'm happy to brainstorm on how to make CAPI specific things pluggable into a single implementation we all leverage on

cc @vincepri

**Comment by coderanger** [comment]
This looks like something that might be better served by Apply anyway?

**Comment by vincepri** [comment]
@fabriziopandini If we also upstream conditions at some point, the CAPI-specific bits should be minimum and potentially pluggable
