### ISSUE TITLE
Where should resourceVersionChangedPredicate be used

### ISSUE THREAD

**Issue by Mei-pris** [kubernetes-sigs/controller-runtime#1740]
ResourceVersionChangedPredicate implements a default update predicate function on resource version change. 
 When an update event occurs，I think the resourceVersion must changed. So where should resourceVersionChangedPredicate be used?

` func (ResourceVersionChangedPredicate) Update(e event.UpdateEvent) bool
 {
	if e.ObjectOld == nil {
		log.Error(nil, "Update event has no old object to update", "event", e)
		return false
	}
	if e.ObjectNew == nil {
		log.Error(nil, "Update event has no new object to update", "event", e)
		return false
	}
	return e.ObjectNew.GetResourceVersion() != e.ObjectOld.GetResourceVersion()
}
`

**Comment by FillZpp** [comment]
@Mei-pris Actually, the only reason for this is to ignore the update events triggered by `resyncPeriod`, which will send update events for all objects in cache every 10 hours by default.
