### ISSUE TITLE
How to elegantly solve the update conflict problem

### ISSUE THREAD

**Issue by moluzhui** [kubernetes-sigs/controller-runtime#1748]
The following problem occurred when I used `r.Update(ctx, instance)` to update the K8S instance
```
2021-12-15T15:26:49.229+0800    ERROR   : the object has been modified; please apply your changes to the latest version and try again"}
```
This should be caused by the modification of `other controllers at the same time`, so is there any suitable way to solve this problem?

[This](https://github.com/kubernetes-sigs/controller-runtime/issues/1464#issuecomment-824551919) provides a way to retry, but in my opinion this is not elegant enough

**Comment by FillZpp** [comment]
@moluzhui Oh, nice to see you here.

Generally 2 ways to handle the conflict error:
1. Use `RetryOnConflict` function that is provided in `"k8s.io/client-go/util/retry"` to get the object and update it again when run into conflict.
2. Just return the error and let controller trigger your reconcile again with rate limiting.

You may choose the better one according to your controller logic.

**Comment by coderanger** [comment]
Better solution, stop using Update(). I can't think of any reason to use it in controller code. Most requests should use Patch() with Server Side Apply and the few that can't use Apply should use auto-merge-patch.

**Comment by FillZpp** [comment]
> I can't think of any reason to use it in controller code.

@coderanger I think we should choose `Patch` or `Update` for different scenarios. If we are updating some fields that will be modified by multiple clients with co-operation, we should use `Update`.

For example: Now I want to create 3 new pods, which means I have to add 3 to the Deployment replicas. If I get the old Deployment, add 3 to the replicas and then patch the replicas field. I might overwrite modification of other people or controllers, e.g. HPA controller. So the best way is update the Deployment. When I got conflict error, I should get it again and add 3 to the latest replicas and update it.

**Comment by coderanger** [comment]
> If we are updating some fields that will be modified by multiple clients with co-operation, we should use Update.

No, that is in fact exactly the situation for Server Side Apply :) That is why it exists. It allows per-field ownership tracking.

**Comment by FillZpp** [comment]
> No, that is in fact exactly the situation for Server Side Apply :) That is why it exists. It allows per-field ownership tracking.

Emm... So for the example I mentioned above, there are multiple controllers or people going to increase or decrease number based on the **latest** `replicas` of a Deployment. How should they do with Server Side Apply?

If the `replicas` has just changed by another controller when I apply a change, how should the applier resolve the concliect? According to the [document](https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts):
- For `Overwrite value, become sole manager`: but I don't want to force overwrite the `replicas` modified by others.
- For `Don't overwrite value, become shared manager`, I still have to retry and I think it makes things more complicated then clearly update. (For example, how should it handle changes applied by multiple shared managers?)

**Comment by coderanger** [comment]
In that very specific example, yes you would set `force` to false and then use a retry loop. However that's an edge case of an edge case. Even then though, you wouldn't use Update().

**Comment by coderanger** [comment]
But also that example is really not how controllers work, you should never be doing "current value + 1", that's not a convergent behavior and will result in a broken state over time :)

**Comment by FillZpp** [comment]
Aha, I keep my reservations. I agree with that we should use Patch as much as possible, but I don't really think Update can be totally deprecated when we are writing controllers. Just like we could not replace all Update operations with Patch in kube-controller-manager. 🤔

**Comment by moluzhui** [comment]
@FillZpp  nice to see you here
Thank you for your help. I used `RetryOnConflict` function to solve this problem
