### ISSUE TITLE
Controller runtime List panic

### ISSUE THREAD

**Issue by oleg-yudovich** [kubernetes-sigs/controller-runtime#1757]
Version: sigs.k8s.io/controller-runtime v0.10.3

 When the cluster's API server is down our controller manager Reconcile crashes when trying to check cluster health by calling  [List](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client#Reader.List)

Attached stack trace:

error="panic: runtime error: invalid memory address or nil pointer dereference [recovered]\n\ngoroutine 593 [running]:\nruntime/debug.Stack(0xc000544fb8, 0x1f10c60, 0x3594aa0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.tools.xxx/xxx/xxx-controller-manager/pkg/controller.PanicHandler(0xc000545d70, 0xc000545d80)\n\t/workspace/pkg/controller/controller_util.go:142 +0x70\npanic(0x1f10c60, 0x3594aa0)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\nsigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping.func1(0xc000545250, 0x40e078)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/apiutil/dynamicrestmapper.go:255 +0x46\nsigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload.func1(0xc000b83900, 0xc000545308, 0x0, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/apiutil/dynamicrestmapper.go:155 +0x6b\nsigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).checkAndReload(0xc000b83900, 0x24fe360, 0xc000ec6fc0, 0xc000545308, 0x0, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/apiutil/dynamicrestmapper.go:156 +0x8f\nsigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).RESTMapping(0xc000b83900, 0x0, 0x0, 0x1d2f83f, 0x9, 0xc000fa0390, 0x1, 0x1, 0xc0000fe2a0, 0x24fe4a0, ...)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/apiutil/dynamicrestmapper.go:253 +0x178\nsigs.k8s.io/controller-runtime/pkg/client.(*clientCache).newResource(0xc00016fd40, 0x0, 0x0, 0x22291b6, 0x2, 0x1d2f83f, 0x9, 0x1d20001, 0xd, 0x0, ...)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/client_cache.go:66 +0x273\nsigs.k8s.io/controller-runtime/pkg/client.(*clientCache).getResource(0xc00016fd40, 0x2512398, 0xc000e60460, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/client_cache.go:102 +0x286\nsigs.k8s.io/controller-runtime/pkg/client.(*typedClient).List(0xc000c510a0, 0x2547e38, 0xc000c9a6c0, 0x255df10, 0xc000e60460, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/typed_client.go:148 +0x94\nsigs.k8s.io/controller-runtime/pkg/client.(*client).List(0xc000c510a0, 0x2547e38, 0xc000c9a6c0, 0x255df10, 0xc000e60460, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/client/client.go:287

**Comment by FillZpp** [comment]
@oleg-yudovich  Did you use `WithCustomMapper`, `WithLazyDiscovery` or some other RESTMapper options?

**Comment by oleg-yudovich** [comment]
> RESTMapper

@FillZpp, sorry for the delay. No, we are not using any of the options across the project.

**Comment by oleg-yudovich** [comment]
@FillZpp do you have any updates?

**Comment by avizov** [comment]
any update with that bug?

**Comment by FillZpp** [comment]
Emm... I haven't figured out why it panic. Do you guys get the same problem?

**Comment by jianglinjian** [comment]
@oleg-yudovich could you provide the `sigs.k8s.io/cluster-api` version which one you used？ only `v0.3.0-rc.0` will been create client using the `WithLazyDiscovery` option
https://github.com/kubernetes-sigs/cluster-api/blob/v0.3.0-rc.0/controllers/remote/cluster.go#L41
