### ISSUE TITLE
Why does my Watches function not work

### ISSUE THREAD

**Issue by acechef** [kubernetes-sigs/controller-runtime#1758]
Version: sigs.k8s.io/controller-runtime v0.10.0

I have two resources, they are: ChainConfig and ChainNode, there is no reference relationship between them.

Now I want to enter the Reconcile loop of ChainNode when ChainConfig changes, I wrote the following code in the `chainnode_controller.go` file:

```
// SetupWithManager sets up the controller with the Manager.
func (r *ChainNodeReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&citacloudv1.ChainNode{}).
		Watches(
			&source.Kind{Type: &citacloudv1.ChainConfig{}},
			&handler.EnqueueRequestForOwner{OwnerType: &citacloudv1.ChainNode{}, IsController: false},
			).
		Complete(r)
```

However, when I modify the ChainConfig resource, the Reconcile loop of the ChainNode Controller does not respond.

Now I don't know what to do...

**Comment by coderanger** [comment]
1) You can just an `Owns()` watch instead of the expanded form but that's not the problem 2) are you 100% sure you are correctly setting the owner reference when creating the ChainNode object?
