### ISSUE TITLE
Cache start should failed if crd of scheme not found

### ISSUE THREAD

**Issue by weilaaa** [kubernetes-sigs/controller-runtime#1759]
**What happened?**
Assumed we didn't apply crds into cluster, and then list/get cr by using cache of controller-runtime, we got error when list rather than got error when cache start.

- code like that:
```golang
func main() {
	scheme := runtime.NewScheme()
	err := hnc.AddToScheme(scheme)
	if err != nil {
		log.Fatalln("add scheme error:", err)
	}

	c, err := cache.New(ctrl.GetConfigOrDie(), cache.Options{Scheme: scheme})
	if err != nil {
		log.Fatalln("cache new error:", err)
	}

	ctx := context.Background()

	go func() {
		err = c.Start(ctx)
		if err != nil {
			log.Fatalln("cache start error:", err)
		}
	}()

	if c.WaitForCacheSync(ctx) {
		sub := &hnc.SubnamespaceAnchorList{}
		err = c.List(ctx, sub, &client.ListOptions{Namespace: "default"})
		if err != nil {
			log.Fatalln("list error:", err)
		}
	}
}
```
- got:
```log
2021/12/30 18:58:56 list error: no matches for kind "SubnamespaceAnchor" in version "hnc.x-k8s.io/v1alpha2"
```

- expect:
expected error occurred when `c.Start(ctx)`, something like: "cache start error: xxx"

**controller-manager**
version: v0.11.0

**Comment by weilaaa** [comment]
If this problem is accepted, I'm willing to deal with it.

**Comment by FillZpp** [comment]
@weilaaa Actually, when you create a new cache with no watch GVK registered in it, it does nothing when start and it has no idea which CRD should it check from scheme. Util you called `List` with some kind of resource, it tries to create an informer for this kind, begins to list watch for it, and gets the no kind error.

**Comment by weilaaa** [comment]
Yep, I noticed that informer will be dynamic created when we try to fetch some resource of a kind at first time.

I agreed with you said that "it has no idea which CRD should it check from scheme" when cache start, thanks.

https://github.com/kubernetes-sigs/controller-runtime/blob/46179a0b83709c2708272d2058aa37e54f4e0eff/pkg/cache/internal/informers_map.go#L186-L198
