### ISSUE TITLE
Is it ok for a Reconcile to take a long time.

### ISSUE THREAD

**Issue by YairHalberstadt** [kubernetes-sigs/controller-runtime#1763]
Hi, I hope this is the right place to ask questions I couldn't find information about anywhere else, if not please do direct me there.

We have a controller that has to do heavy processing which may take a long time. In the worst case scenario maybe even an hour.

At the moment this work takes place in the reconcile loop. This provides us with important guarantees - like that that two controllers won't run at the same time on the same object, and that even if the reconcile crashes we'll still try again later.

Is it ok for a Reconcile loop to take such a long time? Or should we find some way to offload this to a separate goroutine or server?

Thanks!

**Comment by coderanger** [comment]
No, this is not correct. Long-running work should probably be launched as a Job object. Operators just coordinate stuff, no reconcile should ever take more than a few milliseconds.

**Comment by YairHalberstadt** [comment]
@coderanger thanks, just to understand, why not?

**Comment by coderanger** [comment]
Because the operator needs to handle all your other objects too. It's multiplexing by not doing blocking operations. And just design-wise we have no handling in place for stuff like storage management to checkpoint long-running computations or stateful data. All that is expected to be handled by the Kubernetes workload types (Deployments, StatefulSets, Jobs, CronJobs, etc). We would we reinvent that wheel?

**Comment by YairHalberstadt** [comment]
> Because the operator needs to handle all your other objects too. It's multiplexing by not doing blocking operations

But can't we use controller concurrency for that?

> And just design-wise we have no handling in place for stuff like storage management to checkpoint long-running computations or stateful data.

In our particular case there's no need for that. It's a single long running atomic operation.

**Comment by coderanger** [comment]
I mean it's your code and I can't stop you but it breaks the expected model for a controller. I've given you the explanation, if you're response is "I don't care" then ... go for it?

/close

**Comment by YairHalberstadt** [comment]
Ok, thanks for your time! I guess I was trying to understand if this was a hard limit, or something which we could use for a prototype, and move off of when we move to an actual release.
