### ISSUE TITLE
Does it support openshift resources, such as adding, deleting, modifying and checking routes? 

### ISSUE THREAD

**Issue by AllenZMC** [kubernetes-sigs/controller-runtime#1769]
Help! Does it support openshift resources, such as adding, deleting, modifying and checking routes? 
Thanks!
After the schema is registered, there is no problem with the creation of the route, but the get cannot get it .

**Comment by coderanger** [comment]
The client is generic and supports any resource. You can find more documentation at https://book.kubebuilder.io/.

/close

**Comment by AllenZMC** [comment]
> The client is generic and supports any resource. You can find more documentation at https://book.kubebuilder.io/.
> 
> /close
But after the schema is registered, there is no problem with the creation of the route, but the get cannot get it .
