### ISSUE TITLE
[feature request] Add support for pprof

### ISSUE THREAD

**Issue by grzesuav** [kubernetes-sigs/controller-runtime#1779]
# Add support for serving pprof data

It would be nice to extend manager with option to enable pprof when requested, I found similar issue in kubebuilder suggesting it should be added in controller-runtime

Related issues :
 - https://github.com/kubernetes-sigs/kubebuilder/issues/1225

**Comment by alculquicondor** [comment]
/reopen
I believe this is still in the works

**Comment by AmourLinux** [comment]
I have same request. Is there any progress?

**Comment by alculquicondor** [comment]
/reopen
@zqzten still seems to be working on this
