### ISSUE TITLE
parent CRD reconcile slow to react to many child CRD updates

### ISSUE THREAD

**Issue by dgkanatsios** [kubernetes-sigs/controller-runtime#1782]
We are working on the operator in this repo: https://github.com/PlayFab/thundernetes/tree/master/pkg/operator

We have two CRDs, GameServerBuild and GameServer. GameServerBuild has a .standingBy (replicas) field that will create X instances of GameServer. GameServerBuild Controller is .For(GameServerBuild) and .Owns(GameServer), GameServer Controller is .For(GameServer). GameServerBuild Controller creates X instances of GameServer CR, and on Reconcile it also updates GameServerBuild.Status.

For small numbers of .standingBy (replicas), everything works fine. However, for big numbers (200?) of replicas, we observer that the GameServer.Reconcile is called as it should (once for every GameServer CR), whereas GameServerBuild.Reconcile is called really late. For example, if we set the GameServerBuild to 350replicas, we can see that GameServer.Reconcile being called normally whereas GameServerBuild.Reconcile is called after ~60 GameServer CRs have been created. Any ideas what we can do to improve this?

Thanks in advance!

---

[Here](https://github.com/PlayFab/thundernetes/blob/master/pkg/operator/controllers/gameserverbuild_controller.go#L304) is the code for the GameServerBuild controller and [here](https://github.com/PlayFab/thundernetes/blob/master/pkg/operator/controllers/gameserver_controller.go#L264) is the code for the GameServer controller.

Some other points/things we tried:

1. Interestingly, in our tests, if we remove the MaxConcurrentReconciles argument, the .Reconcile is called faster (!!!) (when scaling from 2 to 350, with 10 MaxConcurrentReconciles it's called at ~60 GameServer creation whereas with 1 MaxConcurrentReconciles it's called at ~30).
2. We tried increasing CPU requests/limits for the controller, no chance
3. We switched to an alternative rate limiter, no change in behavior unfortunately

```
return ctrl.NewControllerManagedBy(mgr).
		For(&mpsv1alpha1.GameServerBuild{}).
		Owns(&mpsv1alpha1.GameServer{}).
		WithOptions(controller.Options{
			RateLimiter: clientgo.NewItemFastSlowRateLimiter(time.Second*1, time.Second*5, 5),
		}).
		Complete(r)
```

**Comment by FillZpp** [comment]
Just my thought and questions.

1. There is no relation to the RateLimiter, unless your reconcile returns error.
2. Did you test it with one GameServerBuild or multiple GameServerBuilds? If one, it should be no relation to the MaxConcurrentReconciles of GameServerBuild controller.
3. What do you mean "called at ~60 GameServer creation"?

**Comment by dgkanatsios** [comment]
thanks @FillZpp for the comments!

- I tested with a single GameServerBuild. The MaxConcurrentReconciles I mention is applied to the GameServer controller (code [here](https://github.com/PlayFab/thundernetes/blob/master/pkg/operator/controllers/gameserver_controller.go#L264))
- So what I did is include a fmt.Println at the very top of both controllers' Reconcile method to see when it would be called. When I increased the scale of the GameServerBuild from 2 to 350, I monitored when the GameServerBuild controller Reconcile method would be called, in relation the the GameServer controller Reconcile method. It turns out that the GameServerBuild reconcile was called after ~60 GameServer CRs where created (so the GameServer Reconcile method was called ~60 times). Hope this makes sense, let me know if it doesn't!

The fact that the GameServerBuild Reconcile method gets called late is really weird, since both the GameServerBuild and the GameServer controllers essentially watch the same object (the GameServerBuild controller with a .Owns() and the GameServer with a .For()).

**Comment by FillZpp** [comment]
Aha, I think I have figured out your question. The truth is **both your GameServerBuild and GameServer controllers are fine.** They did not work slowly or have any problems.

It is because your GameServerBuild reconciles and creates desired number of GameServer **ONE BY ONE**, so of course it takes more time when you increase the standingBy number. When GameServerBuild controller is creating GameServer, the created GameServers will be reconciled by GameServer controller. After GameServerBuild have created all GameServer and finished reconcile this time, it can be reconciled again, and GameServer controller may have reconciled some GameServers at this time.

And of course you will see "it called faster when you removed MaxConcurrentReconciles for GameServer controller". It is not because GameServerBuild controller becomes faster, but the GameServer controller reconciles slower (it has less worker to do reconcile). The time that GameServerBuild creates a number of GameServer does not change.

Not sure if I made it clear :)

**Comment by dgkanatsios** [comment]
thanks @FillZpp 
We fixed it with your help!
The solution is that the loop calls .Create(newGameServer) synchronously, so, as you said, the Controller is unresponsive for the time it takes to create the vast amount of game servers. By adding a variable that controls the max number of gameservers to create per loop, everything works fine.
Thanks for your help, much appreciated!

**Comment by FillZpp** [comment]
@dgkanatsios My pleasure.

For this case, GameServerBuild controller can create the gameservers parallelly. You can see how replicaset controller do this with `slowStartBatch`: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L570
It helps ReplicaSet to create a large number of Pod.
