### ISSUE TITLE
Possible leader election deadlock

### ISSUE THREAD

**Issue by fabxc** [kubernetes-sigs/controller-runtime#1784]
I looked at the leader election code in the `controllerManager` and was wondering whether there's a potential deadlock [here](https://github.com/kubernetes-sigs/controller-runtime/blob/f236f0345ad2933912ebf34bfcf0f93620769654/pkg/manager/internal.go#L642).

From the documentation and what I can see in the implementation `LeaderElector.Run` returns if it loses the lease, e.g. due to connectivity issues. Since there is no re-attempting to get the lease, the controller manager should exit and the entire process should restart to reacquire the lease in the future. Otherwise it's just an inactive replica forever.

In the above line, the controller manager waits however for the parent context to be canceled, which may only happen much later or possibly never. If all replicas end up in this state, none of them will consider itself the leader and make progress.

**Comment by FillZpp** [comment]
Then LeaderElector lost the lease, it will call the `OnStoppedLeading` func, which triggers controllerManager to exit immediately.

https://github.com/kubernetes-sigs/controller-runtime/blob/f236f0345ad2933912ebf34bfcf0f93620769654/pkg/manager/internal.go#L621-L632

**Comment by fabxc** [comment]
Thanks! I was lookng for some logic like this but didn't spot it yesterday for some reason.
