### ISSUE TITLE
Expose Discovery Client via controller-runtime

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-runtime#1787]
Currently there is no way to call the discovery apis from client.Client. It will be nice to call discovery apis via the Client. Then we can avoid having to pass multiple clients (one for Client, one for Discovery) everywhere.

**Comment by FillZpp** [comment]
I don't think it is a good idea, multiple clients is fine in this scenario. Just like we can not support all K8s API in controller-runtime client, e.g. pod logs/exec, scale subresource, ...

**Comment by tamalsaha** [comment]
I understand not wanting to support every possible api. But discovery apis are accessed much more frequently than pod log/exec api.

**Comment by m1o1** [comment]
From what I can tell, this seems to be needed in order to use the helm SDK and share the same clients that the controller runtime manager uses. Maybe helm could change to remove that necessity but just wanted to share a possible use case for this.

**Comment by tamalsaha** [comment]
FWIW, I was able to solve this implementing my own delegating client https://github.com/kmodules/client-go/blob/master/client/delegated.go#L122-L127
