### ISSUE TITLE
Support warnings in webhook utils

### ISSUE THREAD

**Issue by fabxc** [kubernetes-sigs/controller-runtime#1788]
The admission package supports returning warnings on webhook requests through `Response.WithWarnings`.
It seems one cannot make use of the utility interfaces and constructors if one wants to respond warnings. So one would end up re-implementing a bunch of the logic.

To not break the existing API, a specific error type could be used which is introspected by the existing utility logic. For an only-warnings error, an Allowed response would be returned.

This could be surfaced through 2 simple functions:

```go
// Triggers an Allowed response with warnings.
func Warnings(...string) error

// Triggers a Denied response with the given error and additional warnings.
func ErrorAndWarnings(error, ...string) error
```

**Comment by sbueringer** [comment]
/close

As 
> It seems one cannot make use of the utility interfaces and constructors if one wants to respond warnings.

Is now possible after https://github.com/kubernetes-sigs/controller-runtime/pull/2014 was merged
