### ISSUE TITLE
client/config package offers no way to avoid merging `HOME` dir configs

### ISSUE THREAD

**Issue by kurt-google** [kubernetes-sigs/controller-runtime#1791]
Originally we assumed `KUBECONFIG` env var would override the search directory for configs and allow us to specify exactly the config we wanted. But it appears there is no way in the `config` package for us to setup a specific config to be used. This is extremely useful functionality for testing.

This is also unexpected in my opinion and reading of https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable where the definition is

> If the KUBECONFIG environment variable does exist, kubectl uses an effective configuration that is the result of merging the files listed in the KUBECONFIG environment variable.

Which makes no mention of also including configs from `$HOME` or other default locations.

**Comment by jmrodri** [comment]
@kurt-google interesting. After reading the KUBECONFIG documentation and the comments in controller-runtime, I agree that if the KUBECONFIG environment variable is set, it should use that.

**Comment by kurt-google** [comment]
>  I agree that if the KUBECONFIG environment variable is set, it should use that.

It does find and use the KUBECONFIG env var, but it does not use it _exclusively_ which is what I understand when reading the docs. It augments the KUBECONFIG configs with the home dir configs which for us results in potentially unwanted or conflicting configs being added.

**Comment by coderanger** [comment]
It should follow the same behavior as `kubectl` so if there is a mismatch, we should fix that :)

**Comment by kurt-google** [comment]
It is simple to test that `kubectl` does not merge in $HOME dir configs by replacing your `$HOME/.kube/config` file with an improperly formatted one. And this test does show that kubectl will not attempt to load this default config unless it is specified in the `KUBECONFIG` env var list.

**Comment by kurt-google** [comment]
I believe this is still an issue.

**Comment by kurt-google** [comment]
I'm not sure how this tool works but I still believe this an issue.

/reopen

/remove-lifecycle rotten
