### ISSUE TITLE
Set controller name as k/v pair in logger

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#1794]
Hey folks,

I saw that the controller name is add via `WithName` calls on the logger of a controller. This results in a logger name of "controller/\<name\>". I wonder if we should set it as a k/v pair instead.

An example: (I'm using k/component-base/logs for logging)

### Current implementation: 

`Log:                     options.Log.WithName("controller").WithName(name),` 
(https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L138)

logging-format: text
> I0208 10:09:22.914540   30061 controller.go:224] controller/cluster "msg"="Starting workers" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="ClusterClass"

logging-format: json
> {"ts":1644313339262.228,"caller":"controller/controller.go:224","msg":"controller/cluster: Starting workers","v":0,"reconciler group":"cluster.x-k8s.io","reconciler kind":"Cluster"}

### Using k/v: 

`Log:                     options.Log.WithValues("controller", name),`

logging-format: text
> I0208 10:40:01.223292   45529 controller.go:224]  "msg"="Starting workers" "controller"="cluster" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"

logging-format: json
> {"ts":1644313298144.636,"caller":"controller/controller.go:224","msg":"Starting workers","v":0,"reconciler group":"cluster.x-k8s.io","reconciler kind":"Cluster","controller":"cluster"}

As you can see the logger name is used as a prefix in the message (that should always be the case with klog, as klog sets the WithName as a prefix, not sure about other log implementations). I think it would be better to have it as a k/v pair instead as that makes it possible to filter logs based on the controller name, without having to parse the log message to do it.

**Comment by ykakarap** [comment]
+1 to the general idea. It would make filtering logs for a specific controller much simpler.

**Comment by sbueringer** [comment]
I'll close this issue for now as the k/v pair has been added. I'll include Fabrizio's requirement in a new issue that I'll open in a bit.

/close
