### ISSUE TITLE
Enable per-reconcile logger customization

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#1811]
It would be great if it would be possible to modify loggers for individual reconciles. 

Some context:
* When using the standard controller `pkg/builder.Builder` today you can set a logger which is later adjusted:
  * during Builder.Build():
    * "reconciler group" and "reconciler kind" k/v pairs are added
    * "controller" and "\<controller-name\>" are added as logger name
    * "controller": "\<controller-name\>" is added as k/v pair
  * per reconcile in reconcileHandler:
    * "name": "\<object-name\>", "namespace": "\<object-namespace\>" k/v pairs are added

The name and the k/v pair are added on top of either the logger provided in the builder or on top of `mgr.GetLogger()`.

We would like to be able to customize the logger according to our requirements. Concrete this means we would like to add a "traceID" and "\<kind\>": "\<namespace\>/\<name\>" k/v pair to the logger (more background info below). We could do this during the `Reconcile` call, but then the error logged by controller-runtime wouldn't have this context ([this one](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L317)).

As I'm pretty sure there are different opinions about what the name of a logger should look like and which k/v pairs should or shouldn't be added, I would propose to add a "hook" so that folks are able to customize the logger in the way they want.
Also e.g. dropping the current "name"/"namespace" k/v pairs would be a breaking change in controller-runtime.

### Background info about "traceID" and "\<kind\>": "\<namespace\>/\<name\>"

* "traceID": we want to be able to correlate logs of an individual reconcile. Furthermore we want to be able to correlate them with traces and metrics in the future
* "\<kind\>": "\<namespace\>/\<name\>": We are trying to follow the upstream [Kubernetes structured logging KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging#references-to-kubernetes-objects). The KEP standardizes the "value" of the k/v pair to be "'\<namespace\>/\<name\>". It doesn't exactly standardize the key of it but in CAPI we will probably follow the examples there and use the lower case singular kind.

I just wanted to provide this as background information. I think the discussion if this is a good or bad idea is out-of-scope (and still TBD in the CAPI project). But I think it should illustrate that it's worth making the logger customizable, so it's possible to accommodate requirements like this.

I've opened the following PR to illustrate how a solution could look like:
* CR: https://github.com/kubernetes-sigs/controller-runtime/pull/1812
* CAPI (very-WIP): https://github.com/kubernetes-sigs/cluster-api/pull/6150/files#r808443915

**Comment by sbueringer** [comment]
/cc @alvaroaleman @fabriziopandini @vincepri 
(of course feel free to cc other folks, not sure who else would want to be cc'ed)

**Comment by sbueringer** [comment]
Hm an additional note. Maybe we should make the customizer a bit more powerful (https://github.com/kubernetes-sigs/controller-runtime/pull/1812/files#r808099005)

By passing the ctx into and out of the customizer the customizer could use additional context to customize the ctx and the logger (obviously the name then doesn't fit that good anymore).

I'm especially thinking about the tracing use case. By passing the ctx in and out of the ctx it would be possible to create a new trace / span and add it to the context

P.S. this could almost also be done inside of the Reconcile func, but then the log.Error wouldn't have the traceID as k/v pair

**Comment by vincepri** [comment]
Could we consider starting the trace within Controller Runtime (other folks might want to use this as well) and inject it into the context?

**Comment by sbueringer** [comment]
> Could we consider starting the trace within Controller Runtime (other folks might want to use this as well) and inject it into the context?

I think that is reasonable. Although I would like to think about tracing specifically a bit more before proposing that and then open a new separate issue. But I think it should be fine to treat tracing as a separate topic and focus here on the log customization as it's (at least in my opinion) still a reasonable improvement independent of tracing.

**Comment by sbueringer** [comment]
I'll open a new with an alternative proposal, i.e. just changing the logging in CR vs. making it customizable.

Let's hold this issue for now.
