### ISSUE TITLE
View runtime

### ISSUE THREAD

**Issue by notadeveloperyet** [kubernetes-sigs/controller-runtime#1814]
Tip: to reduce the size of the resulting binary, you can use `GO_LDFLAGS="-s -w"`

**Comment by coderanger** [comment]
For anyone that finds this in the future, `-s` strips symbol tables and `-w` removes DWARF debugging data used by gdb and related tools. While both do result in a smaller executable, it will also make external debugging against it more or less impossible so caveat emptor.

This isn't a bug per se so I'm going to close it. Please don't open issues for feedback like this.

/close

**Comment by notadeveloperyet** [comment]
I'm set[rescan]()
