### ISSUE TITLE
Add ratelimiter option in  global controller options 

### ISSUE THREAD

**Issue by pigletfly** [kubernetes-sigs/controller-runtime#1819]
Now we have `GroupKindConcurrency` and `CacheSyncTimeout` in ControllerConfigurationSpec https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/config/v1alpha1/types.go#L78-L97, we should provide a way to configrate `ratelimiter` globally so that we needn't have to add ratelimiter options in each controller.

**Comment by FillZpp** [comment]
@pigletfly Sounds reasonable. But question is ratelimiter is an interface, how could you add it in ControllerConfigurationSpec? Are you going to define the args of ItemExponentialFailureRateLimiter and BucketRateLimiter directly?

**Comment by pigletfly** [comment]
Interface is ok, in my opinion, leave the implementation to users, not limited to ItemExponentialFailureRateLimiter or BucketRateLimiter.But we still have the default limiter, and the limiter in specific controller should override the global limiter.Just like controller Options in controller-runtime https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L47

**Comment by FillZpp** [comment]
> Interface is ok, in my opinion, leave the implementation to users

Actually, `ControllerConfigurationSpec` is like the Spec defined in CRD, you can not write a field of interface type in it.

**Comment by pigletfly** [comment]
I missed that point.Any suggestion ? @FillZpp

**Comment by FillZpp** [comment]
Emm.. no yet. Like I said above, you could not do this, unless you directly define the args of ItemExponentialFailureRateLimiter and BucketRateLimiter. But it is not a good idea.
