### ISSUE TITLE
Defaulter is misleading in cases where mutation is not a defaulting operation

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/controller-runtime#1820]
`Defaulter` is the name used for mutating webhook handlers in controller-runtime, specifically the [`Defaulter`](https://github.com/kubernetes-sigs/controller-runtime/blob/c48baad/pkg/webhook/admission/defaulter.go#L28) interface that is required to register mutating webhooks.

Even though it's called `Defaulter` and that's probably what people use mutating webhooks mostly, the term `Mutator` or something related to `Mutation` could be more representative of what it's for. Because after all, API object that we register with api-server is called `MutatingWebhookConfiguration`, not `DefaultingWebhookConfiguration`, and all kinds of mutations are allowed by the api-server. Though I might be missing some historical context here.

If you feel good about it, I can work on this by copying `Defaulter` interface and related types with `Mutator` term and mark the old ones deprecated.

**Comment by sbueringer** [comment]
Not sure if we want to rename, but I agree that Defaulter is misleading. To a point where folks don't understand that they can use it for more than just defaulting.
