### ISSUE TITLE
v0.11 can not work around with golang v1.16.14

### ISSUE THREAD

**Issue by boycs007** [kubernetes-sigs/controller-runtime#1825]
Go Version 1.16.14 & controller-runtime v0.11.1 / v0.11.0 will cause the build to fail : 

/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
FAIL	xxxxxxxx [build failed]

**Comment by alvaroaleman** [comment]
Yes, we require golang 1.17: https://github.com/kubernetes-sigs/controller-runtime/blob/9ee63fc65a9720568f74df9901b16883621636b4/go.mod#L3

This is a won't fix, we are following upstream k/k in terms of go version and will only ever support the go version they support, which for the current release is 1.17.
