### ISSUE TITLE
circular dependency between writeResponse & writeAdmissionResponse

### ISSUE THREAD

**Issue by henrysecond1** [kubernetes-sigs/controller-runtime#1829]
### Environment

- k8s version: v1.19.9 (on-prem)
- controller-runvime version: v0.8.2

### Problem

I'm not sure when it actually happens, but we suffered from a very large stack trace log when admission errors occur.
When we investigate the log, we saw the two functions (`writeResponse` and `writeAdmissionResponse`) are repeatedly calling each other.

- https://github.com/kubernetes-sigs/controller-runtime/blob/v0.11.1/pkg/webhook/admission/http.go#L105
- https://github.com/kubernetes-sigs/controller-runtime/blob/v0.11.1/pkg/webhook/admission/http.go#L129

Could you tell me any suggestions to solve this problem?

**Comment by FillZpp** [comment]
@henrysecond1 It might be caused by the broken connection (e.g., broken pipe) with kube-apiserver, so that the encoder could never write the response into `w io.Writer`, and then it runs into endless circular calling.
