### ISSUE TITLE
Remove vendor directory

### ISSUE THREAD

**Issue by EngHabu** [kubernetes-sigs/controller-runtime#183]
It's not clear to me why the vendor directory exists in source code in the first place... deps will pull and "install" those as needed...
For what it's worth, I'm trying to consume controller runtime in a library project that uses glide and somehow go runtime hasn't figured out that libraries in controller-runtime/vendor/ are actually the same as the ones in my library's vendor directory and hence get type mismatching problems all over...

**Comment by EngHabu** [comment]
@coderanger thanks for your prompt response! from my experience, the only place I can justify vendoring dependencies is in an executable binary repo (like, you have a mian.go)... where you don't expect others to take a dependency on your library... otherwise, conflicts are just bound to happen due to how glide soft-flatening rules work...

As for reproducible builds, not sure why is that though? glide.lock should have a flat list of dependencies pinned to a git SHA... running glide install should ALWAYS install those same exact versions every single time... care to elaborate on that point? In what scenario is that not true?

**Comment by DirectXMan12** [comment]
@EngHabu you should always call `glide install -v` when using glide, which strips vendor directories in vendored projects.

**Comment by DirectXMan12** [comment]
(feel free to continue on this thread if you have further questions, but I'm closing it now for bookkeeping purposes)
