### ISSUE TITLE
FakeClient Status() patch modifies parent object in 0.11.1?

### ISSUE THREAD

**Issue by burmanm** [kubernetes-sigs/controller-runtime#1832]
I have the following code segment (https://github.com/k8ssandra/cass-operator/blob/master/pkg/reconciliation/reconcile_racks.go#L1681):

```go
func (rc *ReconciliationContext) enableQuietPeriod(seconds int) error {
	dc := rc.Datacenter

	dur := time.Second * time.Duration(seconds)
	statusPatch := client.MergeFrom(dc.DeepCopy())
	dc.Status.QuietPeriod = metav1.NewTime(time.Now().Add(dur))
	fmt.Printf("enableQuietPeriod: %v\n", rc.Datacenter.Spec.CanaryUpgrade)
	fmt.Printf("enableQuietPeriod: %v\n", rc.Datacenter.Spec.CanaryUpgradeCount)
	err := rc.Client.Status().Patch(rc.Ctx, dc, statusPatch)
	fmt.Printf("enableQuietPeriodAfterPatch: %v\n", rc.Datacenter.Spec.CanaryUpgrade)
	fmt.Printf("enableQuietPeriodAfterPatch: %v\n", rc.Datacenter.Spec.CanaryUpgradeCount)
	return err
}
```

When using 0.10.0, the output is:

```
enableQuietPeriod: true
enableQuietPeriod: 1
enableQuietPeriodAfterPatch: true
enableQuietPeriodAfterPatch: 1
```

Like one would assume. However, with 0.11.1, the output is:

```
enableQuietPeriod: true
enableQuietPeriod: 1
enableQuietPeriodAfterPatch: false
enableQuietPeriodAfterPatch: 0
```

After Status() patching, the parent object is modified to be all default values suddenly. Is this intended behavioral change or a bug in the 0.11.1 ?

**Comment by FillZpp** [comment]
@burmanm Did you test the cases in clusters with different Kubernetes versions, or in a same cluster? Have you used `kubectl get ...` to see if the object in apiserver is equal to the object you got or not?

**Comment by burmanm** [comment]
This behavior happens against fake client (Kube 0.23.4 deps). It's repeatable in the unit test. Thus, no cluster.

**Comment by burmanm** [comment]
Looking with the debugger, the cause of this behavior change is the addition of this line:

https://github.com/kubernetes-sigs/controller-runtime/blame/b8db76e66383819c94f530bd4b8dea60025b716f/pkg/client/fake/client.go#L344

I assume it was added to fix something else with Patch, but at the same time it broke the Status().Patch() behavior.
