### ISSUE TITLE
use Own() or Watches() for custom resources

### ISSUE THREAD

**Issue by yingyingtang-brex** [kubernetes-sigs/controller-runtime#1834]
We currently have a use case to have the controller create and watch a custom resource that is not written in Go. We could create the customer resource by using the a dynamic client. 
However, to own/watch the created resource, we need to call `Own()` or `Watches()` and pass the `client.Object`, e.g. `&kapps.Deployment{}`, which we do not have.
Is there an approach to own/watch the custom resource, and pass the custom resource information, e.g. Group/Kind/Version, like how we use the dynamic client?

**Comment by coderanger** [comment]
Use an Unstructured.

**Comment by FillZpp** [comment]
`"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"`
