### ISSUE TITLE
Discover ApiVersion of a resource

### ISSUE THREAD

**Issue by fox-md** [kubernetes-sigs/controller-runtime#1836]
Hi,

It is a question, not an issue.

Lets say I have 2 custom resources of different api versions: v1 and v2

```
apiVersion: vm.com/v1alpha1
kind: VmItem
metadata:
  name: vmitem-sample-v1
spec:
  itemtype: mytype
```

```
apiVersion: vm.com/v2alpha1
kind: VmItem
metadata:
  name: vmitem-sample-v2
spec:
  itemtype: mytype
  items: 3
```

Inside of the Reconcile function I would like to get object by name, kind and namespace. 

```
u := &unstructured.Unstructured{}
u.SetKind("VmItem")
u.SetName(req.Name)
u.SetNamespace(req.Namespace)
```

I was hoping to use GetAPIVersion() function to find value for apiVersion field, but controller returns an error:
```
Object 'apiVersion' is missing in 'unstructured object has no version'
```

Can you please advise, is it possible to get apiVersion of an object by kind, name and namespace?

Thank you

**Comment by FillZpp** [comment]
> I was hoping to use GetAPIVersion() function to find value for apiVersion field

@fox-md If you want to get information of CRDs, for example find all apiVersions of kind `VmItem`, you have to use `k8s.io/client-go/discovery` to get server resources in K8s cluster.

The unstructured only helps you read or write CRs, e.g.,
```golang
u := &unstructured.Unstructured{}
u.SetAPIVersion("vm.com/v1alpha1")
u.SetKind("VmItem")
cli.Get(context.TODO(), req, u)
```

It seems your controller will watch the `VmItem` resource with two different versions and then put all of them into workqueue. It is not the recommended way. Is there no conversion between the two versions?

**Comment by fox-md** [comment]
Hi @FillZpp,
Thank you for your response. 
discovery is useful to find all apiVersions of a certain kind, but I was looking for a way to find apiVersion of a certain object.

>  Is there no conversion between the two versions?

Yes, for the moment there is not conversion implemented.

> It seems your controller will watch the VmItem resource with two different versions and then put all of them into workqueue. It is not the recommended way. 

Can you please advise, what is the recommended way to handle multiple versions? According to the guide, that is handled by conversion. Is that really the only way?

Indeed, it seems that now both v1alpha1 and v2alpha1 are getting into the same workqueue. Tried to filter events that are getting into workqueue using below approach, but v2alpha1 items are still getting processed by this loop.

```
func (r *VmItemReconciler) SetupWithManager(mgr ctrl.Manager) error {
	vmItem := vmv1alpha1.VmItem{}
	vmItem.APIVersion = "vm.com/v1alpha1"
	vmItem.Kind = "VmItem"
	return ctrl.NewControllerManagedBy(mgr).
		For(&vmItem).
		Complete(r)
}
```

Can you please advise, is there a way to tell Reconcile function to watch for a specific apiVersion only?

Thank you

**Comment by FillZpp** [comment]
> ```
> func (r *VmItemReconciler) SetupWithManager(mgr ctrl.Manager) error {
> 	vmItem := vmv1alpha1.VmItem{}
> 	vmItem.APIVersion = "vm.com/v1alpha1"
> 	vmItem.Kind = "VmItem"
> 	return ctrl.NewControllerManagedBy(mgr).
> 		For(&vmItem).
> 		Complete(r)
> }
> ```

This will only watch objects with `vm.com/v1alpha1` (btw, you don't have to set fields, only `For(&vmv1alpha1.VmItem{})`), no v2alpha1 object will be handled.

The recommended way is a conversion webhook between two versions, and you only have to watch and handle the storage version.

If you have no conversion, I suggest that you can setup two controllers for them, but the reconcile logic can be reused. For example:

```golang
type VmItemReconciler struct {
    client.Client
    // ...
    APIVersion string
}

func (r *VmItemReconciler) object() client.Object {
    if APIVersion == "vm.com/v1alpha1" {
        return &vmv1alpha1.VmItem{}
    }
    return &vmv2alpha1.VmItem{}
}

func (r *VmItemReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
    // You can also use unstructured here, but it will get directly from apiserver
    err := r.Get(ctx, req, r.object())
    // ...
}

func (r *VmItemReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(r.object()).
		Complete(r)
}

// main.go
    &controllers.SampleReconciler{
        Client: mgr.GetClient(),
        // ...
        APIVersion: "vm.com/v1alpha1",
    }).SetupWithManager(mgr)

    &controllers.SampleReconciler{
        Client: mgr.GetClient(),
        // ...
        APIVersion: "vm.com/v2alpha1",
    }).SetupWithManager(mgr)
``` 

Also note that we usually don't use version `v2alpha1`. The sequence should be `v1alpha1`, `v1alpha2`, ..., `v1beta1`, `v1beta2`, ..., `v1`.

**Comment by fox-md** [comment]
>This will only watch objects with vm.com/v1alpha1 (btw, you don't have to set fields, only For(&vmv1alpha1.VmItem{})), no v2alpha1 object will be handled.

Unfortunately that is not the case. Both VmItem controllers are processing the same object.

Thank you for your recommendations. I renamed `v2alpha1` to `v1`

Can you please advise why do both controllers process the same object? Is there a way to explicitly specify ApiVersion somewhere in `For` maybe? It is seems that `For(&vmv1.VmItem{})` only tells what kind of object to watch.

v1 controller:

```
type VmItemV1Reconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

func (r *VmItemV1Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := log.FromContext(ctx)
	log.Info("V1 reconcile")
	return ctrl.Result{}, nil
}

func (r *VmItemV1Reconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&vmv1.VmItem{}).
		Complete(r)
}
```
v1alpha1 controller:
```
type VmItemReconciler struct {
	client.Client
	Scheme   *runtime.Scheme
	Recorder record.EventRecorder
}

func (r *VmItemReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := log.FromContext(ctx)
	log.Info("v1alpha1 reconcile")
	return ctrl.Result{}, nil
}

func (r *VmItemReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&vmv1alpha1.VmItem{}).
		Complete(r)
}
```

main.go
```
if err = (&controllers.VmItemV1Reconciler{
	Client: mgr.GetClient(),
	Scheme: mgr.GetScheme(),
}).SetupWithManager(mgr); err != nil {
	setupLog.Error(err, "unable to create controller", "controller", "VmItemV1")
	os.Exit(1)
}
if err = (&controllers.VmItemReconciler{
	Client:   mgr.GetClient(),
	Scheme:   mgr.GetScheme(),
	Recorder: mgr.GetEventRecorderFor("myoperator"),
}).SetupWithManager(mgr); err != nil {
	setupLog.Error(err, "unable to create controller", "controller", "VmItem")
	os.Exit(1)
}
``` 

k8s resource
```
cat vmitem-sample-v1alpha1.yaml
apiVersion: vm.com/v1alpha1
kind: VmItem
metadata:
  name: vmitem-sample-v1alpha1
spec:
  itemtype: sometype
```

According to the logs, 2 workers are started and both are watching for kind VmItem of any version
```
2022-03-11T13:20:45.624+0200    INFO    setup   starting manager
2022-03-11T13:20:45.625+0200    INFO    starting metrics server {"path": "/metrics"}

2022-03-11T13:20:45.625+0200    INFO    controller.vmitem       Starting EventSource    {"reconciler group": "vm.com", "reconciler kind": "VmItem", "source": "kind source: /, Kind="}
2022-03-11T13:20:45.625+0200    INFO    controller.vmitem       Starting Controller     {"reconciler group": "vm.com", "reconciler kind": "VmItem"}

2022-03-11T13:20:45.625+0200    INFO    controller.vmitem       Starting EventSource    {"reconciler group": "vm.com", "reconciler kind": "VmItem", "source": "kind source: /, Kind="}
2022-03-11T13:20:45.626+0200    INFO    controller.vmitem       Starting Controller     {"reconciler group": "vm.com", "reconciler kind": "VmItem"}

2022-03-11T13:20:45.727+0200    INFO    controller.vmitem       Starting workers        {"reconciler group": "vm.com", "reconciler kind": "VmItem", "worker count": 1}
2022-03-11T13:20:45.727+0200    INFO    controller.vmitem       Starting workers        {"reconciler group": "vm.com", "reconciler kind": "VmItem", "worker count": 1}

2022-03-11T13:20:45.727+0200    INFO    controller.vmitem       V1 reconcile    {"reconciler group": "vm.com", "reconciler kind": "VmItem", "name": "vmitem-sample-v1alpha1", "namespace": "default"}
2022-03-11T13:20:45.727+0200    INFO    controller.vmitem       v1alpha1 reconcile      {"reconciler group": "vm.com", "reconciler kind": "VmItem", "name": "vmitem-sample-v1alpha1", "namespace": "default"}
```

Thank you

**Comment by fox-md** [comment]
Did a few more tests using the latest version of kubebuilder and got the same results.
This time I created the simplest controller from scratch:
```
fox@md:~/guestbook$ ../kubebuilder_3.3.0/kubebuilder_linux_amd64 init --domain my.domain --repo my.domain/guestbook

fox@md:~/guestbook$ ../kubebuilder_3.3.0/kubebuilder_linux_amd64 create api --group webapp --version v1beta1 --kind Guestbook
Create Resource [y/n]
y
Create Controller [y/n]
y

fox@md:~/guestbook$ ../kubebuilder_3.3.0/kubebuilder_linux_amd64 create api --group webapp --version v1 --kind Guestbook
Create Resource [y/n]
y
Create Controller [y/n]
n
```
Once controller started, I loaded https://github.com/fox-md/guestbook/tree/master/config/samples manifests in k8s. Controller reacted to both resources created. I was expecting to see only `v1beta1` events.

Controller logs:
```
1.647118691713011e+09   INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
1.6471186917140574e+09  INFO    setup   starting manager
1.647118691714432e+09   INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.6471186917146528e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
1.647118691714874e+09   INFO    controller.guestbook    Starting EventSource    {"reconciler group": "webapp.my.domain", "reconciler kind": "Guestbook", "source": "kind source: *v1beta1.Guestbook"}
1.647118691715103e+09   INFO    controller.guestbook    Starting Controller     {"reconciler group": "webapp.my.domain", "reconciler kind": "Guestbook"}
1.6471186918159378e+09  INFO    controller.guestbook    Starting workers        {"reconciler group": "webapp.my.domain", "reconciler kind": "Guestbook", "worker count": 1}
1.6471187112467186e+09  INFO    controller.guestbook    Reconcile started       {"reconciler group": "webapp.my.domain", "reconciler kind": "Guestbook", "name": "guestbook-sample-v1beta1", "namespace": "default"}
1.6471187225371935e+09  INFO    controller.guestbook    Reconcile started       {"reconciler group": "webapp.my.domain", "reconciler kind": "Guestbook", "name": "guestbook-sample", "namespace": "default"}
```
Source code: https://github.com/fox-md/guestbook

@FillZpp , can you please advise, what I am missing here? As per your similar comment it seems not be the expected behavior.
> This will only watch objects with vm.com/v1alpha1 (btw, you don't have to set fields, only For(&vmv1alpha1.VmItem{})), no v2alpha1 object will be handled.

Thank you

**Comment by FillZpp** [comment]
@fox-md Oh, I test it and turn out kube-apiserver has default conversion for the multiple-version CRD, even if we don't configure conversion webhook.

In your case, `v1` is the storage version in your CRD https://github.com/fox-md/guestbook/blob/master/config/crd/bases/webapp.my.domain_guestbooks.yaml#L50 .

So when you create a `v1` object, it will be stored into Etcd. When you create a `v1beta1` object, it will be converted to `v1` and then stored into Etcd. When you get/list/watch `v1`, apiserver will return `v1` objects to you. When you get/list/watch `v1beta1`, apiserver will convert all `v1` objects to `v1beta1` and then return to you.

Which also means, when you create a `v1` object named `guestbook-sample`, apiserver will store it and it can be converted to `v1beta1`. So you can't create a `v1beta1` object with the same name (the object has already existed) and the controller which watches `v1beta1` will get the object which has been converted to `v1beta1` by apiserver.

**Comment by fox-md** [comment]
Thank you for the explanation, @FillZpp .
Indeed, both objects are stored in ETCD as v1 and both are picked up by the controller. It seems the only way to "Discover ApiVersion of a resource" would be to check its managedFields.apiVersion. 

```
root@kmaster:/etc/kubernetes/pki# ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/apiserver-etcd-client.crt --key=/etc/kubernetes/pki/apiserver-etcd-client.key --endpoints=https://127.0.0.1:2379 get --write-out=json /registry/webapp.my.domain/guestbooks/default/guestbook-sample | jq .kvs[0].value | sed 's/"//g' | base64 -d | jq .
{
  "apiVersion": "webapp.my.domain/v1",
  "kind": "Guestbook",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"webapp.my.domain/v1\",\"kind\":\"Guestbook\",\"metadata\":{\"annotations\":{},\"name\":\"guestbook-sample\",\"namespace\":\"default\"},\"spec\":{\"bar\":\"foo\",\"foo\":\"bar\"}}\n"
    },
    "creationTimestamp": "2022-03-14T12:00:24Z",
    "generation": 1,
    "managedFields": [
      {
        "apiVersion": "webapp.my.domain/v1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:kubectl.kubernetes.io/last-applied-configuration": {}
            }
          },
          "f:spec": {
            ".": {},
            "f:bar": {},
            "f:foo": {}
          }
        },
        "manager": "kubectl-client-side-apply",
        "operation": "Update",
        "time": "2022-03-14T12:00:24Z"
      }
    ],
    "name": "guestbook-sample",
    "namespace": "default",
    "uid": "46534b01-fee5-4c07-8ff3-320bd6a8be2e"
  },
  "spec": {
    "bar": "foo",
    "foo": "bar"
  }
}
```

```
root@kmaster:/etc/kubernetes/pki# ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/apiserver-etcd-client.crt --key=/etc/kubernetes/pki/apiserver-etcd-client.key --endpoints=https://127.0.0.1:2379 get --write-out=json /registry/webapp.my.domain/guestbooks/default/guestbook-sample-v1beta1 | jq .kvs[0].value | sed 's/"//g' | base64 -d | jq .
{
  "apiVersion": "webapp.my.domain/v1",
  "kind": "Guestbook",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"webapp.my.domain/v1beta1\",\"kind\":\"Guestbook\",\"metadata\":{\"annotations\":{},\"name\":\"guestbook-sample-v1beta1\",\"namespace\":\"default\"},\"spec\":{\"foo\":\"bar\"}}\n"
    },
    "creationTimestamp": "2022-03-14T12:00:20Z",
    "generation": 1,
    "managedFields": [
      {
        "apiVersion": "webapp.my.domain/v1beta1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:annotations": {
              ".": {},
              "f:kubectl.kubernetes.io/last-applied-configuration": {}
            }
          },
          "f:spec": {
            ".": {},
            "f:foo": {}
          }
        },
        "manager": "kubectl-client-side-apply",
        "operation": "Update",
        "time": "2022-03-14T12:00:20Z"
      }
    ],
    "name": "guestbook-sample-v1beta1",
    "namespace": "default",
    "uid": "0c1ac79c-88e8-4405-8917-f081e9b7db10"
  },
  "spec": {
    "foo": "bar"
  }
}
```

Thanks a lot @FillZpp for your help.
