### ISSUE TITLE
Controller get wrong namespace name for multipe operators instances in different namespaces

### ISSUE THREAD

**Issue by simha5009** [kubernetes-sigs/controller-runtime#1839]
We developed a k8s Operator, after we deploy the first Operator in the first namespace, it works well. Then I deploy the 2nd Operator in the second namespace, I saw the second controller get the request that's namespace still is the first name, but the expected namespace should be second.

Please see the following code, when we play with the second operator in the second namespace, the request's namespace still is the first namespace.

```
func (r *AnexampleReconciler) Reconcile(request ctrl.Request) (ctrl.Result, error) {

    log := r.Log.WithValues("Anexample", request.NamespacedName)

    instance := &v1alpha1.Anexample{}
    err := r.Get(context.TODO(), request.NamespacedName, instance)
    if err != nil {
        if errors.IsNotFound(err) {
            log.Info("Anexample resource not found. Ignoring since object must be deleted.")
            return reconcile.Result{}, nil
        }

        log.Error(err, "Failed to get Anexample.")
        return reconcile.Result{}, err
    }
```

The issue is about getting the wrong namespace. Might be a bug in controller-runtime.

request.NamespacedName from controller-runtime is returning the wrong namespace.

How do we fix this?

Ref: https://stackoverflow.com/questions/64653465/controller-get-wrong-namespace-name-for-multipe-operators-instances-in-different/71514738#71514738

**Comment by FillZpp** [comment]
@simha5009 The objects listwatched by operator have no relationship with the namespace where operator is deployed, which means even if your operator is deployed in namespace A, it will still watches all objects of the specific GVK all over the cluster.

If you expect an operator deployed in namespace A will only watches objects in namespace A, you have to set the `namespace` to `A` in the options of manager:

```golang
    mgr, err := ctrl.NewManager(cfg, manager.Options{
        ...
        Namespace: "A",
    })
```
