### ISSUE TITLE
DeleteAllOf requires a namespace

### ISSUE THREAD

**Issue by YairHalberstadt** [kubernetes-sigs/controller-runtime#1842]
`client.DeleteAllOf` options is simply a pair of `ListOptions` and `DeleteOptions`.

When using `client.List`, if no namespace is set in `ListOptions`, it lists across all namespaces.

When using `client.DeleteAllOf`, if no namespace is set the delete fails with the message "(NotFound): the server could not find the requested resource".

Ideally this should be fixed, but if this is not possible at the client side, I think it would be helpful to validate this case and error if no namespace is set for client.DeleteAllOf, or at the very least to update the documentation.

**Comment by imuxin** [comment]
`DeleteAllOf` will not do delete across all namespaces. That is very hidden.
