### ISSUE TITLE
Is there any way for me to get the event type in Reconcile() ?

### ISSUE THREAD

**Issue by Yl4682B4** [kubernetes-sigs/controller-runtime#1850]
Kubernetes Informer supports AddFunc/UpdateFunc/DeleteFunc for different types of events. Is there anything similar in controller-runtime?  
I use apierrs.IsNotFound() to detect a delete event now (which is actually not so rigorous), while no idea to distinguish an add event.

**Comment by coderanger** [comment]
No, by definition you aren't supposed to care because it's not an event-based API, it's a convergent API.
