### ISSUE TITLE
EnvTest - Does not Accept Some Custom Resources

### ISSUE THREAD

**Issue by DanArlowski** [kubernetes-sigs/controller-runtime#1854]
Referencing the Issue created in Operator-SDK - https://github.com/operator-framework/operator-sdk/issues/5514

Technically - When you create an envtest using ginko, and adding resources to the scheme,
It looks like cluster wide resources are not being accepted (They are added to the scheme, but the envtest API rejects their creation:
```
1.6487184909959798e+09  ERROR   controller.<name>      Reconciler error        {"reconciler group": "<group>", "reconciler kind": "<Kind>", "name": "<name>, "namespace": "", "error": "no matches for kind \"Project\" in version \"project.openshift.io/v1\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        <home>/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        <home//go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

This is the logs from the unittest custom operator creating the resource,

the exact same resource getting applied on a runtime-cluster, and not envtest.

We managed to add custom resources to the scheme, but only namespaced ones (openshift route, for instance)
But both Openshift Project, and SecurityContextConstraint (Openshift, too) were added to the scheme but rejected by the EnvTest.

Another Cause may be because these 2 object extend existing k8s functionality (namespace, securityContext), so it may be the root cause of that.

Thought I'd opened an issue here too, as it might not be completely Openshift & Operator-SDK Related and might be related to the Envtest Behaviour.

**Comment by DanArlowski** [comment]
Sorry for not being fully detailed.

I install the kind:
```go
	err = projectv1.Install(scheme.Scheme)
	Expect(err).ShouldNot(HaveOccurred())
```
In the envtest test-suite

I also install it in the operator itself main.go file:
```go
utilruntime.Must(projectv1.AddToScheme(scheme))
```

So that is not the case.
In the issue I referenced there are a bit more logs & code - Technically - the kind is getting registered sucsessfully (other resources are getting registered & Created correctly.

**Comment by jmrodri** [comment]
This issue seems similar to an old issue: https://github.com/kubernetes-sigs/controller-runtime/issues/1191
