### ISSUE TITLE
pkg/source Kind WaitForSync panics if called before Start

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes-sigs/controller-runtime#1860]
I got a panic from https://github.com/kubernetes-sigs/controller-runtime/blob/adc9fa96250106ebf0a3c589aa64e085e90870fd/pkg/source/source.go#L177 .  There seems to be an assumption that https://github.com/kubernetes-sigs/controller-runtime/blob/adc9fa96250106ebf0a3c589aa64e085e90870fd/pkg/source/source.go#L121 runs earlier.

I did not notice documentation that Start has to complete before WaitForSync is called.  Indeed, I think there should not be such a requirement.

**Comment by FillZpp** [comment]
Please provide the panic stack and describe your usage.

**Comment by MikeSpreitzer** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13fff9c]

goroutine 266 [running]:
sigs.k8s.io/controller-runtime/pkg/source.(*Kind).WaitForSync(0xc0008eda70, {0x1aff2c0, 0xc0479f02a0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/source/source.go:177 +0xbc
sigs.k8s.io/controller-runtime/pkg/source.(*kindWithCache).WaitForSync(0x1aff2f8, {0x1aff2c0, 0xc0479f02a0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/source/source.go:86 +0x25
myrepo/controllers.(*dynamicDeviceInformer).WaitForSync(...)
        /workspace/controllers/device-materializer.go:284
```

My usage is a controller with a dynamic set of cache&informer.  They all are focused on the same type of object, but each has a distinct label selector.
