### ISSUE TITLE
How to use log in my function

### ISSUE THREAD

**Issue by acechef** [kubernetes-sigs/controller-runtime#1861]
In the official [example](https://github.com/kubernetes-sigs/controller-runtime/blob/adc9fa96250106ebf0a3c589aa64e085e90870fd/examples/crd/main.go#L46)，set a variable named `log`，and we can use log.Info() or log.Error() later.

But now I have multi function, do I have to set log := log.FromContext(ctx) at the beginning of every function if I want to use log?

Or Is there any best practice here for me to refer to？

**Comment by coderanger** [comment]
Yes, you should pass the context through as the first argument to any other functions and pull out the logger as needed.

**Comment by SpecialYang** [comment]
> Yes, you should pass the context through as the first argument to any other functions and pull out the logger as needed.

This function `log.FromContext` only works on the log defined in libaray. How the user-defined name logger also use `log.FromContext` to obtain the underlaying values?

**Comment by acechef** [comment]
> Yes, you should pass the context through as the first argument to any other functions and pull out the logger as needed.

👌🏻
