### ISSUE TITLE
Incorrect logr usage

### ISSUE THREAD

**Issue by mindprince** [kubernetes-sigs/controller-runtime#187]
https://github.com/kubernetes-sigs/controller-runtime/blob/a8ea2056444a5d74d7408e4b8798cbe63b14066b/pkg/source/source.go#L89-L90

This seems to not be using logr correctly. I got the following error when I hit this line:

{"level":"dpanic","ts":1540850293.0815783,"logger":"kubebuilder.source","caller":"zapr/zapr.go:129","msg":"odd number of arguments passed as key-value pairs for logging" ...

**Comment by interma** [comment]
Sorry for introducing it, I opened a PR to fix it.

Thanks @mindprince !
