### ISSUE TITLE
EnvTest returns objects with empty TypeMeta object

### ISSUE THREAD

**Issue by 0xDiddi** [kubernetes-sigs/controller-runtime#1870]
# Background

I have a custom resource & controller. As part of the reconciliation of this custom resource, the controller creates some child resources, namely a ConfigMap and a Deployment.

To create these resources, I use a server-side apply via `myClient.Patch(myCtx, myDeployment, client.Apply, myOpts)`.
Since I patch these objects, I also attempt to retrieve them first, and only create a new object when no existing one is found.

When setting up the resource objects, I had initially assumed that I would only need to set `TypeMeta` and `ObjectMeta` fields when first creating the object, and could subsequently assume that they were correct, since I only care about the name & namespace, and not about any annotations or labels etc.

Long story short, my code initially looked essentially like this:

```go
original := &appsv1.Deployment{}
err := myClient.Get(myCtx, types.NamespacedName{Namespace: myNamespace, Name: myName}, original)
if err != nil {
    if errors.IsNotFound(err) {
        original.TypeMeta = &metav1.TypeMeta{APIVersion: appsv1.SchemeGroupVersion.String(), Kind: "Deployment"}
        original.ObjectMeta = &metav1.ObjectMeta{
            Namespace: myNamespace,
            Name:      myName,
        }
    } else {
        return err
    }
}

original.ObjectMeta.ManagedFields = nil
original.Spec = // ... set spec to what I need

err = myClient.Patch(myCtx, original, client.Apply, myOpts)
if err != nil {
    return err
}
```

While developing, I ran my operator against a deployed cluster, specifically OpenShift `4.8.35_1552`, since for me that was faster than spinning up the test env every time I ran unit tests. When running against that cluster, the code above behaved as I would have epected, and the resources were deployed & reconciled successfully.
Once I was done, I did run my unit tests, which run against EnvTest, and I encountered a peculiar error.

# Actual Behaviour

In cases where the child resources already existed and were retrieved, the test env would return them with `original.TypeMeta.APIVersion` and `original.TypeMeta.Kind` set to empty strings (and notably not a nil TypeMeta pointer), which in turn caused the patch to complain since they of course can't be empty then.

# Expected Behaviour

I would have expected that objects returned to me from the kube client as a result of a `Get` operation must have their `TypeMeta` fields set correctly. Since I asked the client for a deployment, and I got a deployment back, I do not understand why the field that says that the object is a deployment can be empty.

# Workaround

For the time being, I now check if the fields inside `TypeMeta` are empty strings, and if so, set them to their expected values.
With my current understanding of Kube, this feels like adding a special case just to compensate for the test framework diverging from the actual system, which is a situation I don't like.

# Open Question

I remember reading about how the env test might behave slightly differently because it's just the API server and not a complete cluster. I don't recall exactly what was described there, but I do wonder if what I'm seeing here is explained by that, and thus for better or for worse "intended behaviour".

Another possible option would be that OpenShift is doing something different from Kubernetes, and I would've seen the same error if I ran against a kube cluster instead of openshift.

**Comment by alvaroaleman** [comment]
The typed decoder clears typemeta when you retrieve an object, please look in any of the various existing issues ppl created in the past for this for a more in-depth explanation: https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+typemeta+empty+is%3Aclosed+

It is also not a pointer btw, so it can not be nil.
