### ISSUE TITLE
Is it okay to put some objects in the Reconciler struct?

### ISSUE THREAD

**Issue by Yl4682B4** [kubernetes-sigs/controller-runtime#1872]
~~~
// Reconciler reconciles a object
type Reconciler struct {
	client.Client
	Scheme	*runtime.Scheme
}
~~~
Do all reconcile() share the same Reconciler object? Actually I want to put some context-related object in it.

**Comment by schrej** [comment]
While I think you can technically reconcile multiple different resource kinds with the same Reconciler, it's probably better to use separate Reoncilers per resource kind you want to reconcile.
Since it looks like you're just getting started I recommend reading the Kubebuilder book. Kubebuilder is a framework (actually just a CLI tool I think) built on top of controller-runtime that helps with generating things like controllers and custom resources. And it comes with documentation on how to implement controllers and so on.
https://book.kubebuilder.io/cronjob-tutorial/controller-implementation.html

/kind support

**Comment by Yl4682B4** [comment]
> 

Thx, looks like a good guide for me. In fact I'm using it for a single resource (pod actually). I want to add some context-related fields (like podName) into the Reconciler struct at the entrance of Reconcile(), I wonder is it safe? I'm worrying about concurrent conflict.

**Comment by schrej** [comment]
Ah, now I get your question. All reconciliations performed by one Reconciler share the same Reconciler instance. So if you add fields there, they will be shared between runs.
You can configure the parallelism of a reconciler by setting [`MaxConcurrentReconciles`](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.2/pkg/controller#Options) when you register the Reconciler with a Manager.

If you want to support parallelism you could also store your data in a map of some sorts, e.g. indexed by the UID of Pods.

Imo the best approach would be to create a new struct and pass that around during one reconciliation though. It's also most in line with the Kubernetes controller pattern, which is supposed to be idempotent. By storing information in the Reconciler its also available in subsequent runs, and that breaks with that pattern.

**Comment by Yl4682B4** [comment]
> Ah, now I get your question. All reconciliations performed by one Reconciler share the same Reconciler instance. So if you add fields there, they will be shared between runs. You can configure the parallelism of a reconciler by setting [`MaxConcurrentReconciles`](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.2/pkg/controller#Options) when you register the Reconciler with a Manager.
> 
> If you want to support parallelism you could also store your data in a map of some sorts, e.g. indexed by the UID of Pods.
> 
> Imo the best approach would be to create a new struct and pass that around during one reconciliation though. It's also most in line with the Kubernetes controller pattern, which is supposed to be idempotent. By storing information in the Reconciler its also available in subsequent runs, and that breaks with that pattern.

Thanks.
