### ISSUE TITLE
TypeMeta is not populated while getting v1beta1 CRD using APIReader

### ISSUE THREAD

**Issue by boylee1111** [kubernetes-sigs/controller-runtime#1874]
**Environments:**
* Cluster Version: 1.21
* controller-runtime version: 0.9.7

**Reproduce Steps:**
1. Use API Reader to bypass the cache.

```
	scheme   = runtime.NewScheme()
	_ = clientgoscheme.AddToScheme(scheme) // all
	_ = crdv1beta1.AddToScheme(scheme)
	_ = crdv1.AddToScheme(scheme)

	mgr, err := ctrl.NewManager(cfg, ctrl.Options{
		Scheme:             scheme,
		MetricsBindAddress: metricsAddr,
		LeaderElection:     enableLeaderElection,
		Port:               9443,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

       client := mgr.GetClient()
       apiReader := mgr.GetAPIReader()
```

2. Use default client and APIReader to query resource separately:

```
       v1beta1CRD := &apiextv1beta1.CustomResourceDefinition{}
	if err := apiReader.Get(ctx, crdNN, v1beta1CRD); err != nil {
		return err
	}
        // TypeMeta (APIVersion and Kind) of v1beta1CRD is empty

	if err := client.Get(ctx, crdNN, v1beta1CRD); err != nil {
		return err
	}
        // TypeMeta (APIVersion and Kind) of v1beta1CRD is populated correctly

```

**Additional Test:**
* Use APIReader to get v1 CRD, TypeMeta is populated correctly.

**Expect Result:**
TypeMeta of v1beta1 CRD should be populated correctly.

**Actual Result:**
TypeMeta of v1beta1 CRD is empty.

**Workaround:**
Use `unstructured` instead of typed object.

**Comment by alvaroaleman** [comment]
It is always empty when using typed objects, please look in any of the closed issues for the same question for an explanation: https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+typemeta+empty+is%3Aclosed+
