### ISSUE TITLE
[Question] Integration with tracing

### ISSUE THREAD

**Issue by STRRL** [kubernetes-sigs/controller-runtime#1876]
Hi! I found that the feature "API Server Tracing" is available as alpha since Kubernetes v1.22, and [this blog](https://kubernetes.io/blog/2021/09/03/api-server-tracing/#example-trace-create-pod-with-mutating-webhook) mentioned that a simple patch could also enable tracing on controller-runtime as well. 

I think integration with tracing would be a powerful tool to enhance the observability of controller-runtime and soo-many operators build on it. 

Is this feature on the roadmap? And I am very interested in building that.

**Comment by STRRL** [comment]
related PR: https://github.com/kubernetes-sigs/controller-runtime/pull/1211

**Comment by FillZpp** [comment]
Thanks @STRRL . I'm not sure, the patch example in the blog adds an otelhttp handler on top of the existing webhook server. Is that all we have to do?

**Comment by STRRL** [comment]
> Is that all we have to do?

No.  

IMO, including the webhook server, there are also other components that need integration with tracing, like 

- Controller and Reconciler
- Client provided by controller-runtime
- Webhook server
- Logger/Contextual Logging

The first 3 things might be resolved by otelhttp, and propagate context properly. And the 4th one might need upstream updates on logr. But we would still implement customized implementation for logr.LogSink as a preview.

**Comment by FillZpp** [comment]
I do understand tracing webhook server may help users to find out the time cost of a request to apiserver. But I don't understand what should we trace for controller or reconciler, for they all work asynchronously. Are you going to trace each object from list/watch to reconcile?

**Comment by STRRL** [comment]
For almost all the controllers/operators based on controller-runtime, the Reconciler is the most important part which contains their core business logic. I think there is no reason to ignore the tracing on them.

> But I don't understand what should we trace for controller or reconciler, for they all work asynchronously.  Are you going to trace each object from list/watch to reconcile?

I did not think about how tracing context/span propagates throw api-server and etcd, it might work or might not. And I am not sure that "trying to find out one reconciliation relates to previous reconciliation" is practical or not in theory, because the current status is the aggregation of all the previous updates, there must be overlapping for the propagation of different tracing contexts/span. I think it should be cleared when we actually design the tracing integration.

On the other side, only tracing operations inside **only one reconciliation** is also very useful:

- what kind of event trigger this reconciliation
- then, which resources are modified/created/deleted
- maybe some other kind of API invoked during the reconciliation
  - for Chaos Mesh, it would invoke chaos-daemon to inject chaos by grpc
  - for cloud provider related controllers, it would invoke cloud provider's openapi
  - etc.
- does this reconciliation "win" the optimistic lock when updating resources.

> Are you going to trace each object from list/watch to reconcile?

Based on the former topic, I want to trace all the single reconciliation, I am not sure, but prefer to yes.

**Comment by STRRL** [comment]
I was suffering with profiling the performance of the chaos mesh controller-manager recently days. It makes me concentrate much more on the tracing of Kubernetes operators.

I will start to work on this issue in the next several weeks.

**Comment by mjnovice** [comment]
Can this be re-opened ?
