### ISSUE TITLE
Update of sigs.k8s.io/controller-runtime from v0.11.2 -> v0.12.0 makes envtest fails on applying CRD configs

### ISSUE THREAD

**Issue by IoanaIvanova** [kubernetes-sigs/controller-runtime#1899]
After updating k8s operator dependency sigs.k8s.io/controller-runtime from version v0.11.2  to v0.12.0 the setup of envtest  started failing to apply CRDs which are different that the one that the k8s operator describes.

I would like to apply a different CRD (an argo workflow CRD) since the operator operates on changes of argo workflows and I would like to test this without installing a whole argo server but rather simulate changes of workflow CR. So I need to have a workflow CRD in order to have a workflow CR and I managed to do this by adding the argo CRD in a testdata dir in the operator's repo and passing this dir to the suite_test.go with the following code:
```
	testEnv := &envtest.Environment{
		CRDDirectoryPaths: []string{
			filepath.Join("..", "..", "config", "crd", "bases"),
			filepath.Join("testdata", "workflows", "definition"),
		},
		ErrorIfCRDPathMissing:    true,
		AttachControlPlaneOutput: true,
	}
```

This works pretty fine before changing sigs.k8s.io/controller-runtime to version  v0.12.0 when the envtest started to search in both described directories the name of the CRD that the k8s operator describe rather then applying the CRD which is in the describe directory.

Could you please tell me if this change is a desired one and if yes how I could change the envtest implementation in order to fulfil the need to apply CRD which is not defined in the testing operator?

**Comment by stijndehaes** [comment]
I am seeing the same issue

**Comment by haugom** [comment]
I am experiencing the same. I believe its this change that broke it:

https://github.com/kubernetes-sigs/controller-runtime/commit/668800548692d401380aed35a224380f829451a8#diff-b6b1b02e41870fbffb46bc5880965e53a92a1c6807bb3fae0e8473154fb416a4R307-R314

It seems it doesn't reset the files slice between each path it is looping over.

A workaround for me seems to be to remove the additional crd's from the environment.crd's and add them manually after testEnv.start()

```
	envtest.InstallCRDs(testEnv.Config, envtest.CRDInstallOptions{
		Paths: []string{
			filepath.Join("..", "somedir", "somepath"),
		},
	})
```

**Comment by IoanaIvanova** [comment]
Thank you @haugom the workaround which you mentioned fix the problem.
