### ISSUE TITLE
New LogConstructur causes all loggers to report the same metadata

### ISSUE THREAD

**Issue by maboehm** [kubernetes-sigs/controller-runtime#1908]
After upgrading to `v0.12.0` all our reconciler loggers have the same `controller`, `controllerGroup` and `controllerKind` set. 

I believe this is caused by https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/builder/controller.go#L312, where it should be `log := ` or maybe to avoid confusion name the variable differently. This was introduced with https://github.com/kubernetes-sigs/controller-runtime/pull/1827.
I guess it is done similarly here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L110

**Comment by maboehm** [comment]
seems like https://github.com/kubernetes-sigs/controller-runtime/pull/1907 will be fixing this

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes-sigs/controller-runtime/pull/1907, thanks for the report!
