### ISSUE TITLE
Add GetOption in client get call

### ISSUE THREAD

**Issue by l1b0k** [kubernetes-sigs/controller-runtime#1915]
Add GetOption so client can work with `metav1.GetOptions`

**Comment by FillZpp** [comment]
Discussion from slack:

> Why do you need ResourceVersion="0" for your get operation? It returns object with ANY resourceVersion according to the doc https://kubernetes.io/docs/reference/using-api/api-concepts/#semantics-for-get-and-list

> resourceVersion="0"  return a cached result , optimize performance at large scale. resourceVersion=""  always get latest result.

> That would be a difference. But mostly we use resourceVersion="0" for list to avoid reading too many objects from etcd. Do you have a large number of get operation that is really necessary to set the flag?

> Sure, i have opened an issue https://github.com/kubernetes-sigs/controller-runtime/issues/1915 to discuss this.
> In short , i have daemonSet agent and controller  ,   prefer to use single kubernetes client  to simplify the code ,also performance is our concern.
