### ISSUE TITLE
How to support AddIndexerIfNotPresent?

### ISSUE THREAD

**Issue by DDKK64** [kubernetes-sigs/controller-runtime#1916]
In threadSafeStore, adding an index with exsiting name throws an error. In the upper level, we cannot IndexField a field twice, even if they are the same index. 
If we want controllers to register required indexers respectively in a loosely coupled way, a solution will be a function like AddIndexerIfNotPresent.

e.g.

```golang
func NewController1(indexer cache.FieldIndexer) {
        // ....
        AddIndexerIfNotPresent(indexer, name, indexFunc)
}

func NewController2(indexer cache.FieldIndexer) {
        // ....
        AddIndexerIfNotPresent(indexer, name, indexFunc)
}
```

**Comment by alvaroaleman** [comment]
AddIndexerIfNotPresent is not posible, because we can not compare functions so we can not check if the indexFunc is the same. If you know for sure that only a specific function will be registered for a given name you can simply tolerate the error. If not, you are out of luck.
