### ISSUE TITLE
NewItemFastSlowRateLimiter ratelimter doesnt seem to implement delay.

### ISSUE THREAD

**Issue by abhilashshetty04** [kubernetes-sigs/controller-runtime#1921]
I work for Openebs/Mayadata. We have a lvm based storage project which has sanpshot create logic(by using controller) which would 
internally use dm-snapshot module to create lvm snaps. If kernel module is not installed on node then node plugin would busyloop.
object will be requeued after 5ms delay on workqueue if using DefaultControllerRateLimiter(). Which doesnt make sense for our usecase.

To fix that i tried to use workqueue.NewItemFastSlowRateLimiter with following args . Please refer screenshot. Requeuing logic
upon failure is also shared in the second screenshot.

<img width="1440" alt="Screenshot 2022-05-31 at 6 23 08 PM" src="https://user-images.githubusercontent.com/95069770/171446141-2624d6d8-c31d-43be-b044-e51b1c074439.png">
<img width="1440" alt="Screenshot 2022-05-31 at 6 27 32 PM" src="https://user-images.githubusercontent.com/95069770/171446194-fc1739a4-acde-413f-81e8-1ce6cfae2800.png">

Upon using this ratelimiter as well. I see no difference in retry intervals. Attaching initial retries which starts at 5ms.
I want retries to be enqueued after 5 secs delays for 12 retries. Then have delay of 30 secs to add item to wq.

This is the logs for retry. It is ~5ms apart.

[retrylogs.txt](https://github.com/kubernetes-sigs/controller-runtime/files/8815753/retrylogs.txt)

**Comment by FillZpp** [comment]
Hi @abhilashshetty04 , first this should be an issue for [kubernetes/client-go](https://github.com/kubernetes/client-go) instead of controller-runtime.

But as I see from your `retrylog.txt`, seems it has retried in 5s interval for the fisrst 12 retries and then 30s.

```
E0531 06:19:48.466281       1 snapshot.go:272] error syncing 'openebs/snapshot-0d03c435-2444-4026-8859-e15dcaffe0aa': exit status 3, requeuing
E0531 06:19:53.476253       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/0d03c435-2444-4026-8859-e15dcaffe0aa cmd [--snapshot --name 0d03c435-2444-4026-8859-e15dcaffe0aa --permission r /dev/lvmvg/pvc-c2411370-58af-4b8d-8937-7c2f491460dd --size 5368709120b] error: modprobe: can't change directory to '/lib/modules': No such file or directory

...

E0531 06:20:48.579160       1 snapshot.go:272] error syncing 'openebs/snapshot-0d03c435-2444-4026-8859-e15dcaffe0aa': exit status 3, requeuing
E0531 06:21:18.588204       1 lvm_util.go:501] lvm: could not create snapshot lvmvg/0d03c435-2444-4026-8859-e15dcaffe0aa cmd [--snapshot --name 0d03c435-2444-4026-8859-e15dcaffe0aa --permission r /dev/lvmvg/pvc-c2411370-58af-4b8d-8937-7c2f491460dd --size 5368709120b] error: modprobe: can't change directory to '/lib/modules': No such file or directory
```

**Comment by abhilashshetty04** [comment]
Apologies, Misinterpreted time. Will close it.
