### ISSUE TITLE
can not watch any resoures

### ISSUE THREAD

**Issue by ycyxuehan** [kubernetes-sigs/controller-runtime#1934]
kubernetes version: 1.23.8
contronner-runtime: 0.12.1

can not watch any resoures, log like this:

`
1.6555559568627317e+09  ERROR   Queue item was not a Request    {"controller": "core", "controllerGroup": "slm.abc.cn", "controllerKind": "Core", "type": "*reconcile.Request", "value": "slm/aaa"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234
`

my code :
```go
type CoreWatcher struct {
	Client client.Client
}

func (c *CoreWatcher) Create(e event.CreateEvent, limitingInterface workqueue.RateLimitingInterface) {
	labels := e.Object.GetLabels()

	if core, ok := labels["abc.cn/core"]; ok {
		limitingInterface.Add(&reconcile.Request{
			NamespacedName: types.NamespacedName{Namespace: e.Object.GetNamespace(), Name: core},
		})
	}
}

func (c *CoreWatcher) Update(e event.UpdateEvent, limitingInterface workqueue.RateLimitingInterface) {
	labels := e.ObjectNew.GetLabels()
	log.Log.Info("update object watched", "object", e.ObjectNew.GetName())
	if core, ok := labels["abc.cn/core"]; ok {
		limitingInterface.Add(&reconcile.Request{
			NamespacedName: types.NamespacedName{Namespace: e.ObjectNew.GetNamespace(), Name: core},
		}) 
	}
}

func (c *CoreWatcher) Delete(e event.DeleteEvent, limitingInterface workqueue.RateLimitingInterface) {
	labels := e.Object.GetLabels()
	if core, ok := labels["abc.cn/core"]; ok {
		limitingInterface.Add(&reconcile.Request{
			NamespacedName: types.NamespacedName{Namespace: e.Object.GetNamespace(), Name: core},
		})
	}
}

func (c *CoreWatcher) Generic(e event.GenericEvent, limitingInterface workqueue.RateLimitingInterface) {

}
```

**Comment by FillZpp** [comment]
@ycyxuehan  You should add objects of `reconcile.Request` type into workqueue, not `*reconcile.Request`.

**Comment by ycyxuehan** [comment]
> @ycyxuehan You should add objects of `reconcile.Request` type into workqueue, not `*reconcile.Request`.

thanks, it works.
