### ISSUE TITLE
redundant manager.Options fields

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/controller-runtime#1936]
The topic was originally raised in https://github.com/kubernetes-sigs/controller-runtime/pull/1897#issuecomment-1151005799

With more functionality being added to `webhook.Server`, I think users should move to use that and also pay attention to things like TLS settings. With that, these `manager.Options` seem redundant:

```
        // Port is the port that the webhook server serves at.
	// It is used to set webhook.Server.Port if WebhookServer is not set.
	Port [int](https://pkg.go.dev/builtin#int)
	// Host is the hostname that the webhook server binds to.
	// It is used to set webhook.Server.Host if WebhookServer is not set.
	Host [string](https://pkg.go.dev/builtin#string)

	// CertDir is the directory that contains the server key and certificate.
	// If not set, webhook server would look up the server key and certificate in
	// {TempDir}/k8s-webhook-server/serving-certs. The server key and certificate
	// must be named tls.key and tls.crt, respectively.
	// It is used to set webhook.Server.CertDir if WebhookServer is not set.
	CertDir [string](https://pkg.go.dev/builtin#string)
```

**Comment by mythi** [comment]
/remove-lifecycle rotten

This is question is still valid. Related changes have been made in this area which makes it even more confusing: #2028, #2041

**Comment by vincepri** [comment]
These have been deprecated on main, does that address the issue?

**Comment by mythi** [comment]
@vincepri yes, this was exactly what I had in mind too. thanks

/close
