### ISSUE TITLE
Does the caching client work when list and watch are not allowed?

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#194]
From https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources:

> Notably, if resourceNames are set, then the verb must not be list, watch, create, or deletecollection. Because resource names are not present in the URL for create, list, watch, and deletecollection API requests, those verbs would not be allowed by a rule with resourceNames set, since the resourceNames portion of the rule would not match the request.

Can the controller-runtime client handle an RBAC rule that restricts by `resourceName`? Seems like this would require a cache bypass.

**Comment by shawn-hurley** [comment]
This feels like a use case that #244 should also complete. I wonder if we should close in favor? /cc @DirectXMan12

**Comment by DirectXMan12** [comment]
yeah, probably.  Closing in favor of #244

**Comment by gdsoumya** [comment]
@DirectXMan12 @shawn-hurley I have a similar requirement and it seems #244 has been solved but I couldn't find a way to watch for specific resourcenames using informer. Is there an example of how this can be achieved for a set of specific resourcenames?
