### ISSUE TITLE
ToRequestsFunc function has been removed from the package handler

### ISSUE THREAD

**Issue by abdennour** [kubernetes-sigs/controller-runtime#1942]
Hello, I had code based on [v0.4.0](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.4.0/pkg/handler) of the handler package

After an upgrade to [v0.11.2](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.2/pkg/handler), I got this error in my vscode:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/1788384/175524915-39c6b982-cff4-46e1-8608-bff47fb4248e.png">

Please support how to migrate/refactor the code after upgrade

**Comment by alvaroaleman** [comment]
Please use https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.2/pkg/handler#EnqueueRequestsFromMapFunc instead

**Comment by abdennour** [comment]
Thank you @alvaroaleman . But I was confused , because this is my current code:

```go
			&handler.EnqueueRequestsFromMapFunc{
				ToRequests: handler.ToRequestsFunc(r.booksUsingRedis),
			}).
```

As per your comment, should i use `EnqueueRequestsFromMapFunc` twice ? like this ?

```go
			&handler.EnqueueRequestsFromMapFunc{
				ToRequests: handler.EnqueueRequestsFromMapFunc(r.booksUsingRedis),
			}).
```
