### ISSUE TITLE
Allow swapping out WorkQueue

### ISSUE THREAD

**Issue by EngHabu** [kubernetes-sigs/controller-runtime#195]
Workquque is built here https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L87 but allows no configuration to the queue (from simple rate limiter options to flat out replacing it with a different queue implementation...
And the built Controller struct is in an internal package to prevent messing with it I guess...

I think we should make it one of the options with the default behavior being to create Ratelimiting queue as is...

**Comment by DirectXMan12** [comment]
Do you have a specific use case in mind that isn't satisfied by the default implementation?  We like to gather concrete use cases for stuff like this (I'd like to avoid adding too many options, since it gets complicated real quick).

**Comment by DirectXMan12** [comment]
Ah, that's an interesting use case.  We have to be careful about how much of the underlying Kubernetes types we expose -- that makes it *really* hard to do API guarantees.

**Comment by DirectXMan12** [comment]
But I can definitely see where you're coming from

**Comment by EngHabu** [comment]
I agree about the general direction of starting with the minimum set of required APIs and only add when there is a justification... this is a dealbreaker for me though.. if you don't think this fits in the model controller-runtime is going with (maybe simple-straightforward usecases?), I'm going to have to stick with raw k8s types...

**Comment by DirectXMan12** [comment]
Well, we never want that to be the case either -- controller-runtime should be sufficiently flexible for what people want to do...

You could potentially use a channel source to implement this behavior, and it probably wouldn't be too complicated.  It'd be similar to what you have now -- push updated into a dedup queue, and then pop and send on the channel.

**Comment by DirectXMan12** [comment]
but it boils down to: if it's not at all possible to use CR for this use case, we have a problem.

**Comment by DirectXMan12** [comment]
closing since we've been waiting on more info for a while now
