### ISSUE TITLE
difference between api reader and delegating client reader (with cache disabled)

### ISSUE THREAD

**Issue by sheelshah9** [kubernetes-sigs/controller-runtime#1959]
Hi,

I have ran into similar issues as #245 wherein I try to patch an object status and fetch it immediately in the next reconcile request. I tried using api reader (https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cluster/cluster.go#L172) and delegating client reader (with ClientDisableCacheFor my object, https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/split.go#L128) and found that api reader only fails to fetch the updated object 5% of times (out of 100) while the delegating client reader never fails. From the implementation of both the functions I can see that api reader uses the same logic as delegating client reader (with cache disabled) wherein both of them try to hit the API server. Any idea why I see this discrepancy?

Thanks

**Comment by FillZpp** [comment]
No, I think they have no difference if you has disabled cache for the object.

> found that api reader only fails to fetch the updated object 5% of times (out of 100)

What do you mean "failed to fetch"? Did it get error from APIServer, or you get an outdated object that is before your patching?

**Comment by sheelshah9** [comment]
I got an outdated object. Would it be helpful to add a flag to the update/patch command that is basically a blocking call to make sure that the object was actually patched in the API server before returning?
