### ISSUE TITLE
`kubebuilder-tools` version `1.21.2-darwin-arm64` not found.

### ISSUE THREAD

**Issue by jayesh-srivastava** [kubernetes-sigs/controller-runtime#1978]
kubebuilder-tools version 1.21.2 is not available for apple silicon machines. Only exists for darwin-amd64 (intel machines)
Also, the only versions available for darwin-arm64 architecture is 1.24.1 and 1.24.2. 

Running `./bin/setup-envtest use --bin-dir ./bin 1.21.2 -v debug` gave this output:
```
2022-08-12T15:19:28.824+0530   DEBUG  setup  setup-envtest@v0.0.0-20220811210453-f27ed4a1ecb1/main.go:82    using binaries directory       {"dir": "./bin"}
2022-08-12T15:19:28.824+0530   DEBUG  use    store/store.go:76      ensuring base binaries dir exists
unable to fetch checksum for requested version: unable fetch metadata for kubebuilder-tools-1.21.2-darwin-arm64.tar.gz -- got status "404 Not Found" from GCS
```

**Comment by camilamacedo86** [comment]
Hi @jayesh-srivastava,

The support for darwin/arm64 was introduced from the build done with k8s 1.24. You can look on all binaries provided here: https://storage.googleapis.com/kubebuilder-tools

I am closing this one as sorted out. feel free to re-open if you.
