### ISSUE TITLE
Add controller to the manager dynamically at runtime

### ISSUE THREAD

**Issue by clyang82** [kubernetes-sigs/controller-runtime#1994]
I have a use case is: 
1. the CRD does not exist in the runtime environment at the beginning.
2. if the users create this CRD and CR, I want to start a controller to watch the CR for reconciling.

for this case, I cannot add this controller to the manager before the manager starts, because the CRD does not exist. so I want to watch the `CustomResourceDefinitions` to see if my desired CRD is created and the CR is also created,  then I want to dynamically start a controller to watch this CR. Is it possible to add a controller to the manager when the manager is running? or How can I start the controller manually? I saw the controller is not exposed - https://github.com/kubernetes-sigs/controller-runtime/blob/15b6689c55745514d6bade4c55efb3333c0da4d9/pkg/builder/controller.go#L331

Thanks.

**Comment by FillZpp** [comment]
> Is it possible to add a controller to the manager when the manager is running?

Yes.

> How can I start the controller manually?

Same as the normal ones:

```golang
func (r *YourDynamicController) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&groupversion.Foo{}).
		Complete(r)
}
```

**Comment by clyang82** [comment]
Yes. It works. Thanks @FillZpp
