### ISSUE TITLE
Logging the reason for a reconcile

### ISSUE THREAD

**Issue by austince** [kubernetes-sigs/controller-runtime#1997]
Hey there, is there any mechanism to log which event caused a reconcile request, or generally some other tooling to figure this out?

We have a controller that owns some resources directly, references others it does not own, and has a custom source for external triggers. All these different sources make it difficult to understand why a given reconcile request was triggered, especially in cases when trying to debug over-active reconcilers.

**Comment by alvaroaleman** [comment]
Not really, the problem is that the reconcile.Request get put into a workqueue that does de-duplication, so custom information like that can not be preserved (or at least not with the current workqueue implementation).

The best you can do is add logging to your eventsources and/or handlers.

**Comment by austince** [comment]
That makes sense, thanks for the reply. I think adding logging to the handlers seems like a good approach.

One complication I could see is that the builder doesn't expose ways to construct the handlers unless you use the lower-level `Watches(..)` method (i.e., not `Owns(..)` or `For(..)`).   

For
https://github.com/kubernetes-sigs/controller-runtime/blob/b93b5f92794b9383427995678d22ddac396dba13/pkg/builder/controller.go#L240-L243

Owns
https://github.com/kubernetes-sigs/controller-runtime/blob/b93b5f92794b9383427995678d22ddac396dba13/pkg/builder/controller.go#L240-L243

What do you think about adding an option to modify the handler that is used? 

I could see something like:

```go
func WithHandlerWrapper(func(handler.EventHandler) handler.EventHandler) HandlerWrapper { 
// ...
}

var _ ForOption = &HandlerWrapper{}
var _ OwnsOption = &HandlerWrapper{}
var _ WatchesOption = &HandlerWrapper{}
```
Then we could wrap the handler with a handler that just logs and delegates.

What do you think?

**Comment by austince** [comment]
Hey @alvaroaleman , hope you don't mind the ping. Just wondering if you have thoughts on this proposal / would be able to review a PR in that direction.

**Comment by alvaroaleman** [comment]
Just use watches and wrap the handler there, no reason to change the builder

**Comment by austince** [comment]
I think that's a decent workaround but forces us to reimplement the special setup for Owns and For. Do you have more concerns other than it's more to maintain?

**Comment by anderssonw** [comment]
Hey @austince, have you gotten a chance to look more into this? We are currently in the same boat and want to see *why* some of our reconciliation loops start in the first place, due to some odd inconsistencies.

If you have any insight I would be glad to take it :)

**Comment by anderssonw** [comment]
Bump @austince :)

**Comment by austince** [comment]
This is the recommended approach: https://github.com/kubernetes-sigs/controller-runtime/issues/1997#issuecomment-1277540770

**Comment by anderssonw** [comment]
Hmm, I'll peep once i get time to prioritise it :)
