### ISSUE TITLE
How to log at debug level ?

### ISSUE THREAD

**Issue by paullaffitte** [kubernetes-sigs/controller-runtime#2002]
I would like to log at debug and warning levels, but the logger implementation that wrap zap doesn't seems to include all features from zap. For exemple, with zap you can log like this :

```golang
package main
import (
  "log"
  "os"
  "go.uber.org/zap"
)
func main() {
  logger, _ := zap.NewDevelopment()
  defer logger.Sync()
  logger.Info("Hello Zap!")
  logger.Warn("Beware of getting Zapped! (Pun)")
  logger.Error("I'm out of Zap joke!")
}
```

**Comment by zqzten** [comment]
There's no warning level in logr, see the warning part of [this blog](https://dave.cheney.net/2015/11/05/lets-talk-about-logging).

For debug level, use `V(1)`.
