### ISSUE TITLE
Events for Owned objects will bypass predicates for the controlled type

### ISSUE THREAD

**Issue by david-a-morgan** [kubernetes-sigs/controller-runtime#2007]
I've detailed the issue and provided a minimal reproduction here: https://github.com/david-a-morgan/cars-example

## The issue

Given a simple predicate:

```
prd, _ := predicate.LabelSelectorPredicate(metav1.LabelSelector{
    MatchLabels: map[string]string{"color": "red"},
})
```

We now associate that predicate to our _For_ type, which has one _Owned_ type:

```
ctrl.NewControllerManagedBy(mgr).
    For(&api.Car{}, builder.WithPredicates(prd)).
    Owns(&corev1.ConfigMap{}).
    Complete(r)
```

So with the above we have a controller that will manage `Car` objects that have the label `color` equal to `red`. If a user creates a `Car` object with the label `color` set to `blue` this controller won't receive any reconcile events for that new, blue `Car` object.

The unexpected occurs when the owned `ConfigMap` receives a create/update/delete event:

Let's assume we have two `Car` controllers; one for `Car` objects labeled `red` and one for `Car` objects labeled `blue`. A user creates a `Car` labeled `blue`. The red controller gets no reconcile request for the new, blue `Car` while the blue controller does receive a reconcile request. The blue controller then creates the owned `ConfigMap` (the blue `ConfigMap`) for the blue `Car`.

Now a new create event is published for the blue `ConfigMap`. As expected the blue controller translates that blue `ConfigMap` create event into a reconcile request for the blue `Car`. Unexpectedly, however, the red controller also translates that create event into a reconcile request, also for the blue `Car`. Where things blow up is that red controller generated reconcile request for a blue `Car` is handled by the red controller! Our red controller, which should handle **only** red `Car` objects is trying to handle a blue `Car`.

In this scenario the create/update/delete event for the blue `ConfigMap` ignores any predicates we have set for our _For_ type. At first blush this seems correct; we haven't specified any predicates for the _Owned_ type. However, because the event on the _Owned_ type gets translated to a reconcile request for the _For_ type this appears to be a way to bypass any filtering a controller expects for its _For_ type. It is unintutive that an event on an _Owned_ object can cause a controller that should **not** handle some _For_ objects to try to reconcile them.

## Why are we running two controllers for one type?

We're in the process of updating our operator from handling custom resources in the same namespace (i.e. a one-to-one relationship of operator to custom resource) to a single controller that handles custom resources cluster-wide. We still need to support older deployments in some cases meaning our cluster-wide controller must ignore particular custom resources (which will still be managed by their namespaced controller).

We're also looking at segmenting our deployments in our larger clusters, i.e. having multiple controllers each managing a subset of custom resources.

**Comment by joelanford** [comment]
The thread here covers how this works: https://kubernetes.slack.com/archives/CAR30FCJZ/p1664212362356139

The informers that make up the watches for a controller are all independently feeding `reconcile.Request` objects into a shared queue. There's no built-in coordination of these predicate -> handler -> queue pipelines. The informers don't coordinate or feed events/requests between each other.
