### ISSUE TITLE
client in validating webhook not works well

### ISSUE THREAD

**Issue by yangxggo** [kubernetes-sigs/controller-runtime#2010]
I create a CRD( name XYZ for example ) and add a validating webhook for it.
I need to use kubernetes native client to get/list some resources in etcd, and then confirm approve it or not .
When I apply the CR one by one, it works well.
BUT, when I define multiple XYZ resource in one yaml file and apply it, the validating will not work well.

**Comment by yangxggo** [comment]
I think that multiple resources applied in one time, the client in webhook will get/list the same resources in etcd.
Is there any way to limit the same resource submit one by one ?

**Comment by zbindenren** [comment]
Yes there is:


You can create a struct that contains your needed clients. The struct must implement the following interface:


```go
type webhook interface {
    Handle(ctx context.Context, req admission.Request) admission.Response
    InjectDecoder(d *admission.Decoder) error 
}
```


And then you can register your struct like:

```go
hookServer := mgr.GetWebhookServer()                                                                                                                                                                                                                   
hookServer.Register("/validate-your-crd", &webhook.Admission{Handler: &yourHandlerStruct) 
```

**Comment by sbueringer** [comment]
Nowadays you can also implement a CustomValidator.

I think we can close this issue

**Comment by sbueringer** [comment]
/close
given comment above
