### ISSUE TITLE
Objects passed to event filter have empty TypeMeta

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/controller-runtime#2016]
Objects in the event object passed to filters like `Create(e event.CreateEvent) bool` have empty `TypeMeta`.

The `TypeMeta` is properly populated when getting objects from the client.

**Comment by alvaroaleman** [comment]
> The TypeMeta is properly populated when getting objects from the client.

It is? I thought that is only the case for metav1.PartialObject where we have a wrapper that re-adds it but not otherwise due to https://github.com/kubernetes/kubernetes/issues/80609

**Comment by alculquicondor** [comment]
No idea what populates it, but yes: I observe the populated TypeMeta in objects I get from the controller-runtime client.

**Comment by vincepri** [comment]
In the client we actively preserve the GVKs, we could potentially do the same in the event filter, I guess?
