### ISSUE TITLE
Allow to pass a custom resourcelock.Interface for leader election

### ISSUE THREAD

**Issue by johscheuer** [kubernetes-sigs/controller-runtime#2026]
The current controller-runtime supports some customisation for the leader election by providing/setting the according `LeaderElection..` options. It would be nice if a user could provide their own `resourcelock.Interface` to be more flexible and allow the user to create different customisations of `resourcelock.Interface` that are currently not supported.

**Comment by alvaroaleman** [comment]
Could you expand on what your use case is/What you want to to configure that you can't and why?

**Comment by johscheuer** [comment]
Sure the https://pkg.go.dev/k8s.io/client-go/tools/leaderelection/resourcelock#MultiLock supports to provide two Interfaces and it's mostly used for a transition path e.g. when using configmaps and leases at the same time but you can also use that mechanism to get a lease in two different Kubernetes clusters e.g. if you run an operator across multiple Kubernetes clusters. Another benefit would be that this change allows to implement a custom Interface that e.g. uses something else than Kubernetes as a lease mechanism.
