### ISSUE TITLE
Multiline String Issues when Creating Objects with Client

### ISSUE THREAD

**Issue by blakeromano** [kubernetes-sigs/controller-runtime#2038]
The developer experience with dealing with multiline strings with controller runtime client has been really painful and I may be using the controller runtime improperly I can give a few examples.

When I try to create a v1 service with the following annotation 
```go
                                 fmt.Sprintf(`>-
				access_logs.s3.enabled=true,
				access_logs.s3.bucket=%v,
				access_logs.s3.prefix=nlb-logs/istio-ingressgateway-%v,
				deletion_protection.enabled=true,
				load_balancing.cross_zone.enabled=true`, "foo", "bar"),
```
It ends up turning out like 
```yaml
service.beta.kubernetes.io/aws-load-balancer-attributes: ">-\n\t\t\t\taccess_logs.s3.enabled=true,\n\t\t\t\taccess_logs.s3.bucket=foo,\n\t\t\t\taccess_logs.s3.prefix=nlb-logs/istio-ingressgateway-bar,\n\t\t\t\tdeletion_protection.enabled=true,\n\t\t\t\tload_balancing.cross_zone.enabled=true
```
With a secret class provider I had to have the following string 
```go
"objects": fmt.Sprintf("- objectName: /ns/%v/PostgresServiceUserSecret\n  objectType: secretsmanager\n  jmesPath:\n    - path: host\n      objectAlias: POSTGRES_HOST\n    - path: username\n      objectAlias: POSTGRES_USERNAME\n    - path: password\n      objectAlias: POSTGRES_PASSWORD", "foo"),
```
For it to properly generate, I had to use spaces, not tabs, couldn't use back ticks.

I could continue with several issues I have had trying to create new objects with multiline string attributes that have been very finicky and honestly super painful.

All of these objects are getting created or patched via this method
```go
if err := r.Client.Create(ctx, obj); err != nil {
	r.Log.Error(err, fmt.Sprintf("Error Occured with Creating %v", resourceConfig.ResourceName))
	return err
}
```
or 
```go
if err := r.Client.Patch(ctx, obj, client.MergeFrom(resource)); err != nil {
        r.Log.Error(err, fmt.Sprintf("Error Occured with Updating %v", resourceConfig.ResourceName))
        return err
}
```
This is all with the `"sigs.k8s.io/controller-runtime/pkg/client"` package using the `client.Client`

Version: `sigs.k8s.io/controller-runtime v0.13.0`

**Comment by alvaroaleman** [comment]
@blakeromano you are confusing a couple of things here:
* The `>-` is yaml and tells a yaml parser how to parse. In the context of a string literal that you don't parse but serialize, it is just a litereal `>-` that does nothing
* The tabs are part of the string literal you are constructing in your yaml
* The tabs cause the yaml serializer to escape everything

If you define your multiline string literal without leading tabs like this it will work perfectly fine:
```
	st := fmt.Sprintf(`foo
access_logs.s3.enabled=true,
access_logs.s3.bucket=%v,
access_logs.s3.prefix=nlb-logs/istio-ingressgateway-%v,
deletion_protection.enabled=true,
load_balancing.cross_zone.enabled=true`, "foo", "bar")
```

None of this has anything to do with controller-runtime btw. I encourage you to in the future read up on how string handling in the programming and serializing language/format of your choice work before opening an issue like this.
