### ISSUE TITLE
Allow RateLimit to take err from reconcile into account when determining backoff

### ISSUE THREAD

**Issue by matthchr** [kubernetes-sigs/controller-runtime#2040]
The [controller code](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L322) treats a an `err` result from a reconcile the same as a `ctrl.Result{Requeue: true}`. Both are subject to the same backoff/rate-limit. 

There are times where it would be nice to be able to write a custom RateLimiter that was able to take the actual content of the returned error into account. Examples of where this would be useful include:
* Making HTTP requests and honoring 429 + `Retry-After`
* Different error classes desiring different `maxDelay`. For example expensive requests to an external service you might want to back off exponentially to try only once every few minutes, where less expensive in-memory checks based on client-go cache or other local state could have a much shorter `maxDelay`.

The above is all accomplishable with a layer before returning to `controller-runtime` that calculates a delay based on those factors and sets it as `ctrl.Result{RequeueAfter: ...}` - effectively bypassing at least in some cases the `RateLimitingInterface` and taking ownership of backoffs yourself. The downside of doing that is if you want say, an exponential backoff, you need to keep track of the same things that the `ItemExponentialFailureRateLimiter` is already tracking. The custom error aware exponential backoff sitting below the level controller-runtime isn't sharing state with any exponential backoff in the ratelimiter which means each of their backoffs increases independently. It also means you can't easily merge `RateLimiter`'s together with something like `workqueue.NewMaxOfRateLimiter`, as setting `RequeueAfter` bypasses the `RateLimiter` entirely.

**Comment by matthchr** [comment]
The easiest way I see to actually accomplish this would be to change the `workqueue.RateLimitingInterface`, or add a new `RateLimitingErrInterface`. This would have knock-on effects resulting in changes to `workqueue.RateLimiter` (or the creation of a `workqueue.ErrRateLimiter`). All of the existing ratelimiters could be trivially extended to support this interface by just ignoring the error and doing exactly what they already do, but it would leave custom implementations open to make use of the provided `err` if they wanted.

There may be ways to do a similar thing without modifying `client-go` by defining the `Err` interfaces in `controller-runtime` instead. None of this is very hard but it's not clear to me what the interest level of doing this is. If there's interest I'm happy to send a PR.

**Comment by alvaroaleman** [comment]
This is configurable already: https://github.com/kubernetes-sigs/controller-runtime/blob/5378660479c2f9895f5ccbd15de17cb5c26fbf8e/pkg/controller/controller.go#L48

**Comment by matthchr** [comment]
`RateLimiter` has no knowledge about the error that triggered the backoff. It doesn't differentiate between `Requeue: true` and `err`.

**Comment by alvaroaleman** [comment]
Right. You can achieve what you are describing by wrapping your reconciler with something that interprets the `error` and sets `ReqeueAfter` accordingly.

**Comment by matthchr** [comment]
Indeed, but this means reimplementing existing `RateLimiter`'s, if you for example want exponential backoff , and bypassing things like `workqueue.BucketRateLimiter` because when `Requeue` is set, any buckets or other criteria configured in the top level `RateLimiter` are bypassed (AFAIK).

Those all feel like foot-guns to me, in addition to the needing to basically reimplement what RateLimiter already has and ensure that you don't leak any errs to the upper `RateLimiter` that will then use its configured backoff, counts, etc and not your wrapper
