### ISSUE TITLE
Allow injection of a panic handler for webhooks

### ISSUE THREAD

**Issue by skyerus** [kubernetes-sigs/controller-runtime#2042]
### The problem

Currently, each webhook handler is forced to defer a call to `recover()` to handle potential panics. 

```go
func (m *PodMutator) Handle(ctx context.Context, req admission.Request) admission.Response {
	defer func() {
		if err := recover(); err != nil {
			admission.Errored(http.StatusInternalServerError, fmt.Errorf("%v", err))
		}
	}()

       ...
```

This seems unnecessarily tedious.

### Solution

Allow setting a panic handler to the webhook server to use (if defined).

e.g.

```go
func (ws *webhookServer) SetPanicHandler(f func(context.Context, admission.Request) admission.Response) {
   ws.panicHandler = f
}
```

**Comment by vincepri** [comment]
Kind of (maybe?) related to #2167, should we recover panic everywhere?

**Comment by RealHarshThakur** [comment]
Yeah, I'm thinking of RunnableFunc at this point too
