### ISSUE TITLE
Support shutdown controller to shutdown watching like SetupWithManager() to start watching.

### ISSUE THREAD

**Issue by jnan806** [kubernetes-sigs/controller-runtime#2047]
### What do you want to happen?

Now, we can setup a controller with the Manager to start watching resource, but there is no function to shutdown the controller has be setup by Manager.

If i want to shutdown the controller which has be setupped, i found there is no way.

**Comment by camilamacedo86** [comment]
I transfered this one for controller-runtime 
However, @jnan806 after you check it out if you would like to collab with a doc/guidance to the kubebuilder project with that would be amazing.

**Comment by jnan806** [comment]
> However, @jnan806 after you check it out if you would like to collab with a doc/guidance to the kubebuilder project with that would be amazing.

😂  I am in the stage of using this product, and I haven't reached the stage of modifying it.

**Comment by jnan806** [comment]
> However, @jnan806 after you check it out if you would like to collab with a doc/guidance to the kubebuilder project with that would be amazing.

😂  I am in the stage of using this product, and I haven't reached the stage of modifying it.

And i am looking for how to remove watch by `ctrl.NewControllerManagedBy(mgr).For(...).Cancel(r)` like `ctrl.NewControllerManagedBy(mgr).For(...).Complete(r)`. Does `controller-runtime` will support it ?

**Comment by jnan806** [comment]
> However, @jnan806 after you check it out if you would like to collab with a doc/guidance to the kubebuilder project with that would be amazing.

😂  I am only in the stage of using this product, and my tech has not reached the stage of contributing it.

And i am looking for how to remove watch by `ctrl.NewControllerManagedBy(mgr).For(...).Cancel(r)` like `ctrl.NewControllerManagedBy(mgr).For(...).Complete(r)`. Does `controller-runtime` will support it ?

**Comment by camilamacedo86** [comment]
Hi @jnan806,

> Does controller-runtime will support it ?
It seems not supported, but has open issue for it: https://github.com/kubernetes-sigs/controller-runtime/issues/1884

**Comment by FillZpp** [comment]
> It seems not supported but has an open issue for it: #1884

Yeah, I'm working on the issue.

**Comment by jnan806** [comment]
> Yeah, I'm working on the issue.

I'm very looking forward to it ~ 😄

**Comment by camilamacedo86** [comment]
Closing as duplicated of : https://github.com/kubernetes-sigs/controller-runtime/issues/1884
