### ISSUE TITLE
Proposal: add possibility to get reconcileID from context

### ISSUE THREAD

**Issue by zbindenren** [kubernetes-sigs/controller-runtime#2055]
Currently the context is added to the log message as follows:

```go
log := c.LogConstructor(&req)

log = log.WithValues("reconcileID", uuid.NewUUID())
ctx = logf.IntoContext(ctx, log)
```

There is no easy way to get the reconcileID.

Sometimes it would be great when you have access to the reconcile ID. For example: when communicating with third party services,  it would be nice if we could send the corresponding reconsileID  in order to add the possibility to match a  request with a specific reconcileID.

I propose to introduce method like:

```go
func ReconcileID(ctx context.Context) string {
...
}
```

to get the reconcileID from the current context. In order that this works, we had to change the above code to something like:

```go
log := c.LogConstructor(&req)

reconcileID := uuid.NewUUID()
log = log.WithValues("reconcileID", reconcileID)

reconcileIDToContext(ctx, reconcileID)

ctx = logf.IntoContext(ctx, log)
```

**Comment by alvaroaleman** [comment]
Sounds reasonable to me

**Comment by zbindenren** [comment]
Great, I will make a PR.

**Comment by grzesuav** [comment]
@zbindenren why do not use `NamespacedName` as logger values ?

**Comment by alvaroaleman** [comment]
Done in #2056

**Comment by zbindenren** [comment]
Thx
