### ISSUE TITLE
Reduce command line flag boilerplate

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#207]
We've so far been somewhat CLI-agnostic in controller runtime.  However, considering that this is a common task, we may wish to set up some optional helpers (i.e. a pattern) for per-controller flag setup.

This pattern helps make controllers more distinct, which makes it easier to refactor large controllers managers out into smaller ones, choose to run certain controllers, but not all, and can clarify controller setup.  It should be advantageous for larger controllers, but not necessarily mandatory for quickly getting up and running.

Something so that you can basically do:

```go
type ControllerOneInit struct {
    Flag1 bool `flag:"flag-one"`
    Flag2 bool `flag:"flag-two"`
}

func (c *MyController) Register(mgr manager.Manager) error {
    return builder.SimpleController().
       ...
       .WithManager(mgr).
       .Reconcile(ControllerOne{
         Option1: c.Flag1,
         Option2: fmt.Sprintf("%v", c.Flag2),
       }).Build()
}

// elsewhere
func main() {
   builder.SimpleManager().
     Controller(&ControllerOneInit{}).
     ...
     .Run(signal.SetupSignals())
}
```

Perhaps this could be simplified (avoiding the separation between raw options and controller fields) to

```go
type ControllerOne struct {
    Option1 bool `flag:"flag-one"`
    Option2 string `flag:"flag-two"`

    client.Client
}

func (c *ControllerOne) Register(mgr manager.Manager) error {
    return builder.SimpleController().
       ...
       .WithManager(mgr).
       .Reconcile(c).Build()
}

// elsewhere
func main() {
   builder.SimpleManager().
     Controller(&ControllerOne).
     ...
     .Run(signal.SetupSignals())
}
```

But the separation between raw options and controller fields may be advantageous enough to warrant the extra separation.

cc @cheftako

**Comment by DirectXMan12** [comment]
/remove-lifecycle rotten

cc @luxas re componentconfig

**Comment by DirectXMan12** [comment]
/lifecycle frozen

see also #518

**Comment by vincepri** [comment]
Closing, superseded by #518 and friends

/close
