### ISSUE TITLE
Add authorization for metrics endpoint

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#2073]
It would be great if controller-runtime would be able to authorize requests to the /metrics endpoint.

Some background information:
* Kubernetes core components protect the /metrics endpoint via authentication (user/group/SA) and authorization (via RBAC verb: `get`, nonResourceURLs: `/metrics`) ([docs](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#metrics-in-kubernetes)).
* The [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) from @brancz can provide this functionality as a sidecar. ([non-resource-url example](https://github.com/brancz/kube-rbac-proxy/tree/master/examples/non-resource-url))

It would be great to have this capability built into controller-runtime as it would make it possible to have this functionality without a dependency to an additional project and a sidecar container.

Is there interest in the controller-runtime community to support the nonResourceURL-based authorization (like core Kubernetes components)?

Notes:
* Not sure how other projects are handling this but in cluster-api we removed kube-rbac-proxy after a few lengthy disussions (I think main reason was that it's not community-owned, xref: https://github.com/kubernetes-sigs/cluster-api/pull/4640). Since then metrics are basically disabled per default in Cluster API since we also didn't want to expose them unauthorized per default for security reasons. 
* ~ related the metrics endpoint should also be served on https instead of http (with the same cert as the webhook?)
* Not sure if other endpoints should be protected as well, but /metrics would be the most important one for us.

**Comment by sbueringer** [comment]
cc @alvaroaleman @joelanford @alvaroaleman What do you think about it?

cc @fabriziopandini @killianmuldoon (given our recent discussions about metrics in Cluster API)

**Comment by sbueringer** [comment]
cc @alvaroaleman @joelanford @vincepri What do you think about it?

cc @fabriziopandini @killianmuldoon (given our recent discussions about metrics in Cluster API)

**Comment by alvaroaleman** [comment]
@sbueringer in general doing that seems ok to me but I also do not have a super precise picture of how much complexity this actually entails. From a cursory look at kube-rbac-proxy, most of the logic here can be imported from upstream?

**Comment by sbueringer** [comment]
Probably.

I'll try to get back to this as soon as I have time and implement a prototype or something so we have more data to decide this.
