### ISSUE TITLE
There comes "the object has been modified" after patch

### ISSUE THREAD

**Issue by ChenWenming1995** [kubernetes-sigs/controller-runtime#2075]
I use the patch function to devoid version check:
```
svcNow := &v1.Service{}
if err := s.Get(context.TODO(), event.NamespacedName, svcNow); err != nil {
    return err
}
updateSvc := svcNow.DeepCopy()
updateSvc.Annotations = newAnno
if err := s.Patch(context.TODO(), updateSvc, client.MergeFrom(svcNow)); err != nil {
    log.Info("Patch status to annotations failed", "patch", string(jsonStatus))
    return err
}
```
But sometimes I get the error `the object has been modified; please apply your changes to the latest version and try again` still.
Why patch return the error? I thought patch will not check the version.
How can I solve this problem?
Thanks a lot!

**Comment by ChenWenming1995** [comment]
@DirectXMan12

**Comment by ChenWenming1995** [comment]
I have get some new information!
If the object in server has been add some finalizer, or its status has been modified, could meet the error `the object has been modified; please apply your changes to the latest version and try again` when patch.

**Comment by ChenWenming1995** [comment]
Bad news :(

Status or Finalizer have been modified is not the reason why patch failed.

**Comment by Noksa** [comment]
I guess the problem is that another controllers (as example) can modify an object.
That's why you get this error. And I think it is okay. It means that to apply changes you **must** do it using the latest version of the resource.

Probably, you can write a wrapper and use it if you want to apply changes anyway.

Here is one of possible solutions.

```

const optimisticLockErrorMsg = "the object has been modified; please apply your changes to the latest version and try again"


func (u updater) CreateOrPatchAndWait(ctx context.Context, r client.Client, obj client.Object, logger logr.Logger, mutateFn controllerutil.MutateFn) (result controllerutil.OperationResult, err error) {
	return u.createOrPatchObjectAndWait(ctx, false, r, obj, logger, mutateFn)
}

func (u updater) createOrPatchObjectAndWait(ctx context.Context, isUpdate bool, r client.Client, obj client.Object, logger logr.Logger, mutateFn controllerutil.MutateFn) (result controllerutil.OperationResult, err error) {
	objName := fmt.Sprintf("%v-%v-%v", obj.GetName(), obj.GetNamespace(), obj.GetObjectKind())
	mutex.Lock()
	objectMutex := cachehelper.GetMutexFromCache(objName)
	mutex.Unlock()
	objectMutex.Lock()
	defer objectMutex.Unlock()
	attempts := 1
	totalAttempts := 5
	for attempts <= totalAttempts {
		result, err = controllerutil.CreateOrPatch(ctx, r, obj, mutateFn)
		if err != nil {
			rLogger := logger.WithName("createOrPatchAndWait")
			if strings.Contains(err.Error(), "resourceVersion should not be set on objects to be created") {
				rLogger.Info("Looks like we tried to update the object that is being deleted or has been already deleted. Skipping")
				break
			} else if strings.Contains(err.Error(), "context canceled") {
				rLogger.Info("Context canceled, exiting")
				return "context canceled", err
			} else if !strings.Contains(err.Error(), optimisticLockErrorMsg) {
				rLogger = rLogger.WithValues("Attempt", attempts, "Total Attempts", totalAttempts)
				errhelper.LogErrorAsInfo(rLogger, err, "Got an error while was creating/updating the object")
			}
			attempts++
			time.Sleep(100 * time.Millisecond)
			continue
		}
		break
	}
	return result, err
}
```

**Comment by ChenWenming1995** [comment]
@Noksa Thanks for your reply and solution!

I learn the difference of patch() and update() from [https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/](url). And replies in the similar issues suggested that use patch() to avoid version check.

I would love to know what is the root cause of this error using patch(). Because it does't match the description.

Thanks your reply again:)

**Comment by Noksa** [comment]
@ChenWenming1995 

If we look at kubernetes code, we can find that this error is returned when your resourceVersion in your manifest doesn't match existing version in a k8s cluster: https://github.com/kubernetes/apiserver/blob/0558eeb9ab12b43cae1dc48fbb729870ef601e7a/pkg/registry/generic/registry/store.go#L637

In other words, a resource can be updated **only** if you are trying to update its **latest** (current) version in the cluster.

**Comment by ChenWenming1995** [comment]
@Noksa Thanks a lot!
