### ISSUE TITLE
Error when create TokenRequest resource using client

### ISSUE THREAD

**Issue by gabriel-farache** [kubernetes-sigs/controller-runtime#2079]
When using latest commit version (`sigs.k8s.io/controller-runtime v0.13.1-0.20221129230916-d7724aa14f59`) or latest table version, when I try to create a `TokenRequest` resource, I have the following error: `no matches for kind "TokenRequest" in version "authentication.k8s.io/v1"`

I am using OpenShift 4.11.17. Here are relevant piece of code:
```
client, err := crClient.New(config, crClient.Options{Scheme: kscheme.Scheme})
...
serviceAccount := &corev1.ServiceAccount{ObjectMeta: v1.ObjectMeta{Name: serviceAccountName, Namespace: namespace}}
requestToken := &authv1.TokenRequest{
	Spec: authv1.TokenRequestSpec{
		ExpirationSeconds: &expirationSec,
	},
}

err := client.Get(cctx, crClient.ObjectKeyFromObject(serviceAccount), serviceAccount)
if err != nil {
	return nil, errors.Wrapf(err, "failed to get service account '%s' in namespace '%s'", serviceAccountName, namespace)
}

err = client.SubResource("token").Create(cctx, requestToken, requestToken)
if err != nil {
	return nil, errors.Wrapf(err, "failed to create subressource TokenRequest '%s' in namespace '%s'", serviceAccountName, namespace)
}
```
I reproduce what I saw on the tests (https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client_test.go#L755) 

With latest version, I tried to create the `TokenRequest` directly (merge `serviceAccount` and `requestToken`)

Before using the controller-runtime client, I was using `k8s.io/client-go/dynamic` and `k8s.io/client-go/kubernetes` clients and it was working fine, so I am not sure it's an issue on the cluster rather than with the library.

I am not sure where to start looking.

**Comment by alvaroaleman** [comment]
Works fine for me:
```go
$ cat main.go
package main

import (
	"context"

	authenticationv1 "k8s.io/api/authentication/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/config"
)

func main() {
	cfg, err := config.GetConfig()
	if err != nil {
		panic(err)
	}

	c, err := client.New(cfg, client.Options{})
	if err != nil {
		panic(err)
	}

	sa := &corev1.ServiceAccount{ObjectMeta: metav1.ObjectMeta{Namespace: "default", Name: "default"}}
	var token authenticationv1.TokenRequest
	if err := c.SubResource("token").Create(context.Background(), sa, &token); err != nil {
		panic(err)
	}

	println(token.Status.Token)
}
```

```shell
TOKEN="$(go run ./ 2>&1)"
$ curl -H "Authorization: Bearer $TOKEN" -k https://$APISERVER:6443/api/v1/namespaces -o /dev/null 2>&1 -v|rg 200
< HTTP/2 200

$ k version 2>&1|rg Server
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

@gabriel-farache please check if the above sample program works for you and if yes, provide a repro. I don't have access to an Openshift cluster so I can not test it against that.

**Comment by gabriel-farache** [comment]
> err = client.SubResource("token").Create(cctx, requestToken, requestToken)

Yes, it's working, I see now what I did wrong: it's the serviceAccount that should be passed as second argument; I was not doing that properly.

Sorry for the inconvenience and thank you very much for the help!
