### ISSUE TITLE
manager never sets started boolean

### ISSUE THREAD

**Issue by terinjokes** [kubernetes-sigs/controller-runtime#2083]
If the manager is started multiple times in error, subsequent calls to `Start` are supposed to return a friendly error message.

https://github.com/kubernetes-sigs/controller-runtime/blob/44c5d5029cc3c19bf6e7df3f5c5943977a39637c/pkg/manager/internal.go#L403-L408

There are also several other checks against `started`, such as preventing modifications to metrics, health checks, and readiness check endpoints while the HTTP server is doing concurrent reads.

https://github.com/kubernetes-sigs/controller-runtime/blob/44c5d5029cc3c19bf6e7df3f5c5943977a39637c/pkg/manager/internal.go#L221-L223
https://github.com/kubernetes-sigs/controller-runtime/blob/44c5d5029cc3c19bf6e7df3f5c5943977a39637c/pkg/manager/internal.go#L243-L245
https://github.com/kubernetes-sigs/controller-runtime/blob/44c5d5029cc3c19bf6e7df3f5c5943977a39637c/pkg/manager/internal.go#L260-L262

It looks like the manager's internals were refactored in 612e9b28858354c69696a91b0778f3440ce4687c, and in the process the code to set `started` was removed.

<details><summary>Example Program</summary><p>

```go
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"sigs.k8s.io/controller-runtime/pkg/client/config"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	controller := manager.RunnableFunc(func(ctx context.Context) error {
		fmt.Println("controller started")
		<-ctx.Done()
		return nil
	})

	cfg := config.GetConfigOrDie()

	m, err := manager.New(cfg, manager.Options{})
	if err != nil {
		fmt.Printf("error creating manager: %s", err)
		os.Exit(1)
	}

	if err := m.Add(controller); err != nil {
		fmt.Printf("error add controller: %s", err)
		os.Exit(1)
	}

        // mimic a user accidentally calling Start on the manager twice.
	go func() {
		err := m.Start(ctx)
		fmt.Printf("err: %s\n", err)
	}()

	go func() {
		err := m.Start(ctx)
		fmt.Printf("err: %s\n", err)
	}()

	<-ctx.Done()
	fmt.Println("Done")
}
```

</p></details>
<details><summary>Example Program Output</summary><p>

```
panic: close of closed channel

goroutine 283 [running]:
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Start.func1(0xc0007c00f0, {0x17c8990, 0xc0002ee900})
	/build/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/cache/internal/informers_map.go:163 +0x1e5
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Start(0xc0003023e0?, {0x17c8990, 0xc0002ee900})
	/build/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/cache/internal/informers_map.go:164 +0x25
created by sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Start
	/build/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/cache/internal/deleg_map.go:70 +0x195
```

</p></details>

**Comment by cuisongliu** [comment]
```
done := make(chan struct{})
	go func() {
		if mgr.GetCache().WaitForCacheSync(context.Background()) {
			done <- struct{}{}
		}
	}()
	<-done
```

add code  retry it ?

**Comment by terinjokes** [comment]
That code doesn't set the internal `started` boolean either?
