### ISSUE TITLE
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest fail

### ISSUE THREAD

**Issue by thetruechar** [kubernetes-sigs/controller-runtime#2086]
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest: module sigs.k8s.io/controller-runtime@latest found (v0.13.1), but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest

**Comment by stijndehaes** [comment]
These statements also do not work:
```bash
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.13.0
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.12.0
```

Not sure why this is happening but it is very strange that earlier versions also stop working

**Comment by ccremer** [comment]
Same issue here.
I was wondering whether this is a Go issue, so I tried using Go 1.19.3 (GitHub Actions), 1.19.0 and 1.18.0, but all failed with same error.

**Comment by joelanford** [comment]
@thetruechar, I just tried `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest`, and it looks like this issue has been resolved. Can you double check to see if this is resolved on your end, and close this issue if so?

@stijndehaes I could be wrong, but I don't think it has ever worked to install setup-envtest by using a controller-runtime tag. `sigs.k8s.io/controller-runtime/tools/setup-envtest` is in a separate go module and therefore does not pick up controller-runtime's tags. If you want to pin to a particular version of setup-envtest, you should be able to use the commit hash as the version.

For example to use the setup-envtest from 0.13.1, you could do:
```
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@44c5d5029cc3c19bf6e7df3f5c5943977a39637c
```

**Comment by thetruechar** [comment]
Yes, it's resolved.
