### ISSUE TITLE
Update to k8s 1.12

### ISSUE THREAD

**Issue by hasbro17** [kubernetes-sigs/controller-runtime#211]
k8s 1.12 has been out for some time now and 1.13 is [scheduled](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.13#kubernetes-113-release-schedule) for the start of December.

I'm taking a stab at updating the k8s deps but I wanted to check if there are any reservations on how this might affect kubebuilder or the controller-tools project e.g https://github.com/kubernetes-sigs/controller-runtime/pull/110. Or if there is an update process beyond simply updating the deps.

**Comment by DirectXMan12** [comment]
I think we're set on the versioning and branching process.  I'll be publishing a doc on how we handle conflicts shortly.  The TL;DR is that if it changes any of the objects we actually expose in the interfaces in a breaking way, it's breaking (e.g. if it changed the signature of runtime.Object).  There are relatively few cases of this, so it's likely the update will be considered non-breaking for us.

**Comment by DirectXMan12** [comment]
/kind versioning

let's see if that works

**Comment by DirectXMan12** [comment]
ah ha!  good bot :-)

**Comment by hzamani** [comment]
Any updates here?

**Comment by hasbro17** [comment]
@hzamani I gave it a shot over the weekend but I'm having some trouble with `dep` getting stuck while resolving a transitive k8s.io dependency:
```
(50)  ? revisit k8s.io/api to add 1 pkgs
(60)    ✓ include 2 more pkgs from k8s.io/api@d1dc89ebaebe945edbeff52a79f50c791a59ff87
(50)  ? attempt github.com/go-openapi/swag with 1 pkgs; 7 versions to try
(61)      try github.com/go-openapi/swag@v0.17.2
(61)  ✓ select github.com/go-openapi/swag@v0.17.2 w/1 pkgs
(51)  ? attempt k8s.io/apiserver with 19 pkgs; 173 versions to try
(62)      try k8s.io/apiserver@master
(63)  ✗   k8s.io/apiserver@master depping on k8s.io/client-go at bf181536cb4da7eeb6ed732fcf79ecf0e36efaa2 has problem subpkg(s):	k8s.io/client-go/informers/auditregistration/v1alpha1 is missing
(62)      try k8s.io/apiserver@release-1.10
(63)  ✗   k8s.io/apiserver at release-1.10 has problem subpkg(s):
(63)    	k8s.io/apiserver/pkg/util/dryrun is missing; required by k8s.io/apiextensions-apiserver@ba848ee89ca33b38df441261aaa6fc32642e5628.
(62)      try k8s.io/apiserver@release-1.11
(63)  ✗   k8s.io/apiserver at release-1.11 has problem subpkg(s):
(63)    	k8s.io/apiserver/pkg/util/dryrun is missing; required by k8s.io/apiextensions-apiserver@ba848ee89ca33b38df441261aaa6fc32642e5628.
(62)      try k8s.io/apiserver@release-1.12
``` 

Currently trying to fix that by pinning bare revisions first(even though that's not encouraged):
```
[[constraint]]
  name = "k8s.io/api"
  # version = "kubernetes-1.12.2"
  revision = "d1dc89ebaebe945edbeff52a79f50c791a59ff87"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  # version = "kubernetes-1.12.2"
  revision = "ba848ee89ca33b38df441261aaa6fc32642e5628"

[[constraint]]
  name = "k8s.io/apimachinery"
  # version = "kubernetes-1.12.2"
  revision = "f71dbbc36e126f5a371b85f6cca96bc8c57db2b6"

[[constraint]]
  name = "k8s.io/client-go"
  # version = "kubernetes-1.12.2"
  revision = "bf181536cb4da7eeb6ed732fcf79ecf0e36efaa2"
```

I'm hoping to get this in soon(in a day or two) unless someone else has better luck first.

**Comment by jimmidyson** [comment]
@hasbro17 Thank you for working on this! How's it going? Need any help?

**Comment by jimmidyson** [comment]
Submitted pr #221 to do this 🤞

**Comment by hasbro17** [comment]
@jimmidyson Sorry I was busy traveling, and was still stuck on some weird dep issue that caused it to hang when pulling the 1.12 tags.
But thanks for speeding this up with your PR 👍 which SGTM.
