### ISSUE TITLE
Question: Handling graceful shutdown without timeout

### ISSUE THREAD

**Issue by relu** [kubernetes-sigs/controller-runtime#2110]
I would like to get some clarification regarding the graceful shutdown implementation in the manager. In the [documentation](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.14.1/pkg/manager/manager.go#L293), it seems that there is support for timeout-less graceful shutdown, however, [this feature has been removed](https://github.com/kubernetes-sigs/controller-runtime/commit/612e9b28858354c69696a91b0778f3440ce4687c#diff-517abdd2f47b744e11990598de732426f33aba68600eaa9600d2ee20bc0b25dcL513-L525). It is not clear if this was removed intentionally or by mistake. If this was indeed removed intentionally then it should be removed from the documentation. Otherwise, I think it would be great if this feature could be restored as it can be helpful for situations when we want to delegate force termination to Kubernetes via `terminationGracePeriodSeconds`.

@vincepri maybe you could help clarify?

**Comment by vincepri** [comment]
The option should still be there, are you saying that the `-1` is not supported? If so, we should be able to add it back and it was an oversight at the time
