### ISSUE TITLE
How to use `fieldSelectors` for CRDs during testing

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/controller-runtime#2112]
I had a question around how to test code that is using the `controller-runtime` `DirectClient` during functional/unit testing.

The direct client is the [recommended client](https://github.com/kubernetes-sigs/kubebuilder/pull/2066) to use for functional testing; however, the direct client doesn't support arbitrary field selectors for CRDs, since it doesn't use a client-side cache for READs.

As a result, if we use the direct client in our testing, we aren't able to properly test code that is doing a LIST on a `fieldSelector` using something akin to

```go
if err := client.List(ctx, &v1alpha1.MyCustomResourceList{}, client.MatchingFields{"status.arbitraryField": "fieldValue"}); err != nil {
    return fmt.Errorf("listing my custom resource, %w", err)
}
```

What is the recommended way to test code like this? I haven't found any solid documentation around this. If I try to use a `DelegatingClient` with a cache and index on these fieldSelectors, then I lose my strong read/write consistency during testing which is causing flakes

**Comment by alvaroaleman** [comment]
It doesn't make sense to me to use a different, non-fake client for testing. Please ask your question on the repo where that recommendation is made.

**Comment by jonathan-innis** [comment]
@alvaroaleman I don't think it's fair to close this issue. Using [envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) is a common paradigm and is part of the project, which sets up etcd and the api-server so you can use a non-fake client against the server locally.

I'd request that you re-open the issue since this is a common testing paradigm. Also, the [recommendation](https://github.com/kubernetes-sigs/kubebuilder/pull/2066) listed above is found in the kubebuilder SIG but relates to the controller-runtime SIG and the recommendation to use the direct client is found throughout the controller-runtime codebase like in [this issue](https://github.com/kubernetes-sigs/controller-runtime/issues/343)

**Comment by alvaroaleman** [comment]
The comment was not about using envtest, it was about using a different client that is not a fake-client. If you do that, you are not actually testing how a production setup of your controller behaves, which is why I disagree with that recommendation. Your controller and as a consequence its tests need to be able to deal with the fact that the cache is eventually consistent.

**Comment by jonathan-innis** [comment]
> which is why I disagree with that recommendation

Has the position on this recommendation changed over time? Like I mentioned, this seems to be confusing since I see a lot of old issues that recommend the direct client specifically for testing.

> it was about using a different client that is not a fake-client

If I understand this recommendation correctly, you are recommending _either_ using a fake-client or using the same `DelegatingClient` that you would use in the real client that is running in production, therefore using the cache. 

If this is used, then we could setup field indexers against the cache and get the expected test behavior as desired?
