### ISSUE TITLE
no required module provides package sigs.k8s.io/controller-runtime/pkg/envtest/printer

### ISSUE THREAD

**Issue by davidkarlsen** [kubernetes-sigs/controller-runtime#2113]
Docs tell to have this code: https://book.kubebuilder.io/reference/envtest.html#writing-tests

but it breaks on upgrade from 0.13.1 to 0.14.1:
https://github.com/evryfs/github-actions-runner-operator/actions/runs/3787812173/jobs/6439954186#step:5:34

as the package has been dropped.

Docs should be updated with new solution.

**Comment by alvaroaleman** [comment]
The docs do not mention the usage of the envtest/printer package anywhere. I've updated the releasenotes to include the removal.

**Comment by davidkarlsen** [comment]
? It says:
```
Using envtest in integration tests follows the general flow of:


import sigs.k8s.io/controller-runtime/pkg/envtest

//specify testEnv configuration
testEnv = &envtest.Environment{
    CRDDirectoryPaths: []string{filepath.Join("..", "config", "crd", "bases")},
}

//start testEnv
cfg, err = testEnv.Start()

//write test logic

//stop testEnv
err = testEnv.Stop()
```
