### ISSUE TITLE
incorrect documentation of readiness and liveness endpoint defaults

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/controller-runtime#2127]
Manager configuration and options incorrect state that probe endpoints default to "readyz" and "healthz". The defaults are actually "/readyz" and "/healthz". This is misleading, if user tries to rename probe endpoint name following this pattern (no "/"), then endpoint will not be correctly registered and probes will fail with 404.

https://github.com/kubernetes-sigs/controller-runtime/blob/8499b67e316a03b260c73f92d0380de8cd2e97a1/pkg/config/v1alpha1/types.go#L120-L126

https://github.com/kubernetes-sigs/controller-runtime/blob/8499b67e316a03b260c73f92d0380de8cd2e97a1/pkg/manager/manager.go#L232-L236

https://github.com/kubernetes-sigs/controller-runtime/blob/8499b67e316a03b260c73f92d0380de8cd2e97a1/pkg/manager/internal.go#L60-L61

**Comment by vincepri** [comment]
Are you able to open a PR to fix?
