### ISSUE TITLE
[Question] Is IsController compatible with the master branch?

### ISSUE THREAD

**Issue by kevin85421** [kubernetes-sigs/controller-runtime#2140]
The commit https://github.com/kubernetes-sigs/controller-runtime/commit/d6a053f8f0979d6f1528fe4d52b0d0f618352d77 changes the name of field from `IsController` to `isController`. That is, the field is not exported, so users need to use `handler.OnlyControllerOwner()` to control the value of the field. Does it mean that this PR breaks the backward compatibility? Thank you!

**Comment by alvaroaleman** [comment]
cc @vincepri was this intentional?
