### ISSUE TITLE
Deny List - Watch all namespaces BUT deny few namespaces.

### ISSUE THREAD

**Issue by AdheipSingh** [kubernetes-sigs/controller-runtime#2148]
- Most common case is when we want to watch all namespace but deny few namespaces.
- currently, it can be achieved by using a predicate to filter out namespaces.

is this something which can be added to ```ctrl.Options``` in manager ?

**Comment by Noksa** [comment]
What’s wrong with predicates?

**Comment by AdheipSingh** [comment]
> is this something which can be added to `ctrl.Options` in manager ?

^^^ @Noksa
