### ISSUE TITLE
Unstructured client's `List` does not propagate GVK to items

### ISSUE THREAD

**Issue by hiddeco** [kubernetes-sigs/controller-runtime#2171]
The `List` method does prepare the `gvk` to an "unsafe guess that doen't actually work, but matches ~99% of the cases out there", but this is never actually being put to use: https://github.com/kubernetes-sigs/controller-runtime/blob/10a02729220c108cb112962b9f227229c708c052/pkg/client/unstructured_client.go#L207-L208

Which does seem to be a left-over from changes in #812, which also mentions:

> [...] feels like I probably need to fix up some GVKs somewhere in the lists...

However, given that for `metav1.PartialObjectMetadataList` the GVK is later restored in the wrapping client: https://github.com/kubernetes-sigs/controller-runtime/blob/4fd4f6e7116453ea4e07a2cdd8ba0d38ad64680f/pkg/client/client.go#L372-L383

I am wondering if the same approach could be taken for the `unstructured.UnstructuredList`, as this would ease consumption in ~99% of the cases. If agreed on, I am happy to submit a PR.

**Comment by vincepri** [comment]
Probably an oversight that needs to be fixed, yes. Could we add a few test cases though to capture the error first? It'd be good to have tests for a custom resource and core one

**Comment by hiddeco** [comment]
Not a problem, if you provide a bit more information about the precise error (trigger) you would like to see captured.
