### ISSUE TITLE
Expose cache metrics

### ISSUE THREAD

**Issue by Segflow** [kubernetes-sigs/controller-runtime#2172]
To better understand an operator/controller memory usage, it would be great to expose cache related metrics, for instance we can expose the cache size per resource type (pod vs nodes, etc..)

**Comment by grzesuav** [comment]
hi, is it possible on controller-runtime side or it requires first changes in client-go ?

**Comment by sbueringer** [comment]
![client-go-controller-interaction (1)](https://github.com/kubernetes-sigs/controller-runtime/assets/4662360/140b0c00-9477-47b0-8b38-4ba09ec39918)
> https://github.com/kubernetes/sample-controller/blob/master/docs/controller-client-go.md

I assume you mean metrics about the "Thread safe store" in this diagram?

Then I think this should be done in client-go

**Comment by grzesuav** [comment]
yes, seems like client-go
