### ISSUE TITLE
Allow restricting the Cache's ListWatch to a set of namespaces

### ISSUE THREAD

**Issue by hasbro17** [kubernetes-sigs/controller-runtime#218]
As a follow up to #124 the manager should allow restricting the cache to a set of namespaces.

Watching on all namespaces and filtering the events(via predicates) to the desired namespaces is the only way to watch a set of namespaces currently.
The problem with that is it still requires a ClusterRoleBinding, whereas the user might want to grant more fine grained permissions of a ClusterRole with multiple RoleBindings(referring to the manager's service account).

**Proposed Fix:**
As discussed in https://github.com/kubernetes-sigs/controller-runtime/issues/124#issuecomment-417489171 we can use a [MultiListWatcher](https://github.com/coreos/prometheus-operator/blob/d1af6132437ba2796cc7cc625893768b67733273/pkg/listwatch/listwatch.go#L103-L105) in the cache if the manager is passed a set of namespaces.

**Comment by shawn-hurley** [comment]
@DirectXMan12 I think this is closed by #267

**Comment by DirectXMan12** [comment]
yep!
