### ISSUE TITLE
Consider removing "Get" prefix from cluster.Cluster interface

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-runtime#2181]
The current Cluster interface https://github.com/kubernetes-sigs/controller-runtime/blob/f127c11669de63e97a0e568b53b09362c8735154/pkg/cluster/cluster.go#L39-L75

exposes a number of methods that start with `Get[...]`, could we consider a breaking change to remove these?

**Comment by FillZpp** [comment]
After that, how should user get those client/cache from it?

**Comment by Noksa** [comment]
> After that, how should user get those client/cache from it?

Using new methods without ‘Get’ prefix

**Comment by sbueringer** [comment]
Sounds fine to me assuming it is consistent with the rest of the code base. Would be good to have consistent naming for our getters

**Comment by troy0820** [comment]
/kind feature 

This would be a minor breaking change so v0.17.0, v0.18.0 👀 ?

**Comment by sbueringer** [comment]
If we have consensus that we want to do it (@alvaroaleman @vincepri ?), whenever is fine I guess :)

**Comment by vincepri** [comment]
Definitely a breaking change, needs a minor version and requires detailed notes

**Comment by alvaroaleman** [comment]
I do agree the name is cleaner without the Get but this will be a lot of churn for users. Is that really worth it?

**Comment by troy0820** [comment]
> I do agree the name is cleaner without the Get but this will be a lot of churn for users. Is that really worth it?

I'm not sure if it is worth it.  The pushback around breaking changes from < v0.15 has caused issue triage and education around migration that is putting the onus on the maintainers and contributors alike.  I don't disagree that the cleaner function names offer better usability, but if we know we are putting a lot into v0.17 already (I'm not saying we are) would this churn bloat the release to cause that same type of issue going forward?

**Comment by vincepri** [comment]
We can keep it for later, there is no reason to do this immediately.

**Comment by sbueringer** [comment]
IIRC we didn't have a lot of breaking changes since the last release (at least I didn't see a many / any (?) PRs flagged like this). 

I think it's mainly a question of do we think it's worth the breaking change / migration effort for users. If we don't think it is, I would just close this issue.
