### ISSUE TITLE
controllerutil.go method CreateOrUpdate() panics when parameter object type uses protobuf

### ISSUE THREAD

**Issue by knelson7** [kubernetes-sigs/controller-runtime#2183]
In the file sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go, the method CreateOrUpdate(ctx context.Context, c client.Client, obj client.Object, f MutateFn) (OperationResult, error) fails with a panic error when the object passed in uses Protobuf—for example Istio types. I came across this issue when trying to pass in an Istio client-go Gateway (https://github.com/istio/client-go/blob/master/pkg/apis/networking/v1alpha3/types.gen.go). This error occurs because equality.Semantic.DeepEqual() is invalid for types that use protobufs (https://developers.google.com/protocol-buffers/docs/reference/go/faq#deepequal). 
Here is the issue I filed with Istio: https://github.com/istio/istio/issues/43001

**Comment by michaelbannister** [comment]
Having the same problem having upgraded from controller-runtime v0.13.1 to v0.14.0. This bumped a few other versions for me:

```diff
 require (
        github.com/coderanger/controller-utils v0.0.0-20201221100905-e26c5734ecc9
-       github.com/google/go-cmp v0.5.8
+       github.com/google/go-cmp v0.5.9
        istio.io/api v0.0.0-20230125212921-f04847bedb29
        istio.io/client-go v1.16.2
-       k8s.io/api v0.25.0
-       k8s.io/apimachinery v0.25.0
-       k8s.io/client-go v0.25.0
-       sigs.k8s.io/controller-runtime v0.13.1
+       k8s.io/api v0.26.1
+       k8s.io/apimachinery v0.26.1
+       k8s.io/client-go v0.26.1
+       sigs.k8s.io/controller-runtime v0.14.0
 )
```
and I _think_ perhaps the crucial change might be in this transitive dependency:
```diff
+       google.golang.org/protobuf v1.28.0 // indirect
-       google.golang.org/protobuf v1.28.1 // indirect
```

Similar issue https://github.com/istio/api/issues/2538

**Comment by knelson7** [comment]
Yes, after testing, I narrowed down the version change that caused the issue to be from v0.13.9 to v0.14.0.

**Comment by michaelbannister** [comment]
@knelson7 I finally figured out how to wire this into a controller-runtime manager:

```go
// SetupWithManager sets up the controller with the Manager.
func (r *MyCustomResourceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	// Add support for comparing istio types
	_ = equality.Semantic.AddFunc(func(vs1, vs2 *v1beta1.VirtualService) bool {
		return cmp.Equal(&vs1.Spec, &vs2.Spec, protocmp.Transform())
	})
	_ = equality.Semantic.AddFunc(func(vs1, vs2 *v1beta1.ServiceEntry) bool {
		return cmp.Equal(&vs1.Spec, &vs2.Spec, protocmp.Transform())
	})

	return ctrl.NewControllerManagedBy(mgr).
		For(&crdv1.MyCustomResource{}).
		Owns(&v1beta1.VirtualService{}).
		Owns(&v1beta1.ServiceEntry{}).
		Complete(r)
}
```
