### ISSUE TITLE
For downstream projects using go modules breaks due to uppercase 'github.com/Sirupsen/logrus'

### ISSUE THREAD

**Issue by paha** [kubernetes-sigs/controller-runtime#219]
For downstream projects using go modules fails due to uppercase reference at 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/Gopkg.lock#L72

Example output:

```bash
go: github.com/Sirupsen/logrus@v1.2.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"
go: error loading module requirements
```

re: https://github.com/golang/go/issues/28489
re: https://github.com/golang/go/issues/26208

**Comment by siscia** [comment]
@paha  How was this solved?

**Comment by Setheck** [comment]
@siscia I was able to workaround with importing
`github.com/Sirupsen/logrus v1.0.6`
and adding the following exclusions to my go.mod
```
exclude github.com/Sirupsen/logrus v1.3.0
exclude github.com/Sirupsen/logrus v1.2.0
exclude github.com/Sirupsen/logrus v1.1.1
exclude github.com/Sirupsen/logrus v1.1.0
```

I'm guessing this is effectively rolling back to a version before the rename broke everything.
