### ISSUE TITLE
[Feature proposal] Add repeatable `Runnable` as a wrapper to execute some `Runnable` every x duration

### ISSUE THREAD

**Issue by grzesuav** [kubernetes-sigs/controller-runtime#2193]
This is proposal to create a wrapper for `Runnable`, which would execute runnable exery `x` time, discussed [here](https://kubernetes.slack.com/archives/C02MRBMN00Z/p1675862721111239)

**Comment by vincepri** [comment]
Could it be possible to achieve this through a [Go ticker](https://gobyexample.com/tickers) instead?
