### ISSUE TITLE
Unable to convert runtime.Object to client.Object

### ISSUE THREAD

**Issue by shubham-yewalekar** [kubernetes-sigs/controller-runtime#2197]
I am trying to load a yaml file using scheme.Codecs.UniversalDeserializer().Decode which returns runtime.Object but client.Create() function requires client.Object as the first parameter
I am getting this error while trying to type cast runtime.Object into client.Object 
"k8s.io/apimachinery/pkg/runtime".Object does not implement client.Object (missing GetAnnotations method)

I am using the following versions : 
go 1.19
require (
	github.com/ghodss/yaml v1.0.0
	github.com/go-logr/logr v1.2.3
	github.com/onsi/ginkgo v1.16.5
	github.com/onsi/gomega v1.19.0
	github.com/pkg/errors v0.9.1
	k8s.io/api v0.25.0
	k8s.io/apimachinery v0.25.0
	k8s.io/client-go v0.25.0
	sigs.k8s.io/controller-runtime v0.13.0
)

**Comment by vincepri** [comment]
There are a couple of options. Do you have the Go types as well? One option is to unmarshal the yaml object directly to the Go type, which should be a client.Object (a union of metav1.Object and runtime.Object). If not, the other option is to use something like `scheme.Convert` to convert the runtime.Object to an unstructured.Object, which satisfies the client.Object interface
