### ISSUE TITLE
Issue with client LIST operation after upgrade

### ISSUE THREAD

**Issue by jdn5126** [kubernetes-sigs/controller-runtime#2210]
Following an upgrade from controller-runtime v0.8.3 to 0.13.1, our integration test started failing with:
```
[FAILED] Unexpected error:
    <*errors.errorString | 0xc0008a7f10>: {
        s: "Index with name field:reason does not exist",
    }
    Index with name field:reason does not exist
occurred
In [It] at: /workplace/jdnelson/go/src/github.com/amazon-vpc-cni-k8s/test/integration/ipamd/ipamd_event_test.go:158
```
This implies that we are missing a index on `Event.reason`, but we added one to the cache when creating a delegating client (source: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/test/framework/framework.go#L65):
```
k8sSchema := runtime.NewScheme()
clientgoscheme.AddToScheme(k8sSchema)
...
cache, err := cache.New(config, cache.Options{Scheme: k8sSchema})
err = cache.IndexField(context.TODO(), &v1.Event{}, "reason", func(o client.Object) []string {
    return []string{o.(*v1.Event).Reason}
})

// set up a context for the signals in tests
stopChan := ctrl.SetupSignalHandler()
go func() {
    cache.Start(stopChan)
}()
cache.WaitForCacheSync(stopChan)
realClient, err := client.New(config, client.Options{Scheme: k8sSchema})

k8sClient, err := client.NewDelegatingClient(client.NewDelegatingClientInput{
    CacheReader: cache,
    Client:      realClient,
})
 ```
I cannot for the life of me figure out what we are doing wrong and I am struggling to figure out what the next debug step is. Can someone point me in the right direction here? Looking through the release notes between these versions, nothing specific stands out. If it helps, the way we are doing the LIST query on the client is:
```
listOpts := client.ListOptions{
    FieldSelector: fields.SelectorFromSet(fields.Set{"reason": "MissingIAMPermissions"}),
    Namespace:     "kube-system",
}
eventList := eventsv1.EventList{}
k8sClient.List(context.Background(), &eventList, &listOpts)
```

**Comment by jdn5126** [comment]
I can confirm that events are returned when I run:
```
kubectl get events -n kube-system --field-selector reason=MissingIAMPermissions
```

**Comment by jdn5126** [comment]
bump, any thoughts here?

**Comment by jdn5126** [comment]
I tried to make the LIST call on the cache directly, i.e. `cache.List`, and I still get the same complaint about the index not existing, which is very confusing. Is an issue here the right avenue to get help with this? I read through the docs and examples and it looks like we are using `DelegatingClient` correctly.

For debugging, is there a way on the client to determine if the request is going to the API server and bypassing the cache? And for the cache, is there a way to dump the contents and/or print what indexes are registered?

**Comment by sbueringer** [comment]
@jdn5126 I don't know the history of the implementation of this in CR but I can provide an example how we use it in Cluster API today with CR v0.15.


https://github.com/kubernetes-sigs/cluster-api/blob/f0b2b03bc7cd35d259a64954bb03c66dc4155700/internal/controllers/topology/cluster/cluster_controller.go#L329-L337


https://github.com/kubernetes-sigs/cluster-api/blob/0a62991e5dcc4203b2c4049cd39e3582c36dc9c8/api/v1beta1/index/cluster.go#L37-L45


Regarding debugging. I would setup a unit test with envtest and then just step into the List function with a debugger

**Comment by jdn5126** [comment]
This turned out to be an issue with using events from `k8s.io/api/core/v1` instead of `k8s.io/api/events/v1`, so closing this. Thanks for the pointer @sbueringer , your example helped me figure this out!
