### ISSUE TITLE
How to differentiate a retried request

### ISSUE THREAD

**Issue by liyu-ma** [kubernetes-sigs/controller-runtime#2213]
Hi team,

In the situation of reconciliation error (an error is returned together with `Result`) and the requeue is going to happen, is there a way to tell whether the future requests are _retried_ requests?

Our use case is, we would like to instrument the reconciliation success rate e.g. `reconcile_success_count / reconcile_total` but we don't want to count in retried failures as it will eat up error budget quickly.

Or this is not the right way of thinking since it is all level-based and we shouldn't differentiate? Any advice would be appreciated.

**Comment by vincepri** [comment]
From a reconciler point of view, having a reconciliation request should usually not matter if it's a retry or not. Metrics on the other side are tracked already in https://github.com/kubernetes-sigs/controller-runtime/blob/af986b86bccaaa3a96e5a76b79a4e023b4056e3f/pkg/internal/controller/controller.go#L314-L336
