### ISSUE TITLE
Allow setting "UseExistingCluster" via OS Env

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes-sigs/controller-runtime#222]
Currently, `controller-runtime` does not support setting `UseExistingCluster` dynamically via environment variables (similarly to `envKubeAPIServerBin` or `envEtcdBin`, etc.). 

It would be very convenient and helpful to provide a uniform way in which users can dynamically set the option to `UseExistingCluster` via the environment.

**Comment by DirectXMan12** [comment]
done
