### ISSUE TITLE
Rate limiting resyncs

### ISSUE THREAD

**Issue by maherbeg** [kubernetes-sigs/controller-runtime#2228]
Is there a way to rate limit the resyncs of cached objects? Our operator manages a lot of objects with a lot of owned resources. Each resync can take a long time to finish reconciling and blocks actual updates to individual resources that come through.

**Comment by sbueringer** [comment]
There is a resync period, but that is probably not what you are looking for.

**Comment by vincepri** [comment]
Duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/857 ?
