### ISSUE TITLE
Add support for setting the transform request function on the actual internal client.

### ISSUE THREAD

**Issue by EraYaN** [kubernetes-sigs/controller-runtime#2236]
This is very useful to use a function like:

```go
func transformRequests(req *rest.Request) {
	req.SetHeader("Accept", strings.Join([]string{
		fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1.SchemeGroupVersion.Version, metav1.GroupName),
		fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1beta1.SchemeGroupVersion.Version, metav1beta1.GroupName),
		"application/json",
	}, ","))
}
```

For use in for example a kubectl plugin. For use with the code below as an example.
```go
var list dep.DeploymentList

listOptions := &client.ListOptions{ TransformRequest: transformRequests }
err = c.List(context.Background(), &list, listOptions)
```

Essentially I would like access to a line like this: https://github.com/kubernetes/kubectl/blob/c22c2cf969ba4c2fabbc979b60cc0c6dd89b1cf0/pkg/cmd/get/get.go#L470 so I can change the request right before the `Do()` call.

**Comment by DanMHammer** [comment]
I am also looking for this functionality instead of having to use that factory pattern to set these transform requests

**Comment by troy0820** [comment]
/kind support 

I'm not understanding the ask.  Are you trying to mutate what comes back from the apiserver? 

Controller-runtime has some ListOptions that are available to filter results but you are trying to change the request before the call? 

What you linked shows the "watch" method being invoked that allows the client side watch of one or more resources.  Also that Transform method is not exposed.  

It seems like you want to create this issue in k8s.io/kubectl and not kubernetes-sigs/controller-runtime as that functionality is different than what the client here is doing.

**Comment by EraYaN** [comment]
It's all about the "as=Table" part of the request. Because the client does not have the actual rendering information but the server does, this instructs the server to return table elements instead of the items itself. This can be very useful when doing CLI things in combination with an operator.

**Comment by EraYaN** [comment]
I'm trying to get (part of) the operator source code to also act as a kubectl plugin. And it's mostly strongly typed except for this one thing about printing, I've since solved this issue by just not support get at all and have people use kubectl. Kubectl itself is a bit too opaque to pipe a custom get command into the existing get command. I figured access to the client in some way would open up these use cases (with all the footguns that it might bring).

And of course I can just reimplement the table printing myself and add any columns or output I want, but that just feels so wasteful. I already need to implement ton of basic functionality because golang is golang, I'd like to reuse all the printing stuff from kubectl and that one accepts the Table type and handles it nicely. Also meaning I wouldn't need to use the CLI at all user computers everytime something changes with the CRD itself.

**Comment by DanMHammer** [comment]
@troy0820 To add some more detail. In a kubectl plugin, for example, you can use `k8s.io/kubectl/pkg/cmd/util` `factory` (or your own implementation of this factory pattern) to list objects from the api and inject `TransformRequests` to change the `Accept` header to `application/json;as=Table...` 

```go

	r := factory.NewBuilder().
		Unstructured().
		NamespaceParam(namespace).
		DefaultNamespace().
		ResourceTypeOrNameArgs(true, args...).
		SingleResourceType().
		ContinueOnError().
		Latest().
		Flatten().
		TransformRequests(transformRequests).
		Do().
		IgnoreErrors(errors.IsNotFound)
```

```go
func transformRequests(req *rest.Request) {
	req.SetHeader("Accept", strings.Join([]string{
		fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1.SchemeGroupVersion.Version, metav1.GroupName),
		fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1beta1.SchemeGroupVersion.Version, metav1beta1.GroupName),
		"application/json",
	}, ","))
}
```

This causes `r.Infos()` to return unstructured objects that include the column definitions. 

This can be utilized to transform the data into a `metav1.Table` object with `k8s.io/apimachinery/pkg/runtime` DefaultUnstructuredConverter

```
	table := metav1.Table{}
	err = runtime.DefaultUnstructuredConverter.FromUnstructured(infos[0].Object.(*unstructured.Unstructured).Object, &table)
	if err != nil {
		return nil, err
	}

	for _, info := range infos[1:] {
		t := metav1.Table{}
		err := runtime.DefaultUnstructuredConverter.FromUnstructured(info.Object.(*unstructured.Unstructured).Object, &t)
		if err != nil {
			return nil, err
		}
		table.Rows = append(table.Rows, t.Rows...)
	}
```

This allows us to display `additionalPrinterColumns` data based on the CRD instead of having to program a formatter everywhere we need it.

Even though envtest launches a kube-api instance, it appears to just completely ignore this header. It would be nice if envtest could support it so that we could have the same functionality in CI and production.


For reference, here is where this is implemented in `kubectl get`

transformRequests: https://github.com/kubernetes/kubectl/blob/7ce6599fc128a522ffa08ba0a594be801afb5cd4/pkg/cmd/get/get.go#L420

builder (with TransformRequests(o.transformRequests)`: https://github.com/kubernetes/kubectl/blob/7ce6599fc128a522ffa08ba0a594be801afb5cd4/pkg/cmd/get/get.go#L458

Table printer: https://github.com/kubernetes/kubectl/blob/7ce6599fc128a522ffa08ba0a594be801afb5cd4/pkg/cmd/get/table_printer.go#L58


This appears to be where this table formatting is performed in the kubernetes api, but I'm not 100% certain. I'm willing to investigate further. https://github.com/kubernetes/kubernetes/blob/9410de78b23eb4f88de900552d90638bc67ffcd4/pkg/printers/tablegenerator.go#L78

**Comment by DanMHammer** [comment]
Here's the whole code snipped for my `FetchTable` function if you'd like to reproduce it

```
import (
	"fmt"

	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/cli-runtime/pkg/genericclioptions"
	cmdutil "k8s.io/kubectl/pkg/cmd/util"
)

func FetchTable(namespace string, kind string, names []string) (*metav1.Table, error) {
	configFlags := genericclioptions.NewConfigFlags(true)
	factory := cmdutil.NewFactory(configFlags)

	args := append([]string{kind}, names...)

	r := factory.NewBuilder().
		Unstructured().
		NamespaceParam(namespace).
		DefaultNamespace().
		ResourceTypeOrNameArgs(true, args...).
		SingleResourceType().
		ContinueOnError().
		Latest().
		Flatten().
		TransformRequests(transformRequests).
		Do().
		IgnoreErrors(errors.IsNotFound)

	infos, err := r.Infos()
	if err != nil {
		return nil, err
	}

	if len(infos) == 0 {
		return nil, fmt.Errorf("no resources found for kind: %s with names: %s", kind, names)
	}

	table := metav1.Table{}
	err = runtime.DefaultUnstructuredConverter.FromUnstructured(infos[0].Object.(*unstructured.Unstructured).Object, &table)
	if err != nil {
		return nil, err
	}

	for _, info := range infos[1:] {
		t := metav1.Table{}
		err := runtime.DefaultUnstructuredConverter.FromUnstructured(info.Object.(*unstructured.Unstructured).Object, &t)
		if err != nil {
			return nil, err
		}
		table.Rows = append(table.Rows, t.Rows...)
	}

	return &table, nil
}
```

**Comment by DanMHammer** [comment]
I've been able to confirm that envtest actually is responding to the header properly. There just isn't a method in the `controller-runtime/client` that is able to handle it.

If you pass the client and rest.Config from envtest into this function, it will fetch the table output 

``` go
func getRestClient(restConfig *rest.Config, scheme *runtime.Scheme, gvk schema.GroupVersionKind) (rest.Interface, error) {
	httpClient, err := rest.HTTPClientFor(restConfig)
	if err != nil {
		log.Fatal("failed to create http client, err: ", err)
	}

	return apiutil.RESTClientForGVK(
		gvk,
		false,
		restConfig,
		serializer.NewCodecFactory(getScheme()),
		httpClient,
	)
}

func FetchTable(runtimeClient client.Client, restConfig *rest.Config, namespace string, obj runtime.Object) (*metav1.Table, error) {
	scheme := runtimeClient.Scheme()

	table := &metav1.Table{}

	gvk, err := apiutil.GVKForObject(obj, scheme)
	if err != nil {
		return nil, err
	}

	r, err := getRestClient(restConfig, scheme, gvk)
	if err != nil {
		return nil, err
	}

	mapping, err := getExpander(restConfig).RESTMapping(schema.GroupKind{Group: gvk.Group, Kind: gvk.Kind})

	if err != nil {
		return nil, err
	}

	return r.Get().
		SetHeader("Accept", strings.Join([]string{
			fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1.SchemeGroupVersion.Version, metav1.GroupName),
			fmt.Sprintf("application/json;as=Table;v=%s;g=%s", metav1beta1.SchemeGroupVersion.Version, metav1beta1.GroupName),
			"application/json",
		}, ",")).
		NamespaceIfScoped(namespace, namespace != "").
		Resource(mapping.Resource.Resource).
		Do(context.Background()).
		Into(table)
}
```

Ex:

```go
			table, _ := FetchTable(runtimeClient, restConfig, "", &v1.Namespace{})

			fmt.Printf("ColumnDefinitions: %+v\nRows: %+v\n", table.ColumnDefinitions, table.Rows)
```

output:
```
ColumnDefinitions: [{Name:Name Type:string Format:name Description:Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names Priority:0} {Name:Status Type:string Format: Description:The status of the namespace Priority:0} {Name:Age Type:string Format: Description:CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata Priority:0}]
Rows: [{Cells:[default Active 3s] Conditions:[] Object:{Raw:[ ....
```

So, this issue can probably be closed. It requires some weird hackiness but envtest is processing the request properly. It would require a change to the client API to add a convenient function or listOption to fetch the table directly.

**Comment by sbueringer** [comment]
Agree. Thx for providing a solution @DanMHammer. I think the ask is pretty far away from what our client is doing today (it always "returns" an object or a list of objects, it doesn't have any possibility to return a table).

As it's already possible with client-go primitives I'll close this issue.

/close
