### ISSUE TITLE
How can I create a New logger with custom zapcore

### ISSUE THREAD

**Issue by mrasnake-doppler** [kubernetes-sigs/controller-runtime#2242]
Hi, I am trying to create a new logger from the /zap sub-package by using a custom zapcore.Core.

Ultimately I am trying to use zapcore.NewTee to create multicore logger to determine stdout vs stderr logging by log level. i.e - info to stdout and errors to stderr.

something like the following: https://stackoverflow.com/questions/68472667/how-to-log-to-stdout-or-stderr-based-on-log-level-using-uber-go-zap

**Comment by mrasnake-doppler** [comment]
for anyone hoping to figure out the same thing, you can add your own core through the `zapOpts` field in the `Options` struct.

**Comment by Technovation22** [comment]
Hi @mrasnake-doppler Could you please provide a sample of how you used that? That would be appreciated.
