### ISSUE TITLE
LeaderElectionConfig UserAgent is not honored

### ISSUE THREAD

**Issue by ludydoo** [kubernetes-sigs/controller-runtime#2243]
## Problem:
We are seeing two different user-agents for our controller in the kubernetes audit logs. 

## Expected:
The leader election user-agent should conform to what was specified in the controllerManager configuration.

## Actual:
The leader-election user-agent is overriden by the controllerManager. 

## Details:

```
725   "userAgent": "stackrox-operator/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election",
893   "userAgent": "rhacs-operator/v3.71.x-17-g7992bde75b development_build (linux/amd64)",
```

We figured that we were missing the `ctrl.Options.LeaderElectionConfig`. Trying to set this has no effect. With the following configuration

```
func getRestConfig() rest.Config {\
   config := ...
   config.UserAgent = "myUserAgent"
}

func main(){
  mgr, err := ctrl.NewManager(getRestConfig(), ctrl.Options{
  Scheme:                  scheme,
  MetricsBindAddress:      metricsAddr,
  Port:                    9443,
  HealthProbeBindAddress:  probeAddr,
  LeaderElection:          true,
  LeaderElectionID:        "1234.stackrox.com",
  LeaderElectionConfig:    getRestConfig(),
  })
}
```

It seems that the user agent for the leader election client is ignored. Drilling through the code, the function used by the controller to build the leader election user agent is `rest.AddUserAgent`. That seems to be a misnomer, since it doesn't really "adds a user agent", but only concatenates the default k8s user agent with some suffix. (I would've expected it to rather append the given suffix to a pre-existing user-agent string)

https://github.com/kubernetes-sigs/controller-runtime/blob/c3c1f058a9a080581e8fe99c004fcc792b2aff07/pkg/leaderelection/leader_election.go#L90
```
...
rest.AddUserAgent(config, "leader-election")
```

https://github.com/kubernetes/client-go/blob/4666344cbcd76aba5a198e0fdfc3e7e5051698a9/rest/config.go#L593
```
func AddUserAgent(config *Config, userAgent string) *Config {
	fullUserAgent := DefaultKubernetesUserAgent() + "/" + userAgent
	config.UserAgent = fullUserAgent
	return config
}
```

**Comment by troy0820** [comment]
This may be resolved as the httpClient for leader election respects the kubeconfig passed into the options for the manager. 

Not sure this is what you were saying but this behavior did change and is now in v0.16.0
https://github.com/kubernetes-sigs/controller-runtime/pull/2464
