### ISSUE TITLE
FieldOwner with controllerutils.CreateOrPatch

### ISSUE THREAD

**Issue by terinjokes** [kubernetes-sigs/controller-runtime#2253]
The `client` package has a [FieldOwner](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/client#FieldOwner) option, which configures the managed fields used by Kubernetes for server-side apply. However, when using the [`controllerutils.CreateOrPatch`](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/controller/controllerutil#CreateOrPatch) helper function, it's not possible to set client options, without massive amounts of wrapping (see `client.NewDryRunClient`)

It would be nice to be able to either pass client options to `CreateOrPatch` or have a client with options that are configurable.

**Comment by alvaroaleman** [comment]
I don't think I quite understand this, why are you using CreateOrPatch in the context of serverside apply instead of just always applying (patching)?

**Comment by terinjokes** [comment]
In previous communications with members of the controller-runtime project, I was advised to use CreateOrPatch in my controllers, as it had a lot of the behavior desired (and made the reconcile functions much shorter and less error prone). More recently, I was looking at what I needed to do to setup the field manager, as it seemed like a best practice, especially when creating objects other controllers may mutate (like Deployments).

Perhaps there's been a miscommunication or misunderstanding on my part.
