### ISSUE TITLE
Does fakeClient support return an error?

### ISSUE THREAD

**Issue by hjiajing** [kubernetes-sigs/controller-runtime#2255]
Hi teams, 

I met a dilemma when I was using controller-runtime package. I used "fakeClient' in my unit tests, but I want to construct some failed cases, in which the errors will be compared with expected errors. So I wonder if the "fakeClient" supports return an specific error.

Thanks.

**Comment by alvaroaleman** [comment]
As of today, no. You can do something like proposed in https://github.com/kubernetes-sigs/controller-runtime/pull/2248 to get that.
