### ISSUE TITLE
golangci-lint action is failing incorrectly

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#2268]
See for example https://github.com/kubernetes-sigs/controller-runtime/actions/runs/4654252286/jobs/8235825217?pr=2259

It started failing without us doing any changes on PRs that are unrelated to the failure. It also seems it complains about something that got deprecated in go 1.20, but we use go 1.19

/kind bug

**Comment by vincepri** [comment]
@alvaroaleman I think https://github.com/kubernetes-sigs/controller-runtime/pull/2272 should fix it
