### ISSUE TITLE
EnqueueRequestForOwner doesn't correctly enqueue cluster-scoped owner

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#228]
_Splitting out the cluster-scoped owner scenario from #214._

As [pointed out](https://github.com/kubernetes-sigs/controller-runtime/issues/214#issuecomment-443343432) by @liggitt, cluster-scoped owners are now [explicitly supported](https://github.com/kubernetes/kubernetes/blob/6e5176b48df8719ab969a233a0411ad6ba35d222/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L288-L290).

`EnqueueRequestForOwner` doesn't support this relationship because it uses the namespace of the owned object as the namespace of the owner. We ran into this in https://github.com/knative/eventing/issues/649.

**Comment by rajathagasthya** [comment]
I'd like to work on this, with some hand-holding. How do I get started with making changes?

**Comment by DirectXMan12** [comment]
looks like #274 is working on this

**Comment by grantr** [comment]
I think this can be closed now that #274 is merged. Reopen if I'm wrong about that.
/close
