### ISSUE TITLE
Pod count sync issue when we scale the no of replicas using deployment

### ISSUE THREAD

**Issue by rajendraindukuri** [kubernetes-sigs/controller-runtime#2292]
Hi,

As part of our operator reconciler logic, we are using informers and client.Get (..) method from package https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/client to update the CR status

We are using the below command to scale the replicas for ex: as below:
`kubectl scale deployment/<nameofthedeployment> --replicas=1`

When we are running the commands like above, informers part is able to capture the deployment update and get the updated count as expected. But the following method which we are leveraging to get the pod status from k8s is not fetching the actual result instead still getting the old count 

![image](https://user-images.githubusercontent.com/82365588/235153232-8a74dc37-3bab-4ca1-8cba-eebb1dce3916.png)

Since the desired and actual count is not matching our CR is going into failed state.

We don't see any errors as such but we get stale pod count and not the latest. 

**More Info**:
Currently we gave defaultResync timeDuration for informers as one hour as below: 
![image](https://user-images.githubusercontent.com/82365588/235222226-b919fe72-21a6-407f-ba41-52768d63eb4c.png)

If we are reducing this time to seconds, it is properly syncing the data but the concern here is about the no of resyncs might slow down the reconcilation process

Can you please guide us on how we can handle this? Thanks.

**Comment by vincepri** [comment]
Is the cache lagging behind? What's the metadata of the object looking like? Is the revision different?
