### ISSUE TITLE
Bump to k8s.io/ v0.27.2

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#2297]
Goal of this issue is to bump to v0.27.2

While bumping to v0.27.1 we had to disable unit tests that verified the correct log format of a namespaced name (https://github.com/kubernetes-sigs/controller-runtime/pull/2189, test: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/2189/pull-controller-runtime-test/1651556343619784704).

As part of bumping to v0.27.2 we will enable those tests again

Note: We will wait with the v0.15.0 release until we bumped to v0.27.2.

Links:
* Upstream fix PR for the log issue: https://github.com/kubernetes/kubernetes/pull/117298
* https://kubernetes.io/releases/patch-releases/#upcoming-monthly-releases (1.27.2 is planned for 17th May)

**Comment by liggitt** [comment]
> While bumping to v0.27.1 we had to disable unit tests that verified the correct log format of a namespaced name

log output is not a guaranteed API (xref https://github.com/kubernetes/kubernetes/pull/117238#issuecomment-1505398537)... I'd strongly suggest removing a hard dependency on a particular format and bumping the version now

**Comment by liggitt** [comment]
oh... I guess https://github.com/kubernetes-sigs/controller-runtime/pull/2189 already bumped and this is waiting to bump again to tag a release?

**Comment by mythi** [comment]
@liggitt yes. the tests failing on a specific log format are not skipped. this is just to track 0.27.2 to do another bump

**Comment by sbueringer** [comment]
Yup. This issue is just to wait for v0.27.2 in 2 weeks. For now we also enable our unit tests again that - as of now - ensure the log format doesn't change.

I think it should be a separate discussion if we want to drop the unit tests. As far as I'm aware we also don't strictly guarantee that our log output is stable, but we try to only break it when necessary to provide users some stability if possible.

**Comment by sbueringer** [comment]
In this case the trade-off for us was basically releae CR v0.15.0 with a changed log format and v0.15.1 would change it back or do we delay the release until mid May.

**Comment by kkkkun** [comment]
> In this case the trade-off for us was basically release CR v0.15.0 with a changed log format and v0.15.1 would change it back or do we delay the release until mid May.

kubernetes:v1.27.2 is released  https://github.com/kubernetes/kubernetes/releases/tag/v1.27.2

**Comment by sbueringer** [comment]
/reopen 
log tests weren't enabled again yet

**Comment by blkperl** [comment]
Can someone tag a new release now that this is fixed?

**Comment by dongjiang1989** [comment]
Please release a new version？  #2320

**Comment by vincepri** [comment]
Beta tag has been published https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0-beta.0, full release is planned for next week
