### ISSUE TITLE
DryRun mode doesn't work with Event Recorder

### ISSUE THREAD

**Issue by BojanZelic** [kubernetes-sigs/controller-runtime#2335]
Even if we set DryRunClient to true, creating events with EventRecorders will still persist events to the cluster
```
mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
                 ...
		DryRunClient: true,
	})
```

**Comment by sbueringer** [comment]
Leader election is constructing its own client. DryRunClient only affects the "default" client that can be e.g. retrieved via mgr.GetClient().

In general it not safe to assume that "DryRunClient" will ensure the entire manager is running in a dry-run mode.

**Comment by troy0820** [comment]
/kind support 

Did this answer your question @BojanZelic? Can we close this issue?

**Comment by BojanZelic** [comment]
Makes sense, feel free to close
