### ISSUE TITLE
cannot find module providing package k8s.io/api/resource/v1alpha1

### ISSUE THREAD

**Issue by tonyliu666** [kubernetes-sigs/controller-runtime#2336]
Hello,folks.when i try to run the codes on [[https://pkg.go.dev/sigs.k8s.io/controller-runtime#example-package](url) ](https://pkg.go.dev/sigs.k8s.io/controller-runtime#example-package) and use go build to install modules.I found there was a problem of installing controller-runtime.

![Screenshot from 2023-05-22 09-20-16](https://github.com/kubernetes-sigs/controller-runtime/assets/48583047/35f44666-7ba2-4f8e-b58c-368622bc8924)
I found I cannot find module providing package k8s.io/api/resource/v1alpha1.Did anyone face this issue before?please tell me if anyone knows thanks.

**Comment by pmalek** [comment]
I also encountered this issue and what helped me was adding the following exclude to get `k8s.io/api` to use one of `v0.26.x` versions

```
exclude k8s.io/api v0.27.2
```

This is related and when that gets released as part of v0.15.0 the example should also be fixed: https://github.com/kubernetes-sigs/controller-runtime/pull/2189.

**Comment by troy0820** [comment]
Issue has been fixed in above PR link.  The example on pkg.go.dev points to k8s.io/api/resource/v1alpha2 with the latest controller-runtime.  

If this issue is still a problem, please reopen this issue. 

/close
