### ISSUE TITLE
Condition helpers/utils

### ISSUE THREAD

**Issue by luisdavim** [kubernetes-sigs/controller-runtime#2342]
Hi, there are some common operations with `Conditions` that would be nice to have some helper methods for, in the `sigs.k8s.io/controller-runtime/pkg/controller/controllerutil` package.

The `cluster-api` project has a `sigs.k8s.io/cluster-api/util/conditions` package that has some functions to deal with `Conditions` that I think would make sense being moved/adapted to the `controllerutil` package

I'm referring to functions like:

- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#Has
- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#IsFalse
- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#IsTrue
- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#IsUnknown
- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#MarkFalse
- https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions#MarkTrue
- etc...

**Comment by sbueringer** [comment]
I think the problem starts with what is the standard definition of the Condition struct. Cluster API does not use the same as upstream. (upstream also evolved a bit since Cluster API introduced conditions)

**Comment by luisdavim** [comment]
Yeah, I was thinking about the meta v1 conditions as the standard
 https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Condition

Another option could be to have a `type Conditions []Condition` and have some methods on it to get and set by type.

**Comment by sbueringer** [comment]
If the types are defined in API machinery shouldn't corresponding utils also be added there?

**Comment by luisdavim** [comment]
Maybe. Specially if it is a new type with methods. But sine the `controllerutils` has similar functionality for dealing with `OwnerReferences` I thought it could make sense there.

**Comment by troy0820** [comment]
/kind support 
I was thinking about this when looking at the controllerutils package but to @sbueringer point, those utility functions should probably be made in `k8s.io/utils` where they'd be more useful and confined to the types they define.  

Whereas cluster-api has their own definition of what Conditions are, trying to fit those types to work with metav1 for a utility function should probably live where the type is defined.  

@luisdavim does this sound reasonable?  Can we close this, if that is the direction we want to go?

**Comment by luisdavim** [comment]
Yes, that makes sense.

**Comment by troy0820** [comment]
Closing as confirmed by @luisdavim 
/close
