### ISSUE TITLE
Event filter should be triggered after checking OwnerReferences for `Owns`ed objects

### ISSUE THREAD

**Issue by samox73** [kubernetes-sigs/controller-runtime#2351]
To my understanding, when creating a new controller with `ctrl#Manager#NewControllerManagedBy` and specifying that the controller owns a resource--e.g. `Deployment`--an object of said type only triggers the reconciliation loop, if its `OwnerReferences` field contains the id of the controller.

When using a predicate function to filter certain objects based on some logic--e.g. the object's namespace--the predicate is called before the objects owner reference is asserted. Let's take an example:
 
```
ctrl.NewControllerManagedBy(mgr).
For(&myCRD).
Owns(&appsv1.Deployment{}).
WithEventFilter(myFilter()).
Complete(r)
```

The predicate `myFilter` will be called on ALL `Deployment`s regardless of the `Deployment`'s owner reference, which might filter the request anyway since it may not have the controller set as its owner.

**Comment by alvaroaleman** [comment]
For better or worse, the pipeline is source -> predicate -> handler. An argument can be made both for having predicate before and after handler, which is why we are not going to change it.

Using `Watches` and filtering in the `Handler` would allow us to do the filtering, yeah.

**Comment by samox73** [comment]
Thanks for the clarification @alvaroaleman
