### ISSUE TITLE
Usage of client-go's `discovery.ErrGroupDiscoveryFailed` breaks apimachinery `errors.IsNotFound`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes-sigs/controller-runtime#2354]
The introduction of the error conversion in controller-runtime v0.15.0:

https://github.com/kubernetes-sigs/controller-runtime/blob/30eae58f1b984c1b8139dd9b9f68dd2d530ed429/pkg/client/apiutil/restmapper.go#L275-L290

breaks the use case of checking available APIs via `k8s.io/apimachinery/pkg/api/errors.IsNotFound`:

https://github.com/kubernetes/kubernetes/blob/2e306e9632b13a3c1530a7e7ddf52a50f4741523/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L525-L536

Reason is the error conversion, which now needs a workaround like this:
https://github.com/kubernetes-sigs/security-profiles-operator/pull/1710/files#diff-fb01936f787b03e615f35a185799e91ec41896c1fcae0991db3a24137f21cf54R78-R87

Do we want to provide an additional API or something similar to make availability checks simpler?

**Comment by alvaroaleman** [comment]
@Fedosin What is the reason for using `discovery.ErrGroupDiscoveryFailed` rather than just passing on the error we got from `ServerResourcesForGroupVersion`?

**Comment by ebensh** [comment]
> @Fedosin What is the reason for using `discovery.ErrGroupDiscoveryFailed` rather than just passing on the error we got from `ServerResourcesForGroupVersion`?

Is this an approach we can take as a fix / patch? I understand that the v0.15.0 contained several changes that had the potential to break us, but detecting whether resources exist is a common operation for controllers to perform, and breaking the pattern of detecting whether a resource exists or not is a problem.

**Comment by dmitri-d** [comment]
Just encountered this issue as well.

**Comment by porridge** [comment]
Note that this also breaks use of `k8s.io/apimachinery/pkg/api/meta.IsNoMatchError` on the resulting error.

I wonder if this will work:
/kind bug
/kind regression

**Comment by porridge** [comment]
I've taken a stab at fixing this in https://github.com/kubernetes-sigs/controller-runtime/pull/2472
Please take a look @alvaroaleman @Fedosin
