### ISSUE TITLE
Want to implement write-only fields when using fake client

### ISSUE THREAD

**Issue by edwardstudy** [kubernetes-sigs/controller-runtime#236]
Hi, I used "sigs.k8s.io/controller-runtime/pkg/client" to test my custom controller function. And there are some differences between fake `runtime.Object` and real `runtime.Object`.

For example, I had following code to init client:
```
client = fakeClient.NewFakeClient(
	&corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "base-manifest",
			Namespace: "default",
		},
		StringData: map[string]string{"key1": "data1"},
	},
	&corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      "opaque-manifest",
			Namespace: "default",
		},
		Data: map[string][]byte{"key2": []byte("data2")},
	},
)
```

And I can get first secret data from `StringData` even it is write-only and get second secret data from `Data`.  But real secret should be set from `StringData` and `Data` both and only get from `Data`. It caused our unit-test didn't cover some `write-only` restriction.

Can we implement this to the fake client or have some plan?

Thanks.

**Comment by DirectXMan12** [comment]
That's not a difference in `runtime.Object`, it's that the API server does special weird behavior when converting `StringData`, serverside.  It's not really feasible for us to try to re-implement API server functionality in the test client.  You've got three options:

1. (I'd recommend this):  do what we do in controller-runtime and generated kubebuilder projects, and stand up a stand-alone API server instance.  We've got helpers to make it really easy, and it ensures that you test against an actual API server, and don't have to work through the quirks/cumbersomeness of the fake client

2. Add "reactors" to your fake client to mimic the API server functionality.  This is more complicated and requires knowledge of how the fakeClient works under the hood, but means you can continue using the fake client.

3. Restructure the way you test your code to not have this problem (this might not be possible -- it's hard to know without looking at your test code)

**Comment by DirectXMan12** [comment]
closing as per above answer
