### ISSUE TITLE
Health checks return 404 code

### ISSUE THREAD

**Issue by Alex-Sizov** [kubernetes-sigs/controller-runtime#2360]
All health checks are return 404 code by default.
In the docs it said that by default endpoints should be `healthz` and `readyz`
```
// Readiness probe endpoint name, defaults to "readyz"
ReadinessEndpointName string

// Liveness probe endpoint name, defaults to "healthz"
LivenessEndpointName string
```
But when checking it with `curl -XGET http://127.0.0.1:8080/healthz` it returns 404, since by default it's metrics endpoint (undocumented).
When configuring a separate health endpoint
``` go
	mgr, err := manager.New(
		config.GetConfigOrDie(),
		manager.Options{
			Scheme: initSheme(),
			HealthProbeBindAddress: "0.0.0.0:8081",
		},
	)
```
Heath probes still return 404
```
> curl -XGET http://127.0.0.1:8081/readyz
404 page not found
> curl -XGET http://127.0.0.1:8081/healthz
404 page not found
```
Is there a way to enable health checks with controller runtime?
controller-runtime version is `v0.15.0`

**Comment by iiiceoo** [comment]
If you only set `HealthProbeBindAddress`, the default health check will listen on the TCP port:

https://github.com/kubernetes-sigs/controller-runtime/blob/30eae58f1b984c1b8139dd9b9f68dd2d530ed429/pkg/manager/manager.go#L634-L644

Perhaps you should use `nc` to send a TCP packet for checking, rather than using `curl` to send a HTTP request:

```bash
$ nc -vz 127.0.0.1 8081
Connection to 127.0.0.1 8081 port [tcp/tproxy] succeeded!
```

Furthermore, if you need to customize your probe handel logic, you can add a healthz.Checker to mgr, then TCP server --> HTTP server and work according to the registered handler:

```go
	mgr, err := ctrl.NewManager(
		ctrl.GetConfigOrDie(),
		ctrl.Options{
			Scheme:                 scheme,
			HealthProbeBindAddress: ":8081",
		},
	)
	if err != nil {
		os.Exit(1)
	}

	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		os.Exit(1)
	}
```

Send a HTTP request:

```bash
$ curl -X GET -v http://127.0.0.1:8081/healthz
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /healthz HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 02 Jun 2023 06:43:54 GMT
< Content-Length: 2
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by Alex-Sizov** [comment]
@iiiceoo Thank you very much it worked! I missed the fact that by default it TCP only. 
Should I add this to the docs somewhere maybe? WDYT?
And btw I will close the issue, since it resolved.
