### ISSUE TITLE
Can we have multiple managers which points to different configs in the same controller? Is that supported?

### ISSUE THREAD

**Issue by Kiruthika-Jayabalan** [kubernetes-sigs/controller-runtime#2369]
We want to create a controller with multiple managers that watches different custom resources. The resources/kinds across each clusters do not match.

**Comment by alvaroaleman** [comment]
Yes, but its better to use the `cluster` abstraction in `pkg/cluster` instead, as that only abstracts the different cluster aspect without the `run stuff` aspect, as you need the latter only once.

**Comment by hitorig** [comment]
> Yes, but its better to use the `cluster` abstraction in `pkg/cluster` instead, as that only abstracts the different cluster aspect without the `run stuff` aspect, as you need the latter only once.

how do we use pkg/cluster?
are there any demos?thanks
