### ISSUE TITLE
Comparing UIDs instead of name, group and version.

### ISSUE THREAD

**Issue by therealak12** [kubernetes-sigs/controller-runtime#2380]
I was reading the code in `controllerutil.go` ([referSameObject function](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/controller/controllerutil/controllerutil.go#L158)) and I wonder why didn't we compare UIDs instead of Group, Version, and Name to check reference equality? As per [kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids), comparing UIDs should be enough.

```go
// Returns true if a and b point to the same object.
func referSameObject(a, b metav1.OwnerReference) bool {
	aGV, err := schema.ParseGroupVersion(a.APIVersion)
	if err != nil {
		return false
	}

	bGV, err := schema.ParseGroupVersion(b.APIVersion)
	if err != nil {
		return false
	}

	return aGV.Group == bGV.Group && a.Kind == b.Kind && a.Name == b.Name
}
```

**Comment by vincepri** [comment]
UIDs are local to a single API server, if you delete and recreate (for example during a backup/restore) the object UIDs get recalculated and the equality won't go through.

**Comment by therealak12** [comment]
Subtle point! Thanks.
