### ISSUE TITLE
SetControllerReference should allow overwriting the previous controller

### ISSUE THREAD

**Issue by therealak12** [kubernetes-sigs/controller-runtime#2381]
I want to change the controller of an object. The current implementation of `SetControllerReference` returns an error if the new owner is different than the previous one.

Adding a new method `SetControllerReferenceOverwrite` can be a solution.

**Comment by vincepri** [comment]
Changing the controller owner of an object is a very rare operation, which can also impact deletion flows in case of forward collection. I'd expect users to remove the older reference first, then set a new one in that case?

**Comment by therealak12** [comment]
Agree it won't be used that much, but for doing so I needed to duplicate some controller-runtime methods such as `referSameObject` and `validateOwner` into our code which wasn't so pleasant!

**Comment by troy0820** [comment]
/kind support 

Would creating a function to remove the controller reference (`RemoveControllerReference`) be something as a compromise?

**Comment by troy0820** [comment]
PR merged for function `RemoveOwnerReference` in controllerutil that should help this use case.

**Comment by therealak12** [comment]
> PR merged for function `RemoveOwnerReference` in controllerutil that should help this use case.

Thanks!
