### ISSUE TITLE
Predicates do not appear to receive objects with non-empty TypeMeta.APIVersion and TypeMeta.Kind fields

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/controller-runtime#2382]
I was working on a schema-agnostic predicate via the use of the `unstructured` package (https://github.com/vmware-tanzu/vm-operator/pull/163). However, my plans fell apart when I kept receiving errors about the expected `Kind` not matching. At first I thought it was my integration tests, that I was not explicitly setting `TypeMeta` when defining objects (there is funkiness around this when doing a `Get`, so maybe it was required here as well). However, what I soon learned was that Predicates seem to be designed to act on Go type information (ex. `if obj, ok := event.Object.(*v1alpha1.MyType); ok {`).

Except, here's the thing, while I *can* do something like this...

```golang
	// Controller-runtime does not assign an object's TypeMeta prior to sending
	// the object into a predicate. In order to ascertain the object's group,
	// version, and kind, we need to use the scheme's object mapper. The code
	// below gets all of the available group, version, kind combinations for
	// the provided object.
	gvks, unversioned, err := r.client.Scheme().ObjectKinds(inObj)
	if err != nil {
		return nil, fmt.Errorf(
			"failed to get group, version, & kinds for object: %w", err)
	}
	if unversioned {
		return nil, errors.New("object is unversioned")
	}

	// Update the inObj with one of the discovered GVKs. The correct version
	// is not important as all versions of VirtualMachine have a spec.className
	// field and all versions of VirtualMachineClass have a spec.controllerName
	// field.
	inObj.GetObjectKind().SetGroupVersionKind(gvks[0])
```

...why should I have to do so? It is clear that at some point prior to [the predicate being defined as part of the event handler](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/source/source.go#L201) for the client-go `Informer`, _something_ knew the `Kind` of the resource, else it would not have been routed correctly. And if the `Kind` is known, it should be possible to read the `APIVersion` information as well. Why can that information not be injected back into the object before it is sent into any registered predicates?

**Update 1**
It seems this is a known issue -- https://github.com/kubernetes/client-go/issues/308, and @nikhita indicates [it is intentional](https://github.com/kubernetes/client-go/issues/308#issuecomment-378165425).  Will read more to understand why and if this behavior can be changed...

**Update 2**
There _was_ a fix in progress at https://github.com/kubernetes/kubernetes/pull/63972, but it was closed due to being stale.

cc @srm09 @bryanv

**Comment by akutz** [comment]
Related to https://github.com/kubernetes/client-go/issues/308

**Comment by troy0820** [comment]
/kind support 

I do see that this method on the client.Client interface is surfaced since v0.15.0 `GroupVersionKindFor(obj runtime.Object)(schema.GroupVersionKind, error)`, however I don't believe that solves your problem of having that information already inferred when receiving the "event".  

I believe because predicate events (we still have to assert the type when we receive the event) deal with the registered scheme, having an unstructured/unstructured schema has to be explicitly set.  

I'm not sure if this method can help during the predicate definition but it may be a step closer to your desired solution.
