### ISSUE TITLE
The work_queue in the controller should be replaced by a new construction method

### ISSUE THREAD

**Issue by ShyunnY** [kubernetes-sigs/controller-runtime#2385]
I found that when creating a controller, the method of constructing workqueue has been enabled
```
return &controller.Controller{
		Do: options.Reconciler,
		MakeQueue: func() workqueue.RateLimitingInterface {
			return workqueue.NewNamedRateLimitingQueue(options.RateLimiter, name)
		},
		MaxConcurrentReconciles: options.MaxConcurrentReconciles,
		CacheSyncTimeout:        options.CacheSyncTimeout,
		Name:                    name,
		LogConstructor:          options.LogConstructor,
		RecoverPanic:            options.RecoverPanic,
		LeaderElected:           options.NeedLeaderElection,
	}, nil
```
Among them, it is recommended to use a new construction method for RateLimitingQueue
We can see from the workqueue in the `client-go` package that it would be better to use NewRateLimitingQueueWithConfig instead
```
// NewNamedRateLimitingQueue constructs a new named workqueue with rateLimited queuing ability.
// Deprecated: Use NewRateLimitingQueueWithConfig instead.
func NewNamedRateLimitingQueue(rateLimiter RateLimiter, name string) RateLimitingInterface {
	return NewRateLimitingQueueWithConfig(rateLimiter, RateLimitingQueueConfig{
		Name: name,
	})
}
```
I think it is possible to add new features to RateLimitingQueueConfig in the future
```[tasklist]
### Tasks
```

**Comment by vincepri** [comment]
`MakeQueue` is an internal constructor; users are expected to use Options.RateLimiter to customize rate limiting

**Comment by sbueringer** [comment]
I think this issue is just about that we should move away from the deprecated func. Opened a PR for it

![image](https://github.com/kubernetes-sigs/controller-runtime/assets/4662360/09c350e2-29fa-42c4-86f2-01e4020e7cf7)
