### ISSUE TITLE
fake client status patch doesn't merge condition but overwrite

### ISSUE THREAD

**Issue by MarkLux** [kubernetes-sigs/controller-runtime#2388]
I'm using **fake client** to write some unit tests, I want to patch a pod to add a new condition, the code:

```
mergePatch, _ := json.Marshal(map[string]interface{}{
		"status": map[string][]corev1.PodCondition{
			"conditions": {*condition},
		},
	})

p.Client.Status().Patch(context.TODO(), podClone, client.RawPatch(types.MergePatchType, []byte(mergePatch)))
```

I expected the pod should change as below:

pod before patch

```
{
  "status": {
    "conditions": [{
			"type": "Ready",
			"status": "True",
			"lastProbeTime": null,
			"lastTransitionTime": "2023-06-27T11:15:38Z"
		}]
  }
}
```

pod after patch

```
{
  "status": {
    "conditions": [
                {
			"type": "Ready",
			"status": "True",
			"lastProbeTime": null,
			"lastTransitionTime": "2023-06-27T11:15:38Z"
		},{
			"type": "SidecarSetUpgradable",
			"status": "True",
			"lastProbeTime": null,
			"lastTransitionTime": "2023-06-27T11:15:38Z"
		} // a condition added
    ]
  }
}
```

but when I run the code I found the pod after patch only have one condition, the existing condition of "Ready" disappeared, seems that the patch overwrited the conditions field instead of merge

```
{
  "status": {
    "conditions": [
                {
			"type": "SidecarSetUpgradable",
			"status": "True",
			"lastProbeTime": null,
			"lastTransitionTime": "2023-06-27T11:15:38Z"
		}
    ]
  }
}
```

this case only happened in unit tests when using fake client, it works well when using real client in production.

![image](https://github.com/kubernetes-sigs/controller-runtime/assets/19239409/04f16069-5861-43cc-b0f2-3af3fabd5674)

**Comment by iiiceoo** [comment]
Hi, I simulated the case you described:

```go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func main() {
	originPod := &corev1.Pod{
		Status: corev1.PodStatus{
			Conditions: []corev1.PodCondition{
				{
					Type:   corev1.PodReady,
					Status: corev1.ConditionTrue,
				},
			},
		},
	}

	curPod := originPod.DeepCopy()
	curPod.Status.Conditions = append(curPod.Status.Conditions, corev1.PodCondition{
		Type:   "SidecarSetUpgradable",
		Status: corev1.ConditionTrue,
	})

	patch := client.MergeFrom(originPod)
	b, _ := patch.Data(curPod)

	var buf bytes.Buffer
	_ = json.Indent(&buf, b, "", "\t")
	fmt.Println(buf.String())
}
```

But the difference is that I created the patch through `client.MergeFrom`, which correctly compares old obj with new obj and calculates the **JSON merge patch**:

```json
{
        "status": {
                "conditions": [
                        {
                                "lastProbeTime": null,
                                "lastTransitionTime": null,
                                "status": "True",
                                "type": "Ready"
                        },
                        {
                                "lastProbeTime": null,
                                "lastTransitionTime": null,
                                "status": "True",
                                "type": "SidecarSetUpgradable"
                        }
                ]
        }
}
```

That is to say, if you want to use `client.RawPatch` to create a merge patch, it should be defined as above. I guess you made some mistakes here.

More generally, I would recommend using `p.Client.Status().Patch(context.TODO(), &curPod, client.MergeFrom(originPod))` to complete patch requests. It incurs some overhead when calculating merge patches, but it greatly reduces the likelihood of errors and the performance of the test code is secondary.

**Comment by MarkLux** [comment]
I should use `StrategicMergePatchType` instead of `MergePatchType`, the problem is resolved 

> Hi, I simulated the case you described:
> 
> ```go
> package main
> 
> import (
> 	"bytes"
> 	"encoding/json"
> 	"fmt"
> 
> 	corev1 "k8s.io/api/core/v1"
> 	"sigs.k8s.io/controller-runtime/pkg/client"
> )
> 
> func main() {
> 	originPod := &corev1.Pod{
> 		Status: corev1.PodStatus{
> 			Conditions: []corev1.PodCondition{
> 				{
> 					Type:   corev1.PodReady,
> 					Status: corev1.ConditionTrue,
> 				},
> 			},
> 		},
> 	}
> 
> 	curPod := originPod.DeepCopy()
> 	curPod.Status.Conditions = append(curPod.Status.Conditions, corev1.PodCondition{
> 		Type:   "SidecarSetUpgradable",
> 		Status: corev1.ConditionTrue,
> 	})
> 
> 	patch := client.MergeFrom(originPod)
> 	b, _ := patch.Data(curPod)
> 
> 	var buf bytes.Buffer
> 	_ = json.Indent(&buf, b, "", "\t")
> 	fmt.Println(buf.String())
> }
> ```
> 
> But the difference is that I created the patch through `client.MergeFrom`, which correctly compares old obj with new obj and calculates the **JSON merge patch**:
> 
> ```json
> {
>         "status": {
>                 "conditions": [
>                         {
>                                 "lastProbeTime": null,
>                                 "lastTransitionTime": null,
>                                 "status": "True",
>                                 "type": "Ready"
>                         },
>                         {
>                                 "lastProbeTime": null,
>                                 "lastTransitionTime": null,
>                                 "status": "True",
>                                 "type": "SidecarSetUpgradable"
>                         }
>                 ]
>         }
> }
> ```
> 
> That is to say, if you want to use `client.RawPatch` to create a merge patch, it should be defined as above. I guess you made some mistakes here.
> 
> More generally, I would recommend using `p.Client.Status().Patch(context.TODO(), &curPod, client.MergeFrom(originPod))` to complete patch requests. It incurs some overhead when calculating merge patches, but it greatly reduces the likelihood of errors and the performance of the test code is secondary.
