### ISSUE TITLE
Un-Leader manager will not process a mannual trigged GenericEvent from watched source.Channel.

### ISSUE THREAD

**Issue by so2bin** [kubernetes-sigs/controller-runtime#2389]
* I create a manager with `LeaderElection` enabled, and controller watched a source.Channel which will generating mannual-triggered GenericEvent. 
The code is like the follows:

```go
// new a manager
mgr, err := manager.New(config, manager.Options{
	LeaderElection:          true, // Enable leader election
	LeaderElectionID:        fmt.Sprintf("%s-%s", conf.LeaseLockName, conf.CurClusterKey),
	Scheme:                  scheme,
	LeaderElectionNamespace: conf.LeaseLockNs,
	HealthProbeBindAddress:  conf.ControllerHealthProbeAddr,
})
// new controller
c, err := controller.New("xxx-controller", mgr,
	controller.Options{
		Reconciler: reconcilers.NewAtmsDReconciler(mgr.GetClient(), mgr.GetEventRecorderFor("xxx-controller")),
	},
)
// watch deployment events
err = c.Watch(source.NewKindWithCache(&appsv1.Deployment{}, mgr.GetCache()), &handler.EnqueueRequestForObject{}, filters...)
// watch genericevents from channel
err = c.Watch(&source.Channel{Source: gloCtrlMgr.deployEvents}, &handler.EnqueueRequestForObject{}, filters...)
```

* My intention for monitoring `source.Channel` is to collect manually triggered GenericEvents and converge changes in deployment status. In the case of multiple instance deployment of controller-runtime, if a non-leader instance receives a manually triggered event, it will not trigger the controller's `Reconcile()` function. Is there any way to solve this problem?
* I want the controller's `Reconcile()` function is always triggerd even if current runinng-instance is not the election-leader.

Thanks!

**Comment by vincepri** [comment]
Doesn't reconciling events in a non-leader go against the purpose of having leader election in the first place?

**Comment by so2bin** [comment]
> Doesn't reconciling events in a non-leader go against the purpose of having leader election in the first place?

Yes, this is a right design. I will close this issue.
