### ISSUE TITLE
Webhook path is not configurable in 0.15

### ISSUE THREAD

**Issue by Noksa** [kubernetes-sigs/controller-runtime#2390]
Before 0.15 we were able to register webhooks and specify path for them.

It looks like starting from 0.15 we don't have such opportunity.
Moreover, for some reason hardcoded paths use double-dash (why? It wasn't highlighted in the release notes) like that `mutate--v1-pod`. 

Not sure why we don't omit dash + `gvk.Group` if the latter is empty: https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/builder/webhook.go#L243

An example how it works now:
```
mutator := &webhookcontroller.PodMutator{Reader: operator.GetMgr().GetAPIReader()}
err := ctrl.NewWebhookManagedBy(operator.GetMgr()).For(&v1.Pod{}).WithDefaulter(mutator).Complete()
if err != nil {
	panic(err)
}
```

No way to set path for the webhook and it is set via https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/builder/webhook.go#L243

Before we could do it like that:
```
operator.GetMgr().GetWebhookServer().Register("/mutate-v1-pod", &webhook.Admission{Handler: &webhookcontroller.PodMutator{Reader: operator.GetMgr().GetAPIReader()}})
```

I took the examples from here: https://github.com/kubernetes-sigs/controller-runtime/tree/main/examples/builtins

Should old behavior still work?

**Comment by sbueringer** [comment]
> Moreover, for some reason hardcoded paths use double-dash (why? It wasn't highlighted in the release notes) like that mutate--v1-pod.

This was always the case and the cause for this is that we don't handle the core APIGroup differently then any other ones. But this should be purely cosmetic and thus not worth the breaking change to change it.

> It looks like starting from 0.15 we don't have such opportunity.

What makes you think this doesn't work anymore? (do you have an example that broke with v0.15?)

In Cluster API we are using this and we didn't have to modify our code between CR v0.14 and v0.15 and it still works:
https://github.com/kubernetes-sigs/cluster-api/blob/ea0dc4da091b13bea47dbb6d41340c1f434bac5d/controlplane/kubeadm/internal/webhooks/scale.go#L37

**Comment by Noksa** [comment]
@troy0820  Hi.
With behaviour from @sbueringer it works as expected (using `mgr.GetWebhookServer().Register(...)`)
In this case, an additional `-` was added to webhook path.
