### ISSUE TITLE
Struct from another module embedded in CRD remains empty on Client.Get()

### ISSUE THREAD

**Issue by tommazzo89** [kubernetes-sigs/controller-runtime#2400]
Hi all,

I'm encountering a strange issue with `client.Client.Get()` in a kubebuilder v3.11.0 project. When I try to `Get()` an instance of my CRD in the `Reconcile()` method of my controller, the fields of the Spec struct remain empty, but the ObjectMeta is correctly filled.  I'm using a multi-module workspace, where the Spec struct contains a field of a type from another module.

This is my Spec in the `controller` module:
```Go
type FunctionDescriptionSpec struct {
	// The function.FunctionDescription struct comes from another module in the same workspace.
	FunctionDescription function.FunctionDescription `json:",inline"`
}
```

This is the FunctionDescription struct definition in the `common` module:
```Go
// +kubebuilder:object:generate=true
type FunctionDescription struct {

	// The name of the function. This must be the name of a Knative Service object
	// in the same namespace as the FunctionDescription.
	FunctionName string `json:"functionName" yaml:"functionName"`

	// The name of the container in the pod that hosts the function code.
	FunctionContainer string `json:"functionContainer" yaml:"functionContainer"`

	// ...
}
```

I have already modified the Makefile of the kubebuilder project to generate the DeepCopy() functions:
```
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="../common/pkg/function"
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
```

The manager binary builds fine, but when I try to load an instance of my CRD, all fields of `FunctionDescription` remain at their default/empty values:
```go
var fnDesc chunkFunc.FunctionDescription
if err := fdr.Get(ctx, req.NamespacedName, &fnDesc); err != nil { ... }
// There is no error reported, but all fields of fnDesc.FunctionDescription are empty
```

This problem reminds of [this Kubebuilder issue](https://github.com/kubernetes-sigs/kubebuilder/issues/863), but this specific issue is not discussed there.

If I add a field to `FunctionDescriptionSpec` that uses a struct from the `controller` module as its type, its subfields get properly filled by `Get()`.
Is there any way to fix this other than moving the respective structs to the `controller` module?

**Comment by vincepri** [comment]
Is function.FunctionDescription an actual CRD or part of it? The example Get provided above wouldn't usually work, given that Get needs the full object to work, and that object needs to be registered in the Scheme.

**Comment by tommazzo89** [comment]
Thanks a lot for your fast response! `function.FunctionDescription` is just part of the CRD, but `chunkFunc.FunctionDescription` is an actual CRD. Yes, the naming is not ideal, there are two types called `FunctionDescription`: one is the CRD in the `controller` module and another one is the model object in the `common` module.

However, I just found out that that the issue is not the multi-module setup. Instead, the problem is the JSON inline configuration. If I define the Spec this way, it works perfectly:
```go
type FunctionDescriptionSpec struct {
	// With `json:",inline"` it would remain empty on Client.Get()
	FunctionDescription function.FunctionDescription `json:"functionDescription"`
}
```

Furthermore, I found out that this issue seems to apply to types from the same module as well. Not inlining this field is something I can definitely live with :) But there still seems to be a bug related to inlined fields. Should I change the title of this issue or create a new one instead?

**Comment by tommazzo89** [comment]
This is an actual manager running against an API server and I tried both versions of the CRD, i.e., with and without inlining and modified the respective resource to match the CRD.

There does appear to be a bug somewhere, because I just created a minimal repro from scratch, where I create two fields using the same struct in a CRD, one is linlined, the other not.
```go
type GuestbookSpec struct {
	GuestbookDefinition GuestbookDefinition `json:",inline"`

	GuestbookDefinitionNotInlined GuestbookDefinition `json:"guestbookDefinitionNotInlined"`
}
```

The inlined one remains empty after loading it from the API server:
```go
func (r *GuestbookReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	// ...

	var guestbook webappv1.Guestbook
	if err := r.Get(ctx, req.NamespacedName, &guestbook); err != nil {
	// ...
	}

	log.Info("Inlined values", "HotelName", guestbook.Spec.GuestbookDefinition.HotelName, "City", guestbook.Spec.GuestbookDefinition.City)
	log.Info("Not inlined values", "HotelName", guestbook.Spec.GuestbookDefinitionNotInlined.HotelName, "City", guestbook.Spec.GuestbookDefinitionNotInlined.City)

	// This prints the following:
	// Inlined values  {"controller": "guestbook", "controllerGroup": "webapp.my.domain", "controllerKind": "Guestbook", "Guestbook": {"name":"guestbook-sample","namespace":"default"}, "namespace": "default", "name": "guestbook-sample", "reconcileID": "45abae21-c3b4-4c40-87b0-68c65d0c1499", "HotelName": "", "City": ""}
	// Not inlined values      {"controller": "guestbook", "controllerGroup": "webapp.my.domain", "controllerKind": "Guestbook", "Guestbook": {"name":"guestbook-sample","namespace":"default"}, "namespace": "default", "name": "guestbook-sample", "reconcileID": "45abae21-c3b4-4c40-87b0-68c65d0c1499", "HotelName": "Plaza", "City": "Rome"}
}
```

I've uploaded the repro to this repo: https://github.com/tommazzo89/kubebuilder-inlining-test

**Comment by sbueringer** [comment]
Just a quick guess.

Can you try it with the following struct instead:
```go
type GuestbookSpec struct {
	GuestbookDefinition `json:",inline"`

	GuestbookDefinitionNotInlined GuestbookDefinition `json:"guestbookDefinitionNotInlined"`
}
```

**Comment by sbueringer** [comment]
Random quote from the internet :)

> “inline”: includes the fields of an embedded struct directly within the parent struct when serializing or deserializing JSON. This only works with embedded structs.

I think you're struct is only actually embedded if you don't explicitly define a field name.

**Comment by sbueringer** [comment]
Worked for me. Thx for providing the repro to make it easy to reproduce

![image](https://github.com/kubernetes-sigs/controller-runtime/assets/4662360/7c6a89b6-1bd7-45df-8a98-6b4cf50bf2a1)

P.S. The actual decode is happening here: https://github.com/kubernetes/client-go/blob/master/rest/request.go#L1373. But I would guess the way inlining works is just Go SDK behavior

**Comment by tommazzo89** [comment]
Hi @sbueringer,
Thanks a lot for investigating this and for providing the explanation! That resolves the issue, of course.
