### ISSUE TITLE
Change of behavior in `Client.Get` with empty object key name

### ISSUE THREAD

**Issue by metlos** [kubernetes-sigs/controller-runtime#2402]
Hi all,

while trying to upgrade from controller-runtime 0.14.6 to 0.15.0, we've come across a subtle change of behavior in `Client.Get`.

Consider this code:

```go
var cl client.Client = ...
if err := cl.Get(context.TODO(), client.ObjectKey{Name: "", Namespace: "default"}, &v1.ConfigMap{}); err != nil {
  if errors.IsNotFound(err) {
     createConfigMap()
  } else {
    return err
  } 
}
```

Prior to controller-runtime 0.15.0, the Get call would return a "not found" error, while in 0.15.0, a generic string error complaining that the resource name must not be empty is returned. This breaks the error handling of the callers that depended on `errors.IsNotFound` to also handle the case of empty names.

Our logic creates objects that can either have an explicit name or just generateName and we are using an analog of the above example to quickly check whether a potentially conflicting object exists in the cluster.

**Comment by vincepri** [comment]
Are you getting this specific error https://github.com/kubernetes/kubernetes/blame/e1fbd0c113af4b4c835ed2355b725506dfeda9e7/staging/src/k8s.io/client-go/rest/request.go#L278 ?

Having `not found` for an empty name can and probably will confuse users, the resource name validation seems a better way to warn users.

**Comment by metlos** [comment]
> Are you getting this specific error https://github.com/kubernetes/kubernetes/blame/e1fbd0c113af4b4c835ed2355b725506dfeda9e7/staging/src/k8s.io/client-go/rest/request.go#L278 ?
> 

Yes.

> Having `not found` for an empty name can and probably will confuse users, the resource name validation seems a better way to warn users.

I can agree with that, but nevertheless it is a change in behavior that breaks our particular way of supporting both name and generateName when creating a resource similar to the following example (which used to work in 0.14.x):

```go
res := corev1.ConfigMap{}
...
// either res.Name or res.GenerateName is set
if err := cl.Get(ctx, client.ObjectKeyFromObject(res), &res); err != nil {
  if errors.IsNotFound(err) {
    return createResource(res);
  }
  return err
}
```

So when upgrading to 0.15.0 we had to change that logic to explicitly handle the two possible cases.

I just wanted to point out that this behavior changed and let you decide how to deal with that. I didn't find a note about it so I assume it came by as a "collateral damage" of other code change.

**Comment by vincepri** [comment]
I don't think the change was in controller-runtime itself, but I might be wrong. Generally an empty name is an error, and not found wouldn't make sense to return to users.

**Comment by sbueringer** [comment]
Tested with CR v0.14.5 same issue. This check in client-go existed at least since Kubernetes 1.20.

I suspect something else changed and because of that you're now hitting this case.

**Comment by troy0820** [comment]
/kind support 

Can this be closed @metlos ?

**Comment by troy0820** [comment]
Closing because the behavior existed in controller-runtime v0.14.5 and this check has been around since k8s 1.20.  If the problem still remains, feel free to reopen. 

@metlos 
/close
