### ISSUE TITLE
Allow logging in JSON

### ISSUE THREAD

**Issue by smg247** [kubernetes-sigs/controller-runtime#2403]
It would be nice if there was a configuration to allow logging to be in json format. This would help to standardize logging across our various pods using `controller-runtime`.

**Comment by vincepri** [comment]
You can set your own logger, usually I've seen folks use `zap` https://github.com/kubernetes-sigs/controller-runtime/blob/56a973c46efe463ef7b5fbecd8495e8378b50d20/examples/builtins/main.go#L36-L38

**Comment by alvaroaleman** [comment]
This is definitely supported and in wide use. I am going to assume that vincepris suggestion helped you and close this. If that is not the case, please freel free to re-open :)
