### ISSUE TITLE
req.NamespacedName giving invalid name

### ISSUE THREAD

**Issue by ragarwal06** [kubernetes-sigs/controller-runtime#2404]
I am using `sigs.k8s.io/controller-runtime v0.15.0`.
In `SetupWithManager` I had specified 2 things
```go
return ctrl.NewControllerManagedBy(mgr).
	For(&test.NewPort{}).
	// Watch Instance
	Owns(instanceGVK).
	// Watch Binding
	Watches(
		bindingGVK,
		&handler.EnqueueRequestForObject{}
	).
	Complete(r)
```
`instanceGVK` and `bindingGVK` are just `PartialObjectMetadata` with their Group, Version & Kind.

---
Now the issue is with `req.NamespacedName` in `Reconcile`.
When an event occurs for `instanceGVK`, i get the Name & Namespace for `NewPort`, which is correct.

But, when an event occurs for `bindingGVK`, I am getting the name & namespace for `bindingGVK` & not for `NewPort`.

Is that the expected behaviour? Or their is some issue with this API.

---
Note: `bindingGVK` has ownerRef to `instanceGVK`, and `instanceGVK` has ownerRef to `NewPort`

**Comment by vincepri** [comment]
/kind support

`&handler.EnqueueRequestForObject{}` should only be used for the same object that you're reconciling, in the example above that's the object in the `For` call. 

To handle `bindingGVK`, you'd need to use a mapping function https://github.com/kubernetes-sigs/controller-runtime/blob/56a973c46efe463ef7b5fbecd8495e8378b50d20/pkg/handler/enqueue_mapped.go#L32-L46

The mapping function serves as a bridge from `bindingGVK`, to `NewPort`. The result of the mapping function is usually one or more `NamespacedName` for `NewPort`.

**Comment by ragarwal06** [comment]
@vincepri thanks for replying

I was following this
https://github.com/kubernetes-sigs/controller-runtime/blob/56a973c46efe463ef7b5fbecd8495e8378b50d20/pkg/handler/example_test.go#L68-L82

But here I guess, it `Reconciles` with the name(s) for Deployments(i.e. Watched) resource only. 
It would be great if you could point to an example for getting the `NamespacedName` for `NewPort` when event for `bindingGVK` occurs.

**Comment by vincepri** [comment]
In your example `a.GetName()` and `a.GetNamespace()` will enqueue a request using the `bindingGVK`'s name and namespace, which might not map to your reconciled `For()` object.

How are these two objects linked together?

**Comment by troy0820** [comment]
@ragarwal06 Are you still facing issues with this issue?

**Comment by ragarwal06** [comment]
@troy0820 no, I will close it
