### ISSUE TITLE
Clarify that in the default case, an empty ContentType is json for everything, and protobuf for core

### ISSUE THREAD

**Issue by krancour** [kubernetes-sigs/controller-runtime#2408]
The first argument to `ctrl.NewManager(...)` is a normal `*rest.Config` from client-go.

That type is composed of the `rest.ContentConfig` type among others.

`rest.ContentConfig` has fields `Accept ContentTypes` and `ContentType` that are documented as follows:

```golang
type ContentConfig struct {
	// AcceptContentTypes specifies the types the client will accept and is optional.
	// If not set, ContentType will be used to define the Accept header
	AcceptContentTypes string
	// ContentType specifies the wire format used to communicate with the server.
	// This value will be set as the Accept header on requests made to the server, and
	// as the default content type on any object sent to the server. If not set,
	// "application/json" is used.
	ContentType string

	//...
}
```

Controller runtime does not seem to honor these rules. When neither `ContentType` nor `AcceptContentTypes` are explicitly set, JSON is used for CR types (since that is all that is possible), but _protobufs_ are used for any type that is built-in to k8s.

I cannot find any documentation or even an issue explaining this. The change occurred in #1149, but was made without explanation.

So the only documentation anyone has to go on is what `rest.Config` says and Controller Runtime seems to defy those rules.

Would it be possible for this behavior be explicitly documented somewhere along with the rationale for doing so (so that people know what they're getting themselves into if they override it)?

Many apologies in advance if this _is_ documented somewhere and I have failed to find it.

**Comment by krancour** [comment]
Thanks for the response @vincepri. You're echoing my understanding.

I first noticed this when working on a proxy that could only handle application/json.

I know how to solve for that. I just opened this issue to call attention to surprising behavior that doesn't seem to be documented anywhere.

**Comment by vincepri** [comment]
If you set the `ContentType`, this https://github.com/kubernetes-sigs/controller-runtime/blob/56a973c46efe463ef7b5fbecd8495e8378b50d20/pkg/client/apiutil/apimachinery.go#L203-L210

_should_ go through and ignore protobuf, if that's not the case we might need a reproducible test that shows the bug and correct it.

cc @FillZpp

**Comment by vincepri** [comment]
/retitle Clarify that in the default case, an empty ContentType is json for everything, and protobuf for core

**Comment by FillZpp** [comment]
@krancour The documentation you showed is the doc of client-go, which means if controller-runtime does not set `ContentType`, it will use `application/json` for all types. But actually controller-runtime uses protobuf for built-in types by default, which could extremely improve performance and reduce the memory cost of serialize/deserialize.

So I will open a PR to add some documentation for this. Thanks for reporting!
/assign
