### ISSUE TITLE
`DynamicRESTMapper` does not return `No{Kind,Resource}MatchError` for non-present API groups

### ISSUE THREAD

**Issue by timebertt** [kubernetes-sigs/controller-runtime#2424]
When calling `RESTMapping()` and friends for an API Group/GroupVersion that is not present in the system (e.g., CRDs not yet installed), a `RESTMapper` should return `No{Kind,Resource}MatchError`.

However, with v0.15.0, the new `DynamicRESTMapper` returns `ErrGroupDiscoveryFailed` instead, e.g.
```
failed to get API group resources: unable to retrieve the complete list of server APIs: some.group/v1: the server could not find the requested resource
```

A consequence of this behavior is that managers will crash if they register controllers for resources that will only be registered during runtime. This was supported previously with the old `DynamicRESTMapper` implementation before v0.15.0.

/kind bug

**Comment by troy0820** [comment]
Is this issue still necessary?  I see that this PR https://github.com/kubernetes-sigs/controller-runtime/pull/2425 is closed but the above PR that was merged took changes from that PR and applied it.  
@timebertt

**Comment by timebertt** [comment]
Yes!
/close
