### ISSUE TITLE
source.Kind-based Controller never reconciles missed deletion events

### ISSUE THREAD

**Issue by danwinship** [kubernetes-sigs/controller-runtime#243]
A Controller based on Watching a `source.Kind` source will not reconcile deletion events that occur while the controller is not running.

Eg, taking specifically the case of https://github.com/openshift/cluster-network-operator (hi @squeed), if the operator is run, and then creates network infrastructure, and then exits, and then the `NetworkConfig` object is deleted, and then the operator is started again, it will behave as though nothing has changed, because it doesn't get any notification about the deletion. (Admittedly, cluster-network-operator doesn't even do the right thing if the deletion occurs while it *is* running, but that's a cluster-network-operator bug, not a controller-runtime bug.)

(There may not be a good way of fixing this generically, but @DirectXMan12 said I should file a bug so people could think about it.)

Similarly/relatedly, if the controller is started before any objects of the type it watches have been created, then the Reconcile function will never be called, which may be surprising. eg, in the case of cluster-network-operator, if there is no NetworkConfig object, then the operator wants to update its ClusterOperatorStatus to indicate that it is Failing. Admittedly, it could do this by just checking *before* it starts the controller running, but since the handling is so similar to the case where the NetworkConfig object is deleted, it seems like it might make more sense to have the code inside Reconcile rather than separate. But then again, maybe not. I'm not sure about this part...

**Comment by M00nF1sh** [comment]
Hi,
I think the source.Channel can solve this problem.
You can get the list of "network infrastructure" object from external source, and get the k8s identify from these external object(tags/names/description/etc), and send event.Generic to the channel.

**Comment by DirectXMan12** [comment]
For deleting:

Yeah, the general pattern here is that one of two things should be happening -- you should *either* be watching the state of the external world (like @M00nF1sh suggested), or use a finalizer on the Kubernetes object in question.

For initial creation:

Do you have an object that represents just the status for the network operator?  You might want to watch that, in which case you'll get an initial reconcile when you start up.

**Comment by DirectXMan12** [comment]
closing due to no response
