### ISSUE TITLE
Continuation token not set when reading from cache

### ISSUE THREAD

**Issue by polakovicp** [kubernetes-sigs/controller-runtime#2463]
(Similar issue I guess: https://github.com/kubernetes-sigs/controller-runtime/issues/1162)

When listing resources (for example Pods) with limit, continuation token is not set in response, resulting in incomplete listing.

Sample code:
```go
	opts := []client.ListOption{
		client.Continue(""),
		client.InNamespace(namespace),
		client.Limit(MaxResourcesListLimit),
	}

	if selector, err := metav1.LabelSelectorAsSelector(labelsSelector); err != nil {
		return nil, err
	} else {
		opts = append(opts, client.MatchingLabelsSelector{
			Selector: selector,
		})
	}

	var result []corev1.Pod

	for {
		pods := corev1.PodList{}

		if err := restClient.List(ctx, &pods, opts...); err != nil {
			return nil, err
		}

                result = append(result, pods.Items...)

		if len(pods.Continue) == 0 { // token is always ""
			return result, nil
		}
                ... 
         }
```

My `List` call ends in `cache_reader.go`:
```
func (c *CacheReader) List(_ context.Context, out client.ObjectList, opts ...client.ListOption) error {
```

Seems like the cache is not supporting paging :(

**Comment by alvaroaleman** [comment]
No, the cache does not support paging. What is your use case for that?

**Comment by alvaroaleman** [comment]
I don't follow. That seems to be a use-case for watching things, not a use-case for pagination. Why do you need pagination against the cache?

**Comment by troy0820** [comment]
/kind support 

Also don't follow, what are you trying to accomplish with having pagination on the cache if you are watching "selected" resources?

**Comment by polakovicp** [comment]
Cache is opaque. I realised what's going on by debugging the `List` method. I just used the documented API and pagination is part of it. But `cache_reader` supports only `Limit`.

> if you are watching "selected" resources?

Because I have predicates in place, thus not receiving everything.

Anyway, I think documenting this behaviour is not a bad idea. And I am going to redesign my code :)

**Comment by multi-io** [comment]
My use case is etcd re-encryption at rest, which requires implementing something equivalent to `kubectl get secrets --all-namespaces -o json | kubectl replace -f -` in clusters with potentially thousands of secrets. See https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#ensure-all-secrets-are-encrypted

**Comment by sbueringer** [comment]
Are you running into performance issues when reading all secrets from the local cache?
