### ISSUE TITLE
How to pass the Namespace while creating a Manager using NewManager(cfg,ctrl.Options{}) Method

### ISSUE THREAD

**Issue by Pradumn99** [kubernetes-sigs/controller-runtime#2467]
Hi Team, 

Hope you are doing great. Need some help in understanding how to pass namespace while creating new manager. Actually we could pass that as a key value pair in previous version of this library but now the controller-options have removed these labels like "Namespace", "SyncPeriod".

Need to know and understand how to pass the namespace or create a namespace scoped controller.

Thanks in advance

**Comment by troy0820** [comment]
Would cache.Options help? I think this may be what you are looking for. @Pradumn99 https://github.com/kubernetes-sigs/controller-runtime/blob/v0.16.1/pkg/cache/cache.go#L125

**Comment by sbueringer** [comment]
Yes. You can set it like this:
```go
		cache.Options{
			DefaultNamespaces: map[string]cache.Config{
				namespace: {},
			},
		},
```

**Comment by troy0820** [comment]
@Pradumn99 did @sbueringer suggestion help your issue?

**Comment by Pradumn99** [comment]
Yeah that helped. Thanks a lot @troy0820 and @sbueringer !
