### ISSUE TITLE
The fake client Status().Update() should not store object meta

### ISSUE THREAD

**Issue by berlin-ab** [kubernetes-sigs/controller-runtime#2474]
```
obj.SetAnnotations(map[string]string{
	"foo": "bar",
})
			
err = testClient.Status().Update(ctx, obj)
require.NoError(t, err)

_ = testClient.Get(ctx, k8sclient.ObjectKeyFromObject(obj), obj)
require.Equal(t, cluster.Annotations["foo"], "bar")
```
			
This test fails when using a real client, but succeeds when using the fake client.

**Comment by berlin-ab** [comment]
The same is true of labels.

**Comment by troy0820** [comment]
/kind support 
What version of controller runtime is this? 
Also if you put that `Get` in a new “obj” bar and not shadow it, does this happen?

**Comment by troy0820** [comment]
```
 _ = testClient.Get(ctx, k8sclient.ObjectKeyFromObject(obj), obj)
require.Equal(t, cluster.Annotations["foo"], "bar")
```
This also doesn’t seem to test `obj` but asserts that the cluster.Annotations[“foo”] is equal to bar. Is this `obj.Annotations[“foo”]`?

**Comment by berlin-ab** [comment]
> This also doesn’t seem to test `obj` but asserts that the cluster.Annotations[“foo”] is equal to bar. Is this `obj.Annotations[“foo”]`?

Sorry, I was changing some variable names to make it less specific to my situation and missed one.

**Comment by berlin-ab** [comment]
> What version of controller runtime is this?

v0.15.2

**Comment by berlin-ab** [comment]
I've modified the fake client test suite to show an example:

https://github.com/kubernetes-sigs/controller-runtime/pull/2475/files

**Comment by berlin-ab** [comment]
```
Fake client [It] should not change non-status field of typed objects that have a status subresource on status update
/Users/aberlin/workspace/controller-runtime/pkg/client/fake/client_test.go:1445

  [FAILED] Expected
      <string>:   &v1.Node{
        	TypeMeta: {Kind: "Node", APIVersion: "v1"},
        	ObjectMeta: v1.ObjectMeta{
        		... // 8 identical fields
        		DeletionTimestamp:          nil,
        		DeletionGracePeriodSeconds: nil,
      - 		Labels:                     nil,
      + 		Labels:                     map[string]string{"some-label-key": "some-label-value"},
      - 		Annotations:                nil,
      + 		Annotations:                map[string]string{"some-annotation-key": "some-annotation-value"},
        		OwnerReferences:            nil,
        		Finalizers:                 nil,
        		ManagedFields:              nil,
        	},
        	Spec:   {PodCIDR: "old-cidr"},
        	Status: {NodeInfo: {MachineID: "machine-id-from-status-update"}},
        }
      
  to be empty
  In [It] at: /Users/aberlin/workspace/controller-runtime/pkg/client/fake/client_test.go:1480 @ 09/07/23 22:55:45.781
  ```

**Comment by troy0820** [comment]
/kind bug 

Thanks for updating the issue.

**Comment by troy0820** [comment]
I'm trying to see if this is true for only core types and not custom resource types.  Not to say that you shouldn't be able to use this on core types but it will help to understand the scope of this.   

There is a test where unstructured.Unstructured works as you would expect.  client-go has a fake with updateStatus that handles this.  

@sbueringer @alvaroaleman any ideas?

**Comment by berlin-ab** [comment]
> I'm trying to see if this is true for only core types and not custom resource types.

I noticed this issue while working with a custom resource type.

**Comment by troy0820** [comment]
@berlin-ab The PR will hopefully address the issue with the test case you provided.  The other issue you mentioned may be coupled with issue https://github.com/kubernetes-sigs/controller-runtime/issues/2478 as well.

**Comment by berlin-ab** [comment]
@troy0820 Thanks for the really quick response. I really appreciate that this fake client has folks helping to make it more real/correct.
