### ISSUE TITLE
FakeClient patch on any subresource other than status is not working

### ISSUE THREAD

**Issue by acumino** [kubernetes-sigs/controller-runtime#2503]
FakeClient patch on any subresource other than status is not working.

For identifying if the last patch call was to update the status sub resource [here](https://github.com/kubernetes-sigs/controller-runtime/blob/cda3b29e29b8759e6c4507329082777257b36c0b/pkg/client/fake/client.go#L361-L367) we check if the stack trace has `sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeSubResourceClient).Patch`,  and if true only allow to update status. 
This is wrong as  `sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeSubResourceClient).Patch` will be present in the stack trace if a patch is done on any subresource. 

For ex, Patching `scale` subresource in deployment will also have `sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeSubResourceClient).Patch` in the stack trace because of which the code above will identify it as a status subresource update call and will not allow spec(replica) change in deployment.

Issues introduced with https://github.com/kubernetes-sigs/controller-runtime/pull/2259
controller-runtime version - v0.16.2

**Comment by alvaroaleman** [comment]
Feel free to take a stab at it
