### ISSUE TITLE
The CRD controller I built using controller runtime can only process approximately 20 requests per second, but my processing time is very short. How to configure it to increase the number of requests

### ISSUE THREAD

**Issue by zhouzhifeisdcn** [kubernetes-sigs/controller-runtime#2510]
The CRD controller I built using controller runtime can only process approximately 20 requests per second, but my processing time is very short. How to configure it to increase the number of requests

**Comment by troy0820** [comment]
/kind support 

Are you talking about manager.Options.Controller.MaxConcurrentReconciles?

**Comment by zhouzhifeisdcn** [comment]
opts := controller.Options{}
	opts.MaxConcurrentReconciles = maxConcurrent
	
	rateLimiter := workqueue.NewMaxOfRateLimiter(
		&workqueue.BucketRateLimiter{Limiter: rate.NewLimiter(rate.Limit(1000), 20000)},
	)
	opts.RateLimiter = rateLimiter
	logger.Info("test_info pod controller opts.MaxConcurrentReconciles:" + strconv.Itoa(opts.MaxConcurrentReconciles))
	return ctrl.NewControllerManagedBy(mgr).WithOptions(opts).
		For(&corev1.Pod{}).
		WithEventFilter(predicate.NewPredicateFuncs(func(object client.Object) bool {
			pod := object.(*corev1.Pod)
			//hostnetwork不处理
			if pod.Spec.HostNetwork == false {
				return true
			}

			
			annotations := pod.GetAnnotations()
			if annotations == nil {
				return false
			}
			if len(annotations[api.WooshPortsAnnot]) < 1 && len(netconf.MultusDefaultNetworkAttachmentAnnot) < 1 && len(netconf.NetworkAttachmentAnnot) < 1 {
				return false
			}

			return true
		})).
		Complete(r)

**Comment by zhouzhifeisdcn** [comment]
I have set maxConcurrent and ratelimit, but from the log time when entering Reconciler, it seems that they are all restricted; Initial 100 followed by 20 per second

**Comment by aerfio** [comment]
You're probably experiencing the effect of those lines
https://github.com/kubernetes-sigs/controller-runtime/blob/e787eaac7b6e380e5c6ec22fc6e16ab96195ada5/pkg/client/config/config.go#L101-L105
Adjust those values, you probably use ^ this function indirectly, by calling https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.16.2/pkg/client/config#GetConfigOrDie

**Comment by troy0820** [comment]
Is this still an issue @zhouzhifeisdcn? Did the above recommended fix help this?

**Comment by troy0820** [comment]
Closing as fix was provided.  Please feel free to open if this issue is not resolved. 

/close
