### ISSUE TITLE
The RELEASE.md file has markdown links that aren't rendering correctly

### ISSUE THREAD

**Issue by timflannagan** [kubernetes-sigs/controller-runtime#2526]
The root [RELEASE.md](https://github.com/kubernetes-sigs/controller-runtime/blob/main/RELEASE.md) currently has broken links in the "Now, let's generate the changelog" header. See https://github.com/kubernetes-sigs/controller-runtime/blob/main/RELEASE.md#now-lets-generate-the-changelog for a concrete reference.

**Comment by timflannagan** [comment]
I'm not sure if this repository has a "good first issue" label, but this would qualify. Happy to fix this too.

**Comment by troy0820** [comment]
Are you seeing 404 errors or the anchor not going to the correct place? Clicking that brings me to the page and the section.  

/kind support

**Comment by timflannagan** [comment]
I'm seeing the "kubebuilder-release-tools" and "here" anchors aren't rendering correctly for me:

```
Create the changelog from the new branch release-<MAJOR.MINOR> (git checkout release-<MAJOR.MINOR>). You will need to use the [kubebuilder-release-tools][kubebuilder-release-tools] to generate the notes. See [here][release-notes-generation]
```

![Screenshot 2023-10-06 at 12 26 10 PM](https://github.com/kubernetes-sigs/controller-runtime/assets/9899409/54bc1402-2c97-4d0a-869f-44021dd7914e)
