### ISSUE TITLE
v1.GetOptions is not suitable for converting to "..." in scheme

### ISSUE THREAD

**Issue by siredmar** [kubernetes-sigs/controller-runtime#2530]
Hi!

I am using controller-runtime client to access a CRD within a controller. 
I registered the schema and handle it to the client. Running the controller in a cluster works fine. I can Get() my resources, but i'm struggling writing a unit test for the reconcile loop using envtest.

This is my controller code (main.go) that works well.

```go
var (
	scheme   = runtime.NewScheme()
)

func init() {
	utilruntime.Must(clusterv1.AddToScheme(scheme))
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
}

func main() {
    //...	
    mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
                //...
	})
```

This is the corresponding part for the unit test 

```go

var (
    /// ...
    Scheme        *runtime.Scheme
)

var _ = BeforeSuite(func() {
	By("bootstrapping test environment")
	logf.SetLogger(zap.New(zap.WriteTo(GinkgoWriter), zap.UseDevMode(true)))

	Scheme = runtime.NewScheme()
	gv := clusterv1.GroupVersion
	Scheme.AddKnownTypes(gv, &clusterv1.Cluster{}, &clusterv1.ClusterList{})
	utilruntime.Must(clientgoscheme.AddToScheme(Scheme))
	utilruntime.Must(apiextensionsv1.AddToScheme(Scheme))
	_ = clusterv1alpha4.AddToScheme(Scheme)

	TestEnv = &envtest.Environment{
		Scheme: Scheme,
		CRDDirectoryPaths: []string{
			"../tests/vendor/cluster-api/crd/v1beta",
		},
	}
	Cfg, err := TestEnv.Start()
	Expect(err).NotTo(HaveOccurred())
	Expect(Cfg).NotTo(BeNil())
        // ...
```

When running the test i get `v1.GetOptions is not suitable for converting to "cluster.x-k8s.io/v1beta1" in scheme "/home/armin/edgefarm/capi2argo-cluster-operator/controllers/capi2argo_reconciler_test.go:73"`. I've look at it all day, googled the hell out of it but could not get anywhere near a solution. I suspect this has something to do with the Schema?

**Comment by troy0820** [comment]
I would suggest following the documentation with kubebuilder to set up your testing environment and anything outside of that recommendation will be on the person changing to understand the consequences of that change.  
As well as structuring you test/logic to get the required resources when they are created so what you are looking for will be available for testing.  

Closing as issue is now being tracked in @siredmar's pull request as support for testing is out of scope for triage. 

/close
