### ISSUE TITLE
fake client panics when adding an object with a deletion timestamp and no finalizers

### ISSUE THREAD

**Issue by gotwarlost** [kubernetes-sigs/controller-runtime#2536]
Ref: https://github.com/kubernetes-sigs/controller-runtime/blob/e39539c4bad06c2fab5070e9e433fb0c831696b5/pkg/client/fake/client.go#L281

This is intentionally done in the code and I guess I'm questioning this intention :) 

Let me explain.

I have a tool that loads a bunch of cluster objects and shows some stats using the controller-runtime client. I added a feature to this tool such that it can save what was loaded in local YAML files and use this information to carve out the stats differently on subsequent runs.

So the flow is that the "save-state" option saves whatever was loaded from the cluster into a local file and other commands have a "use-state" option. When this is set I create a fake client and pass it the lists that were saved to the state. A lot of times this hits the assertion above and panics the program.

Now, my question is: if it is valid for an object in K8s to be in this state (presumably because it is loaded between the time the finalizer was removed and the time that k8s actually deletes the object), why isn't it valid for the fake client to load it?

Hope I've expressed myself in a way that can be understood :)

**Comment by troy0820** [comment]
/kind support 

I don't believe that you can create objects that have a deletiontimestamp already set on them by the client.  This seems to mimic the behavior you would assume that the client, will not be able to create those objects.  If you are trying to "load" these resources in at the state they are in, it may be best to manipulate the list to work with how fake client works or use a different way of translating that.

**Comment by gotwarlost** [comment]
I guess I don't understand why the fake client cannot represent a state of an object that the server can return even if one cannot create such an object on the server. The act of throwing out the object seems like a server-side concern to me, one that the client shouldn't have opinions about.

Anyway, I appreciate the quick response, thanks! And I understand that such a change could have knock-on effects on other aspects of the fake client so I'll just preprocess such objects before loading them.
