### ISSUE TITLE
Informer watching fails with goroutine hanging after a while

### ISSUE THREAD

**Issue by yanfeng1992** [kubernetes-sigs/controller-runtime#2547]
We created informers to watch resources. But after a few days of normally running, we can't receive any events when the resource clusterresourcebindings changes(other resources and apiserver are normal). We found out that the corresponding goroutine has been hung for a long time:

clusterresourcebindings informer client is generated by informer-gen.

sigs.k8s.io/controller-runtime v0.14.2

![image](https://github.com/kubernetes-sigs/controller-runtime/assets/89568107/b2acaf2a-1eeb-438e-bfc3-c561ec929439)

**Comment by liangyuanpeng** [comment]
@yanfeng1992  Any update here?

**Comment by yanfeng1992** [comment]
> Any update here?

The cause of the problem has not been found yet

**Comment by sbueringer** [comment]
I think there is not much we can do here to help to be honest

**Comment by sbueringer** [comment]
How is this related with controller-runtime?
