### ISSUE TITLE
Webhook server random port broken

### ISSUE THREAD

**Issue by TheSpiritXIII** [kubernetes-sigs/controller-runtime#2548]
Use case:
I am running integration tests in parallel. As such, I would like to assign a random port to my webhook server so that I can run multiple instances.

What I tried:
I can start the server easily with a random port by updating the global variable: `webhook.DefaultPort = 0`. Then, I create a new webhook server with port 0 and it gets started with a random port.

What goes wrong:
While this now allows me to start multiple instances of my application since ports don't overlap anymore, there are a few ways this approach fails:
1. I cannot retrieve the port. The listener is created in the `Start` method and is not exposed outside.
2. The health check uses a different random port. This is due to the `StartedChecker` method trying to connect to port 0. This is related to  1 -- the server thinks a static port 0 was assigned. The server does not save the port number to check from `Start`.

**Comment by troy0820** [comment]
Wouldn't you use the options for setting the port?  If you use the options to set the port, you have the port you need to query the endpoint.  I'm not understanding exactly the issue you are facing beyond the port not being exposed on the webserver interface.  

`webhook.NewServer(webhook.Options{Port: <random int>})`

**Comment by TheSpiritXIII** [comment]
How do you find and reserve a random port? If you find an empty port and pass that into the port-forwarder, then there is a chance that another application gets it before the port-forwarder has a chance to reserve it so you have to add retry logic which keeps looking for new random unused ports. If the library does it, that would simplify the code a lot.

Another motivation for this feature is that `kubectl port-forward` supports using 0. I would expect the controller-runtime library to be on par with built-in `kubectl` operations.

**Comment by troy0820** [comment]
> How do you find and reserve a random port? If you find an empty port and pass that into the port-forwarder, then there is a chance that another application gets it before the port-forwarder has a chance to reserve it so you have to add retry logic which keeps looking for new random unused ports. If the library does it, that would simplify the code a lot.

I'm unsure exactly how you are doing these parallel tests with the setup and the randomization of ports.  I would assume that a range is utilized and within that range is where you expect the webhookserver to consume the random port. 

The webhook server doesn't randomize ports for you.  That is set through the `NewServer` function.  

If it is not set, 9443 is chosen to be utilized with the defaultServer.
