### ISSUE TITLE
Provide a way to create more selective cache to tackle memory consumption

### ISSUE THREAD

**Issue by jotak** [kubernetes-sigs/controller-runtime#2570]
From what I've seen this is a recurring topic and solutions have already been provided to tackle cache memory consumption:

1. By configuring cache limitations by-namespace and/or by-label
2. By caching only partial meta-data

I'll explain the problems that I see, but perhaps I don't have a full/correct understanding of these things, in which case I'm happy to be contradicted.

There are still use cases that aren't covered: when queried objects aren't known beforehand, at cache setup time, and their namespace and labels aren't under control (e.g. user-supplied resource references). In those cases, operators would watch resources cluster-wide to get the desired ones - which is a big waste of memory and kube API traffic, especially on big clusters with tons of Configmaps and Secrets.

Caching partial meta-data certainly helps but isn't a panacea: first, because it's still watching a lot of unneeded objects - so there is still a compressible overhead; second, because it forces you to still run queries to the kube API to get the desired object content, if metadata isn't enough for you - which is kind of defeating the idea of a cache?; and perhaps last but I'm not sure about that one: it saves memory but does it saves kube API traffic as well? Said differently, if the metadata filtering is performed after getting informed via the Kube API, it won't prevent the traffic overhead - or is it a feature implemented server-side?

Anyway, I think it would be great to have an option to cache certain GVKs only per object reference rather than full GVKs at large.

I am currently testing such an approach in the operator I'm working on, this is here: https://github.com/jotak/network-observability-operator/tree/configmap-no-cache/pkg/narrowcache

Here's basically how it's used:

```go
	 // This creates a narrowcache.Client for ConfigMaps and Secrets.
	 narrowCache := narrowcache.NewConfig(cfg, narrowcache.ConfigMaps, narrowcache.Secrets)
	 client, err := narrowCache.CreateClient(mgr.GetClient())
	 if err != nil {
		 setupLog.Error(err, "unable to create narrow cache client")
		 os.Exit(1)
	 }
```

This new cache layer is invoked for any call to `client.Get` on the configured GVK. For other
GVKs and other verbs, the underlying client is used.

Furthermore, cached objects are available as `source.Source`, so that they can be used as controller
watches to enqueue reconcile requests:

```go
	 src, _ := client.GetSource(ctx, obj)
	 controller.Watch(
		 src,
		 handler.EnqueueRequestsFromMapFunc(func(ctx context.Context, o client.Object) []reconcile.Request {
			// etc.
		 }),
	 )
```

This implementation is in certain aspects tailored for my use case - e.g. I'm not caring about `List` calls. But I think something along those lines would be great to have directly in controller-runtime. Especially as I duplicated some logic that already exists there.

**Comment by jotak** [comment]
For info, with this approach I could cut memory of our operator by more than half in my tests ; though that really depends on what's on the cluster, could be much more or much less

**Comment by joelanford** [comment]
Am I understanding correctly that in your implementation, 
- when the narrowcache client sees a `Get` request for a `Secret` it doesn't yet know about, it creates a new informer with a `metadata.name=<name>, metadata.namespace=<namespace>` field selector, waits for the informer to sync and then returns the object.
- the narrowcache client returns that informer, wrapped in the `source.Informer`, for `GetSource()`
- on subsequent `Get` calls, the client finds an existing informer for the object, so fetches from there.

**Comment by jotak** [comment]
> Am I understanding correctly that in your implementation,
> 
>     * when the narrowcache client sees a `Get` request for a `Secret` it doesn't yet know about, it creates a new informer with a `metadata.name=<name>, metadata.namespace=<namespace>` field selector, waits for the informer to sync and then returns the object.
> 

Not exactly: it's not using the informer API, but the watch API:

```
cl.CoreV1().Secrets(key.Namespace).Watch(ctx, opts)
```

Since I'm interested in caching one object at a time, I found it more relevant to use directly the watch API rather than informers.

So, calling `Get` when the cache is empty would first do a blocking `Get` call on the live client and then set the watch: https://github.com/jotak/network-observability-operator/blob/configmap-no-cache/pkg/narrowcache/client.go#L84-L96


>     * the narrowcache client returns that informer, wrapped in the `source.Informer`, for `GetSource()`
> 

Yes, or it creates it if it doesn't exist.

>     * on subsequent `Get` calls, the client finds an existing informer for the object, so fetches from there.

Correct (again except it's not an Informer per se)

**Comment by joelanford** [comment]
> Not exactly: it's not using the informer API, but the watch API:

It may be worth just using an informer with a field selector. There are important semantics that you don't get automatically with separate `Get` and `Watch` calls. For example, your watch needs to be setup with a starting resource version based on the `Get`. If you don't do that, you risk missing an event between the time the `Get` and `Watch` calls happen.

That would likely also simplify your `GetSource` function, since there's already an off-the-shelf `source.Informer` wrapper.

> `cl.CoreV1().Secrets(key.Namespace).Watch(ctx, opts)`

controller-runtime doesn't use typed clients. Did you look into using a dynamic client/informer?

**Comment by alvaroaleman** [comment]
The proposal as described seems overly specific to me, not supporting LIST at all and creating a dedicated informer per single resource on `Get` does not seem like something that will be useful for the general case. We deliberately offer `NewCache` that allows you to bring your own cache for cases like this, but I do not think your implementation is something that makes sense to upstream.

I am going to close this issue, feel free to re-open if you disagree.

**Comment by jotak** [comment]
Hi @alvaroaleman 
I didn't open this issue to push for _my_ implementation, only to show as an example of what I'd like to solve, but designing a solution available for the more general use case, and opening a discussion about that (this isn't . I really really don't think the problem is super specific, because looking at a bunch of other operators randomly, I see a lot of them affected by this issue, ie. wasting memory / bandwidth by watching too broad.

I think the root cause is on the API which doesn't help figuring out the problem when you don't have a good understanding of controller-runtime internal, because the default is to watch cluster-wide. For instance, the fact that a simple `client.Get(<configmap>)` ends up caching all configmaps of the cluster by default is quite counter-intuitive IMO. 

While I guess it wouldn't be easy to change the API, I would however imagine that providing an easy-to-implement solution to be a reasonable answer, instead of all operator developers having to reimplement the same thing on their end?

**Comment by alvaroaleman** [comment]
> I really really don't think the problem is super specific, because looking at a bunch of other operators randomly, I see a lot of them affected by this issue, ie. wasting memory / bandwidth by watching too broad (configmaps or secrets in particular).

Current controller-runtime versions allow super granular configuration of what you want to watch: https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/cache_options.md

Do you have an example use-case that is not covered by the above?

> For instance, the fact that a simple client.Get(<configmap>) ends up caching all configmaps of the cluster by default is quite counter-intuitive IMO.

Probably true, but this is a default you can change (`cache.ReaderFailOnMissingInformer`). Changing the default is problematic, because It will break a lot of things at runtime.

**Comment by jotak** [comment]
> > I really really don't think the problem is super specific, because looking at a bunch of other operators randomly, I see a lot of them affected by this issue, ie. wasting memory / bandwidth by watching too broad (configmaps or secrets in particular).
> 
> Current controller-runtime versions allow super granular configuration of what you want to watch: https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/cache_options.md
> 
> Do you have an example use-case that is not covered by the above?
> 

Yes, cf in above description:

> There are still use cases that aren't covered: when queried objects aren't known beforehand, at cache setup time, and their namespace and labels aren't under control (e.g. user-supplied resource references). [...]

I think it is quite common to watch a resource that isn't clearly identified yet at controller startup time, ie. when initializing the cache with options.

**Comment by alvaroaleman** [comment]
> There are still use cases that aren't covered: when queried objects aren't known beforehand, at cache setup time, and their namespace and labels aren't under control (e.g. user-supplied resource references). [...]

So the actual issue is that you want to re-configure the cache selectors at runtime? That requires a restart of the informers to re-establish the watches.

**Comment by jotak** [comment]
How do you restart all that? You need to restart the manager and all the controllers as well, then?
This sounds interesting, if it's a good approach I'd say it deserves to be documented :-)

**Comment by alvaroaleman** [comment]
> This sounds interesting, if it's a good approach I'd say it deserves to be documented :-)

Feel free to contribute docs.

What I meant was that the watch has to be restarted because the selectors are passed as query args, which means its not possible to change them. This also entail that a watch has to be created from scratch, which is expensive.

It's one of these problems I'd personally rather avoid to have than to solve because there won't be a good solution. I've worked around this in the past using a downstream client wrapper that falls back to an APIReader on NotFound and adds a label that matches the caches selector if it exists.

**Comment by thesuperzapper** [comment]
My recommendation is to do something similar to this PR in external-secrets:

- https://github.com/external-secrets/external-secrets/pull/4086

## Disable Caching Manager's Default Client

You can disable the cache for specific resource kind in your [`manager.Manager`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Manager) default client using `DisableFor` in the [`client.CacheOptions`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#CacheOptions):

For example, your outer `main()` function might look like this:

```go
import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"log/slog"
	"os"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
)

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
	restConfig := ctrl.GetConfigOrDie()
	scheme := runtime.NewScheme()

	// add default Kubernetes types to the scheme
	if err := clientgoscheme.AddToScheme(scheme); err != nil {
		logger.Error("failed to add Kubernetes types to scheme", "error", err)
		os.Exit(1)
	}
	// add your custom types to the scheme
	//if err := XXXXv1beta1.AddToScheme(scheme); err != nil {
	//	logger.Error("failed to add XXXX types to scheme", "error", err)
	//	os.Exit(1)
	//}

	ctrlOpts := ctrl.Options{
		Scheme: scheme,
		Client: client.Options{
			Cache: &client.CacheOptions{
				// this disables caching for all Secrets and ConfigMaps
				// as caching all secrets can take a LOT of memory in a large cluster
				DisableFor: []client.Object{
					&corev1.Secret{},
					&corev1.ConfigMap{},
				},
			},
		},
		Metrics: metricsserver.Options{
			BindAddress: "0", // not required, just for example
		},
		HealthProbeBindAddress: "0",   // not required, just for example
		LeaderElection:         false, // not required, just for example
	}

	// create a new manager
	mgr, err := ctrl.NewManager(restConfig, ctrlOpts)
	if err != nil {
		logger.Error("unable to create manager", "error", err)
		os.Exit(1)
	}

	//
	// ADD THE BuildManagedSecretClient() FUNCTION HERE
	// SEE THE NEXT SNIPPET FOR AN EXAMPLE
	//

	// start the manager
	logger.Info("starting manager")
	err = mgr.Start(ctrl.SetupSignalHandler())
	if err != nil {
		logger.Error("unable to start manager", "error", err)
		os.Exit(1)
	}
}
```

## Example of Filtered Cached Client

You can construct a new filtered client using [`ByObject`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#ByObject) from [`cache.Options`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#Options). 

(__WARNING:__ a client which uses a filtered cache will be completely unable to see resources in the cluster which don't match the cache, even if they exist)

For example, here is the one from external-secrets which only caches secrets with the `reconcile.external-secrets.io/managed=true` label:

```go
import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/selection"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func BuildManagedSecretClient(mgr ctrl.Manager) (client.Client, error) {
	// secrets we manage will have the `reconcile.external-secrets.io/managed=true` label
	managedLabelReq, _ := labels.NewRequirement("reconcile.external-secrets.io/managed", selection.Equals, []string{"true"})
	managedLabelSelector := labels.NewSelector().Add(*managedLabelReq)

	// create a new cache with a label selector for managed secrets
	// NOTE: this means that the cache/client will be unable to see secrets without the "managed" label
	secretCacheOpts := cache.Options{
		HTTPClient: mgr.GetHTTPClient(),
		Scheme:     mgr.GetScheme(),
		Mapper:     mgr.GetRESTMapper(),
		ByObject: map[client.Object]cache.ByObject{
			&corev1.Secret{}: {
				Label: managedLabelSelector,
			},
		},
		// this requires us to explicitly start an informer for each object type
		// and helps avoid people mistakenly using the secret client for other resources
		ReaderFailOnMissingInformer: true,
	}
	secretCache, err := cache.New(mgr.GetConfig(), secretCacheOpts)
	if err != nil {
		return nil, err
	}

	// start an informer for secrets
	// this is required because we set ReaderFailOnMissingInformer to true
	_, err = secretCache.GetInformer(context.Background(), &corev1.Secret{})
	if err != nil {
		return nil, err
	}

	// add the secret cache to the manager, so that it starts at the same time
	err = mgr.Add(secretCache)
	if err != nil {
		return nil, err
	}

	// create a new client that uses the secret cache
	secretClient, err := client.New(mgr.GetConfig(), client.Options{
		HTTPClient: mgr.GetHTTPClient(),
		Scheme:     mgr.GetScheme(),
		Mapper:     mgr.GetRESTMapper(),
		Cache: &client.CacheOptions{
			Reader: secretCache,
		},
	})
	if err != nil {
		return nil, err
	}

	return secretClient, nil
}
```

**Comment by jotak** [comment]
@thesuperzapper thanks, that's great examples to provide here. I also ended up disabling cache for Secrets and CMs - but creating a custom cache for them might not always be that easy. Here you restrict to resources having a specific label, which means you have some control/ownership on these resource, but imagine the operator has to be able to read any sort of CM/Secret (e.g. user-supplied certificates), that wouldn't work, and the solution becomes slightly more complicated.
Also my main point when opening this issue was that it's too easy to do it wrong - I've seen plenty of operators using an absurd amount of memory (and bandwidth) because of that, so it's more like a design flaw to me, which should be addressed in controler-runtime directly.

**Comment by thesuperzapper** [comment]
> Also my main point when opening this issue was that it's too easy to do it wrong - I've seen plenty of operators using an absurd amount of memory (and bandwidth) because of that, so it's more like a design flaw to me, which should be addressed in controler-runtime directly.

@jotak I agree there should be some improvements on `controller-runtime` (at least for Secrets and ConfigMaps).

I think there are two things we should consider:

1. __Create a per-resource config called "split cache":__

     - This would allow a filtered list-watch cache, without making un-cached objects invisible to the default client object.
     - The implementation could be to do a `PartialObjectMetadata` "metadata-only" cache for ALL resources of a kind, in addition to a filtered "full cache" for objects that match the selector.
     - Then, when the user tries to `Get()`/`List()` that resource, we first check with the "metadata-only" cache to know if we can use the "full cache" or not, and we either use a raw API request or the "full cache" accordingly.
     - We also don't need to separately check for existence, because the "metadata only" is sufficient to know.
     - WARNING: there is a race condition between the caches. The best way to address this is to have a new client error called something like `SplitCacheNotSyncronized` which the `Get/List` methods will throw if the latest resource version known to either cache is not the same so users can retry or requeue.
     - NOTE: users can already approximate this with what I did in https://github.com/kubernetes-sigs/controller-runtime/issues/2570#issuecomment-2466564432, if they always query `PartialObjectMetadata` first, but it's way cleaner to implement as a first-part feature.

2. __For parts of objects we know can be very large, we should compress them in memory:__
      
      - There is already a way to [compress results of a ListWatch with GZip](https://kubernetes.io/docs/reference/using-api/api-concepts/#response-compression), but I am not sure if our Go client does this by default?
      - We could also compress larger parts of objects in Go itself (e.g. the `data` fields of a Secret/ConfigMap)
      - We might need to make this optional, as it trades memory usage for CPU usage.
