### ISSUE TITLE
Does GenericEvent Originate from Cache Synchronization in Kubernetes?

### ISSUE THREAD

**Issue by kasmoghaile9** [kubernetes-sigs/controller-runtime#2577]
I am currently researching the `GenericEvent` type in the Kubernetes client package. Specifically, could it originate from cache synchronization processes within a Kubernetes cluster? 

```go
// GenericEvent is an event where the operation type is unknown (e.g. polling or event originating outside the cluster).
// GenericEvent should be generated by a source.Source and transformed into a reconcile.Request by an
// handler.EventHandler.
type GenericEvent struct {
	// Object is the object from the event
	Object client.Object
}
```

**Comment by alvaroaleman** [comment]
Hey, no, the only source that emits those is the `source.Channel`. The events a controller gets from the initial list are `Add`s.

**Comment by alvaroaleman** [comment]
I am going to close this, please feel free to re-open if the above didn't answer your question.
