### ISSUE TITLE
Fine grained collection

### ISSUE THREAD

**Issue by yigang01** [kubernetes-sigs/controller-runtime#2581]
Excuse me, does Metrics support collecting all resource object dimensions under each controller，I hope to collect all the current running records of the resource object

**Comment by yigang01** [comment]
Can you provide a detailed document explaining the meanings of each indicator in your metrics collection item? I think some values do not quite meet expectations

**Comment by yigang01** [comment]
controller_runtime_max_concurrent_reconciles and controller_runtime_active_workers These two indicators cannot be collected

**Comment by sbueringer** [comment]
What do you mean with they cannot be collected?

**Comment by troy0820** [comment]
@yigang01 Are you still having issues with this?

**Comment by sbueringer** [comment]
/close 

Lack of feedback
