### ISSUE TITLE
Core functionalities are not very clear to me =))

### ISSUE THREAD

**Issue by mohammadne** [kubernetes-sigs/controller-runtime#2584]
Hi, thanks for your great library

I wonder how can I use my custom `logger`, `health-probes`, etc without using the library . I think there are lot of responsibilities handled by this library and what I want is only the helper to easily define reconciliation loops and handle the rest of things with my own (my operator has a lot of other parts like a database and I think that I'm doing mess with current design and I can't extend my structure and design of the operator because I very depend to the structure of the project)

Also, I'd like to separate my controller-manager from my webhook server which seems impossible for me (they have different deployments)

I wonder to know how to achieve these goals.

thanks a lot

**Comment by lou-lan** [comment]
if you want to custom logger, you can ref the followe code, define `log` in your new controller `Options`.

```go
mgrOpts := manager.Options{
	Logger:                  log,
}
```

log it is a warrper `logr.Logger`.

Then, if you want to custom health check function, you can ref follower:

```
err = mgr.AddHealthzCheck("healthz", healthz.Ping)
if err != nil {
	return nil, fmt.Errorf("failed to AddHealthzCheck: %w", err)
}
```

you can replace `healthz.Ping` to you custom function.

**Comment by troy0820** [comment]
Is this still an issue @mohammadne ?

**Comment by troy0820** [comment]
Closing issue as explanation was provided.  If this continues to be an issue, please reopen.

/close
