### ISSUE TITLE
controller can't recover from missing CRD

### ISSUE THREAD

**Issue by liuyuan10** [kubernetes-sigs/controller-runtime#2589]
I'm running a controller with sigs.k8s.io/controller-runtime v0.15.1. I find that if CRDs are not applied when calling mgr.Start(), it won't recover by itself after applying the CRDs and continuously printing error:

```
if kind is a CRD, it should be installed before calling Start
```

To making things worse, /healthz passes that avoid a quick fix by liveness probe failure.

It doesn't happen when running with 0.13.

What's more strange is that I even run `Manager.GetRESTMapper().RESTMapping` in a loop before continue to run mgr.Start() but it doesn't help so the claim `it should be installed before calling Start` seems fake.

After about two mins, the controller restarts itself due to `timed out waiting for cache to be synced` and things start to work after that.

note: we are using Options.NewCache to filter on those CRDs.

**Comment by alvaroaleman** [comment]
> timed out waiting for cache to be synced

This timeout was delibaretely added, because before that, it would just silently not work. You can adjust this timeout to a very high value if that is what you want.

**Comment by liuyuan10** [comment]
> ibaretely added, because before that, it would just silently not work. You can adjust this timeout to a very high value if that is what you want.

that's not what I want. I want to find out a way for manager to recover quickly after CRD is applied instead of waiting for 2mins.

**Comment by alvaroaleman** [comment]
I would expect that to work but its definitely something we do not test. Feel free to debug and file a fix.

**Comment by damdo** [comment]
I'm hitting this issue too now.

In my case we have a manager that has multiple controllers.
One controller is responsible for installing CRDs
While another controller sets up a watch to a resource that is belonging to one of the CRDs that the other controller installs.

As such I'm seeing :
```
if kind is a CRD, it should be installed before calling Start
```
which is expected.

What is not expected is that once the CRD gets installed (by the first controller), the manager keeps retrying without finding it, and it eventually fails starting with `timed out waiting for cache to be synced`, in my case causing the operator to non-zero exit.


Would we be able to reopen this?
@vincepri @sbueringer

Thanks!

**Comment by alvaroaleman** [comment]
What controller-runtime version is this? The caches restmapper should reload the mapping

**Comment by damdo** [comment]
@alvaroaleman  sigs.k8s.io/controller-runtime v0.17.4

**Comment by sbueringer** [comment]
Hm works for me. It might depend on some details of which apiGroups / CRs exist and what exactly is added later

**Comment by JoelSpeed** [comment]
It may also be useful to test if you use a dynamic rest mapper directly, whether the issue goes away. That would let us prove that this is an issue with the caching in our discovery rest mapper implementation.

This would mean setting the manager `Options.MapperProvider` to something custom to return a `restmapper.NewDiscoveryRESTMapper` to leverage the upstream restmapper without caching

**Comment by damdo** [comment]
> Can you try to create a minimal controller + CRDs to reproduce?

@sbueringer More than a year later me tried with a minimal reproducer against v0.23.0 😄 to repro [it](https://github.com/kubernetes-sigs/controller-runtime/issues/2589#issuecomment-2191811597) and I couldn't (c-r keeps checking for CRD to be present, throws errors every 10s, immediately picks up the CRD if applied before the `CacheSyncTimeout` expires).

So c-r is behaving as expected here, thanks!

**Comment by sbueringer** [comment]
Perfect! :)
