### ISSUE TITLE
Does controller-runtime support preloading resources when selecting a leader?

### ISSUE THREAD

**Issue by duanmengkk** [kubernetes-sigs/controller-runtime#2600]
The controller-manager stores a significant number of objects, and the overhead of fetching and deserializing these objects from the API server during each upgrade process is unavoidable. Restarting the controller-manager may take several minutes to complete the recovery process. My question is, how can we preload the required resources into memory before the controller-runtime selects the leader? Does controller-runtime support this space-time trade-off strategy?

**Comment by alvaroaleman** [comment]
No, this is currently not possible. Someone attempted it, but it didn't get to the point of being mergeable: https://github.com/kubernetes-sigs/controller-runtime/pull/2005

**Comment by duanmengkk** [comment]
> No, this is currently not possible. Someone attempted it, but it didn't get to the point of being mergeable: #2005

OK, do we have any progress or discussions about this plan? Our cluster scale has reached several hundred thousand nodes, so we want our controller-runtime's work replicas to switch within seconds in case of failures.

**Comment by alvaroaleman** [comment]
> Our cluster scale has reached several hundred thousand node

Right.

You won't get second range fail over one way or another because the old lease needs to expire first. But feel free to take a stab at it.

**Comment by duanmengkk** [comment]
> > Our cluster scale has reached several hundred thousand node
> 
> Right.
> 
> You won't get second range fail over one way or another because the old lease needs to expire first. But feel free to take a stab at it.

Yes, the lease renewal time in Kubernetes is generally configured for 15 seconds. This means that it takes at least 15 seconds to complete the controller-runtime replica switch. However, when the cluster size is very large, for example, when the number of pods in the cluster reaches 1 million, and a controller-runtime switch occurs, the list requests in the Informer's list-watch are paginated. Let's assume the page size is 500 (forgive me for not being sure about the specific value). Assuming each request takes 0.5 seconds, it would require 2000 list requests to complete the loading of the Informer. This would result in a start time of 16 minutes for controller-runtime, during which the entire operator based on controller-runtime would be unable to function. We encountered this issue in production, and I'm not sure if controller-runtime can currently address this problem. Can using the `LeaderelectionRunable` interface solve this issue? If needed, we are willing to contribute this feature. What are your thoughts on this?
