### ISSUE TITLE
Question: CRD not found when we delete it

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes-sigs/controller-runtime#261]
## Versions

k8s version used : 1.11
Go deps
```
[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name="github.com/openshift/client-go"
  branch="release-3.11"

[[override]]
  name="github.com/openshift/api"
  branch="release-3.11"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.4"

[[override]]
  name = "github.com/kubernetes-incubator/service-catalog"
  version = "=v0.1.30"
```

## Description

When a CRD is deleted using the command `kubectl delete cp --all`, then the `reconcile()` function which is called from the controller runtime

```
	// RunInformersAndControllers the syncHandler, passing it the namespace/Name string of the
	// resource to be synced.
	if result, err := c.Do.Reconcile(req); err != nil {
```

is not not able to find the the component CRD `r.client.Get(context.TODO(), request.NamespacedName, component)` as it has been deleted

```
func (r *ReconcileComponent) Reconcile(request reconcile.Request) (reconcile.Result, error) {
	operation := ""
	// Fetch the AppService instance
	component := &v1alpha1.Component{}
	err := r.client.Get(context.TODO(), request.NamespacedName, component)
	if err != nil { // ERROR IS REPORTED HERE
		if errors.IsNotFound(err) {
			// Component has been deleted like also its dependencies
			operation = "deleted"
		}
	}
```

Questions: 
- How can I be notify within the reconcile function that the CRD has been deleted ? 
- How can the reconcile function been called before the CRD is deleted ?

![screenshot 2018-12-19 13 01 31](https://user-images.githubusercontent.com/463790/50219116-72eec200-038e-11e9-870b-a9d3097a56d5.png)

**Comment by cmoulliard** [comment]
> `EventHandler`

How can I subscribe to such event to be notified ?

**Comment by cmoulliard** [comment]
Got it. Thanks. I have updated my code to add a `predicate` able to handle `delete event` and will see if that helps 

```
// add adds a new Controller to mgr with r as the reconcile.Reconciler
func add(mgr manager.Manager, r reconcile.Reconciler) error {
	// Create a new controller
	c, err := controller.New("component-controller", mgr, controller.Options{Reconciler: r})
	if err != nil {
		return err
	}

	// Create a source to watch Component events
	src := &source.Kind{Type: &v1alpha1.Component{}}

	// Create a handler for handling events from Components
	h := &handler.EnqueueRequestForObject{}

	pred := predicate.Funcs{
		DeleteFunc: func(e event.DeleteEvent) bool {
			return !e.DeleteStateUnknown
		},
	}

	// Watch for changes to primary resource AppService
	err = c.Watch(src, h, pred)
	if err != nil {
		return err
	}

	return nil
}
```

**Comment by cmoulliard** [comment]
I did a mistake in my code as I updated only the status and not the component to add  the finalizer

```
	log.Infof("#### Created %s CRD's service component", component.Name)
	component.Status.Phase = v1alpha1.PhaseServiceCreation
	svcFinalizerName := "service.component.k8s.io"
	if !ContainsString(component.ObjectMeta.Finalizers, svcFinalizerName) {
		component.ObjectMeta.Finalizers = append(component.ObjectMeta.Finalizers, svcFinalizerName)
	}

	// err := c.Update(context.TODO(), component)
	err := c.Status().Update(context.TODO(), component)
```

I will change my code.

**Comment by cmoulliard** [comment]
I have added a finalizer. 

According to my screenshot, I see nevertheless 2 problems

- Why do we get 2 components under the delete event -> see data ?
- Why is the GKV of each component empty ?

![screenshot 2018-12-19 14 55 55](https://user-images.githubusercontent.com/463790/50224595-93bf1380-039e-11e9-99f9-967878f6807d.png)

**Comment by DirectXMan12** [comment]
> Why do we get 2 components under the delete event -> see data ?

We expose the object meta and the full object as separate fields (which is occasionally useful).  Your IDE is probably just having a hard time displaying the struct, if I had to guess.

> Why is the GKV of each component empty

I think the GVK bug was fixed in a recent release -- we weren't populating it sometimes before.  Are you still seeing it with a copy from master?

**Comment by DirectXMan12** [comment]
no response, closing
