### ISSUE TITLE
Would a MR request reconcile.IsTerminalError(err error) bool accepted

### ISSUE THREAD

**Issue by zbindenren** [kubernetes-sigs/controller-runtime#2616]
I have currently the usecase where I need to check if the returned error is a terminal error. Currently this can only be done by parsing the error string. There exist two possible solutions to check if the error is terminal:

1. Make  `terminalError` public
2. Create a helper func  `reconcile.IsTerminalError(err error) bool`

I would prefer the second solution. Would A MR accepted?

**Comment by troy0820** [comment]
Could you do something like this? I know this is a contrived example but I believe this will fit your use case.  

```golang
It("should allow to test the existence of a terminal error", func() {
  // define terminal error 
  err := reconcile.TerminalError(fmt.Errorf("oops"))
  Expect(err.Error()).To(ContainsSubstring("terminal error: ")
```

**Comment by zbindenren** [comment]
Actually it is possible to check for a terminal error:

```go
// IsTerminalError is true when err is a reconcile terminal error.
func IsTerminalError(err error) bool {
	return errors.Is(err, reconcile.TerminalError(nil))
}
```

So this MR is probably not necessary.

**Comment by troy0820** [comment]
Closing as PR is not necessary to check for terminal error.  If this is still an issue, please reopen.

/close
