### ISSUE TITLE
cannot set syncperiod for CRs and cache independently

### ISSUE THREAD

**Issue by ggaurav10** [kubernetes-sigs/controller-runtime#2620]
In version 0.15.0, the `manager.Options.SyncPeriod` has been deprecated in favor of `manager.Options.Cache.SyncPeriod`. The `cache.Options.Resync` has been effectively removed. Before this release it was possible to set different sync periods for the watched CRs and the cache. The earlier `syncPeriod` insured against these as mentioned in the comments:
![image](https://github.com/kubernetes-sigs/controller-runtime/assets/31065672/26bdfca0-acdc-4311-8e78-0c3792a6326f)

If we still want to insure against these, do we need to shorten the cache sync period now? would it have larger effect on the apiserver load? If yes, should we introduce cache resync again?

**Comment by sbueringer** [comment]
> would it have larger effect on the apiserver load?

I think this depends on what you do in your Reconcile func. The sync itself does not execute a List call against the APIserver (it just enqueues objects that are stored locally)

**Comment by ggaurav10** [comment]
> > Before this release it was possible to set different sync periods for the watched CRs and the cache.
> 
> Can you please give an example what exactly you did with CR v0.15?

we set the `syncPeriod` to 2 minutes and leave `cache.Resync` to default (10 hours).
