### ISSUE TITLE
DefaultNamespaces Cache Option doesn't allow All Namespaces for List

### ISSUE THREAD

**Issue by manno** [kubernetes-sigs/controller-runtime#2628]
I'm trying to l[imit the controller to watch config maps only in one namespace](https://github.com/rancher/fleet/pull/2033/commits/42c7e7fcf7367f196b39f9d3451e44616d0f5177), while watching other resources in all namespaces. Mainly for performance reasons, I don't want the controller to trigger for any config map event in the cluster.

The [cache design document](https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/cache_options.md) describes the config as ` DefaultNamespaces map[string]*Config`, while the code implements `DefaultNamespaces map[string]Config`. Since all options are nil-able I guess that's not an issue.

From the [cache tests](https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.16/pkg/cache/cache_test.go#L1801-L1808) I'd expect this to allow list and get in all namespaces:

```
Cache: cache.Options{
	DefaultNamespaces: map[string]cache.Config{cache.AllNamespaces: {}},
},
```

However, it results in `unable to list: test-7af124d because of unknown namespace for the cache`. 
I think that's because the`List` func in multi cache is missing the special handling, that was added to `Get` func: 

```
diff --git a/pkg/cache/multi_namespace_cache.go b/pkg/cache/multi_namespace_cache.go
index 87c31a7c..8e58b0c0 100644
--- a/pkg/cache/multi_namespace_cache.go
+++ b/pkg/cache/multi_namespace_cache.go
@@ -237,6 +237,9 @@ func (c *multiNamespaceCache) List(ctx context.Context, list client.ObjectList,
        if listOpts.Namespace != corev1.NamespaceAll {
                cache, ok := c.namespaceToCache[listOpts.Namespace]
                if !ok {
+                       if global, hasGlobal := c.namespaceToCache[metav1.NamespaceAll]; hasGlobal {
+                               return global.List(ctx, list, opts...)
+                       }
                        return fmt.Errorf("unable to list: %v because of unknown namespace for the cache", listOpts.Namespace)
                }
                return cache.List(ctx, list, opts...)
```

If I understand the consequences of cache options correctly, they do limit `Watch`, but also affect the cached client. I need another client, e.g. APIReader, to retrieve configmaps in other namespaces.

**Comment by alvaroaleman** [comment]
So you are limiting the watch for configmaps to one namespace using `ByObject` and then use `DefaultNamespaces` to wach everything else in all namespaces?

The `DefaultNamespaces` option does nothing for a type that has the `Namespaces` setting set. To quote from the godocs:  https://github.com/kubernetes-sigs/controller-runtime/blob/1b80b9629af8ec55ae200e2c649a9603533eed20/pkg/cache/cache.go#L233-L234

Also, the default is to cache all namespaces without further selection logic, so putting `cache.AllNamespaces: {}` into `DefaultNamespaces` does nothing either.

And yeah, the client reads from the cache by default, hence if you limit the cache to a given namespace, you can't use the default client to read from a different namespace.

Does this answer your question? Do you think the godocs are unclear here?

**Comment by manno** [comment]
> So you are limiting the watch for configmaps to one namespace using `ByObject` and then use `DefaultNamespaces` to wach everything else in all namespaces.

Yes, that was my intention, as I expect configmaps to change a lot, but I'm only interested in changes to one specific config map (the controllers "config" file).

> The `DefaultNamespaces` option does nothing for a type that has the `Namespaces` setting set. To quote from the godocs:
> 
> https://github.com/kubernetes-sigs/controller-runtime/blob/1b80b9629af8ec55ae200e2c649a9603533eed20/pkg/cache/cache.go#L233-L234

I see now, that https://github.com/kubernetes-sigs/controller-runtime/blob/1b80b9629af8ec55ae200e2c649a9603533eed20/pkg/cache/cache.go#L239-L242 only refers to `AllNamespaces/NamespaceAll` in `ByObject`, like  [in this test](https://github.com/kubernetes-sigs/controller-runtime/blob/release-0.16/pkg/cache/cache_test.go#L1833-L1845).

However, the DefaultNamespace option suggests it's possible to use both together, however that only applies if the  `ByNamespace.Namespaces` map is nil? Not just an entry in that map?

That still leaves me confused about this godoc:

https://github.com/kubernetes-sigs/controller-runtime/blob/1b80b9629af8ec55ae200e2c649a9603533eed20/pkg/cache/cache.go#L182-L189

I read this and thought, it would apply `DefaultNamespace` to namespaces not listed in `ByObject.Namespaces`.

I'm pretty sure it works for `Get`, because of https://github.com/kubernetes-sigs/controller-runtime/pull/2539/files, but not for `List`: https://github.com/rancher/fleet/pull/2033/commits/a42f11a5ba06a8bfebe18d9925b8ca67934df632#diff-441906b5a1987de7cd7b6bb6ac66908c1aaa84a318fd6b68ed69466f5d304793R114-R115

**Comment by MuneebAijaz** [comment]
hi @manno did you find any solution for this? i am facing the same issue. Basically this:

> So you are limiting the watch for configmaps to one namespace using ByObject and then use DefaultNamespaces to wach everything else in all namespaces?
