### ISSUE TITLE
fake client: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by lanyao-travel** [kubernetes-sigs/controller-runtime#2634]
Problem Description

I encountered a fatal error indicating a concurrent map read and map write while using the fake client package. Here is the stack trace of the error:

fatal error: concurrent map read and map write

goroutine 85 [running]:
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc000254230, {0x1876b10?, 0xc000680c00})
        /home/goproject/pkg/mod/k8s.io/apimachinery@v0.24.2/pkg/runtime/scheme.go:267 +0xf0
sigs.k8s.io/controller-runtime/pkg/client/apiutil.GVKForObject({0x1876b10?, 0xc000680c00}, 0x0?)
        /home/goproject/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/client/apiutil/apimachinery.go:98 +0x21c
sigs.k8s.io/controller-runtime/pkg/client/fake.getGVRFromObject({0x1876b10?, 0xc000680c00?}, 0x2?)
        /home/goproject/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/client/fake/client.go:659 +0x53
sigs.k8s.io/controller-runtime/pkg/client/fake.(*fakeClient).Get(0xc00049bb40, {0x7f4fca4bbb28?, 0x30?}, {{0xc00023a2b8?, 0xc000580000?}, {0xc00071e2e8?, 0xc0005d3640?}}, {0x1899430?, 0xc000680c00})
        /home/goproject/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.0/pkg/client/fake/client.go:333 +0xa5

**Comment by nathanperkins** [comment]
We had a similar issue with a data race in our code. We found the root cause using the [golang data race detector](https://go.dev/doc/articles/race_detector). Our issue was caused by a reconciler watch predicate that was modifying cached objects.

Context: #2391
