### ISSUE TITLE
Proposal: Naming consistency for leader election lock options

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/controller-runtime#2636]
This is probably a very minor naming suggestion but when I first started out using controller-runtime, the `LeaderElectionNamespace` option's identifier confused me a bit as to what it does and made me look under the covers to see how it is used.

I think clarifying this as follows would address the problem:

```diff
@@ -176,13 +176,13 @@ type Options struct {
 	// act on the same resources concurrently.
 	LeaderElectionResourceLock string
 
-	// LeaderElectionNamespace determines the namespace in which the leader
+	// LeaderElectionLockNamespace determines the namespace in which the leader
-	// election resource will be created.
+	// election lock resource will be created.
-	LeaderElectionNamespace string
+	LeaderElectionLockNamespace string
 
-	// LeaderElectionID determines the name of the resource that leader election
+	// LeaderElectionLockID determines the name of the resource that leader election
 	// will use for holding the leader lock.
-	LeaderElectionID string
+	LeaderElectionLockID string
 
 	// LeaderElectionConfig can be specified to override the default configuration
 	// that is used to build the leader election client.
```

If we go through with this, I think changing `LeaderElectionLockID` → `LeaderElectionLockName` would  be quite useful as well (since ID is not the Kubernetes term for unique resource names).

I understand these names have been there since the inception, but since I observed this repo regularly changes Options structs (and this is particularly not a troublesome migration), I'm proposing this. Thoughts?

/kind feature

**Comment by troy0820** [comment]
Would we target this for v0.17 or v0.18?  

Naming would provide clarity if that's the intent and not change any functionality.  I agree that being concise may help future users around the unclear options are defined.  

/kind feature

**Comment by ahmetb** [comment]
This is a breaking change so we'd probably target the next minor version?
Since the direction sounds good, following up with a patch: #2637.

**Comment by troy0820** [comment]
Should this be closed because of the comments in the PR? 

Are we closing the PR? 

@ahmetb @alvaroaleman

**Comment by ahmetb** [comment]
Yeah let's close this. Benefits are minimal.
/close
