### ISSUE TITLE
Remove deprecated webhook interfaces

### ISSUE THREAD

**Issue by nathanperkins** [kubernetes-sigs/controller-runtime#2641]
Context: #2596

After giving projects a few versions to migrate, we should remove the webhook.Validator and webhook.Defaulter interfaces to prevent this issue from happening.

**Comment by nathanperkins** [comment]
cc: @alvaroaleman

**Comment by troy0820** [comment]
/kind support 

@nathanperkins This will probably have to be a couple of minor releases before removal to prevent churn?  Also, Kubebuilder scaffold will probably have to implement the webhook generation to not include this as well.

**Comment by sbueringer** [comment]
cc @camilamacedo86 for awareness

**Comment by nathanperkins** [comment]
>This will probably have to be a couple of minor releases before removal to prevent churn?

Yeah, do you have milestone tracking so that it can be added to a future version? We might want to update the deprecation message to say when it will be removed as well so that users know when they will need to remove it.

**Comment by nathanperkins** [comment]
>Also, Kubebuilder scaffold will probably have to implement the webhook generation to not include this as well.

I asked them to look into it here:

https://github.com/kubernetes-sigs/kubebuilder/issues/3721

**Comment by troy0820** [comment]
> Yeah, do you have milestone tracking so that it can be added to a future version? We might want to update the deprecation message to say when it will be removed as well so that users know when they will need to remove it.

I do not, but if we announce the planned deprecation for this in v0.17.0 and deprecate it in v0.18.0 and then remove it in v0.19.0, it'll give a little run way to be planned around k8s releases.  Since we are on 1.29 now, that'll also give kubebuilder a chance to implement their strategy for this around their release schedule as well. 

We probably should mark this as part of the v0.17.0 milestone? @sbueringer

**Comment by nathanperkins** [comment]
>I do not, but if we announce the planned deprecation for this in v0.17.0 and deprecate it in v0.18.0 and then remove it in v0.19.0, it'll give a little run way to be planned around k8s releases. Since we are on 1.29 now, that'll also give kubebuilder a chance to implement their strategy for this around their release schedule as well.

@alvaroaleman already added the deprecation notice for next version in #2596. The deprecation notice is just to encourage shifting new usage and migration to the other interface so it probably doesn't need to wait for an entire version to be added.

So maybe we can announce and deprecate in 0.17 and then remove in 0.19?

**Comment by alvaroaleman** [comment]
yeah the deprecation will definitely be in the next version, the removal we will see, 0.19 sounds reasonable I guess

**Comment by sbueringer** [comment]
I created a v0.19.x milestone and added it there *for now*. Let's see what sort of feedback / pushback we get from the deprecation.

**Comment by sbueringer** [comment]
We're planning to merge this for 0.20, https://github.com/kubernetes-sigs/controller-runtime/pull/2877#issuecomment-2274993780

**Comment by camilamacedo86** [comment]
**Kubebuilder scaffold will be impacted by.**
The new interfaces are not scaffolded used by it yet.

See that we have an open pr for it but the implamentation does not seems to be accurate: https://github.com/kubernetes-sigs/kubebuilder/pull/3723/files

Help to move forward is more than welcome.

**Comment by sbueringer** [comment]
@camilamacedo86 Responded on the thread there. Let me know if you have any specific questions that I can help with (I don't have time to impelment the change in kubebuilder though).

**Comment by sbueringer** [comment]
Not sure I follow for the kubebuilder changes to be honest. But the situation in controller-runtime seems clear to me. We're going to drop Defaulter/Validator entirely with CR v0.20.0

**Comment by camilamacedo86** [comment]
Hi @troy0820,

First,

We cannot change the Kubebuilder layout without careful consideration. We have a stable layout, and breaking changes would require a new plugin version unless we can ensure that these changes do not affect pre-existing projects and maintain backward compatibility. You can find more information about this in the [Kubebuilder plugin versioning documentation](https://kubebuilder.io/plugins/plugins-versioning).

**The effort in Kubebuilder is divided into two steps:**

1. **Replace the deprecated interfaces with the new ones**  
   The key here is to ensure that we properly scaffold the Custom Interfaces and that they are implemented correctly. You can see more details in this [pull request](https://github.com/kubernetes-sigs/kubebuilder/pull/4060).

2. **Discuss layout changes**  
   After completing step 1, we can move on to discuss potential layout changes. For that discussion, let's use this [issue thread](https://github.com/kubernetes-sigs/kubebuilder/issues/4062).

_(Maybe moving them to `internal`, similar to where we keep the controllers.)_

Webhooks are implemented for specific API versions, so before considering moving them to an `internal` directory within the APIs, we need to evaluate scenarios where:

- a) Is it a good practice to import one project into another and have **Operator A** with `controller-runtime` version **N** and **Operator B** importing the APIs from **A** with `controller-runtime` version **N+1**?
- b) Should nobody be encouraged to import the webhooks, as is the case with controllers, or is that valid only for specific scenarios?
- c) What approach do we want to encourage people to adopt?

More info: https://kubernetes.slack.com/archives/C02MRBMN00Z/p1723373582440229
