### ISSUE TITLE
Support startup probes

### ISSUE THREAD

**Issue by ramperher** [kubernetes-sigs/controller-runtime#2644]
Hi all! I was working in the update of some operators I'm building with [operator-sdk](https://github.com/operator-framework/operator-sdk), which is consuming from this project, and I was able to define liveness and readiness probes for the pods, feature already supported based on https://github.com/kubernetes-sigs/controller-runtime/issues/297.

However, I also wanted to introduce startup probes, which are also documented in [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/), but there's no reference in operator-sdk project for that. I evaluated the code to try to implement that, but then I discovered controller-runtime seems not to have support for that probe yet.

I would like to ask if it's feasible to introduce this feature in the controller-runtime, probably following the same work it was done [here](https://github.com/kubernetes-sigs/controller-runtime/pull/419). I can work on that if you agree on that. Thanks!

**Comment by ramperher** [comment]
> What's the underlying use case we're trying to solve?

Hi @vincepri, currently, the use case where we want to introduce this feature is a dummy workload, called [example-cnf](https://github.com/openshift-kni/example-cnf), that our team is maintaining to define a well-developed CNF, according to [CNF best practices](https://github.com/test-network-function/cnf-best-practices-guide). In that guide, which is eventually taken as reference for [Red Hat CNF Certification](https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.72/html/red_hat_software_certification_workflow_guide/con_cnf-certification_openshift-sw-cert-workflow-submitting-your-helm-chart-for-certification), there's a specific section for _Liveness, readiness and startup probes_, referencing to this [unit test](https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#lifecycle-startup-probe) that is the one used to evaluate if a CNF has a startup probe defined.

So, as a summary, startup probes are needed then for passing one of the tests of this certification workflow without any issue, and currently, the operators built with operator-sdk (which is consuming from this repo) don't have this feature.

**Comment by troy0820** [comment]
This seems to be on the pod of the workload and not the underlying controller runtime components. 

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ shows how to do this on workloads along with liveness/readiness probes.

**Comment by ramperher** [comment]
> This seems to be on the pod of the workload and not the underlying controller runtime components.
> 
> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ shows how to do this on workloads along with liveness/readiness probes.

Hi @troy0820 , thanks for your comments! I also took a look to these docs as a reference, and in [this example](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes), yes, the startupProbe is using the same endpoint as livenessProbe, but it's because it's using this [code](https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/liveness/server.go) as example, and this webserver only implements `/healthz` endpoint for the purpose of the tests.

Of course, this depends on the pod of the workload, but the problem that I tried to expose here is that, in operator-sdk, if you check the code (e.g. [this one](https://github.com/operator-framework/operator-sdk/blob/master/internal/cmd/helm-operator/run/cmd.go#L177-L184)), it uses the `AddHealthzCheck` and `AddReadyzCheck` methods from [here](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/manager.go#L70-L74) in this project, and I was wondering if it's possible to also add the logic to support the startup probe health check, instead of reusing the ones from liveness and/or readiness. The pods created by operator-sdk-realted operators rely on the controller-runtime library, in the end, that's why I was asking for this. Don't know if it's clearer now.

**Comment by alvaroaleman** [comment]
I don't understand what the endpoint that would serve the startup probe would do differently from the normal healthz one and a dummy workload that should pass a certification doesn't seem a particularly convincing use-case. You can point the startupProbe at the healthz endpoint.

**Comment by ramperher** [comment]
> I don't understand what the endpoint that would serve the startup probe would do differently from the normal healthz one and a dummy workload that should pass a certification doesn't seem a particularly convincing use-case. You can point the startupProbe at the healthz endpoint.

It's just to have a different endpoint per probe. My assumption is that each probe offered by Kubernetes (liveness, readiness and startup) has a different meaning, so they should be covered by a different endpoint. If pointing the startup probe to the healthz endpoint, for me it's more a workaround to make the startup probe to work, rather than offering a really different endpoint for it, so that the startup probe would offer a different functionality.

However, based on k8s documentation, it's true that the startup probe is set to the liveness probe endpoint, so they're relying on the healthz endpoint at the end. As I said, I don't think it's a good practice if we think on the meaning of each probe, but if you don't think this would be useful, feel free to close the issue.

**Comment by ramperher** [comment]
Hi team, following @vincepri 's advices offline, I've decided to create a PR to show you how this feature would look like, you have it here: https://github.com/kubernetes-sigs/controller-runtime/pull/2669

**Comment by ramperher** [comment]
PR was finally closed, so I'll close this issue as won't fix.
