### ISSUE TITLE
proper versioning for setup-envtest

### ISSUE THREAD

**Issue by lukas016** [kubernetes-sigs/controller-runtime#2646]
Hi,

we have little problem with kubebuilder which using go install for installation of setup-envtest in latest version.
Using latest version creates unexpected problems with synchronization between developers.

It is possible little optimize and use branch name for installation the same minor version, but if we want to use really the same version, it isn't possible.

Main problem is with go install which requires own tag for every submodule.

```bash
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.16.3
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.16.3: module sigs.k8s.io/controller-runtime@v0.16.3 found, but does not contain package sigs.k8s.io/controller-runtime/tools/setup-envtest
```

Is possible start doing proper version for multimodule repository where tag contains path to submodule too?
Ideally if you create release v0.16.4, you will create tag tools/setup-envtest/v0.16.4 too.

```bash
go install github.com/lukas016/controller-runtime/tools/setup-envtest@tools/setup-envtest/v0.16.3
go: finding module for package sigs.k8s.io/controller-runtime/tools/setup-envtest/remote
go: finding module for package sigs.k8s.io/controller-runtime/tools/setup-envtest/workflows
...
```

**Comment by troy0820** [comment]
There is a work around for this as main isn't versioned along with tools/setupenv-tools. 
https://github.com/kubernetes-sigs/controller-runtime/issues/1670#issuecomment-1010602287 

I'm not sure the impact of now bundling the new tag you request for setup-envtest to coincide with the controller-runtime's release process.  I'm not aware of anything needing to change which why this needs to be hard to coordinate this with the current release process.

**Comment by lukas016** [comment]
@troy0820 can i ask you why it isn't store in separate repository? I checked https://github.com/kubernetes-sigs/controller-runtime/blob/main/tools/setup-envtest/go.sum and i don't see any dependencies to controller-runtime library. It can be easy manage this tool in separate repo and we can follow standard versioning for golang tools.

**Comment by lukas016** [comment]
@vincepri can ask you why setup-env is part of this repo and it doesn't have own repo? thx

**Comment by lukas016** [comment]
@alvaroaleman can we discuss proper versioning of setup-env with separate tags for keep compatibility with go install or maybe other options?

**Comment by Yesphet** [comment]
I've encountered the same issue, the method mentioned in this issue regarding tags is very simple and elegant. By synchronously creating the 'tools/setup-envtest/vX.Y.Z' tag, one can easily install it using `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@vX.Y.Z`
Before such tags are created, a workaround can be utilized via `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@BRANCH`. For instance `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.15`

**Comment by sbueringer** [comment]
Hey folks,
we are currently experimenting a bit on setup-envtest because the envtest binaries are today hosted on the Google-owned kubebuilder repository.

Going forward we will start hosting the envtest binaries on controller-tools releases. We currently also plan to move setup-envtest to controller-tools as it fits better there. As part of that we will build & publish setup-envtest binaries on controller-tools releases in the future. This should also give proper versioning.

**Comment by sbueringer** [comment]
@lukas016 There are no plans to break go install (probably just has to be run against controller-tools instead of controller-runtime).

**Comment by sbueringer** [comment]
Potentially this issue will just get rid of the additional module: https://github.com/kubernetes-sigs/controller-runtime/issues/2790

Then setup-envtest can be automatically installed with the CR version and there would be no need to move it to the controller-tools repo.

**Comment by troy0820** [comment]
Not sure if this issue still relevant or not with the changes that went in or with the workaround in the comment that I mentioned.

**Comment by sbueringer** [comment]
I think still okay to keep it open for now. I think two things would enitrely solve it eventually
* getting rid of the separate module or
* attaching setup-envtest binaries to CR releases

the 2nd one is on my TODO list, just not much bandwidth atm

**Comment by sbueringer** [comment]
The second one is now implemented.

Quoting my comment from another issue
> Now starting with the v0.19 release setup-envtest binaries are available via release attachments (see e.g. https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.0)
> I would recommend using these binaries if:
> * a specific setup-envtest version is required
> * folks have trouble compiling the binary themselves
> https://github.com/kubernetes-sigs/controller-runtime/issues/2744#issuecomment-2290805873

/close
