### ISSUE TITLE
How to correctly use context arguments is unclear

### ISSUE THREAD

**Issue by coderanger** [kubernetes-sigs/controller-runtime#265]
Most of the examples use `context.TODO()` on each call into the client. Would be nice to have a better explanation of what this is for.

And someday it would be cool to add a `.Context` field on the `reconcile.Request` for controllers (and maybe something similar for webhooks, though that's harder), and have the controller machinery create a `context.Background()` at the start of a request so you can thread it down into calls to the client library and whatnot.

**Comment by sr** [comment]
I was wondering about this too, my understanding is the controller runtime doesn't enforce any timeout on reconciliation attempts, which could cause the entire controller to lock up:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go#L215

Doing something like this doesn't seem so bad:

```go
func (r *MyReconciler) Reconcile(req reconcile.Request) (reconcile.Result, error) {
	ctx := context.WithTimeout(context.Background(), r.timeout)

	instance := &api.MyCRD{}
	_ = r.Get(ctx, request.NamespacedName, instane)
	_ = r.someAPI.Call(ctx, &RPCRequest{})

	// ...
}
```

Though I could also see a new field on `controller.Option`, with a sane default:

```go
type Options struct {
	MaxConcurrentReconciles int
	ReconcilerTimeout time.Duration // default to 10 seconds?
	Reconciler reconcile.Reconciler
}
```

Then have the controller pass in a context as part of the request:

```go
func (c *Controller) processNextWorkItem() bool {
	if c.ReconcilerTimeout != time.Duration(0) {
		req = req.WithContext(context.WithTimeout(context.Background(), c.ReconcilerTimeout))
	}
	if result, err := c.Do.Reconcile(req); err != nil {
		// handle
	}
}
```

**Comment by DirectXMan12** [comment]
we can't actually *enforce* timeouts, but we can totally allow you to configure a timeout context builder that gets passed to all reconcile requests that you can pass to clients.  It won't help if you manually block yourself, but in the case of well-behaved clients it's probably a good idea.

**Comment by DirectXMan12** [comment]
since you might want contexts for other things, a `ContextBuilder` option (with a sane timeout-based helper and good defaults) is probably something we'll want eventually.

**Comment by seh** [comment]
I noticed today that [Webhooks get invoked with `context.Background`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/http.go#L87). It would be nice if we could inject a `context.Context` value that would be used as the starting context for each request, in order to attach things like a shared tracing configuration handle.

**Comment by seh** [comment]
> It would be nice if we could inject a `context.Context` value that would be used as the starting context for each request, in order to attach things like a shared tracing configuration handle.

Putting my money where my mouth is, see #549.

**Comment by DirectXMan12** [comment]
thanks, merged!

**Comment by vincepri** [comment]
/remove-lifecycle frozen

@coderanger Seems this issue can now be closed given that most functions and reconcilers accept a context starting from v0.7.x

**Comment by coderanger** [comment]
/close

Wow I had forgotten I wrote this :)
