### ISSUE TITLE
Incorrect interface assertions in example/mutatingwebhook.go

### ISSUE THREAD

**Issue by perryao** [kubernetes-sigs/controller-runtime#266]
I believe [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/example/mutatingwebhook.go#L67) and [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/example/mutatingwebhook.go#L77) need to be updated to assert `podAnnotator`'s conformance to `inject.Client` and `inject.Decoder`. 

`example/validatingWebhook.go` already does the interface assertions for `podValidator`. 

I can submit the PR you agree this needs done.

**Comment by DirectXMan12** [comment]
yep, please do update that.  Good catch :-)
