### ISSUE TITLE
Create a separate registry for work-queue metrics

### ISSUE THREAD

**Issue by sonamkshenoy** [kubernetes-sigs/controller-runtime#2670]
Hi all! 

We are using custom controllers to manage our custom resources, and wish to export the workqueue metrics to Prometheus.
This is done by using the [`workqueue.SetProvider()`](https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go#L262) provided by `kubernetes.io/client-go`. 
When we try to register our metrics using this function in our `init()`, this doesn't take effect, as the `init()` function [being used](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/metrics/workqueue.go#L90) in the `metrics` package of this repo seems to making the call to `SetProvider()` first.

We can make use of this registry that you provide. It however comes with a [whole lot](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/metrics/client_go_adapter.go) of other metrics which we do not wish to export, such as - leader election, latency, request size, response size and other client metrics. And since they're `internal` we aren't able to unregister them.

Wonder if we can either:
1. [The best option in my opinion] Create a separate registry for just workqueue metrics in this repo and not add the other metrics to it, so that we can use it in our project. We can then combine all those metrics along with the non-workqueue related ones in a separate registry, thus unaffecting the previous behaviour.
2. Not have the `init()` function altogether in the [`metrics.go`](https://github.com/kubernetes/client-go/blob/master/util/workqueue/metrics.go) file. Instead provide those functionalities as a separate function, so that we users can call it in our `init()`. This way, if we choose to, we can create our own metrics and call `SetProvider()` ourselves.
3. Any other option which might not have been covered above...
4. Or is there a way we can tackle this on our side without having to make any changes here?

I'm up for working on this issue.

**Comment by troy0820** [comment]
/kind support feature 

> [The best option in my opinion] Create a separate registry for just workqueue metrics in this repo and not add the other metrics to it, so that we can use it in our project. We can then combine all those metrics along with the non-workqueue related ones in a separate registry, thus unaffecting the previous behaviour.

I think this is a reasonable request.  Do you mean that the defined metrics can then be registered to this "new" registry and pick the metrics you want to export rather than having all in one?  Such as workqueue, etc?  

And allow the user to register the metrics they want to expose?

**Comment by sonamkshenoy** [comment]
Yep! 
Something like: https://github.com/kubernetes-sigs/controller-runtime/pull/2671

**Comment by alvaroaleman** [comment]
This issue is effectively a duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/2238, except that it assumes a solution. Lets keep the discussion for this in the other issue.
