### ISSUE TITLE
how can i get node info using client supported by manager

### ISSUE THREAD

**Issue by GeorgeGuo2018** [kubernetes-sigs/controller-runtime#270]
while using the Get function of client, function schema as follow:
Get(ctx context.Context, key ObjectKey, obj runtime.Object) error
，we should give a ObjectKey to the 2cd paramerer.
But if i want to get nodes info using this method, there is no namespace info of a certain node.
what can i do? does the package "sigs.k8s.io/controller-runtime/pkg/client" supports getting node info?

any reply would be appreciated.

**Comment by coderanger** [comment]
For non-namespace-scoped object types, the `Namespace` value is ignored. So something like `client.get(ctx.TODO(), types.NamespacedName{Name: "mynode"}, node)`

**Comment by GeorgeGuo2018** [comment]
it works, thx a lot.
