### ISSUE TITLE
Go Version Format is incorrect

### ISSUE THREAD

**Issue by pagrawal10** [kubernetes-sigs/controller-runtime#2741]
Getting this error 
```
go.mod:3: invalid go version '1.22.0': must match format 1.23
```
Go version used: 1.20.6

We should update the go.mod file to have `go 1.22` instead of `go 1.22.0`

**Comment by sbueringer** [comment]
No it's correct. Please see https://github.com/kubernetes-sigs/controller-runtime/issues/2720

Please either use go 1.22 if you want to use latest or pin to a release branch
