### ISSUE TITLE
Allow modifying context per `Reconcile(ctx context.Context, req ctrl.Request)` 

### ISSUE THREAD

**Issue by programmer04** [kubernetes-sigs/controller-runtime#2743]
There is [BaseContextFunc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#BaseContextFunc) that can be configured to provide Context values to Runnables managed by the Manager. When not specified Runnables will receive a new Background Context instead.

Let's imagine that some additional data has to be available in each `Reconcile(ctx context.Context, req ctrl.Request)` method. Passing it via context can be a solution. Implementation of the method can get it from `ctx` and make use of it. But `BaseContextFunc` is evaluated only once after a start, hence it can't be used for values that should be evaluated per `Reconcile` call and preserve its value during the whole single `Reconcile` execution. 

The proposition is to introduce `ReconcileContextFunc` which will be similar to already existing [BaseContextFunc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#BaseContextFunc), but it will be evaluated before every calling of `Reconcile(ctx context.Context, req ctrl.Request)` by a manager.

Such a feature will allow a static value (just evaluated before) available in the context of the whole `Reconcile` call. Such a thing resolves a consistency problem. Let's imagine that such value can change at any moment it is needed multiple times in `Reconcile`, by having evaluated it in context before the call it won't change. Actual use case for this feature ([currently achieved by workaround](https://github.com/Kong/gateway-operator/blob/eb54adebaf5bad1e15880c2cc96028165de44a28/controllers/dataplane/bluegreen_controller.go#L85-L302)).

**Comment by alvaroaleman** [comment]
You can achieve this by wrapping your reconciler, there is no need for a change in controller-runtime
