### ISSUE TITLE
Multi Cluster Example / Pattern  

### ISSUE THREAD

**Issue by Smithx10** [kubernetes-sigs/controller-runtime#2755]
I'm starting to write a controller that will need to span clusters,  and I am not sure if what was documented 4 years ago is still the way to move forward.  https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/move-cluster-specific-code-out-of-manager.md

I've read through: https://github.com/kubernetes-sigs/controller-runtime/issues/745

Is there an example / pattern people should use when writing a controller that spans more than 1 cluster?

**Comment by Danil-Grigorev** [comment]
Yes, this pattern still applies and is pretty simple to use - here is an [example for2 cluster setup](https://github.com/rancher/turtles/pull/136/files#diff-ae2b5bedb202b6d356db5151c725e79b85ffc0dd690ad816ed4e79fb7c2cb2e6R54-R70). You will only need to correctly use both clients and be conscious about that. However, at some point I’ve seen problems with integration tests using envtest, while deploying 2 clusters in parallel ([slack message](https://kubernetes.slack.com/archives/C02MRBMN00Z/p1695328971472149)). Still needed to be tested on latter versions, maybe it is no longer an issue.

**Comment by Smithx10** [comment]
I am trying to implement the following:   But this old code doesn't match up anymore...

Not sure how I am supposed to get the cache of other clusters so I can mirror CRDs created in other clusters etc. 
```
func NewSecretMirrorReconciler(mgr manager.Manager, mirrorCluster cluster.Cluster) error {
	return ctrl.NewControllerManagedBy(mgr).
		// Watch Secrets in the reference cluster
		For(&corev1.Secret{}).
		// Watch Secrets in the mirror cluster
		Watches(
			source.NewKindWithCache(&corev1.Secret{}, mirrorCluster.GetCache()),
			&handler.EnqueueRequestForObject{},
		).
		Complete(&secretMirrorReconciler{
			referenceClusterClient: mgr.GetClient(),
			mirrorClusterClient:    mirrorCluster.GetClient(),
		})
	}
}
````

I imagine something changed that I can't find .

**Comment by Smithx10** [comment]
Looks like this behavior changed in https://github.com/kubernetes-sigs/controller-runtime/commit/d6a053f8f0979d6f1528fe4d52b0d0f618352d77  .

**Comment by Smithx10** [comment]
Looks like after taking another look you can use "WatchesRawSource" to get cretae a source and pop them on Mgr.  

I was able to apply from the other cluster and see the Reconile loop get invoked.  

Is this the intention?

```
func (r *GuestbookReconciler) SetupWithManager(mgr ctrl.Manager, c1, c2 cluster.Cluster) error {

	c1src := source.Kind(c1.GetCache(), &webappv1.Guestbook{})
	c2src := source.Kind(c2.GetCache(), &webappv1.Guestbook{})

	return ctrl.NewControllerManagedBy(mgr).
		For(&webappv1.Guestbook{}).
		Watches(&webappv1.Guestbook{}, &handler.EnqueueRequestForObject{}).
		WatchesRawSource(c1src, &handler.EnqueueRequestForObject{}).
		WatchesRawSource(c2src, &handler.EnqueueRequestForObject{}).
		Complete(r)
}

```

**Comment by Smithx10** [comment]
While going through the design / testing and implementation I've come accross the following to solve the leader election for multi-cluster:

If we are running a control that is going to act upon multiple clusters, we can elect a leader to in 1 of the clusters to take actions.  The default settings in the manager package of controller-runtime doesn't support this but does support providing our own logic for handling it via  "LeaderElectionResourceLockInterface resourcelock.Interface"

https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/manager.go#L202

The following interface exposes which controller will be the leader.
```
type Interface interface {
      // Get returns the LeaderElectionRecord
      Get(ctx context.Context) (*LeaderElectionRecord, []byte, error)

      // Create attempts to create a LeaderElectionRecord
      Create(ctx context.Context, ler LeaderElectionRecord) error

      // Update will update and existing LeaderElectionRecord
      Update(ctx context.Context, ler LeaderElectionRecord) error

      // RecordEvent is used to record events
      RecordEvent(string)

      // Identity will return the locks Identity
      Identity() string

      // Describe is used to convert details on current resource lock
      // into a string
      Describe() string
}
```

**Comment by sbueringer** [comment]
Probably too much for what you need. But in Cluster API we create additional caches/clients per cluster that we want to communicate with. Maybe there's something useful for you in this code: https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/remote/cluster_cache_tracker.go

**Comment by Smithx10** [comment]
@sbueringer   Thanks,  some nice things in there.    Do you by chance know if there is a simple way to not dump when one of the cluster caches time out?  I saw you made a accessor which brought them in and out,  is that required or is there anything in the manager than helps with this?  My expectation is that cluster will come up eventually,  removing it would require a config change in my scenario.  

Will be experimenting with this more. 

I was testing with this and firewalling off the k8s api.   Still resulted in:

```
2024-04-09T19:06:57-04:00       ERROR   setup   problem running manager {"error": "failed to wait for guestbook caches to sync: timed out waiting for cache to be synced for Kind *v1.Guestbook"}
main.main
        /home/smith/projects/guestbook/cmd/main.go:233
runtime.main
        /usr/lib/go/src/runtime/proc.go:271
```


```
// SetupWithManager sets up the controller with the Manager.
func (r *GuestbookReconciler) SetupWithManager(mgr ctrl.Manager, clusters []cluster.Cluster) error {
	rp := true
	cb := ctrl.NewControllerManagedBy(mgr).
		For(&webappv1.Guestbook{}).
		Watches(&webappv1.Guestbook{}, &handler.EnqueueRequestForObject{}).
		WithOptions(controller.Options{
			RecoverPanic: &rp,
		})
```

**Comment by sbueringer** [comment]
> Do you by chance know if there is a simple way to not dump when one of the cluster caches time out?

No I don't know. We create a separate cache and client per cluster we communicate with. We don't use the "Cluster" struct.
