### ISSUE TITLE
Run tests via prow

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#276]
We should be running our test suite in prow instead of Travis, so the normal kube workflow commands work.

**Comment by alvaroaleman** [comment]
@DirectXMan12 Is this still desired or are you considering GitHub actions instead?

**Comment by DirectXMan12** [comment]
yeah, I'd still like to do this.  I'd love for GitHub actions to work out, but I expect there'll be issues around GitHub actions' interaction with forks during the beta period.  AIUI (can't test, actions seems to be borked for k-sigs ATM), this'll make actions unusable till they're on by default.

**Comment by DirectXMan12** [comment]
we need something better than travis in the mean time
