### ISSUE TITLE
Add a validation script to verify go.mod is in sync with k/k

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#2769]
xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2765#issuecomment-2048566997

Idea is to verify on PRs (pre-submit) that our go.mod file doesn't go out of sync with Kubernetes (with the k/k version we use). The goal is to avoid issues like this: https://github.com/kubernetes-sigs/controller-runtime/issues/2742 which can easily sneak in when we just merge dependabot PRs.

(we might want to consider exceptions for a few dependencies like ginkgo / gomega but that is TBD)

**Comment by alexandremahdhaoui** [comment]
@sbueringer I created a small tool to verify go.mod and added it to the `verify-modules` make target. To proceed with enabling this verification in PRs, should I create a new dedicated workflow? Or should I add the tool to  [kubernetes-sigs/kubebuilder-release-tools](https://github.com/kubernetes-sigs/kubebuilder-release-tools/tree/master/verify)

**Comment by sbueringer** [comment]
We already run make verify-modules as part of our test job (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/2774/pull-controller-runtime-test/1779757108166660096).

This should be fine
