### ISSUE TITLE
Allow to ignore globalPredicates for specific resources

### ISSUE THREAD

**Issue by johscheuer** [kubernetes-sigs/controller-runtime#2785]
In the current implementation of the controller-runtime builder the global predicates added with [WithEventFilter](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/builder/controller.go#L314-L328) will be added to all resources. There could be cases where the global predicates should be added to all resources except for one, e.g. when watching external managed resources like nodes. Right know the only solution is to remove the `WithEventFilter` and add the previous global predicates to the `For` and all `Owns` calls and then add the `Watches` with the dedicated predicate. I'm happy to help implement this feature if others think that would be a useful feature.

**Comment by alvaroaleman** [comment]
Being global is pretty much the purpose of a global predicate ;) Any suggestions as to how the API for this could look like?
