### ISSUE TITLE
Incorrect patch generated with jsonpatch

### ISSUE THREAD

**Issue by com6056** [kubernetes-sigs/controller-runtime#281]
I am encountering an issue when trying to inject things into pods with more than 1 container.

The ReplicaSet returns `Error creating: Internal error occurred: Internal error occurred: Unable to remove invalid index: 1`. I've narrowed it down to an issue with `jsonpatch`.

The issue is outlined here: https://github.com/mattbaird/jsonpatch/issues/7
This fork has the fixes: https://github.com/appscode/jsonpatch

As a note, in the fork `JsonPatchOperation` is now just `Operation`.

**Comment by mengqiy** [comment]
Thanks for pointing this out!
We are considering switching to `appscode/jsonpatch`.

> As a note, in the fork JsonPatchOperation is now just Operation.

This is a breaking change. We probably will switch to `appscode/jsonpatch` in v0.2.0 if we plan to introduce it as is.

**Comment by rajathagasthya** [comment]
@mengqiy (tangential) Just curious why https://github.com/evanphx/json-patch isn't used here. It's used in k/k.
