### ISSUE TITLE
StatusWriter doesn't support Get

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#282]
I want to write a test to verify that the status subresource works. Naively I'd expect to write something like this:

```go
// A
client.Status().Update(ctx, obj)
client.Get(ctx, key, fetched)
if !reflect.DeepEqual(obj, fetched) {
  t.Errorf("not equal")
}
```

This doesn't work because the response from `Status().Update()` updates the SelfLink to append `/status`, which is reasonable from an API perspective (we're operating on the Status subresource) but mildly surprising from a user perspective. It would be nice if I could do a Get on the status subresource instead:

```go
// B
client.Status().Update(ctx, obj)
client.Status().Get(ctx, key, fetched)
if !reflect.DeepEqual(obj, fetched) {
  t.Errorf("not equal")
}
```

Except I can't do that because `StatusWriter` doesn't support `Get`. I can do something like this:

```go
// C
client.Status().Update(ctx, obj)
client.Get(ctx, key, fetched)
obj.SetSelfLink(fetched.SelfLink)
if !reflect.DeepEqual(obj, fetched) {
  t.Errorf("not equal")
}
```

This also works:

```go
// D
statusobj := obj.DeepCopy()
client.Status().Update(ctx, statusobj)
client.Get(ctx, key, fetched)
if !reflect.DeepEqual(obj, fetched) {
  t.Errorf("not equal")
}
```

Neither C nor D are as nice as B imo. Can `StatusWriter` support `Get`?

/cc @droot

**Comment by coderanger** [comment]
This matches the actual Kubernetes API, `GET .../status` is not a valid request. Not sure what you would expect this to do?

**Comment by grantr** [comment]
@coderanger works for me:

```
$ curl http://127.0.0.1:8001/api/v1/namespaces/default/pods/busybox/status
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "busybox",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/busybox/status",
    "uid": "90da8589-fe6d-11e8-b779-42010a8a0196",
    "resourceVersion": "1720758",
    "creationTimestamp": "2018-12-13T00:25:16Z",
    "labels": {
      "run": "busybox"
    },
    "annotations": {
      "kubernetes.io/limit-ranger": "LimitRanger plugin set: cpu request for container busybox"
    }
  }
  ... includes entire spec and status of the pod
}
```

Also works for `.../scale` on a Deployment.

**Comment by coderanger** [comment]
That's exactly the same as `GET .../` though. Why make a separate API for it? The only value of the status subresource is 1) PUT to that endpoint will ignore non-status data and 2) PUT/POST elsewhere will ignore status data.

**Comment by grantr** [comment]
It's **almost** exactly the same. The difference is in the `SelfLink`:

```
"selfLink": "/api/v1/namespaces/default/pods/busybox/status"
```

Note also that this changed `SelfLink` value is present in the object "returned" by `Status().Update()`. Any object given to the StatusWriter will, after calling `Update()`, have a `SelfLink` pointing to their status subresource instead of the root resource. This is the root cause of the behavior described in the issue body and would be surprising for users expecting the SelfLink to be unchanged (it was surprising to me).

Maybe the proper fix is to have `StatusWriter` revert the change to SelfLink after making the subresource request?

**Comment by shawn-hurley** [comment]
Changing the self link or exposing a new method seems like the wrong thing to do just to get a `reflect.DeepEqual` working easily for a test IMO. 

Could you not just compare the `obj.Status`?

**Comment by grantr** [comment]
> Changing the self link or exposing a new method seems like the wrong thing to do

I agree, it seems wrong to change the self link. It's already happening though - the `Status().Update()` method changes the self link on an object given to it. That seems like the wrong thing to do too. :stuck_out_tongue:

We're pretending that the `PUT <resource>/status` response metadata is equal to the `PUT <resource>` response metadata, but it actually isn't. I don't see a way around this in the API though. Is there a shared interface (in Go) for the status field of an object, or just a field name convention?

> Could you not just compare the obj.Status?

Sure, and that's what I'll do for now. The test thing is less of a deal for me than silently changing the SelfLink value.
