### ISSUE TITLE
failed to install setup-envtest

### ISSUE THREAD

**Issue by wingyiu** [kubernetes-sigs/controller-runtime#2824]
go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest (in sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20240507051437-479b723944e3): go.mod:3: invalid go version '1.22.0': must match format 1.23

**Comment by sbueringer** [comment]
Please see:
* https://github.com/kubernetes-sigs/controller-runtime/issues/2795
* https://github.com/kubernetes-sigs/controller-runtime/issues/2720

You can either upgrade to Go 1.22 or pin setup-envtest to release-0.17
