### ISSUE TITLE
Reconcile is triggered after status update

### ISSUE THREAD

**Issue by beatrausch** [kubernetes-sigs/controller-runtime#2831]
Hi all,

we observed an interesting behavior that after an status update without any change leads to an reschedule of the resource, which triggers the reconcile loop again. 

Code that is executed in the reconcile loop:
```
func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := logging.FromContext(ctx)

	resource := r.newResource()
	if err := r.client.Get(ctx, req.NamespacedName, resource); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	logger.Infof("Reconcile ....")
	return ctrl.Result{RequeueAfter: time.Minute}, r.client.Status().Update(ctx, resource)
}
```
Output after the resoruce creation:

2024-05-15T15:18:43+02:00       INFO    Reconcile ....  {"controller": "stream", "reconcileID": "fad5bca2-9729-4799-b05c-80a2e9d929a8"}
2024-05-15T15:18:43+02:00       INFO    Reconcile ....  {"controller": "stream", "reconcileID": "521a821c-49fb-42fc-a07e-78f977a6f109"}

Why does it not trigger more than two times after object creation? If an update on the status leads to a new reconciling, we would expect an infinite loop without sleeping/delay. 

How could we ensure that the object is just once reconciled?

Used controller-runtime version:
sigs.k8s.io/controller-runtime v0.16.3

Thx, Regards

**Comment by alvaroaleman** [comment]
This is expected. The only way to avoid this is to have the status subresource enabled and use the `GenerationChangedPredicate`.

/kind support

**Comment by beatrausch** [comment]
Hi, 

thx for the fast feedback. 
Can you explain why it stops after the second reconciliation? What is the circuit breaker?

Regards

**Comment by beatrausch** [comment]
After some investigation it seems that the resource version does not change after the second reconciliation. which then stops to send updates to the controller. 

Can you confirm?

**Comment by sbueringer** [comment]
You get update events as long as your object changes. If it stops changing you won't get them anymore
(same for spec & status)

**Comment by roodymoody** [comment]
Open
