### ISSUE TITLE
Upgrade problem (v0.15.2->v0.17.3): configuring namespace

### ISSUE THREAD

**Issue by Svintooo** [kubernetes-sigs/controller-runtime#2833]
I inherited an unfamiliar code-base that broke when controller-runtime was upgraded from v0.15.2 to v0.17.3.
I think I fixed it, but I am asking for a second opinion. How I set the namespace seems unnecessary complicated.

### Questions

1. Should the below fix preserve the old functionality correctly?
2. Is this the intended way to set the namespace and metrics bind address?

### Code fix
The code that broke looked something like this:
```go
import (
  "k8s.io/apimachinery/pkg/runtime"
  ctrl "sigs.k8s.io/controller-runtime"
)

func managerOptions(scheme *runtime.Scheme, namespace string) ctrl.Options {
  return ctrl.Options{
    Scheme:                     scheme,
    Namespace:                  namespace, // unknown field Namespace in struct literal of type manager.Options
    LeaderElection:             true,
    LeaderElectionResourceLock: "leases",
    LeaderElectionID:           "a-string-of-some-kind",
    MetricsBindAddress:         "0" // unknown field MetricsBindAddress in struct literal of type manager.Options
  }
}
```

My fix:
```go
import (
  "k8s.io/apimachinery/pkg/runtime"
  ctrl "sigs.k8s.io/controller-runtime"
  "sigs.k8s.io/controller-runtime/pkg/cache" // NEW
  metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server" // NEW
)

func managerOptions(scheme *runtime.Scheme, namespace string) ctrl.Options {
  return ctrl.Options{
    Scheme: scheme,
    Cache: cache.Options{ // NEW
      DefaultNamespaces: map[string]cache.Config{ // NEW
        namespace: {}, // NEW
      }, // NEW
    }, // NEW
    LeaderElection:             true,
    LeaderElectionResourceLock: "leases",
    LeaderElectionID:           "a-string-of-some-kind",
    Metrics:                    metricsserver.Options{BindAddress: "0"}, // NEW
  }
}
```

### Extra

Nameserver fix was inspired by the following change in pkg/manager/example_test.go between v0.15.2 and v0.17.3:
https://github.com/kubernetes-sigs/controller-runtime/blob/36bb89936b37aca36ba4ad34760f4879db97dba2/pkg/manager/example_test.go#L64

https://github.com/kubernetes-sigs/controller-runtime/blob/c25fe2f5ca0f9e10d571f85da61c3d210d6345e7/pkg/manager/example_test.go#L64-L67

`Namespace` was removed in favor of `Cache: Cache.Options.Namespaces` in v0.16.0 in commit e92eadb0.
`Cache.Options.Namespaces` was changed to `Cache.Options.DefaultNamespaces` in v0.16.0 in commit 3e35cab1.
`MetricsBindAddress` was changed to `Metrics: metricsserver.Options.BindAddress` in v0.16.0 in commit e59161ee.

**Comment by sbueringer** [comment]
Yup, that's correct.
