### ISSUE TITLE
[issue] regarding horizontal scaling for operators

### ISSUE THREAD

**Issue by ragarwalll** [kubernetes-sigs/controller-runtime#2836]
when we deploy any operator, lets say I have scaled upto 2 replicas.
The watcher will basically watch the specified path/resources in both the replicas right?

If yes, this in turn means that it might happen that both "reconciles" would be called in both pod, right?
So, my question here is how do I manage efficiency for operators. In recent weeks, one of the operators I build is taking heavy traffic and I am looking for addressing this issue is the right way.

Can you please suggest how do I approach this issue in the best possible way?

**Comment by troy0820** [comment]
You can use leader election which can prevent this.

**Comment by troy0820** [comment]
/kind support 

Closing as the question was answered.  Feel free to reopen if this is unclear.

/close
