### ISSUE TITLE
MapObject.Object contains empty GroupVersionKind

### ISSUE THREAD

**Issue by liyinan926** [kubernetes-sigs/controller-runtime#284]
I noticed that `MapObject.Object` instances passed to a `handler.ToRequestsFunc` function contains empty `GroupVersionKind`. The code I have looks like the following:

```go
mapFn := handler.ToRequestsFunc(
	func(a handler.MapObject) []reconcile.Request {
		var requests []reconcile.Request
		apps := listApplications(mgr.GetClient(), a.Meta.GetNamespace())
		for _, app := range apps {
			ref := app.Spec.Selector.ObjectRef
			gvk := a.Object.GetObjectKind().GroupVersionKind()
			if gvk.Empty() {
				log.Printf("Empty GVK for object %s/%s", a.Meta.GetNamespace(), a.Meta.GetName())
				return requests
			}
			if ref != nil && ref.Name == a.Meta.GetName() && ref.Kind == gvk.Kind {
				requests = append(requests, reconcile.Request{
					NamespacedName: types.NamespacedName{
						Namespace: app.Namespace,
						Name:      app.Name,
					},
				})
			}
		}
		return requests
	})
``` 

The logs show multiple occurrences of `Empty GVK for object ...`.

**Comment by liyinan926** [comment]
Looks like https://github.com/kubernetes-sigs/controller-runtime/pull/212 might have solved the issue. Can anyone help confirm?

**Comment by DirectXMan12** [comment]
in general, you probably want to use the scheme to get the GVK of a type, but we're trying to clean up the places where we don't set a GVK.  It's pretty common throughout the code not to have a GVK set, because it's not actually needed most places in the client/apimachinery (which use Scheme instead).

**Comment by liyinan926** [comment]
@shawn-hurley I can do it.

**Comment by JoelSpeed** [comment]
/remove-lifecycle stale

PR #389 is open to fix this issue
