### ISSUE TITLE
Question: update status field

### ISSUE THREAD

**Issue by mohammadne** [kubernetes-sigs/controller-runtime#2850]
Hi, hope you are well.

I'm pretty new to controller-runtime and I want to know for updating the status field, do I have to call `client.Status().Update(context.Background(), &obj)` or calling the `client.Update(context.Background(), &obj)` will be enough?

I tried updating the status filed with both approaches, both are succeeds but the second one didn't affect the object and the status doesn't update. I want to ask is this behavior correct?

**Comment by troy0820** [comment]
/support 

Yes, this behavior is correct.  

The `client.Status().Update(....)` writer is the update that you need to update subresrouce Status items.  The other update, only updates the spec/metadata.
