### ISSUE TITLE
Add support for SSA into the fake client

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#2866]
Upstream fake clients started to support SSA in https://github.com/kubernetes/kubernetes/pull/125560, we should follow suit.

/kind feature

**Comment by sbueringer** [comment]
Nice!

Dedup with https://github.com/kubernetes-sigs/controller-runtime/issues/2341?

**Comment by alvaroaleman** [comment]
You are right, lets use the other one
