### ISSUE TITLE
Support onStart option in controller and webhook 

### ISSUE THREAD

**Issue by qingwave** [kubernetes-sigs/controller-runtime#2871]
**What expected?**
Add `OnStart` option in `controller.Options` and `webhook.Options`. User can customize start function, just likes follow
```golang
// pkg/controller/controller.go
type Options struct {
  OnStart func(ctx context.Context) error
}
```
**Why we need it?**
Sometime we need do some initialization during controller strating(record start date, do some init), but now we can only do the same action in `Reconcile` with `once.Do`, it's more better to support it in controller.Options and webhook.Options.

Furthermore, we can more hooks likes `PreStart, PostStart, PreStop`.

**Comment by vincepri** [comment]
Can these operations be done in a main.go file instead of controller runtime?

**Comment by qingwave** [comment]
> Can these operations be done in a main.go file instead of controller runtime?

Hi @vincepri , thanks for your quick reply.There are some misleading, these operations should do when **controller starting**(controller may has a leader select), that cannot do in the main.go(project starting). 

There are some operation examples from my side, record the controller start date, watch resources that without a eventhandler.

**Comment by vincepri** [comment]
If leader election is needed, a simple Runnable that returns true on NeedsLeaderElection should suffice

**Comment by sbueringer** [comment]
^^

/close
