### ISSUE TITLE
Start function of manager object not always returns error if it happens.

### ISSUE THREAD

**Issue by Alexseij** [kubernetes-sigs/controller-runtime#2873]
In my case error happened during initialization `l` object:
https://github.com/kubernetes-sigs/controller-runtime/blob/e28a8424d69df972355952277dba0e7f0d4263f2/pkg/manager/internal.go#L572-L603

Error contains this message:
`
leaseDuration must be greater than renewDeadline
`

After that error, function of manager object `Start` dont return it.

Because this code call here by function `startLeaderElection`:

https://github.com/kubernetes-sigs/controller-runtime/blob/e28a8424d69df972355952277dba0e7f0d4263f2/pkg/manager/internal.go#L432-L449

After this defers:
https://github.com/kubernetes-sigs/controller-runtime/blob/e28a8424d69df972355952277dba0e7f0d4263f2/pkg/manager/internal.go#L355-L371

And this defers call another defers one of which waiting for value in channel:
https://github.com/kubernetes-sigs/controller-runtime/blob/e28a8424d69df972355952277dba0e7f0d4263f2/pkg/manager/internal.go#L511-L521

But this channel is never being close because `close` function calls only when there is no error when `l` object initializing
https://github.com/kubernetes-sigs/controller-runtime/blob/e28a8424d69df972355952277dba0e7f0d4263f2/pkg/manager/internal.go#L601-L611

I fix this issue in my fork repository, if this issue will be accepted I can do pull request.

**Comment by alvaroaleman** [comment]
/kind bug
Please feel free to submit a fix
