### ISSUE TITLE
Watch resources by GroupVersionKind not only by object

### ISSUE THREAD

**Issue by vie-serendipity** [kubernetes-sigs/controller-runtime#2889]
**Background**
When I use `"sigs.k8s.io/controller-runtime/pkg/controller"`, controller currently seems to only watch objects like &Pod{}, &Node{}, but not groupversionkind.
**Enhancement Request**
I noticed that it actually gets GVK information from the object underneath. So is this feature possible, or is there any way I can currently watch using gvk?
**Version**
sigs.k8s.io/controller-runtime v0.18.4

**Comment by alvaroaleman** [comment]
Why do you want to pass a gvk to the watch rather than a concrete type?

**Comment by vie-serendipity** [comment]
Here is my scenario. I want to propagate resources to multiple clusters. So I have to watch every kind of resource, I use `discoveryClient.ServerPreferredResources` to fetch api resource list. And I didn't find a way to convert. In this way, I have to pass a gvk rather than a concrete type.
Is there a more elegant way to implement global resource watching?

**Comment by alvaroaleman** [comment]
You can use `unstructured.Unstrecuted{}` and configure it with any GVK of your choice

**Comment by vie-serendipity** [comment]
I got it, thanks.
