### ISSUE TITLE
Restmapper: Use aggregated discovery if available

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#2897]
We've built a lazy restmapper that only fetches mappings when needed to reduce the number of api calls made and thus speed things up. In the meantime, upstream built [aggregated discovery](https://github.com/kubernetes/enhancements/issues/3352) which allows to fetch all restmappings with a single api call.

We should update our restmapper to use `aggregated discovery` if available.

/kind feature

**Comment by sbueringer** [comment]
Sounds good!
