### ISSUE TITLE
Logging should be streamlined

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-runtime#291]
The current controller runtime offers a log package that includes a zap logger and lets users to bring their own logger by implementing https://github.com/go-logr/logr interfaces. Most of the other tools in the Kubernetes ecosystem use `klog` as the main logging point, which makes it hard to have a single output and logger given that klog doesn't expose any interface that implements logr interfaces. 

Some related issues in the community:
- https://github.com/kubernetes/klog/issues/22
- https://github.com/kubernetes/klog/issues/19
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/323
- https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/330

**Comment by DirectXMan12** [comment]
github.com/go-logr/glogr should be trivially adaptable to klog (it was originally written for glog).  We'll see how klog evolves, but getting that situation squared away is something I would definitely like to do.

**Comment by DirectXMan12** [comment]
kubernetes/klog#37 at least partially solves this problem with its klogr package.  The other half is being worked on it kubernetes/klog#20.
