### ISSUE TITLE
`pkg/manager/internal.go` - panic on log

### ISSUE THREAD

**Issue by bejaneps** [kubernetes-sigs/controller-runtime#2916]
Can someone address please below tiny bug ? It `panic`s otherwise.

https://github.com/kubernetes-sigs/controller-runtime/blob/v0.18.4/pkg/manager/internal.go#L190

```go
cm.GetLogger().Info("warn: metrics server is currently disabled, registering extra handler %q will be ignored", path)

// "path" key should be added
cm.GetLogger().Info("warn: metrics server is currently disabled, registering extra handler %q will be ignored", "path", path)
```

Panic:
```
panic: odd number of arguments passed as key-value pairs for logging
```

**Comment by bejaneps** [comment]
Oh I see it's already in `main` https://github.com/kubernetes-sigs/controller-runtime/commit/545b2b0d589893d5fa1dc84a6e607db4fadfb8d9

Will wait for next release then 🙇

**Comment by sbueringer** [comment]
Yup, thix was fixed in https://github.com/kubernetes-sigs/controller-runtime/pull/2874

I'll close the issue as there is nothing else todo (except waiting for the release)
