### ISSUE TITLE
When watching a resource in multiple namespaces, cluster-wide rbac is needed

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#2930]
Pretty much title, it should be enough to have access to the namespaces in use but it looks like we instead require cluster-wide list/watch rbac

**Comment by sbueringer** [comment]
Interesting. Would have expected that the multiNamespaceInformer thing creates informers per namespace

**Comment by alvaroaleman** [comment]
This was a configuration issue on our end, controller-runtime works correctly and doesn't require cluster-wide RBAC in this situation.
