### ISSUE TITLE
Cannot install @latest version v0.19.0 due to dependencies issues

### ISSUE THREAD

**Issue by github-daniel-stoian** [kubernetes-sigs/controller-runtime#2939]
When I'm trying to update to v0.19.0 I got a strange dependency issue:

`go install sigs.k8s.io/controller-runtime/pkg/ratelimiter@latest
go: sigs.k8s.io/controller-runtime@v0.19.0 requires go >= 1.22.0; switching to go1.22.6
go: sigs.k8s.io/controller-runtime/pkg/ratelimiter@latest: module sigs.k8s.io/controller-runtime@latest found (v0.19.0), but does not contain package sigs.k8s.io/controller-runtime/pkg/ratelimiter`

What could be the cause ?
Thank you.

**Comment by sbueringer** [comment]
Why are you trying to install the ratelimiter package? Wasn't `go install` only for binaries?

**Comment by github-daniel-stoian** [comment]
My bad, go get it's trowing the same error:

`go get sigs.k8s.io/controller-runtime/pkg/ratelimiter@latest
go: module sigs.k8s.io/controller-runtime@latest found (v0.19.0), but does not contain package sigs.k8s.io/controller-runtime/pkg/ratelimiter`

**Comment by troy0820** [comment]
> Did you at least tried to reproduce the issue ?

@github-daniel-stoian I would think the person submitting the issue would show the reproducer.

This package was removed in https://github.com/kubernetes-sigs/controller-runtime/pull/2799 this pr which was released in v0.19.  If there are dependencies that you are working with that rely on that, they cannot upgrade to v0.19.0 without settling that with the dependent package.  It seems that karpenter is still using that which means they cannot upgrade to v0.19.0 which will leave you stuck on the controller-runtime version they are using.

If you need to use v0.19.0 you may have to wait until karpenter moves to that with a new release or decouple your dependencies where you reliance on older versions doesn't conflict with your uplift of controller-runtime.

**Comment by github-daniel-stoian** [comment]
Ok. Thank you.
