### ISSUE TITLE
Ability to watch resources in a particular namespace in predicate when cache is watching all namespaces

### ISSUE THREAD

**Issue by MuneebAijaz** [kubernetes-sigs/controller-runtime#2940]
Hi, I have an operator which is watching multiple resources. 
One of the watched resources is `configmaps`. 
For the sake of example, let's assume the second one is `pods`.

This is how it looks like 

```
		For(&v1alpha1.RandomResource{}).
		Owns(&v1.ConfigMap{}, builder.OnlyMetadata).
		Owns(&v1.Pod{}).
		Complete(r)
```

Now, the cluster is huge and it has a lot of namespaces, 500+ with approx 10 ConfigMaps per Namespace. Few of the configmaps themselves are large in size, injecting multiple certs. 
But I only need to watch a single ConfigMap in one Namespace. At the same time, I need to watch Pods in multiple namespaces. 

Problem is, due to some reason cache is getting stuck on Get requests in the Reconciler. and its not throwing any error or recovering from that Get call. (I probably need to add a Error Handler Func for cache maybe, but I think it should throw the error by default). The code was stuck at the same place for weeks. 

Memory profiling of the stuck code shows that it has a very huge ConfigMap cache. 

I was wondering if there's a way in predicate/Owns where i can specify name/namespace of the configmap so that cache doesnt build up for the whole cluster for this resource. 
(I know it can be controlled on cache level by passing namespace but that would affect the other resources but I was wondering if i can fine tune that cache even further on resource level)

**Comment by joelanford** [comment]
The cache can be fine-tuned to control settings by object, by namespace, or a combination of object and namespace. See `cache.Options.ByObject` 

https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/cache#ByObject

**Comment by alvaroaleman** [comment]
Joes answer is the right one. I also want to clarify that a `Predicate` is always a client-side filter which means using it will never reduce memory usage. It could be used to filter out events though.

The reason that Predicates exist is that the cache must hold a superset of all objects any controller in the binary cares about.  If you had another controller that does something with all configmaps in the same binary, you would have to use a Predicate and filter there. Arbitrary predicates can be plumbed into the builder by doing e.G. 
```go
For/Owns/Watches(&MyType{}, WithPredicates(predicate.Funcs(func(o client.Object) bool {
    return o.GetName() = "the-one-cm-I-care-about"
})))
```

Hope that helps, will close the issue under the assumption that the question has been answered.

**Comment by kivikakk** [comment]
For anyone finding this by search like me, you might want to try something like this:

```go
Owns(&MyType{}, builder.WithPredicates(predicate.NewPredicateFuncs(func(o client.Object) bool {
    return o.Name() == "whatever"
})))
```

`Funcs` is a struct type, with one function for each of Create/Update/Delete/Generic; `NewPredicateFuncs` creates such a `Funcs` using the same filter function.
