### ISSUE TITLE
client.Status().Update() causes pod Metadata update

### ISSUE THREAD

**Issue by Simon-Dongnan** [kubernetes-sigs/controller-runtime#2941]
I use the v0.19.0 version, and when using client.Status.Update() to update the Status, the Metadata information is also updated, which does not seem to be as expected.

``` go
        client := mgr.GetClient()
	obj := &corev1.Pod{}
	err = client.Get(context.Background(), types.NamespacedName{
		Namespace: "default",
		Name:      "test-pod",
	}, obj)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println(obj.Labels)

	obj.Labels["test"] = "test"

	err = client.Status().Update(context.Background(), obj)

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	time.Sleep(5 * time.Second)

        obj2 := &corev1.Pod{}

	err = client.Get(context.Background(), types.NamespacedName{
		Namespace: "default",
		Name:      "test-pod",
	}, obj2)
	if err != nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println(obj2.Labels)
```

I tested with the above code and the following content was output. The metadata was indeed updated at the same time.

```
map[]
map[test:test]
```

**Comment by alvaroaleman** [comment]
We just use the status subresource and pass the object as body: https://github.com/kubernetes-sigs/controller-runtime/blob/076d14e52cdcc43c66b030db2dc19f0bf41e60cc/pkg/client/typed_client.go#L228-L244

This matches what upstream does in the generated client: https://github.com/kubernetes/kubernetes/blob/9d374b1cdeb8b6ef7d5307e7da08390fd3821a6f/staging/src/k8s.io/client-go/gentype/type.go#L253-L263

Looking at the pod rest code, it only resets spec and unsets deletion timestamp: https://github.com/kubernetes/kubernetes/blob/9d374b1cdeb8b6ef7d5307e7da08390fd3821a6f/pkg/registry/core/pod/strategy.go#L220-L229

The status update validation also validates that the metadata is valid, which seems to imply that this was somewhat deliberate: https://github.com/kubernetes/kubernetes/blob/9d374b1cdeb8b6ef7d5307e7da08390fd3821a6f/pkg/apis/core/validation/validation.go#L5344-L5346

Can you please open an issue in kubernetes/kubernetes? This behavior doesn't come from controller-runtime and looks somewhat deliberate. I do agree its surprising.
