### ISSUE TITLE
Can't wrap existing client with WithWatch()

### ISSUE THREAD

**Issue by 2uasimojo** [kubernetes-sigs/controller-runtime#2967]
In some cases, one can wrap already-extant `client.Client`s to confer extra functionality. For example:

```go
cWithFieldOwner := client.WithFieldOwner(cWithoutFieldOwner, "owner")
```

However, it is not possible to confer `WithWatch` on an existing client: one can only obtain a `client.WithWatch` via a constructor:

```go
cWithWatch, err := client.NewWithWatch(cfg, opts)
```

The resulting client is "frozen" -- i.e. can't be subjected to decorators like `WithFieldOwner` -- because those wrappers return a `client.Client`, which can't `Watch()`!

It would be great to have a decorator function to allow an existing client to grow `WithWatch` functionality:

```go
c, err := client.New(cfg, opts)
c = client.WithFieldOwner(c, "owner")
// ... chain other decorators ...
cWithAllTheThings, err := client.AsWithWatch(c)
```

Notes:
- It would be better to call the wrapper `WithWatch`, but that name is already taken by the interface. Sad face.
- I can't think of a way to get around this client being "the end of the line". It can't be further wrapped, unless the wrapper is `WithWatch`-specific. Sad face.
- It would be great if you could do this to any `client.Client`; but as written today that would be hard because the `Watch()` implementation relies on internals of the specific `client` (lowercase) implementation in the library. Sad face.

See #2929 where I prototyped an imperfect version of the solution that suffers from all of the above issues.

**Comment by alvaroaleman** [comment]
Can we use generics for this?

**Comment by alvaroaleman** [comment]
To expand on what I was thinking, I thought we might be able to have some sort of wrapper type for the various options that takes a `client.Client` or `client.WithWatch` through generics and returns whatever it has gotten. The main drawback is that the return will always be assertable to `WithWatch` even if it it isn't.

Note that this plays into https://github.com/kubernetes-sigs/controller-runtime/issues/2888, we should probably solve the two problems together

**Comment by 2uasimojo** [comment]
Cool, yeah, it makes sense to sweep this up with 2888 -- I'll close this for now.
