### ISSUE TITLE
Check if the other resources referenced by an object exist within a webhook

### ISSUE THREAD

**Issue by zhixiongdu027** [kubernetes-sigs/controller-runtime#2968]
I want to check if the other resources referenced by an object exist within a webhook. Could someone please help me complete the logic in the following code example? Thank you very much.

```go
// SetupWebhookWithManager will setup the manager to manage the webhooks
func (r *Pool) SetupWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr).
		For(r).
		Complete()
}

var _ webhook.Validator = &Pool{}

func (r *Pool) Validate() error {
	var allErrs field.ErrorList

	model := r.Spec.Model

	/*
		check model is exist here;
	*/

	if len(allErrs) == 0 {
		return nil
	}

	return apierrors.NewInvalid(schema.GroupKind{Group: GroupVersion.Group, Kind: "Pool"}, r.Name, allErrs)
}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Pool) ValidateCreate() (admission.Warnings, error) {
	poollog.Info("validate create", "name", r.Name)

	// TODO(user): fill in your validation logic upon object creation.
	return nil, r.Validate()
}

```
```[tasklist]
### Tasks
```

**Comment by zhixiongdu027** [comment]
I will try，Many tks

**Comment by sbueringer** [comment]
Please also note that Validator has been removed and won't exist in the next CR release (xref https://github.com/kubernetes-sigs/controller-runtime/pull/2877)

**Comment by mensylisir** [comment]
> You can implement a CustomValidator and then set a Client on the struct that implements it. Here's an example https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/webhooks/cluster.go#L75

The Default function has no more parameters and can only handle the current object? I want to manipulate other objects

**Comment by sbueringer** [comment]
You can add a Client on your CustomDefaulter struct and use the client to modify other objects.

The mutating webhook only gets the current object passed in. So the Default func shouldn't hand over any other objects.
