### ISSUE TITLE
Support health and liveness probes

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes-sigs/controller-runtime#297]
I'm adding a liveness probe to a manager built with `controller-runtime`.
The manager already leverages the HTTP service provided natively to serve Prometheus metrics.

I would like to add another endpoint `/live` to provide the liveness of the application, on the same HTTP server that is used for metrics.
There does not seem to be a way to do this today because the http mux is created internally and attached to the HTTP server.

A way to circumvent this is to basically copy/paste the http server logic into a package of my own and add the extra handler but it feels sad that there is no way to reuse the existing code.

**Comment by DirectXMan12** [comment]
we should have a general liveness hook.  I'm not sure we want to make this a general HTTP serving platform, but liveness support would definitely be useful.

/kind feature
/priority important-longterm

**Comment by GrigoriyMikhalkin** [comment]
Hi, i would like to try to implement this.

**Comment by estroz** [comment]
@DirectXMan12 has this been fully implemented in #419 or is there more to do?

**Comment by DirectXMan12** [comment]
I think so
