### ISSUE TITLE
Typo, `SecretSyncReconcier` -> `SecretSyncReconciler`

### ISSUE THREAD

**Issue by smmuirhead100** [kubernetes-sigs/controller-runtime#2988]
There is a small typo in one of the example files (`/examples/multiclustersync/main.go`)
I believe `secretSyncReconcier` is supposed to be `secretSyncReconciler`.

```
// secretSyncReconcier is a simple reconciler that keeps all secrets in the source namespace of a given
// source cluster in sync with the secrets in the target namespace of all target clusters.
type secretSyncReconcier struct {
	source  client.Client
	targets map[string]client.Client
}
```

I would be happy to take this one!

**Comment by sbueringer** [comment]
Feel free to open a PR

**Comment by smmuirhead100** [comment]
Submitted here: [2993](https://github.com/kubernetes-sigs/controller-runtime/pull/2993)

**Comment by sbueringer** [comment]
Thx!
/close 
(PR merged)
