### ISSUE TITLE
multiNamespaceInformer lack GetIndexer func

### ISSUE THREAD

**Issue by furykerry** [kubernetes-sigs/controller-runtime#3010]
Code-generator lister need an indexer to initialize, but multiNamespaceInformer does not implement GetIndexer func as sharedIndexInformer, what is the correct way to initialize a lister from multiNamespaceInformer?

lister: https://github.com/kubernetes/code-generator/blob/master/cmd/lister-gen/generators/lister.go
multiNamespaceInformer: https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/cache/multi_namespace_cache.go

**Comment by alvaroaleman** [comment]
Controller-Runtime is not interface compatible with the generated code from Kubernetes. You can not initialize a generated lister from a controller-runtime cache.

**Comment by furykerry** [comment]
thanks for your hint, i will try to use controler-runtime client directly
