### ISSUE TITLE
How to filters configmaps with 2 distincts selectors in the cache

### ISSUE THREAD

**Issue by FloMedja** [kubernetes-sigs/controller-runtime#3024]
I have configsmaps with 2 distincts labels lets say `labelA=valueA` and `labelB=valueB`. 

I would like to filter the configMaps and only add the one with those 2 labels to my cache with the `cache.Options`. However It is not possible to add  two times the same Object type to [ByObect](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/cache#Options) because support a `map[client.Object]ByObject`. Additionally the selector on a type of object in the map didn't support the `OR` operation on `labels`

Do someone have a tips on how to do this ? Thanks

**Comment by alvaroaleman** [comment]
This is not possible because Kubernetes label selectors do not support OR directly: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

The best you can get to is to re-use the key and use a selector of the form `label-key in (value1, value2)`

**Comment by FloMedja** [comment]
That's what I thought but I want to confirm anyway. I would look for another approach.
 Thanks for the quick response.
