### ISSUE TITLE
 Fix leader election request timeout

### ISSUE THREAD

**Issue by serathius** [kubernetes-sigs/controller-runtime#3027]
The `controller-runtime` uses the `resourcelock.New` function for configuring leader election. This function is known to have an incorrectly configured request timeout, which sets the request timeout equal to the leader election deadline. This allows a single request timeout to trigger a change in leadership.

**Source:**

https://github.com/kubernetes-sigs/controller-runtime/blob/8e44a4307f70a4d5f4c5aaf0869e2bec7167f4ab/pkg/leaderelection/leader_election.go#L101-L109

**Impact:**

This issue causes unnecessary leader changes, which can cause:
* Lower availability - new leader might require reinitialization of informers which can take tens of seconds in large clusters.
* Waste of resources - Increased API server load due to concurrent re-initializations, potentially triggering a KCP scale-up and wasting resources.

**Fix:**

Update controller-runtime to use `resourcelock.NewFromKubeconfig` for leader election. This will ensure that the request timeout is correctly configured and prevent unnecessary leadership changes due to transient network issues or API server unavailability. This change should involve approximately 10 lines of code.

**Example**:

https://github.com/kubernetes/kubernetes/pull/98059

**Comment by alvaroaleman** [comment]
@serathius thanks for the report, I've opened https://github.com/kubernetes-sigs/controller-runtime/pull/3028 to fix it

Why is the `resourceLock.New` not deprecated if it has known issues?

**Comment by serathius** [comment]
> Why is the resourceLock.New not deprecated if it has known issues?

No breaking change policy :P 
Issue is just `resourceLock.New` allows users to configure deadline and timeout independently, so most users are not aware that relation between those two parameters can impact reliability.
