### ISSUE TITLE
reconcile.Result is ambiguously documented

### ISSUE THREAD

**Issue by cflewis** [kubernetes-sigs/controller-runtime#303]
`reconcile.Result{}` is defined as:

```go
// Result contains the result of a Reconciler invocation.
type Result struct {
	// Requeue tells the Controller to requeue the reconcile key.  Defaults to false.
	Requeue bool

	// RequeueAfter if greater than 0, tells the Controller to requeue the reconcile key after the Duration.
	RequeueAfter time.Duration
}
```

It is ambiguous as to whether you have to set `Requeue: true` for the requeue to occur, or if you only need `RequeueAfter`. You can see both uses on GitHub. After digging through the implementation, the latter is true:

https://sourcegraph.com/github.com/kubernetes-sigs/controller-runtime@d561f55e5064583c18d7c2de357b08bf396d3659/-/blob/pkg/internal/controller/controller.go#L221

This is good because it means no-one is bugged, but the documentation of the function needs to be modified a bit so there's no confusion.

**Comment by kibbles-n-bytes** [comment]
Also, `controller-runtime/pkg/internal/controller/controller_test.go`even has a test that says it's setting both, but then only sets one. And then doesn't have a test that says it's setting only one.

https://sourcegraph.com/github.com/kubernetes-sigs/controller-runtime@d561f55e5064583c18d7c2de357b08bf396d3659/-/blob/pkg/internal/controller/controller_test.go#L362

**Comment by DirectXMan12** [comment]
Heh, good catch!  Want to make a PR?

/kind documentation
/priority important-soon

**Comment by cflewis** [comment]
Just the documentation fix or a unit test as well?

I can do just docs, testing is not going to get on my slate.

**Comment by DirectXMan12** [comment]
just the docs is fine :-).
