### ISSUE TITLE
EnqueueRequestForObject events in the Reconcile function

### ISSUE THREAD

**Issue by mikebz** [kubernetes-sigs/controller-runtime#3042]
Question about how to properly set up the watch.  Let's say we have a simple controller that just watches `ConfigMap`

```
func (r *CheckReconciler) SetupWithManager(mgr ctrl.Manager) error {

	return ctrl.NewControllerManagedBy(mgr).
		For(&probev1.Check{}).
		Watches(
			&corev1.ConfigMap{},
			&handler.EnqueueRequestForObject{},
		).Complete(r)
}
```

Problem is that by the time we get this event in `Reconcile` function:

```
func (r *CheckReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {...}
```

the `req.NamespacedName` is the name of the ConfigMap, but there is no other signal that this is a ConfigMap.  Technically you could have your own CR with the same name and namespace.

**Comment by troy0820** [comment]
The watch queues the parent object the `For` `&probev1.Check{}` when events for the configmap are created.  If you need to watch the configmap and do something with changes, you can use an informer to respond directly to the configmap or have your controller be idempotent that when the event from the configmap triggers a reconcile to the &probev1.Check, you can handle the configmap that triggered the reconcile.

**Comment by mikebz** [comment]
thank you!  I guess what I am not sure is by the time the `Reconcile` function gets the event there is no way to know what object it's actually responding to.

You know that it's not a Probe when Getting it returns an error, but I wish there was some quick way to tell what the source was.

```
	if err := r.Get(ctx, req.NamespacedName, &check); err != nil {
```

I am new to using controller-runtime myself but it seems to me that Informer is rarely used directly.  Maybe there is a guideline that can be done.

**Comment by mikebz** [comment]
after looking around it seems like the easier and more canonical thing to do is to create another controller which watches the ConfigMaps and updates the probe Checks that need to be updated.

This of course only makes sense when you are dealing with predictable resources you are watching.

**Comment by mikebz** [comment]
Happy to provide a sample of the solution for posterity if anyone else is interested.
