### ISSUE TITLE
Webhook: Need more injection Interface in webhook server

### ISSUE THREAD

**Issue by kdada** [kubernetes-sigs/controller-runtime#309]
Webhook server only implements `inject.Client` and `inject.Decoder`.  I think the server should implement all of injection interfaces. Then I can use these interfaces in my webhooks.

**Comment by DirectXMan12** [comment]
yep, noticed this bug when trying to reword dep injection.  the webhook dep injection code is currently wrong -- it should call injectfields in children, and only implement specific injectors for dependencies it needs.

cc @mengqiy 

/kind bug
/priority important-soon
/good-first-issue

**Comment by DirectXMan12** [comment]
this is closed by #323
