### ISSUE TITLE
No list option for Continue or Limit

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#310]
The new functional list options from #294 don't support setting Limit or Continue with a functional option. If the user wants to use those options, they need to fall back to `UseListOptions`. Not a huge deal, but probably not too hard to fix.

**Comment by rajathagasthya** [comment]
@DirectXMan12 Can I take this?

**Comment by DirectXMan12** [comment]
go ahead!  Always happy for more contributions :-)

**Comment by rajathagasthya** [comment]
@DirectXMan12 Thanks! Do you have any pointers on how to get started with this? How are the Limit and Continue options used?

**Comment by DirectXMan12** [comment]
basically, you'd just need to implement additional `ListOptionsFunc` implementations that set limit and continue on the list options -- the pattern should be fairly straightforward if you look at some of the other list options, but LMK if it's unclear.

Limit and continue themselves are used as part of the paginated list API in Kubernetes (e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#list)

**Comment by rajathagasthya** [comment]
@DirectXMan12 Thanks! I actually figured out what to do after reading some code in k/k. I'm writing tests (which are failing so far), but I'll create a WIP PR to make sure I'm doing the right things.
