### ISSUE TITLE
support different resync period for each controller within same repository

### ISSUE THREAD

**Issue by crimsonfaith91** [kubernetes-sigs/controller-runtime#312]
A repository may have multiple controllers. For now, we only support same resync period for all the controllers. However, some use case may require supporting different resync periods among the controllers.

For example, a repository may have 3 controllers (A, B, and C). Controller A may need to be resynced every one hour to work properly, while controllers B and C are fine with the default resync period of 10 hours.

@droot 
@kow3ns

**Comment by DirectXMan12** [comment]
/kind feature
/priority important-longterm

We generally recommend that controllers not rely on resync periods.  That being said, we do need a good solution for the "timer" usecase, which is what I generally see.  It can be done with the current components (`client.List` --> `source.Channel` or `client.List` --> custom source), but it's potentially inefficient (listing/copying all objects when we really only need names/namespaces) and requires some extra coding.

**Comment by droot** [comment]
>We generally recommend that controllers not rely on resync periods. That being said, we do need a good solution for the "timer" usecase, which is what I generally see. It can be done with the current components (client.List --> source.Channel or client.List --> custom source), but it's potentially inefficient (listing/copying all objects when we really only need names/namespaces) and requires some extra coding.

+1 This is what I suggested @crimsonfaith91 in person just now :)

**Comment by crimsonfaith91** [comment]
I synced with @droot , and he provided in-depth details on some potential solutions.

Regarding the source channel solution, although it is potentially inefficient, IMO we can implement a helper API at `controller-runtime` that users can use to set up the source channel. The API will take at least 2 parameters: `GVK` and `resyncPeriod`. This will save the users some time and prevent them to implement the source channel wrongly. However, @droot also pointed out that this may result in the users to call the API without understanding the inefficiency, so we have to have a good documentation for this.

Another solution is to add the `resyncPeriod` parameter to watcher API (IIUC, it is the `controller.Watch`). Although this solution allows different `resyncPeriod` among different controllers within the same repo, this solution requires the same `resyncPeriod` for an object type (e.g., same `resyncPeriod` for Pods, which watched by several controllers within the repo). According to @droot, this is fine though because adding the `resyncPeriod` parameter to watcher API is more intuitive for users.

**Comment by ikruglov** [comment]
Hi folks. I'm interested in this feature. Reading the posts above I understand that there are two possible implementations:
1. human-friendly wrapper around client.List() + source.Channel
2. resyncPeriod as part of Controller.Watch() method.

as I used I would prefer the second one, while, looking at the codebase - it's more tricky to implements as it would require either new method in the Controller interface or a change to the existing one.

Please guide me which of the options if more preferential, so I can contribute.

**Comment by DirectXMan12** [comment]
I'd prefer something closer to option 1 -- it's more explicit where things are coming from, and doesn't rely on a quirk of the underlying implementation.  Channel source is probably not the right way if we're building it in -- we probably just want a custom source.  The trick is that we probably just want access to the keys from the cache w/o the full objects, so client.List is insufficient.  This may take a bit of design back and forth, but you're welcome to start prototyping if you're up for that.
