### ISSUE TITLE
Using unstructured objects to discover real object type

### ISSUE THREAD

**Issue by j-vizcaino** [kubernetes-sigs/controller-runtime#315]
I have a manager that handles multiple API types. 90% of the logic is generic and can treat API types irrespective to their actual type (as long as they implement the proper interfaces).

Now, the last 10% needs to get the actual content of the custom resource, process it somehow before delegating it the generic engine.

One solution to this would be to have separate controllers but the amount of code that amounts for setting up, processing and calling the generic engine amounts to roughly 150 lines of code.
Considering the manager will likely handle dozens of custom API types, I would prefer not duplicating code.

Another solution I could think of, was to use an `unstructured.Unstructured{}` object to `Get()` the object in the reconcile function, then, based on its GVK delegate the custom handling to some other dedicated handler, then call the generic engine. Using a single reconciler, the manager would be able to handle many API types, reducing to the minimum the amount of duplicated code.

The issue is that I can't seem to get this solution to work, because the function expects the unstructured object to provide a GVK! The relevant line of code is here: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/unstructured_client.go#L96

How can I achieve this unstructured `Get` using `controller-runtime`?

Maybe related to #33

**Comment by DirectXMan12** [comment]
For unstructured, that just pulls from the group-version-kind fields in unstructured.  We need that information to know which object to fetch with Get.  I'm not entirely certain as to your usecase -- how are you determining which resource to fetch from if you don't know group-version-resource or group-version-kind?

**Comment by j-vizcaino** [comment]
You're absolutely right, I don't know how I ended up with that flawed logic: there's basically no way I can retrieve an object given its reconcile request only since many objects with different GVK but the same identity can coexist in Kubernetes 🤦‍♂️ 

This is clearly a non-issue. Sorry about the noise. Closing this.
Thanks for your help!

**Comment by DirectXMan12** [comment]
no worries :-).  I've had similar moments before :-)
