### ISSUE TITLE
Watching resources after a controller has started

### ISSUE THREAD

**Issue by gerred** [kubernetes-sigs/controller-runtime#329]
Currently, when a controller is started, it's sync.Mutex is locked and doesn't unlock until after the stop channel is called. Attempting to watch a resource after a controller has started causes a deadlock. A fix to this is to unlock the mutex before receiving on the stop channel.

I'm adding controllers dynamically to an already running manager - except for this, it works fine. Is this something we could consider changing (if so I will PR it) or is this intended? Could we add post-start watches as a feature?

Thanks!

**Comment by gerred** [comment]
Turns out this is already in. The version we have in dep didn't have this. Closing.

**Comment by abhijitherekar** [comment]
hi @gerred if you don't mind, please can you reference the PR which fixed this issue.

Thanks.
