### ISSUE TITLE
Manually terminate caches

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#332]
It can occasionally be useful to manually terminate caches (for example, dynamically created CRDs, or bugs in the kubernetes API server's watch code).

**Comment by DirectXMan12** [comment]
cc @gerred

**Comment by DirectXMan12** [comment]
for example: https://github.com/kubernetes/kubernetes/issues/74105

**Comment by DirectXMan12** [comment]
We could potentially either have an `unwatch` method, refcounting style

**Comment by gerred** [comment]
@DirectXMan12 I have time to start working on this now. Going to take an initial crack at it.
