### ISSUE TITLE
Serve metrics independently of `manager.Start`

### ISSUE THREAD

**Issue by LiliC** [kubernetes-sigs/controller-runtime#336]
Currently metrics are only started to be served when `manager.Start()` is called. In operator-sdk we have a use case as we implemented our own leader election, so we block `Start()` until that pod becomes a leader. Due to this problem we are not getting metrics for all the pods. We do want to still like to collect metrics for all the running pods even if the manager is not started.

Proposed solution:

Add `MetricsServingDisabled` option to ovveride serving of metrics. Expose the `serveMetrics` https://github.com/kubernetes-sigs/controller-runtime/blob/45d652077cba5ccc29621e8db615f25084c701cb/pkg/manager/internal.go#L180 that can be used by users who want to start serving metrics independently of the `Start()` method.

**Comment by LiliC** [comment]
Opened https://github.com/kubernetes-sigs/controller-runtime/pull/337 to demonstrate the above proposed solution.

**Comment by DirectXMan12** [comment]
For reference, any particular reason why you implemented your own leader election vs CR's leader election?  If there's something it doesn't do, that'd be good to know :-).

If you want to disable metrics serving, you should just be able to do `MetricsPort: "0"`, though.

**Comment by LiliC** [comment]
> For reference, any particular reason why you implemented your own leader election vs CR's leader election? If there's something it doesn't do, that'd be good to know :-).

cc @shawn-hurley think he knows more about the reason behind that.

**Comment by mhrivnak** [comment]
That's all correct. I wrote up a summary and basic implementation here: https://github.com/mhrivnak/leaderelection

I've been meaning to propose it for controller-runtime, but just haven't gotten around to it. So here we are! The implementation changed slightly when I added it to operator-sdk, but it's fundamentally the same.

From the README, I'll just point out this excerpt, which I think highlights the key benefits: "There is no possibility for multiple pods to think they are the leader at the same time. The leader does not need to renew a lease, consider stepping down, or do anything related to election activity once it becomes the leader."

**Comment by LiliC** [comment]
As suggested in the https://github.com/kubernetes-sigs/controller-runtime/pull/367#issuecomment-475321599 PR comment we want to instead use the `.Runnable` approach. 

@DirectXMan12 you mentioned you want to have metrics enabled by default, so how do we want to disable them then. Any prefrence on the approach there?

**Comment by DirectXMan12** [comment]
Set MetricsListenAddress to `0` on the mnnager, and then just pass the desired actual listen address directly to the runnable.
