### ISSUE TITLE
Better logging in the webhook server

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#340]
We should have logging in the webhook server to log requests and results (at a higher log level, most likely), otherwise it's hard to debug admission webhooks.

**Comment by anthonyho007** [comment]
Hi  ! If no one is working on this issue, I want to take on this issue. I have been implement admission controller with controller-runtime and i do wanna improve logging in webhook server.

**Comment by DirectXMan12** [comment]
We can't officially assign it to you, but consider it unofficially assigned.  Thanks!
