### ISSUE TITLE
Manager does not wait for Runnables to stop

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#350]
Currently `Manager.Start` immediately returns when stop channel is closed without waiting for Runnables to stop:

https://github.com/kubernetes-sigs/controller-runtime/blob/6649bdbe3f1f5f9769b91c031e52be253c87e922/pkg/manager/internal.go#L216-L219

This makes writing a Runnable with blocking stop logic difficult or impossible. For example, the Manager's internal `serveMetrics` is basically a Runnable (a blocking method that takes a stop channel). When the stop channel is closed, `serveMetrics` tries to shut down its http server:

https://github.com/kubernetes-sigs/controller-runtime/blob/6649bdbe3f1f5f9769b91c031e52be253c87e922/pkg/manager/internal.go#L188-L192

But [in normal usage, the process immediately exits when Manager.Start returns](https://github.com/kubernetes-sigs/kubebuilder/blob/4228ca5e22d680aff3ec499e6451f51b2405f515/test/project/cmd/manager/main.go#L80-L83) so the `Shutdown` call is unlikely to complete.

Adding `sync.WaitGroup` accounting [inside the Runnable wrapper goroutines](https://github.com/kubernetes-sigs/controller-runtime/blob/6649bdbe3f1f5f9769b91c031e52be253c87e922/pkg/manager/internal.go#L249-L251) would allow the addition of a `Wait()` method to the `Manager` interface that blocks until all Runnables have returned (or `WaitWithTimeout(time.Duration)`, `Shutdown(context.Context)` for a termination timeout), without changing either the Runnable contract or the Manager contract:

```go
if err := mgr.Start(signals.SetupSignalHandler()); err != nil {
    log.Error(err, "unable to run the manager")
    os.Exit(1)
}
mgr.Wait()
```

**Comment by DirectXMan12** [comment]
/kind bug
/priority important-soon

good catch

**Comment by rajathagasthya** [comment]
I'll take this!

**Comment by DirectXMan12** [comment]
awesome!

**Comment by grantr** [comment]
While investigating this I discovered another issue: the Manager's `errChan` is unbuffered, so only one Runnable goroutine (including the metrics server) will be able to terminate correctly. Others will block indefinitely. An easy fix for this is making the errChan buffered, but that's not a great long-term solution.

Anyone working on solutions in this area might want to keep #330 in mind too.

**Comment by rajathagasthya** [comment]
/remove-lifecycle stale

Sorry, haven't had a chance to look at this. Will do shortly. Might need your guidance a bit @DirectXMan12

**Comment by DirectXMan12** [comment]
ack, lmk if/when you need my guidance

**Comment by rajathagasthya** [comment]
@DirectXMan12 I'm starting to take a look at this. Could you guide me on what a solution could look like?

**Comment by DirectXMan12** [comment]
off the top of my head, we'd need some way to check that the runnables each terminate.  A wait group, as suggested, seems reasonable.  Just rolling it into Start instead of a separate wait method could be reasonable, but I'd imaging that'd have some issues too (like delayed error reporting).  Need to weigh the pros and cons there.

**Comment by DirectXMan12** [comment]
probably at least log immediately

**Comment by seh** [comment]
I’m bitten by this problem with my use of an instrumentation package that I try to shut down cleanly before the process exits. My predicates and reconcilers are making calls into this package, and there’s no way I can see that I can wait for them all to finish before trying to close the connection they’re all using.

It’s one thing to know that the manager observed the “stop” channel becoming ready, when it returns from `Start`, but that says nothing about the current state of the `Runnable`s—even those that ask for the “stop” channel to be injected.

Using a`sync.WaitGroup` sounds like the way to go. Whether delaying the return from `Start` should be something you can opt into or out of warrants consideration.

**Comment by vincepri** [comment]
Closing in favor of #764

/close
