### ISSUE TITLE
NewFakeClientWithScheme dies silently

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes-sigs/controller-runtime#354]
Current master commit: https://github.com/kubernetes-sigs/controller-runtime/blob/45d652077cba5ccc29621e8db615f25084c701cb/pkg/client/fake/client.go#L65

This line does not result in actual logging in my case, just results (confusingly) in a call to os.Exit(1).

Simple test case (replace clusterautoscaler with a suitable object that is not part of default scheme):

```go
package clusterautoscaler

import (
	"testing"
	fakeclient "sigs.k8s.io/controller-runtime/pkg/client/fake"
	"k8s.io/apimachinery/pkg/runtime"
)

func TestAvailableAndUpdatedCheck2(t *testing.T) {
	tscheme := runtime.NewScheme()
	// With the following commented, we fail silently.
	//apis.AddToScheme(tscheme)
	ca := NewClusterAutoscaler()
	_ = fakeclient.NewFakeClientWithScheme(tscheme, ca)
}
```

**Comment by DirectXMan12** [comment]
a) that should probably be a panic, not a log-then-exit.  I suspect it was an incorrectly replaced pattern from our purge of fatalf (which doesn't existing in logr).

b) you should generally set up logging in `TestMain`, `BeforeSuite`, each test, or what have you (by calling `"pkg/log".SetLogger`).

**Comment by anthonyho007** [comment]
@DirectXMan12  Can i work on this issue ?

**Comment by DirectXMan12** [comment]
go ahead. Can't officially assign unless you're an org member, but consider it assigned :-)

/assign @anthonyho007

**Comment by DirectXMan12** [comment]
close as per above PRs
