### ISSUE TITLE
Manager cash on cert creating

### ISSUE THREAD

**Issue by SchSeba** [kubernetes-sigs/controller-runtime#359]
Hi folks,

I will like to know if there is a way to prevent the manger restart(pod restart) for the first run(when generating the certs)

Example:
```
INFO	kubebuilder.admission.cert.writer	cert is invalid or expiring, regenerating a new one
....
	ERROR	kubebuilder.webhook	server returns an unexpected error	{"error": "open /tmp/cert/cert.pem: no such file or directory"}
```

I will like if there is no cert to generate one save it as secret but also put it under the `/tmp/cert/` folder for the first time the manager start and not cause an error.

**Comment by DirectXMan12** [comment]
In the long term: We recommend that you generate serving certificates externally (and, in fact, in master we've removed the certificate generation code).  cert-manager is one option (and will have support for injecting the corresponding CA into webhook configs automatically), but if you having existing cert provisioning infrastructure, you could use that as well.

**Comment by SchSeba** [comment]
Thanks for the comment @DirectXMan12 !

**Comment by DirectXMan12** [comment]
Closing as per v0.2.0 removing generate anyway.
