### ISSUE TITLE
Recommended database read/write pattern 

### ISSUE THREAD

**Issue by jakesjohn** [kubernetes-sigs/controller-runtime#360]
I have written a custom controller using kubebuilder.  My custom controller also writes CR to a Mysql database(Same schema as of CR) for historical purposes.  

I had a similar problem in #245 . How can I handle eventual consistency nature of Kubernetes to write into a database that works on strong consistency ? 

For eg:
1. How can i handle a reconcile function called with a stale entry?  
2. Calling "Insert" into a table more than once will return error incase of a database. (against K8s philosophy)  Or Is it always a "update" entry during every reconcile function (This is very expensive)? What should be the logic to write into DB during every reconcile function? 

@DirectXMan12

**Comment by DirectXMan12** [comment]
> How can I handle a reconcile function called with a stale entry

Treat it like it's the freshest data you have, if it's the root object.  I outline some suggestions in the [FAQ](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-my-cache-might-be-stale-if-i-read-from-a-cache-how-should-i-deal-with-that) for dealing with potentially stale child objects, depending on your situation.

> Calling "Insert" into a table more than once will return error incase of a database

It returns an error in Kubernetes as well.  Calling `Create` on an already created object returns an error.  It's presumed that you'll either return an error from reconcile (in which case you requeue and eventually get up-to-date information), or you'll otherwise explicitly deal with it.  Can you clarify how this scenario differs from what you expect?

**Comment by jakesjohn** [comment]
Thanks @DirectXMan12  for the reply . Sorry if the question was not clear. Adding more details for clarity.

> > How can I handle a reconcile function called with a stale entry
> 
> Treat it like it's the freshest data you have, if it's the root object. I outline some suggestions in the [FAQ](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-my-cache-might-be-stale-if-i-read-from-a-cache-how-should-i-deal-with-that) for dealing with potentially stale child objects, depending on your situation.
> 
> > Calling "Insert" into a table more than once will return error incase of a database
> 
> It returns an error in Kubernetes as well. Calling `Create` on an already created object returns an error. It's presumed that you'll either return an error from reconcile (in which case you requeue and eventually get up-to-date information), or you'll otherwise explicitly deal with it. Can you clarify how this scenario differs from what you expect?

I think, scenario in kubernetes reconcile is slightly different.  In K8s reconcile, we can assume  that every reconcile to be called with the freshest data. (as you mentioned earlier)  The common pattern that I have seen in k8s reconcile is 

```
During each reconcile,
      read object X in the cache(the freshest data that we know)
      copy = X
      recalculate  X.Status
      if !reflect.deepEqual(X.Status, copy.Status)
            call Update(X)
      else
             do nothing
      return
```

In my case, i need an extra step of keeping a replica copy of X in DB. Then reconcile logic becomes slightly complicated due to eventual consistency property of k8s. I am looking for the right pattern for DB writes.

Similar to kubernetes api objects, I have two requirements for adding a DB write to the above flow.

1.  I need to differentiate between Create vs Update. The implementation would be similar to this pattern 
        
```
 During each reconcile,
      read object X in the cache(the freshest data that we know)
      Get Object X from DB
      if Get fails,
            Create Object X in DB  //Object is not present in DB, hence create
     else 
            Update Create X in DB //Object is present in DB, hence update
      ....

```
This would require  a `GET` from DB during every reconcile

2.  I need to skip DB update if there is no change in X.status or X.Spec. If I borrow the same idea of reflect.deepEqual,     the implementation pattern would be
     
```
         Y = GetFromDB(X) 
         if ! reflect.DeepEqual(X, Y)
              UpdateDB(Y)
```

Combining both,  if we want to include DB in my workflow(X.Spec can also change),  Reconile function would look like 

```
During each reconcile,
      read object X in the cache(the freshest data that we know)
       Y = GetFromDB(X) 
       if Get fails,
            DBOperation='create'  //Object is not present in DB, hence create operation
      else
            DBOperation='update' //Object is present in DB, hence update operation

      Copy = X
      recalculate  X.Status
      
      if !reflect.deepEqual(X.Spec, Y.Spec) || !reflect.deepEqual(X.Status, Copy.Status)
             err := DBOperation(X)  
              if err != nil
                  RequeueRequest
                  return
   
      if !reflect.deepEqual(X.Status, Copy.Status)
             call Update(X) // k8s api write
             if err != nil
                   return RequeueRequest
      else
             do nothing
      return
```
        
  Is this the right pattern for maintaining a DB copy from a k8s controller ?

**Comment by jakesjohn** [comment]
Any pointers? Thanks in advance

**Comment by DirectXMan12** [comment]
that seems pretty reasonable to me, assuming either a) nothing else is updating the db or b) your db can provide the same optimistic locking via resource version.  Otherwise, you'd need a DB transaction in there somewhere.
