### ISSUE TITLE
support per-controller leader election

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#364]
It's been pointed out that per-controller leader election can be very useful, since it allows you to safely migrate controllers across binaries.

/kind feature
/priority important-longterm

**Comment by GrigoriyMikhalkin** [comment]
Hi, i would like to try to implement this.

**Comment by DirectXMan12** [comment]
/lifecycle frozen

work is in progress

**Comment by vincepri** [comment]
Closing this given that we're heavily relying on managers today to achieve leader election, and it'd be hard to support per-controller LE settings

/close
