### ISSUE TITLE
Envtest: support loading multiple CRDs from a single file

### ISSUE THREAD

**Issue by nrfox** [kubernetes-sigs/controller-runtime#369]
Currently envtest supports [installing CRDs](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest#CRDInstallOptions) from yaml at specified paths however it assumes that there is only one CRD per file. Given a single file with multiple CRD documents separated by `---`, envtest will read/install the first document but not the rest. This is confusing while testing because the scheme has all of the correct GVKs but tests will fail when [registering the watch](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/controller/controller.go#L175-L181) for the second CRD in the file with the error `no matches for kind "MyKind" in version "mygroup/version"`. When running outside of tests, there are no errors because all the CRDs get installed properly using `kubectl apply`.

I'm not sure the current library used for parsing yaml supports reading multiple documents from a single file however I believe the apimachinery [decoder](https://godoc.org/k8s.io/apimachinery/pkg/util/yaml#YAMLOrJSONDecoder) does.

I discovered this issue because I have an external CRD as a dependency of my project which exposes its definitions as a single yaml file.

**Comment by DirectXMan12** [comment]
/kind bug

Yeah, we should tackle this.  It's not hard -- it just requires a tweak to the CRD loading code

/help-wanted

**Comment by delp** [comment]
Hello,

I am a first time contributor and I wanted to try taking on this issue. I have been working with the operator-sdk, and so have some familiarity with CRDs, watches, and the controller. But I can't figure out how to build this repository, and didn't find what I was looking for in any of the docs for FAQ. Can someone help me get started?

**Comment by GrigoriyMikhalkin** [comment]
Hi, i would like to take this issue, seems like no one is working on it
