### ISSUE TITLE
fake client to record method calls

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [kubernetes-sigs/controller-runtime#372]
Hi, this is more like a question, and not implementation request or something. I'm currently developing k8s operator, and to test it i'm using `fakeClient`. Operator monitoring some service for updates, and if something new available -- updates deployment. Scenario that i want to test:

1) First controller got updates from service
2) Second controller checks if deployment is up to date
3) If it isn't -- updates it

In my test, i want to check that controller doesn't call `client.Update` in case if deployment is up to date. For that it would be convenient if `fakeClient` recorded method calls or something like `mockClient` would be available. Is it redundant?

**Comment by DirectXMan12** [comment]
there's #381, but we generally don't recommend testing logic like that, since it (generally) doesn't really matter if an update is done, as long as it's an identical update.

**Comment by DirectXMan12** [comment]
(closing for now in light of #381, but feel free to re-open if you have future questions).
