### ISSUE TITLE
We should need an event return

### ISSUE THREAD

**Issue by MengZn** [kubernetes-sigs/controller-runtime#374]
## Question

**What did you do?**

We can get the return of the event etc Create,Delete ...

**What did you expect to see?**

If we design an action here, we can know the state of the current resource.
```
type Request struct {
	// NamespacedName is the name and namespace of the object to reconcile.
	types.NamespacedName
}
```

**What did you see instead? Under which circumstances?**
By passing the action through the handler, the user can know the current resource situation.
```
// Create is called in response to an create event - e.g. Pod Creation.
func (h *NetHandler) Create(evt event.CreateEvent, q workqueue.RateLimitingInterface) {
	if evt.Meta == nil {
		fmt.Printf("evt.Meta == nil")
		return
	}

	q.Add(reconcile.Request{NamespacedName: types.NamespacedName{
		Name:      evt.Meta.GetName(),
		Namespace: evt.Meta.GetNamespace(),
		Action:    Create,
	}})
}
```

**Comment by j900155** [comment]
I have the same problem, @MengZn do you want to implement it?

**Comment by shawn-hurley** [comment]
Could you explain the use case and how you would use this field in your reconciler?

**Comment by MengZn** [comment]
@shawn-hurley 
It's still useful if the operator knows that an object has been deleted or modified!
The operator can handle his related business logic.

**Comment by shawn-hurley** [comment]
To handle the deletion, I believe that you should be using a [finalizer](https://book.kubebuilder.io/beyond_basics/using_finalizers.html).

Can you explain how you intend to use the modified data?

**Comment by MengZn** [comment]
I think that it is not just a deletion.
If the operator can know the correction status of the object in the business. Help external operators understand changes in objects

**Comment by DirectXMan12** [comment]
You should *never* be writing reconcilers that differentiate between the different operations.  That's bound to get you into trouble.  Instead, each reconcile, you should check to see if the state of the world is different from what you expect, and act accordingly.  It shouldn't matter if the object was just created or has been updated, what matters is that the state of the world conforms to what's specified in the object.

This request is explicitly against the design principles of controller-runtime, so I'm going to close it now.  If I'm misunderstanding you, please let me know, and I'll re-open the issue.
