### ISSUE TITLE
Ignorable Errors

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#377]
We have a couple classes of errors that should not trigger requeues (not-found, already-exists), as they're not errors that will be solved by requeuing (not-found will remain not-found until a cache updates, at which point you should get a requeue from the cache update, for instance, and already-exists is the same way).

The quickest, most-likely-to-not-break-users way to solve this is to have helpers for ignorable errors, along the lines of

```go
func IgnoreNotFound(err error) error {
    if apierrors.IsNotFound(err) {
        return nil
    }
    return err
}
```

An easier/possibly better solution is to apply that logic on the results of reconciler by default, and allow an option to force overriding this in `Result`, but this could potentially break people in the case of non-watched/incorrectly-watched resources.

At any rate, the helpers are a good first step -- I find myself writing them a lot by hand.

/kind feature
/priority important-longterm.

**Comment by adracus** [comment]
Related: Comment in #357 + Fix in #428

**Comment by DirectXMan12** [comment]
Not quite actually fixed -- the helper helps, but I'd like to figure out something automatic

**Comment by adohe** [comment]
sure I will give a try to find something automatic.

**Comment by negz** [comment]
https://godoc.org/github.com/crossplaneio/crossplane-runtime/pkg/resource#Ignore

By way of an experience report, the pattern proposed by this issue is exactly what we do in Crossplane and it works well for us.

**Comment by DirectXMan12** [comment]
> I'm a little worried about the existing requeue logic becoming "cleverer" to handle such situations

Yeah, that's my hesitance too, but I've seen a lot of people not realizing that requeuing on not found errors might cause them to see repeated backoff, and it's super-common boiler plate to write `if IgnoreNotFound(err) == nil { ... }`.

Still, the real experience report is super useful.  Thanks :+1:

**Comment by vincepri** [comment]
Closing in favor of #617

/close
