### ISSUE TITLE
switch to golangci-lint instead of gometalinter

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#384]
CT already did this as part of controller-tools#175, so CR should follow suit.

**Comment by alaypatel07** [comment]
@DirectXMan12 Interested in taking this one, if no one's on to it. Thanks

**Comment by DirectXMan12** [comment]
go ahead!
glad to have the help :-)

**Comment by DirectXMan12** [comment]
closed by #414
