### ISSUE TITLE
Functions in testutil are commented out

### ISSUE THREAD

**Issue by bogdanpetrea** [kubernetes-sigs/controller-runtime#386]
I would like to disable the client caching in some of my tests as it doesn't always seem to reflect the latest resource changes and it really gets in the way.

If I use a new client I can see the latest changes as expected so I assume it's a caching thing. But If I use a different client from the one that the test manager uses, they will always be unsynced, so it's still a caching problem.

It seemed like [these functions](https://github.com/kubernetes-sigs/controller-runtime/blob/036f37fbd3cd8a67ce1a3519e600818022762755/pkg/manager/testutil.go#L19
) might help me in disabling the cache, although I'm not sure it's possible. Any clue why they are commented?

**Comment by DirectXMan12** [comment]
I'm not even sure why they're still there.  For tests, the recommendation is just to do
`"sigs.k8s.io/controller-runtime/pkg/client".New(...)` for use in the actual test methods (which will get you a non-caching client).

**Comment by DirectXMan12** [comment]
/remove-lifecycle rotten
/lifecycle frozen

we should remove that file
