### ISSUE TITLE
Test environment should support passing crd file path in additional to directories 

### ISSUE THREAD

**Issue by yuzisun** [kubernetes-sigs/controller-runtime#394]
When building a controller which watches another CRD we need to add CRD file to the test environment, those CRD files usually resides in your project's vendor directory. However test environment struct only supports directories not file path, if we point to the vendor directory which contains files other than crd files, the tests would fail.  	
```
t := &envtest.Environment{
    CRDDirectoryPaths: []string{filepath.Join("..", "..", "..", "config", "crds")},
}
```

**Comment by DirectXMan12** [comment]
/kind bug
/priority important-longterm
/good-first-issue

I'd welcome a PR to fix this, so that we only try and load CRDs (I seem to recall reading a similar PR recently, so double-check to see if it's still an issue)

**Comment by DirectXMan12** [comment]
Flake here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/713/pull-controller-runtime-test/1204197535384604672

Can you take a look please?
