### ISSUE TITLE
Why doesn't controller-runtime allow access to the old object on updates?

### ISSUE THREAD

**Issue by negz** [kubernetes-sigs/controller-runtime#399]
I've been using kubebuilder and controller-runtime for a little while, but just hit my first case in which it might be useful to have access to the old version of an object during an update. I know `cache.EventHandler`'s `OnUpdate` hook is passed both the old and new versions of the updated object. controller-runtime adds a few layers of abstraction such that we just see two `reconcile.Request`s  - one for the old object's `types.NamespacedName` and one for the new object's, which will subsequently be deduplicated to one request.

Does controller-runtime avoid exposing the old object by design? I imagine it's not actually possible to guarantee we'll always see the old version of an updated object, for example when our watch restarts after a long absence and we get a `410 Gone` response because it fell out of etcd?

I wanted access to the old version of the object in order to enforce immutability of certain spec fields (a label selector). I believe a validating webhook would be the better tool for this, so this issue is purely a design/documentation enquiry.

**Comment by DirectXMan12** [comment]
> Does controller-runtime avoid exposing the old object by design?

Yes, because it generally encourages writing subtle bugs into your controller.  Namely, you should be assuming any event could come from any source (e.g. it could be a sub-object's event, or a genericevent, etc), and should be reading *all* state from the current state of the world.  

> I believe a validating webhook would be the better tool for this, so this issue is purely a design/documentation enquiry.

Yeah, validating webhooks are the way to go here.

I'm closing this issue, since I believe I've answered your question, but feel free to respond here if you have any follow-ups, etc.

**Comment by shenlanse** [comment]
I really want access old object. Sometimes, reconcile is a really time-consuming operation. And I only need reconcile on some specific field update. If i can't get old object, i will not distinguish that and have to reconcile on all update event.

**Comment by shenlanse** [comment]
@DirectXMan12

**Comment by DirectXMan12** [comment]
You can still use a predicate filter if you really need that, which should allow you to do that: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/predicate.  Be careful though.

**Comment by shenlanse** [comment]
@DirectXMan12 Thanks, I will have a try.

**Comment by shenlanse** [comment]
@DirectXMan12 Works as expected, thanks.
