### ISSUE TITLE
Dependencies out of sync

### ISSUE THREAD

**Issue by jonsabo** [kubernetes-sigs/controller-runtime#401]
The docs indicate that the k8s dependencies of controller-runtime and controller-tools will be the same (though granted it does not mention across what versions, I am assuming the same versions of each should have the same deps):
https://book.kubebuilder.io/beyond_basics/dependencies.html
>controller-runtime and controller-tools each list a specific, identical set of dependencies on Kubernetes libraries and related libraries.

But it looks like they fell out of sync with the v0.1.10 releases
https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.10/Gopkg.toml
https://github.com/kubernetes-sigs/controller-tools/blob/v0.1.10/Gopkg.toml

which appears to make it so kubebuilder projects can only use up to v0.1.9 of both. I think this is because we're using specific tag names (e.g. `kubernetes-1.13.1`) and not semver tags that dep could use to do version comparisons?

It looks like controller-runtime has the latest dependencies in master, so cutting a new release should allow it to go through.

**Comment by DirectXMan12** [comment]
We've now decoupled this due to moving to modules and installing controller-tools as a binary/using `go get` with modules, so I think this can be closed.
