### ISSUE TITLE
BUG: client.UpdateStatus.Update() func clears Kind of the local object

### ISSUE THREAD

**Issue by TenSt** [kubernetes-sigs/controller-runtime#406]
**Description**
Using client.UpdateStatus.Update() func clears Kind of the local object.

**How to reproduce**
I've encountered this during my work with operator SDK. So repro steps use it too:
1. Get instance using:
`r.client.Get(context.TODO(), request.NamespacedName, instance)`
2. Update status of the CR:
`instance.Status.Result = "success"`
3. Run client.Status().Update() func to update object in the K8S:
'r.client.Status().Update(context.TODO(), instance)'
4. Look at the Kind fields in the instance object:
`reqLogger.Info("Instance typeMeta kind: " + instance.TypeMeta.Kind)
reqLogger.Info("Instance kind: " + instance.Kind)`

**Actual result**
client.Status().Update() func cleared Kind fields thus `instance.TypeMeta.Kind` and `instance.Kind` are empty.

**Expected result**
client.Status().Update() func did nothing with Kind fields thus `instance.TypeMeta.Kind` and `instance.Kind` store appropriate values.

**Additional information**
Here is a link to my repo with simple operator which demonstrates this behavior.
https://github.com/TenSt/app-operator

Please let me know if you need any additional information.

**Comment by GrigoriyMikhalkin** [comment]
Bug is caused by https://github.com/kubernetes/apimachinery/issues/19

**Comment by jcrossley3** [comment]
I'm just now hitting this, too. Any thoughts on a workaround?

**Comment by GrigoriyMikhalkin** [comment]
@jcrossley3 Not sure, but it seems that you have to write your own implementation of [Client interface](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L97) for that. At least i didn't found any other way to pass your own decoder to [client.New](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L53) function, for now.

**Comment by jcrossley3** [comment]
@DirectXMan12 is this too naive of a fix? https://gist.github.com/jcrossley3/16621ee70f21c095c11be1262ad04ee2

If not, I can PR.

**Comment by DirectXMan12** [comment]
I think that actually looks good.  I'd have to double check where we do it for other things, but that's probably fine.

**Comment by jcrossley3** [comment]
I tried to write a failing test for it, but it seems it's not broken in whatever harness is used to run the tests. Did it accidentally get fixed? :)

**Comment by DirectXMan12** [comment]
The test harness just uses the kube apiserver.  You can check the version used in hack/check-everything.sh.  It's 1.14.1 on CR master
