### ISSUE TITLE
pkg/cache methods should implement deadline semantics for context parameter

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/controller-runtime#41]
All exported methods on client interface takes in `context.Context` parameter, but the methods don't implement the deadline semantics.

**Comment by DirectXMan12** [comment]
/remove-lifecycle rotten

IIRC, this is still a problem for the unstructured client

**Comment by DirectXMan12** [comment]
will be fixed by #580

**Comment by vincepri** [comment]
/help
/assign @alexeldeib 

/priority awaiting-more-evidence 
might or might not be fixed by #663

**Comment by alexeldeib** [comment]
#663 fixes the cache semantics, but the unstructured client doesn't plumb through context. We can either track that here or in a separate issue, since there's already so many around context. I can start working on plumbing the context for the unstructured client.

**Comment by alexeldeib** [comment]
#663 and #812 both merged, so:

/close
