### ISSUE TITLE
Request of a new release with the commit fc804a4 (Adding multinamespaced cache)

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#413]
Hi folks, 

We have the need to pass a List of Namespaces when a manager is created as it was attended in the commit  https://github.com/kubernetes-sigs/controller-runtime/commit/fc804a411c06919561edbcb0453601c436556613. Our need is the same of this test [here](https://github.com/kubernetes-sigs/controller-runtime/blob/68ae79ea094aab567d78d7d8596accac2dc27fd0/pkg/manager/example_test.go#L59). See that is solved before the [v0.2.0-alpha.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.2.0-alpha.0) but just released on it.

Unfortunately, appears that the [v0.2.0-alpha.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.2.0-alpha.0)  has break changes and cannot be used with the current version of OCP 3.11 and the Kube used by it. 

We would like to kindly ask if you folks could please release a new version based on the latest stable release just with this commit https://github.com/kubernetes-sigs/controller-runtime/commit/fc804a411c06919561edbcb0453601c436556613 for we are able to use it.    

Really thank you for your attention and support.  

c/c @shawn-hurley

**Comment by DirectXMan12** [comment]
The referenced commit is a breaking change (as per the :warning: icon in front of it), so it *has* to be in a "major" version.  Hypothetically, we could've done just that in v0.2.0, and then did everything else in v0.3.0, but that ship has sailed a bit with the alpha.

> Cannot be used with the current version of OCP 3.11 and the Kube used by it.

What specific issues are you encountering?  The v0.2.0-alpha.0 should work fine against Kube 1.11 clusters, so I'd love to know what's not working properly.

**Comment by camilamacedo86** [comment]
HI @DirectXMan12,

Really thank you for your reply. It will be really wonderful if you be able to release a new version based on the latest release with just this commit because it shows the only way to solve properly our need. 

We need to make sure that the "operator will only watch a List of namespaces" for further detail as the code and versions used you can check it here: https://github.com/operator-framework/operator-sdk/issues/1386. We raised this question to ask what to do to solve it if you folks cannot do this release. 

I am afraid that may we cannot use the alpha one with the version of Kube used in OCP 3.11 (1.11). Am I right? Could you help me find an alternative to attend this need without a release or if possible do this release?

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,

We could solve the break changes here : https://github.com/operator-framework/operator-sdk/pull/1388 .
Now, we are just waiting for you to release the stable version of v0.2.0-alpha.0 for we are able to move forward. Really tks.

**Comment by camilamacedo86** [comment]
Hi @DirectXMan12,

I am closing this PR since we are waiting for the final release. Really tks for your explanation.
