### ISSUE TITLE
pkg/cache's reader methods should block until caches are sync'd

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/controller-runtime#42]
This should also respect the deadline semantics for the context argument.

**Comment by calind** [comment]
Is there a way to wait for the client to sync it's caches? I'm experiencing data races in tests where the manager and the client.Get try to sync the caches.

**Comment by DirectXMan12** [comment]
we should already be doing that for the cache, but yeah, there's a function to wait for the caches to sync on the `Cache` interface called `WaitForCacheSync`.

**Comment by nvachhar** [comment]
I just filed #370. I'm not sure if this is the same thing that this issue is mentioning.

**Comment by DirectXMan12** [comment]
I believe this is fixed now, as per #370.
