### ISSUE TITLE
Bug in manager_test

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/controller-runtime#429]
/kind bug

https://github.com/kubernetes-sigs/controller-runtime/blob/d6324a464299673cd0f8edd456f7a9f62fd22c90/pkg/manager/manager_test.go#L254-L286

This piece of code should expect an error in the end but actually it's not.

This test case should not panic, it should not use `GinkgoRecover`.

Probably there is a bug in the test.

**Comment by mengqiy** [comment]
cc: @droot @DirectXMan12

**Comment by DirectXMan12** [comment]
You almost always want to use GinkgoRecover when spawing goroutines (which a runnable is), and just about anything *can* panic (yay side effects not captured by the type system).  In this case, for instance, if that channel is somehow nil, the test could panic.

**Comment by vincepri** [comment]
Closing in favor of https://github.com/kubernetes-sigs/controller-runtime/issues/764

/close
