### ISSUE TITLE
self-generated secret for webhook does not seem to generate a compliant tls secret

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/controller-runtime#430]
self-generated webhook secrets do not seem to follow the standard rules for tls secrets. Which to my undertsanding are:
1. the secret must be of type `kubernetes.io/tls`
2. the keys should be `tls.key`, `tls.crt`, `ca.crt`. ca.crt should contain the entire ca_bundle, so there should not be a need for a fourth file. 
From what I see the code does not set the type of the secret and generates the followinf keys:
```
const (
	// CAKeyName is the name of the CA private key
	CAKeyName = "ca-key.pem"
	// CACertName is the name of the CA certificate
	CACertName = "ca-cert.pem"
	// ServerKeyName is the name of the server private key
	ServerKeyName = "key.pem"
	// ServerCertName is the name of the serving certificate
	ServerCertName = "cert.pem"
)
```
Which I guess are  the files expected by the code. 
This limits interoperability with other mechanism of generating secrets.

**Comment by DirectXMan12** [comment]
we've removed self-generating certificates in v0.2.0, so this is less of an issue (and changing it might be a breaking change).  I'm going to close this, but if you have an argument for why it wouldn't be a breaking change to the 0.1.x branch, I'd be happy to review a PR there.
