### ISSUE TITLE
Dependency(client) injection in webhook

### ISSUE THREAD

**Issue by jiachengxu** [kubernetes-sigs/controller-runtime#451]
Hi folks,
Are there any smart ways to inject the client into the webhooks of CRDs? Because in my case, I also want to do some lookups by using the `client.Get`  in the `ValidatingCreate`.
Thanks,
Jiacheng

**Comment by jiachengxu** [comment]
ping @thetechnick

**Comment by adohe** [comment]
@jiachengxu u may reference [this example](https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/builtins/validatingwebhook.go),  controller-runtime will inject client into ur webhook automatically.

**Comment by jiachengxu** [comment]
Hi @adohe, thanks for your useful reference!
Actually, we are trying to inject the client into the webhooks of **CRDs**, and we are following this [example](https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/crd/pkg/resource.go), any ideas about how to inject client into webhook in this case?
Thanks,
Jiacheng

**Comment by jiachengxu** [comment]
Hi @adohe,
Thanks for your information, actually we tried to re-implement our webhooks as you mentioned, and it works! Thanks for your help :)
Thanks,
Jiacheng
