### ISSUE TITLE
All was working until the v.0.2.0-alpha.1 of the controller-runtime be released. From v0.2.0-alpha.0 to v0.2.0-alpha.1 .

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#454]
## WHAT:

```
# github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/metrics
vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go:292:63: undefined: workqueue.HistogramMetric
vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go:296:68: undefined: workqueue.HistogramMetric
# github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/client
vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go:364:7: undefined: v1.PatchOptions
# github.com/operator-framework/operator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection
vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go:83:25: too many 
```

Place: https://github.com/operator-framework/operator-sdk/pull/1388

**Comment by DirectXMan12** [comment]
looks like a dependency issue.  Are you using dep or modules?  In either case, can you paste your dependency list (`Gopkg.toml` in the case of dep, or `go.mod` in the case of modules)

**Comment by camilamacedo86** [comment]
H @DirectXMan12,

I thought the same. However, after checking the changes made between both releases shows that just the kube was changed and it was applied as well.  See here the deps: https://github.com/operator-framework/operator-sdk/pull/1388/files#diff-836546cc53507f6b2d581088903b1785

Also, note that the issues are explicit in the "vendor/sigs.k8s.io/controller-runtime/pkg/"

**Comment by camilamacedo86** [comment]
Closing since we confirm that the problem is with OLM which is not using ks8 1.14+
