### ISSUE TITLE
Helper to fetch config using a particular kubeconfig context

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#479]
It would be nice if a `--context` flag would be supported (same semantics as in kubectl).

Use Case:
I'm developing locally on a ClusterAPI controller (which uses controller-runtime). It's kind of dangerous, if it uses whatever the current context is in my local kubeconfig. It would be nice to just "pin" the context via command-line flag.

I would like to open a PR, if this feature makes sense to you.

**Comment by DirectXMan12** [comment]
we're trying to avoid adding new flags (in fact, IMO, a library shouldn't register any flags).  That being said, I believe we currently respect the `KUBECONFIG` environment variable, so that should solve your usecase, I believe.

**Comment by sbueringer** [comment]
Kind of, yes. Currently I'm storing multiple clusters in the same kubeconfig so the current context is used. Of course if the current context changes after a restart the controller uses that one.

But you're right it makes absolutely sense to not add flags as a library. 

In my case it's okay. I just cannot use the sigs.k8s.io/controller-runtime/pkg/client/config.GetConfig() method but there are enough helper functions in client-go/tools/cliencmd to build a config and than create a new manager with manager.New().

**Comment by DirectXMan12** [comment]
ah, sorry, triaging too fast and misread :woman_facepalming: .  We should add a method for getting the config with a given context -- that seems pretty reasonable.

**Comment by sbueringer** [comment]
Ah yeah you're right that would also make sense. To avoid an additional flag, but make it possible to retrieve a specific context of the auto-discovered config. It would start working on this and open a PR for it.
