### ISSUE TITLE
Multiple CRDs in single yaml file ignored by envtest.InstallCRDs()

### ISSUE THREAD

**Issue by nstogner** [kubernetes-sigs/controller-runtime#480]
`envtest.InstallCRDs()` silently ignores all CRDs defined in a yaml file past the first definition.

- Documents in yaml file were seperated by `---`.
- `envtest.CRDInstallOptions.Paths` was used to specify directories containing the yaml files.

Suspect code (`pkg/envtest/crd.go`) in `func readCRDs(path string)` only unmarshals into a single struct:

```go
		// Unmarshal the file into a struct
		b, err := ioutil.ReadFile(filepath.Join(path, file.Name()))
		if err != nil {
			return nil, err
		}
		crd := &apiextensionsv1beta1.CustomResourceDefinition{}
		if err = yaml.Unmarshal(b, crd); err != nil {
			return nil, err
		}
```

**Comment by adohe** [comment]
I will take a look asap.

**Comment by GrigoriyMikhalkin** [comment]
@nstogner 
Looking at code snippet, i think you using older version of `controller-runtime`. Can you please confirm that?

Issue with multiple CRDs was fixed in https://github.com/kubernetes-sigs/controller-runtime/pull/397

**Comment by nstogner** [comment]
I was on v0.1.1, sorry for the oversight.
