### ISSUE TITLE
envtest.Environment.Start() silently fails for missing CRD paths

### ISSUE THREAD

**Issue by nstogner** [kubernetes-sigs/controller-runtime#481]
There is no way to specify `envtest.CRDInstallOptions.ErrorIfPathMissing = true` when calling `envtest.Environment.Start()`. As a result, silent failure in the case of missing CRD directories is the default and only behavior when using `.Start()`.

Workaround:

Call `envtest.InstallCRDs()` directly:

```go
	t.Start()
	// ...
	if _, err := envtest.InstallCRDs(t.Config, envtest.CRDInstallOptions{
		Paths: []string{
			filepath.Join("..", "..", "..", "config", "crds"),
			filepath.Join("..", "..", "..", "third_party", "crds"),
		},
		ErrorIfPathMissing: true,
	}); err != nil {
```

**Comment by DirectXMan12** [comment]
/kind feature
/priority backlog
/good-first-issue

This is probably pretty easy to add.  We should have that option.

**Comment by shufanhao** [comment]
Could I grab this issue for me to fix it as my first k8s issue ? BTW, could you give me a direction to fix it ? Thanks

**Comment by nstogner** [comment]
Hey @shufanhao, if it were me I would add a field like `ErrorIfCRDPathMissing` field to `envtest.Environment` and pass it in to the call to `InstallCRDs` in the `Start()` method. See links below for reference.

https://github.com/kubernetes-sigs/controller-runtime/blob/b5e34e45a56a75cec5b47f2b9a346527fe93c859/pkg/envtest/server.go#L75

https://github.com/kubernetes-sigs/controller-runtime/blob/b5e34e45a56a75cec5b47f2b9a346527fe93c859/pkg/envtest/server.go#L206

**Comment by connor1989** [comment]
@shufanhao are you still tracking this one? I have some bandwidth tomorrow otherwise

**Comment by shufanhao** [comment]
> @shufanhao are you still tracking this one? I have some bandwidth tomorrow otherwise

@connor1989 , sorry be late for response, you can take it.
