### ISSUE TITLE
Reconcile is triggered twice for mapped requests

### ISSUE THREAD

**Issue by timuthy** [kubernetes-sigs/controller-runtime#490]
The `EnqueueRequestsFromMapFunc` event handler calls its enclosed `Mapper` twice in case of an update event.

https://github.com/kubernetes-sigs/controller-runtime/blob/c1cf624e468ab84b9f25cc76b17d36d0f9573055/pkg/handler/enqueue_mapped.go#L51

As a consequence, the `Reconcile` function is possibly also called twice for a single event which may be inappropriate for users and can also be confusing because this behavior isn't obvious, imho.

I'd suggest to add more context to the `MapObject` and let the `Mapper` decide which information - old/new or both objects - to use for mapping a request.

/cc @adracus

**Comment by DirectXMan12** [comment]
That's actually completely intentional -- when an object gets updated, the mapping can change completely (e.g. you might've changed the `secretName` field to something else, for instance), so you need to enqueue both to handling things properly.

In general, we don't want to encourage people writing to specific actions, and it's my suspicion that giving more context to `MapObject` would allow for that.

That being said, I'm always open to debate, so feel free to lay out what's causing you issues in more detail, or present a counter argument :-)

**Comment by BuddhiWathsala** [comment]
As a suggestion, I think it is better to call reconcile loop twice if there is a spec change of the object. When it comes to object status it is redundant to call the reconcile twice. 

In the reconcile loop we normally change the `status` of the object to show the current status of the object to the user(for example object is in Running mode or Failure mode). Even for that status change, I notice there are multiple reconcile loop calls triggered.

I have used even predicates to stop these redundant calls and it only prevents it to a certain extent.

**Comment by andreasgerstmayr** [comment]
> That's actually completely intentional -- when an object gets updated, the mapping can change completely (e.g. you might've changed the `secretName` field to something else, for instance), so you need to enqueue both to handling things properly.

Could you please elaborate on that with a (more) concrete example? I'm running in the same issue and don't understand the reasoning explained here. Currently the mapper gets called once with the old object and again with the new object: https://github.com/kubernetes-sigs/controller-runtime/blob/9fd57745d6e93f85ee59e2a3b17f3d84dc5ef688/pkg/handler/enqueue_mapped.go#L61-L65

What's the purpose of calling the handler with the old version of the object (and creating a reconcile request), shouldn't the cluster already be reconciled with the old version of the object?

**Comment by rfranzke** [comment]
It seems this has been fixed with https://github.com/kubernetes-sigs/controller-runtime/pull/1390, part of `v0.9+` (see also previous PR https://github.com/kubernetes-sigs/controller-runtime/pull/1380 for some more context information).
