### ISSUE TITLE
Better handling `kind is not registered in scheme` error

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/controller-runtime#492]
When a kind is not registered in the scheme, it returns a typed error. We should handle it and return a more user friendly error message.

**Comment by vincepri** [comment]
There is a log message now that explains this a bit more https://github.com/kubernetes-sigs/controller-runtime/blob/98e2435ba8888cb3332978e4aaa02b31e3e2e73a/pkg/internal/source/kind.go#L62-L66 in a few cases

/close
