### ISSUE TITLE
Understanding Client/Informer/Indexer interaction in Reconcile

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes-sigs/controller-runtime#498]
I am trying to understand how does the controller-runtime pattern of using client.Get() in Reconcile() function compares with sample-controller's Lister call to obtain an Object from local index cache given a key.

Specifically, following two lines:

https://github.com/kubernetes/sample-controller/blob/master/controller.go#L251

and

https://github.com/kubernetes-sigs/controller-runtime/blob/master/examples/crd/main.go#L51

In sample-controller, we get access to Listers which read from the local indexer cache.
In the CRD example of controller-runtime, there is no Lister or Indexer exposed to the user. And it seems like client.Get() reads directly from the API server as per https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L99.

Is this correct understanding?

**Comment by shawn-hurley** [comment]
The controller runtime client by default is: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/split.go#L29

This is where it is set up:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L284

You can see that Reader is set to use the cache, which will use the cache, which is an abstraction over the informer cache. Which means it will not read directly from the API server every time! 

Hope that helps!

**Comment by DirectXMan12** [comment]
Closing as per shawn's response.  feel free to continue asking questions here, though

/triage support
