### ISSUE TITLE
The XYZDryRunAll functions are frustratingly numerous

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#503]
Our current "functional options" scheme works well for providing fluent options, but isn't so great when multiple function calls need to share a particular option -- see `PatchDryRunAll`, `UpdateDryRunAll`, and `CreateDryRunAll`.

AFAICT, the only way around this that provides type proper type checking & doesn't break backwards compatibility if we need to extend the set of things the option applies to looks like this:

```go
type Writer interface {
     Patch(ctx context.Context, obj runtime.Object, patch Patch, opts ...PatchOption) error 
     Create(ctx context.Context, obj runtime.Object, patch Patch, opts ...CreateOption) error
     Update(ctx context.Context, obj runtime.Object, patch Patch, opts ...UpdateOption) error
}

type PatchOption interface {
    ApplyToPatch(*PatchOptions)
}
type CreateOption interface {
    ApplyToCreate(*CreateOptions)
}
type UpdateOption interface {
    ApplyToUpdate(*UpdateOptions)
}

type DryRunAllOption struct {}
func (_ DryRunAllOption) ApplyToPatch(opts *PatchOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToCreate(opts *CreateOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToUpdate(opts *UpdateOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToDeleteCollection(opts *DelCollOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}

var DryRunAll DryRunAllOption = DryRunAllOption{}
```

It yields the same usage:

```go
// Today:
err := cl.Update(ctx, obj, client.UpdateDryRunAll)

// Probably not the darkest timeline:
err := cl.Update(ctx, obj, client.DryRunAll)
```

It's slightly more verbose from a options-writing perspective, and puts another public type in our API surface, but means that we can safely add methods to that type as they come along w/o breaking compatibility (because neither function signature or interface signature need to change -- we just add methods to the struct's method set, which is a compatible operation).

It's something to think about.  If anyone else has any ideas, please write them here.

/kind feature

#### Rejected alternatives

* Similar to above, but `var DryRunAll interface{CreateOption; PatchOption} = dryRunAllOption`: hides the public type from our API surface, but changing that interface to add another (say, `UpdateOption`) causes a change in the type signature for functions that return one of these (e.g. `func GracePeriodSeconds(gp int64) interface{ListOption; DeleteOption}` --> `func GracePeriodSeconds(gp int64) interface{ListOption; DeleteOption; UpdateOption}`)

**Comment by DirectXMan12** [comment]
Alternative (precludes the use of functions, 'cause Go won't coerce those)
 
```go
type Writer interface {
     Patch(ctx context.Context, obj runtime.Object, patch Patch, opts ...PatchOption) error 
     Create(ctx context.Context, obj runtime.Object, patch Patch, opts ...CreateOption) error
     Update(ctx context.Context, obj runtime.Object, patch Patch, opts ...UpdateOption) error
}

type PatchOption interface {
    ApplyToPatch(*PatchOptions)
}
type CreateOption interface {
    ApplyToCreate(*CreateOptions)
}
type UpdateOption interface {
    ApplyToUpdate(*UpdateOptions)
}

type dryRunAllOption struct {}
func (_ DryRunAllOption) ApplyToPatch(opts *PatchOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToCreate(opts *CreateOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToUpdate(opts *UpdateOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}
func (_ DryRunAllOption) ApplyToDeleteCollection(opts *DelCollOptions) {
    opts.DryRun = []string{metav1.DryRunAll}
}

var DryRunAll interface{PatchOption;CreateOption;UpdateOption} = dryRunAllOption
type FieldOwner string
func (f FieldOwner) ApplyToCreate(opts *CreateOptions) {
    opts.FieldManager = string(f)
}

// A future with a few more beings from beyond space & time:
err := cl.Create(ctx, obj, client.DryRunAll, client.FieldOwner("my-controller"))
```

This differs in that the public type isn't in our API.  Go'll type-coerce that interface down into "smaller" interfaces, to adding additional methods/other interfaces to the list in the anonymous interface in `DryRunAll` is fine.  Functions can't be used because go won't type coerce them (they have differing return values), but we can "fake" single-argument functions with type aliases (which otherwise look the same as the option produced above).

I'm not convinced this is better, but it's a bit different.

**Comment by mengqiy** [comment]
There were syntax errors in the above comment. I updated it and you can find what I have changed in the revision history.

From GoDoc perspective, I'm leaning towards the latter one.

**Comment by DirectXMan12** [comment]
In either case, the type alias approach is growing on me aesthetically speaking, regardless of the approach taken WRT to options that don't take arguments (public return types vs anonymous interfaces).

**Comment by droot** [comment]
The type alias approach appears to be more elegant IMO.
