### ISSUE TITLE
Need a README.md file for examples/

### ISSUE THREAD

**Issue by functicons** [kubernetes-sigs/controller-runtime#506]
I think we need a README.md file for [examples/](https://github.com/kubernetes-sigs/controller-runtime/tree/master/examples) to explain: 1) what the examples are about; 2) how to build and run these examples.

**Comment by devdattakulkarni** [comment]
+1

**Comment by hasheddan** [comment]
Happy to take this one!

**Comment by functicons** [comment]
Thank you very much!
