### ISSUE TITLE
Better labels for reflector metrics

### ISSUE THREAD

**Issue by ksurent** [kubernetes-sigs/controller-runtime#509]
Hi,

the labels attached to reflector metrics currently are hardly readable or even useful:

```
reflector_list_duration_seconds{name="reflector_sigs_k8s_io_controller_runtime_pkg_cache_internal_informers_map_go_126_4141",quantile="0.99"} 0.00408348
```

All we have is a callsite that's common for all informers inside a controller. I think a breakdown by GVK could be helpful. What do you think?

PS: I realise that to improve this situation the majority of work will likely need to be done in `k8s.io/client-go/pkg/cache`, not here.

**Comment by DirectXMan12** [comment]
I think something's borked with the auto-reflector-naming code that went into client-go.  Someone tried to be too clever.

**Comment by ksurent** [comment]
Related: https://github.com/kubernetes/kubernetes/pull/74636.
