### ISSUE TITLE
Support adding new watches dynamically at runtime

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/controller-runtime#540]
This feature was added before (and requested in #246), but the updated Manager & Builder patterns don't support this any more because they take care of creating a Controller instead of having user-written code do it, and the Controller isn't accessible to your reconciler.

There was a discussion about this in Slack (https://kubernetes.slack.com/archives/CAR30FCJZ/p1561759175084100). I'm thinking we could modify the inject package like so (names TBD - I know they don't follow the current pattern 100% but we need to scope down the Controller interface to avoid import cycles):
```go
type Watcher interface {
  Watch(src source.Source, eventhandler handler.EventHandler, predicates ...predicate.Predicate) error
}

type WatcherInjector interface {
  InjectWatcher(watcher Watcher)
}
```

Do you think something like this would work @DirectXMan12?

**Comment by ncdc** [comment]
cc @vincepri

**Comment by DirectXMan12** [comment]
We're trending towards not adding more injectors when they're not strictly needed by internals -- most cases are more obviously solved by structuring your application so that you can pass them to your reconcilers directly (like we do in KB v2).

Thus, I'd prefer to see a solution to this that makes it possible to get a handle to the underlying controller with the builder somehow.  If we can't figure out how to do that cleanly, an injector is fine, but I'd prefer the more direct approach.

**Comment by ncdc** [comment]
Ok, I'll do some brainstorming to see what I can come up with.

**Comment by ncdc** [comment]
@DirectXMan12 what if we modify `build.Complete()` to return the controller it just created? Then the user can do whatever they want with it (including passing it to their reconciler).

**Comment by ncdc** [comment]
Or expose a `GetController()` method on `Builder`

**Comment by vincepri** [comment]
+1 On having either a method to get the controller or `Complete()` to return the created controller and an error. Today [kubebuilder invokes ctrl.NewControllerManagedBy(...)](https://github.com/kubernetes-sigs/kubebuilder/blob/v2.0.0-beta.0/pkg/scaffold/v2/controller.go#L98) which usually, I'd think it's going to return a new `Controller` object that I can use.

**Comment by DirectXMan12** [comment]
I'd prefer not `Complete` (just to avoid breakage of a commonly used function, if we can), but I'm on board with a similar method.  Since `Build` has been deprecated for a couple releases now, we could repurpose that (although it could lead to breakage) or come up with a new method.

**Comment by ncdc** [comment]
I don't think we'd want 2 different ways to complete/build - 1 that returns a controller, and 1 that doesn't - would we?

**Comment by ncdc** [comment]
Summarizing our discussion from Slack yesterday (https://kubernetes.slack.com/archives/CAR30FCJZ/p1564433195123400), we're going to un-deprecate `Build` and have it return the `Controller` instead of the `Manager`. We're also going to remove the logic in the builder that creates a manager for you if you don't pass one in.

**Comment by karthick18** [comment]
If I use Build to save controller instance and then at runtime in my reconciler, when I try to add a watch on the controller that is already started (as mgr is started),
