### ISSUE TITLE
Read existing controllers from manager

### ISSUE THREAD

**Issue by michaelhenkel** [kubernetes-sigs/controller-runtime#547]
I have a use case where one controller dynamically registers other controllers with manager. The initial registration works fine but then I need to check if the controllers are already registered with the manager, otherwise new controllers are created even though they already exist.
I was hoping that something like
```
sharedIndexInformer, err := r.cache.GetInformerForKind(configResource.GroupVersionKind())
if err == nil {
    controller := sharedIndexInformer.GetController()
    if controller != nil {
        controllerRunning = true
    }
}
```
would tell me if there is a controller for a certain GVK already exists but GetInformerForKind() seems to create an informer in case there is none, so controllerRunning is always true in that case.

**Comment by DirectXMan12** [comment]
since the shared index informers are, by definition, shared, that would not work (plus, you can have multiple controllers for a GVK anyway).  I'd recommend keeping track of which controllers you register externally, and using that as the source of truth.
