### ISSUE TITLE
DeleteCollection does not work with Limit and Continue list options

### ISSUE THREAD

**Issue by rajathagasthya** [kubernetes-sigs/controller-runtime#548]
PR #341 is trying to add Limit and Continue list options for paging. But there's no way to make it work with `DeleteCollection` because there is no way to grab the continue token returned by the server to delete the next page of things.

**Comment by DirectXMan12** [comment]
/kind bug

we need to fix this before the v0.2.0 release

**Comment by DirectXMan12** [comment]
somehow

**Comment by DirectXMan12** [comment]
The fix to this is fairly straightfoward -- accept a list object instead of a single object, and populate it with the results.

**Comment by DirectXMan12** [comment]
See also https://github.com/kubernetes/kubernetes/issues/80877

**Comment by DirectXMan12** [comment]
might have to wait for an update on that ^

**Comment by adohe** [comment]
sure, I will take this.

**Comment by DirectXMan12** [comment]
(note that there's some discussion on the above issue, so be aware.  We might want to switch anyway, though, since getting back the list of deleted objects *could* be nice).

**Comment by serbrech** [comment]
@DirectXMan12 DeleteAllOf is not in the 0.2.0-beta4 release, is it supposed to be in the final 0.2.0 release?

https://github.com/kubernetes-sigs/controller-runtime/blob/aaddbd9d9a89d8ff329a084aece23be0406e6467/pkg/client/interfaces.go#L65

**Comment by DirectXMan12** [comment]
It's in master now.  It'll be in the final release.

**Comment by DirectXMan12** [comment]
upstream consensus seems to be that supporting this is a mistake.  Plus, we can add support for passing list objects in the future w/o making breaking changes, so we can drop this for now

**Comment by rajathagasthya** [comment]
@DirectXMan12 So what needs to be dropped here? Not adding `Limit` and `Continue` support means pagination is not supported for list. But `DeleteCollection` doesn't permit adding that. In other words, how can we add limit and continue without affecting DeleteCollection?

**Comment by DirectXMan12** [comment]
We can add limit and continue support to list options, and just not support the functional option variants on deletecollection calls.  You'll still be able to manally set them in the DeleteCollectionOptions struct if you really want, but if you do that, then you've explicitly gone out of your way to break yourself.

**Comment by vincepri** [comment]
See https://github.com/kubernetes/kubernetes/issues/80877 upstream issue for more information
