### ISSUE TITLE
Release 0.1.x is tied to kubernetes 13.4. 

### ISSUE THREAD

**Issue by rohantmp** [kubernetes-sigs/controller-runtime#561]
Would it be possible to backport 14.x support? or is version tied to kube version? Sorry if this is a dumb question.

**Comment by coderanger** [comment]
The Kubernetes version that your operator is built against does not have to match the version you are running against. All Kubernetes APIs are versioned and backwards compatible within specific deprecation timelines.

**Comment by rohantmp** [comment]
I understand that this is true about the cluster, but the operator I want to incorporate controller-runtime into uses informer callbacks. It's [Gopkg.toml](https://github.com/rook/rook/blob/master/Gopkg.toml) has constrained the kube version to 14. I can upgrade it to 14.1 and use your 0.2  release but it's in beta.

**Comment by DirectXMan12** [comment]
for various reasons, we're unlikely to attempt to update v0.1.x to 1.14, unfortunately.

**Comment by rohantmp** [comment]
Ok, looks like we're going with the 0.2 release. Any major known issues? I don't see anything alarming when filtering `is:issue is:open label:kind/bug `

**Comment by DirectXMan12** [comment]
Hopefully not.  We've one item (give or take) left for all the projects included in KubeBuilder v2 before release (the one item is not CR related, though).  You can track progress here: https://github.com/kubernetes-sigs/kubebuilder/projects/6

**Comment by DirectXMan12** [comment]
closing for now for bookkeeping, but feel free to continue commenting.
