### ISSUE TITLE
GetConfig does not respect multi-value KUBECONFIG

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#564]
`GetConfig` doesn't respect multi-value KUBECONFIG, and it should, according to the [docs on kubeconfig](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).

`clientcmd` has code to do this -- we should audit our config loading logic and see if we can lean on clientcmd more agressively to match desired behavior.

re-filed from kubernetes-sigs/kubebuilder#936

/kind bug
/priority important-soon

**Comment by joelanford** [comment]
@ericzhang08 did you get a chance to work on this? If not, I'm planning to pick this up and submit a PR.
