### ISSUE TITLE
typedclient.Patch should not send the patch request when patch.Data got no change

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/controller-runtime#565]
in [this issue](https://github.com/kubernetes-sigs/cluster-api/issues/1259) we call the  typeClient.Patch and Status.Patch to update our crd, but if we got only status change or spec change, we should not send the request to avoid trigger another update event.

**Comment by DirectXMan12** [comment]
it's up to you to determine whether or not to send the patch request.  We can't determine if a patch will have some effect or not client-side.
