### ISSUE TITLE
checksum mismatch in jsonpatch when depending on controller-runtime

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/controller-runtime#570]
Hi,

I've got a problem with checksum mismatches when depending on controller-runtime rc.0. It's explained in detail here: https://github.com/kubernetes/test-infra/pull/13918

I would propose updating the dependency to `gomodules.xyz/jsonpatch/v2 v2.0.0-20190626003512-87910169748d` to avoid this problem.

**Comment by DirectXMan12** [comment]
/kind bug
/priority critical-urgent

seems reasonable.  Can you submit a PR?

**Comment by sbueringer** [comment]
@DirectXMan12 Yup. Done. I'm just not sure if it's enough to adjust go.mod & go.sum
