### ISSUE TITLE
Cannot specify per-watch predicates on builders

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/controller-runtime#572]
however, it had no problem in v1

**Comment by DirectXMan12** [comment]
need to change the builder interface ever so slightly to allow for per-watch predicates.

**Comment by mszostok** [comment]
Hi,

I can provide a PR for that, are you interested?

**Comment by DirectXMan12** [comment]
/lifecycle frozen

waiting to make a set of breaking changes
