### ISSUE TITLE
Finalize namespace

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/controller-runtime#573]
Because of legacy reasons namespaces in addition to `.meta.finalizers` have also `.spec.finalizers`. There is also a separate endpoint for the purpose `PUT /api/{version}/namespaces/{namespace}/finalize` - see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/namespaces.md#rest-api and https://github.com/kubernetes/kubernetes/issues/77086#issuecomment-486832745.

`k8s.io/client-go` has `clientset.CoreV1().Namespaces().Finalize(ns)` that can finalize namespace. 

I would be great if controller-runtime client can also perform this action.

**Comment by DirectXMan12** [comment]
/kind feature

I *think* we have someone working on generic subresource support, which would bring in this as well.

**Comment by DirectXMan12** [comment]
#172

**Comment by ialidzhikov** [comment]
Ok, then closing this one in favour of #172.
