### ISSUE TITLE
client.MatchingFields should be a fields.Selector

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/controller-runtime#576]
As far as I know, there's no way to parse a field selector string, ex. from [`v1.ListOptions.FieldSelector`](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#ListOptions) into a [`fields.Set`](https://godoc.org/k8s.io/apimachinery/pkg/fields#Set), making it hard to create [`client.MatchingFields`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#MatchingFields) from a string. You could directly construct the Set (which is just a map) by manually splitting out keys and values, but the accepted way to do this is to directly parse the string into a [`fields.Selector`](https://godoc.org/k8s.io/apimachinery/pkg/fields#Selector) using [`fields.ParseSelector()`](https://godoc.org/k8s.io/apimachinery/pkg/fields#ParseSelector). You can also create a Selector from a Set using [`fields.SelectorFromSet()`](https://godoc.org/k8s.io/apimachinery/pkg/fields#SelectorFromSet), so a map can still be used directly without much extra effort. Additionally a Selector has more matching options than a Set, which only checks for equality.

I suggest either changing the underlying type of `client.MatchingFields` to `fields.Selector`, or creating a separate `client.MatchingFieldsSelector` that implements `client.ListOption` and `client.DeleteAllOfOption` with an underlying type of `fields.Selector`.

/cc @DirectXMan12 @mengqiy

**Comment by mengqiy** [comment]
> I suggest either changing the underlying type of client.MatchingFields to fields.Selector, or creating a separate client.MatchingFieldsSelector that implements client.ListOption and client.DeleteAllOfOption with an underlying type of fields.Selector.

The former one is a breaking change. Since CR v0.2.0 has been released, we probably need to go with the latter option if we want to do it in a patch release.

cc: @droot
