### ISSUE TITLE
Update to 0.3.0 or later of gnostic import

### ISSUE THREAD

**Issue by fejta** [kubernetes-sigs/controller-runtime#583]
A bad `v0.2.1` release makes it impossible for people to patch upgrade controller-runtime

Repro:
```console 
$ GO111MODULE=on GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org go get -u=patch sigs.k8s.io/controller-runtime

go: finding github.com/googleapis/gnostic v0.2.1
go get: upgrading github.com/googleapis/gnostic@v0.2.0: github.com/googleapis/gnostic@v0.2.1: reading https://proxy.golang.org/github.com/googleapis/gnostic/@v/v0.2.1.info: 410 Gone
```

See https://github.com/googleapis/gnostic/issues/147 for more details about why this is failing.

**Comment by fejta** [comment]
Fixed by #584 
/close

**Comment by fejta** [comment]
/reopen

/assign @DirectXMan12 

Would you be up for me pulling #584 into v0.2.0 and creating a v0.2.1 patch release with this change?

**Comment by DirectXMan12** [comment]
yeah, can do that now
