### ISSUE TITLE
client.New should not connect to cluster

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/controller-runtime#586]
client.New currently connects to the cluster, unlike the equivalent client-go functions.  This makes switching to controller-runtime harder, because the failure point for "cluster not available" moves.

We should have a wrapper which supports deferred construction of client.New, so that the failure site moves to the "connecting methods" e.g. Get

**Comment by DirectXMan12** [comment]
client.New only connects to the cluster for discovery, IIRC.  We're switching to a lazy discovery client (that also refreshes) by default in #554, so that *should* solve this issue I think.

**Comment by DirectXMan12** [comment]
we have support for lazy discovery now, so I think we can close this
