### ISSUE TITLE
Expose a union interface for metav1.Object and runtime.Object

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#594]
Most (all?) Kubernetes API types implement both metav1.Object and runtime.Object. Code that needs both usually accepts either, then type asserts for the other.

It would be nice to have a union interface for the two and re-use that throughout our code

**Comment by munnerz** [comment]
Just my 2c - not all types *do* implement both, only those that are actually created as CRDs.

In cert-manager we have a few extensibility mechanisms that rely on webhooks, and so we use a type that implements TypeMeta but not ObjectMeta: https://github.com/jetstack/cert-manager/blob/master/pkg/acme/webhook/apis/acme/v1alpha1/types.go#L30

This means we implement runtime.Object, but not metav1.Object. This gives us conversion etc. It’s a pattern borrowed from apiextensions-apiserver itself with the AdmissionReview and ConversionReview types.

I think there are places where this sort of union interface could be useful, but we should use it sparingly where it’s actually helpful, and consider that we limit the number of things that can use such a method to those that also have a ‘metadata’ stanza.

**Comment by DirectXMan12** [comment]
Right -- there are places where we actually want to say "we need object metadata", places where we say "we can do more stuff if we have object metadata", and places where all we need is the type.

**Comment by Adirio** [comment]
As I said in #666, unifying the interface in cases when there is a type assertion (and by assertion I mean a type cast that returns an error if it doesn't meet it) would move some errors from run time to compile time and would also allow IDEs to catch this errors. `SetControllerRef` seems to be one of them. Should we make a list and categorize them as @DirectXMan12 suggests (both interfaces required vs extra interface helpful)?

**Comment by DirectXMan12** [comment]
> Should we make a list and categorize them as @DirectXMan12 suggests (both interfaces required vs extra interface helpful)?

:+1: from me

**Comment by ruromero** [comment]
FWIW we introduced the KubernetesResource to our [operator-utils](https://github.com/RHsyseng/operator-utils/blob/master/pkg/resource/types.go) library and found it useful in multiple situations.

As has been already mentioned, this interface can avoid runtime errors and avoid unnecessary type conversions and maybe create higher level abstractions for some methods.

**Comment by alvaroaleman** [comment]
Heads-up for ppl watching this issue, #898 merged so we now have such an union interface in pkg/controller/controllerutil. We don't yet use it anywhere though, hence leaving this issue open until we do use it where it makes sense.

**Comment by fabriziopandini** [comment]
I'm taking a look at this issue and it seems that https://github.com/kubernetes-sigs/controller-runtime/pull/1195 addressed most of it; is there something else left?

**Comment by alvaroaleman** [comment]
@fabriziopandini yeah, this got implemented, seems we just forgot to close the issue. Thank you for looking into it!
