### ISSUE TITLE
client.Get not finding role

### ISSUE THREAD

**Issue by Devin-Holland** [kubernetes-sigs/controller-runtime#595]
I am trying to use client.Get to check to see if a role exists within a namespace.

```
foundRole := &rbacv1.Role{}
	err = r.client.Get(context.TODO(), types.NamespacedName{
		Name:      role.Name,
		Namespace: role.Namespace,
	}, foundRole)
	if err != nil && errors.IsNotFound(err) {
		reqLogger.Info("Role Not Found - Creating")
		err = r.client.Create(context.TODO(), role)
		if err != nil {
			return reconcile.Result{}, err
		}
	} else if err != nil {
		return reconcile.Result{}, err
	} else {
		reqLogger.Info("Updating Role")
		err = r.client.Update(context.TODO(), role)
		if err != nil {
			return reconcile.Result{}, err
		}
	}
```

It falls into the "role not found" if block even though the role exists in the namespace and I have no idea why. Any ideas?

**Comment by DirectXMan12** [comment]
/triage support

Is that a live client, or a cached client (did you construct it with client.New, or mgr.GetClient)?

**Comment by Devin-Holland** [comment]
I'm using the operator-sdk which uses mgr.GetClient() 

To note, this worked with namespaces and ClusterRole and ClusterRoleBinding using 
```
client.ObjectKey{
		Name: namespace.Name,
	}
```

Anything inside of a namespace couldn't be found using ObjectKey or NamespacedName. I was able to get them working by doing the following, but I'm not sure why it wouldn't work without using an unstructured type and setting the GVK myself.

```
foundRole := &unstructured.Unstructured{}
	foundRole.SetGroupVersionKind(schema.GroupVersionKind{
		Group:   "rbac.authorization.k8s.io",
		Kind:    "Role",
		Version: "v1",
	})
	err = r.client.Get(context.TODO(), client.ObjectKey{
		Name:      role.Name,
		Namespace: role.Namespace,
	}, foundRole)
	if err != nil && errors.IsNotFound(err) {
		reqLogger.Info(role.Name + " " + role.Namespace)
		reqLogger.Info("Role Not Found - Creating")
		err = r.client.Create(context.TODO(), role)
		if err != nil {
			return reconcile.Result{}, err
		}
	} else if err != nil {
		return reconcile.Result{}, err
	} else {
		reqLogger.Info("Updating Role")
		err = r.client.Update(context.TODO(), role)
		if err != nil {
			return reconcile.Result{}, err
		}
	}
```

**Comment by DirectXMan12** [comment]
huh, let me try and repro

**Comment by DirectXMan12** [comment]
The following code works acceptably for me: 

```go
package main

import (
    "context"
    "flag"

    ctrl "sigs.k8s.io/controller-runtime"
    "sigs.k8s.io/controller-runtime/pkg/client"
    "sigs.k8s.io/controller-runtime/pkg/log/zap"
    "sigs.k8s.io/controller-runtime/pkg/manager"
    rbac "k8s.io/api/rbac/v1"
    _ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
    "k8s.io/klog"
)

func main() {
    ctrl.SetLogger(zap.Logger(true))
    klog.InitFlags(nil)
    flag.Parse()

    mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{})
    if err != nil {
        panic(err)
    }

    cl := mgr.GetClient()
    ctx := context.Background()

    mgr.Add(manager.RunnableFunc(func(stopCh <-chan struct{}) error {
        var role rbac.Role
        if err := cl.Get(ctx, client.ObjectKey{Name: "system:pod-nanny", Namespace: "kube-system"}, &role); err != nil {
            panic(err)
        }

        ctrl.Log.Info("role", "role", role)
        return nil
    }))

    if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
        panic(err)
    }
}
```

The only way I can reproduce the "not found" is if the manager isn't started at all when I do the call.

**Comment by DirectXMan12** [comment]
(klog imports to see the low-level client-go logs)

**Comment by DirectXMan12** [comment]
Can you post a full reproducer?  Unstructured doesn't go through the cache, which makes me think this is a weird cache issue.

**Comment by DirectXMan12** [comment]
(or just the "haven't started the manager yet", which seems like a bit of a foot-gun to me)

**Comment by Devin-Holland** [comment]
It seems to have just resolved itself during some restart of the operator so I'm assuming there was somehow a caching issue with it not picking up the right values. We are using AKS which has been giving us a lot of issues with the controller manager and the scheduler so it may have been because of that.

I have it working with unstructured and using the normal way with an rbacv1.Role{} now without having changed anything.
