### ISSUE TITLE
unable to decode watch event error with non-conforming CR

### ISSUE THREAD

**Issue by otto-von-bivouac** [kubernetes-sigs/controller-runtime#603]
/kind bug

I am trying to include PersistentVolumeClaimSpec, PodAffinity and other Kubernetes objects into our CR, using Kubebuilder 2.0. When a CR is posted which has non-conforming / invalid PersistentVolumeClaimSpec (for example: `PersistentVolumeClaimSpec.resources.requests.storage` is set to "foo"), then the controller-runtime is throwing the following errors:
```
E0914 08:06:51.835806   31496 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1alpha1.Ioping.Spec: v1alpha1.IopingSpec.Volume: v1alpha1.VolumeSpec.PersistentVolumeClaimSpec: v1.PersistentVolumeClaimSpec.Resources: v1.ResourceRequirements.Requests: Limits: unmarshalerDecoder: unable to parse quantity's suffix, error found in #10 byte of ...|":"1GiKKK"},"request|..., bigger context ...|imSpec":{"resources":{"limits":{"storage":"foo"},"requests":{"storage":"1GiG"}}},"volumeSource":{|...
```

Given that the reconile function is not called at this stage it seems impossible to capture this problem in my controller.

I have found a similar issue reported here: https://github.com/kubernetes/kubernetes/issues/57705#issuecomment-354552314

Is it possible to use the same workaround (watch decodes into `runtime.Unstructured`) in a kubebuilder based setup?

For reference: [controller code](https://github.com/xridge/kubestone/pull/128/files#diff-135e87e23ff10717d00284a62d9d681c) & [CRD spec](https://github.com/xridge/kubestone/pull/128/files#diff-ce0a4dc2d00b3784c6a5fb7accacbff2).

Any help/hint/idea would be appreciated! Thank you!

**Comment by DirectXMan12** [comment]
hmm... we should add regex validation for Quantity from controller-tools so that this doesn't happen.  Can you file a bug in controller-tools?

Separately, you could use an unstructured watch in controller-runtime (pass an unstructured.Unstructured to `.For`), but ideally we'd just fix this by rejecting the bad resource.Quantity at validation time.
