### ISSUE TITLE
move off of github actions HCL syntax

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes-sigs/controller-runtime#610]
@k8s-ci-robot received the following warning for this repo (excerpt)
> ...
> With these updates, GitHub Actions now uses YAML syntax in workflow files. The HCL syntax in GitHub Actions will stop working on September 30, 2019. We are contacting you because you’ve run workflows using HCL syntax in the last week in your account @kubernetes-sigs with the following repos: kubernetes-sigs/cluster-api-provider-docker, kubernetes-sigs/controller-runtime. 
>
> To continue using workflows that you created with the HCL syntax, you'll need to [migrate the workflow files to the new YAML syntax](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax
). Once you have your YAML workflows ready, visit your repositories and follow the prompts to upgrade. Once you upgrade, your HCL workflows will stop working.
> ...

**Comment by DirectXMan12** [comment]
Cool, I'll try again with the new syntax -- nothing was happening last time I tried.

/priority important-soon
