### ISSUE TITLE
"non-exact field matches are not supported by the cache" when using fieldSelector with not exact fields

### ISSUE THREAD

**Issue by sarjeet2013** [kubernetes-sigs/controller-runtime#612]
I am getting the following error when trying to get list of pods with their state filetered with fieldSelector.

"error":"non-exact field matches are not supported by the cache"

Here is the sample code:
```
fieldSelector, err := fields.ParseSelector("spec.nodeName=" + nodeName + ",status.phase!=" + string(corev1.PodSucceeded) + ",status.phase!=" + string(corev1.PodFailed))
activePodsList := &corev1.PodList{}
listOptions := &client.ListOptions{FieldSelector: fieldSelector}
if err := r.List(context.TODO(), listOptions, activePodsList); err != nil {
  return reconcile.Result{}, err
}
```

This look like a current limitation and not supported. See https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/internal/cache_reader.go#L99

**Comment by DirectXMan12** [comment]
it's unclear to me how we'd support this w/o becoming fairly complicated.

/kind feature
/priority backlog

**Comment by lawrencegripper** [comment]
In case anyone else lands here from KubeBuilder and wants an workaround I was able to create a `client` instance without caching using the `mgr` in the autogen'd `main.go` like this:

```golang
directClient, err := client.New(mgr.GetConfig(), client.Options{Scheme: mgr.GetScheme(), Mapper: mgr.GetRESTMapper()})
if err != nil {
	panic(err)
}
```

**Comment by shawn-hurley** [comment]
Another option is to use the `mgr.GetReader()` which will allow you to hit the API server directly with a reader interface.

**Comment by maplain** [comment]
figured out another approach:
1. use client.MatchingFields; 
2. customize the IndexField to make it return a value that is parameterized by multiple fields

eg:
```
m := client.MatchingFields{
  key: getValue(obj)
}

mgr.GetFieldIndexer().IndexField(obj, key, func(xx) []string{
   return []string{getValue(obj)}
})

func getValue(obj) string {
   return obj.Spec.A + "," + obj.Spec.B + "," + obj.Spec.C
}
```

**Comment by kscharm** [comment]
> I am getting the following error when trying to get list of pods with their state filetered with fieldSelector.
> 
> "error":"non-exact field matches are not supported by the cache"
> 
> Here is the sample code:
> 
> ```
> fieldSelector, err := fields.ParseSelector("spec.nodeName=" + nodeName + ",status.phase!=" + string(corev1.PodSucceeded) + ",status.phase!=" + string(corev1.PodFailed))
> activePodsList := &corev1.PodList{}
> listOptions := &client.ListOptions{FieldSelector: fieldSelector}
> if err := r.List(context.TODO(), listOptions, activePodsList); err != nil {
>   return reconcile.Result{}, err
> }
> ```
> 
> This look like a current limitation and not supported. See https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/internal/cache_reader.go#L99

@sarjeet2013 I'm trying to do the same thing you are here (same field selector). Were you able to find a workaround? I have tried the suggestions in the comments, but I think I am going to have to directly hit the API to get this to work.

**Comment by JohnNiang** [comment]
Exactly caused by Line#192:

https://github.com/kubernetes-sigs/controller-runtime/blob/386c2b5b29bace1e1e0b35afd0f6c1acc38cd140/pkg/cache/internal/cache_reader.go#L190-L200

But I really don't know why we need that. I would appreciate it if someone could explain to me.
