### ISSUE TITLE
unexpected behavior in log

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/controller-runtime#614]
ref https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md, we can use following code 
```
logger := log.Log.WithName("controller").WithName("replicaset")
// in reconcile...
logger = logger.WithValues("replicaset", req.NamespacedName)
// later on in reconcile...
logger.Info("doing things with pods", "pod", newPod)
```
in a reconcile. But in some situation, we can not put all the codes in a single function. after dividing the long function into sub function,  i should pass the logger to the sub function to they can share the same logger(doubts here, is there any other better solution?).  This makes the code a little unintelligible. 

So i try to use the logger in `reconciler` as common logger for all sub function using following codes:
```go
r.Log=r.Log.WithValues("replicaset", req.NamespacedName)
//others just call r.Log.Info() 
```
in my thought, it should work because each time, the key is always "replicaset" so just the value changes. But in fact, it just append another k/v to the log. After serval reconcile, the log is much longer.

I have done some test:
```go 
package main

import (
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
)

func main() {
	ctrl.SetLogger(zap.Logger(true))
	logger := ctrl.Log.WithName("test")
	for index := 0; index < 5; index++ {
		logger = logger.WithValues("replicaset", index)
		logger.Info("Hello World")
	}
}
```
the output is 
```
2019-09-27T15:57:19.410+0800    INFO    test    Hello World     {"replicaset": 0}
2019-09-27T15:57:19.410+0800    INFO    test    Hello World     {"replicaset": 0, "replicaset": 1}
2019-09-27T15:57:19.410+0800    INFO    test    Hello World     {"replicaset": 0, "replicaset": 1, "replicaset": 2}
2019-09-27T15:57:19.410+0800    INFO    test    Hello World     {"replicaset": 0, "replicaset": 1, "replicaset": 2, "replicaset": 3}
2019-09-27T15:57:19.410+0800    INFO    test    Hello World     {"replicaset": 0, "replicaset": 1, "replicaset": 2, "replicaset": 3, "replicaset": 4}
```
 source code: https://github.com/kubernetes-sigs/controller-runtime/blob/801e12a501606245062a6ff77ac91eef8936d9fb/pkg/log/deleg.go#L60

Is it designed or my misuse?

**Comment by mengqiy** [comment]
That's is WAI, but we can improve our documentation for log package and make it more discoverable (I guess it's nor very easy for people to find and its name has `TMP` which is "weird")

> r.Log=r.Log.WithValues("replicaset", req.NamespacedName)

Normally, we don't assign it back to itself, since the length just keeps growing.

What we normally do is something like:
```
import(
	ctrl "sigs.k8s.io/controller-runtime"
	...
)

var (
	setupLog = ctrl.Log.WithName("setup")
	recLog   = ctrl.Log.WithName("reconciler")
)

type reconciler struct {
	client.Client
	scheme *runtime.Scheme
}

func (r *reconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
	log := recLog.WithValues("myCRD", req.NamespacedName)
	// log below
	log.Info("reconciling myCR")
	log.Error(err, "unable to reconciling myCR")
}

func main() {
	ctrl.SetLogger(zap.Logger(true))

	setupLog.Info("starting manager")
	...
}
```

You can check the `/examples` under controller-runtime.

cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
Re-assigning also breaks for parallel reconciles, and is generally not reccomended.  If you need to split your code up, have it take a log object, or put it in a context.

The "length growing" is implementation-dependent, but it's not surprising that we see it with zap due to the way zap works.
