### ISSUE TITLE
Allow concurrent reconciliation only for distinct resources

### ISSUE THREAD

**Issue by sebbonnet** [kubernetes-sigs/controller-runtime#616]
At present, `reconcile.Reconciler` allows multiple concurrent reconciliations through adjustment of the `MaxConcurrentReconciles` property to values above 1. However, this opens the possibility that there could be two concurrent reconciliations for the same resource, which is a situation we would like to avoid.

We would like to be able to configure the `Reconciler` so that it supports concurrent reconciliations only for distinct resources. In other words, it would be possible to concurrently reconcile resources A and B, but not to have two concurrent reconciliations for either A or B.

**Comment by DirectXMan12** [comment]
This shouldn't happen -- the underlying workqueue should prevent this from occurring (see the bullet item for "stingy" in https://godoc.org/k8s.io/client-go/util/workqueue).  Do you see this actually occurring?

**Comment by DirectXMan12** [comment]
(if you do, it's a bug)

**Comment by sebbonnet** [comment]
That's a very good point - if it works as described it would simplify quite a few things on our end.
I'm currently testing this and will report here.
