### ISSUE TITLE
Controller-gen fails to parse valid json-schema regex

### ISSUE THREAD

**Issue by alastor-erinyes** [kubernetes-sigs/controller-runtime#619]
This regex, which previously worked (or at least caused no error) in `v0.2.0-beta.4` now fails to parse in `v0.2.1`.

```
// +kubebuilder:validation:Pattern=^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$
```
Quoting with single quotes makes no difference in the parsing.

According to this page, it's a valid json schema regex token series: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

Here is the error controller-gen gives:
```
controller-gen crd:trivialVersions=true rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/b
ases
<dir> extra arguments provided: ",}$"
<dir> extra arguments provided: ",}$"
<dir> extra arguments provided: ",}$"
<dir> extra arguments provided: ",}$"
Error: not all generators ran successfully
```

**Comment by DirectXMan12** [comment]
You need to add quotes following the Go quoting rules (i.e. you need double quotes or backticks, each with the same meanings as in Go).  Don't use unquoted strings for anything more than single words.

https://book.kubebuilder.io/reference/markers.html#marker-syntax
