### ISSUE TITLE
Extend client.Reader.Get(..) method to support retrieval of cluster-scoped resources

### ISSUE THREAD

**Issue by muralov** [kubernetes-sigs/controller-runtime#629]
I would like to retrieve cluster-scoped custom resources with [client.Reader.Get(..)](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/interfaces.go#L52) function. I have learnt that it can only be used for namespace-scoped resources.

Can we extend this method to support retrieval of cluster-scoped resources?

**Comment by DirectXMan12** [comment]
I'm not certain where you learned that, but it's not true.  Any resource that supports get can be fetched with the `Get` method.  Closing for now, but if you have something that's not working feel free to ask questions.
