### ISSUE TITLE
Client.Get() does not recognize new api resource if new CRD installed on the fly

### ISSUE THREAD

**Issue by jzhoucliqr** [kubernetes-sigs/controller-runtime#630]
I have a use case that controller need to install new CRDs on the fly. After CRDs installed and are available from apiserver, Client.Get() within current controller doesn't recognize the new api resource, even after waiting for a long time.

Tried with set SyncPeriod to force resync, and mgr.GetAPIReader(), won't work either. Only restart the controller pod works. 

Is there any suggestions how to reload the client to recognize the new resources?

**Comment by DirectXMan12** [comment]
this'll be solved by #554

**Comment by DirectXMan12** [comment]
it's because we need to re-query discovery

**Comment by jzhoucliqr** [comment]
Thanks @DirectXMan12 !
