### ISSUE TITLE
Cannot use with Kubernetes 1.16 apimachinery

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#633]
When building, I see errors like 

```
sigs.k8s.io/controller-runtime/pkg/client/apiutil
../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/client/apiutil/apimachinery.go:74:30: undefined: serializer.DirectCodecFactory
```

I think this is due to `k8s.io/apimachinery => k8s.io/kubernetes/staging/src/k8s.io/apimachinery v0.0.0-20191001043732-d647ddbd755f` in my go.mod, since I want to use Kubernetes 1.16 libraries.

Is it possible to update this to `serializer.WithoutConversionCodecFactory`? Or do will that break users with older apimachinery?

**Comment by DirectXMan12** [comment]
we're in the process of updating to 1.16 (see #588).  In general, you'll probably encounter errors if you try to use Kubernetes libraries other than those specified in CR's go.mod

/triage support
