### ISSUE TITLE
Clean up event handling code goroutine leaks

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#637]
Technically, we can leak goroutines when you create a manager, since the event initialization code used in CR creates new goroutines.

There's two places -- the first is when we create a new broadcaster, it launches some goroutines.  As of https://github.com/kubernetes/kubernetes/pull/83489, that can be shut down, but we probably need to move that to start.

The second is in the actual event provider setup code -- that launches some goroutines when we set up the sinks.  If we grab the results of the setup functions, we can call their stop methods to clean them up.  Those should probably also be moved to start.

Actually unwinding this will probably require some changes to the event setup flow, though, so if anyone comes across this, it might be tricky.

Not the highest priority since it only occurs if you repeated create managers -- the normal "1 manager per process" model doesn't actually care about this issue.

/kind bug
/priority important-longterm

**Comment by mindprince** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/1089
