### ISSUE TITLE
envtest needs to set service-cluster-ip-range

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#641]
service-cluster-ip-range is no longer going to be defaulted after 1.16 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals), so we'll need to set it in envtest for 1.17 compat.  There's no harm in setting it now, AFAICT

/kind feature
/priority important-soon
/good-first-issue

**Comment by Dingshujie** [comment]
\assign
