### ISSUE TITLE
use ResyncPeriod func in case of multi controllers list simultaneously

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/controller-runtime#648]
like [kube-controller-manger](https://github.com/kubernetes/kubernetes/blob/f7091992c04e2d4f16f6b462d4a711e5b9eb0f22/cmd/kube-controller-manager/app/controllermanager.go#L151) do

**Comment by DirectXMan12** [comment]
We generally recommend not touching resync period (because it often doesn't do what you think it does), and using ResyncAfter or something else if you really need periodic behavior

**Comment by DirectXMan12** [comment]
(closing for now, feel free to keep commenting)

**Comment by xrmzju** [comment]
@DirectXMan12 Sorry, I may not express myself clearly. my point is the default behaviour of controller-runtime for now is all reflectors will do resync action simutaneourly, which means multiple controllers may all hammer the apiserver with list requestes.

**Comment by DirectXMan12** [comment]
Ok, so to summarize -- this is about adding jitter to the resync interval?

**Comment by DirectXMan12** [comment]
I think that seems reasonable
