### ISSUE TITLE
404 when trying to update resource Status

### ISSUE THREAD

**Issue by andrewmyhre** [kubernetes-sigs/controller-runtime#661]
I have a test which is creating a resource and calling a function which will update the status of the resource:

```
k8sClient, err = client.New(cfg, client.Options{Scheme: scheme.Scheme})
err := k8sClient.Create(ctx, myResource)
if err != nil {
  t.Error(err)
}
updateStatus(ctx, k8sClient, myResource)

func updateStatus(...) {
  myResource.Status.SomeValue = "testing"
  err = k8sClient.Status().Update(ctx, myResource)
}
```

Calling `.Update()` returns `the server could not find the requested resource`. I am able to `Get()` the resource prior to calling `.Update()`. What might I be doing wrong?

**Comment by DirectXMan12** [comment]
Did you enable the status subresource on your CRD?

**Comment by andrewmyhre** [comment]
I forgot I had posted this.. It turned out I needed to update my code generation markers and some dependencies in my project to have the custom resource generate with the status subresource enabled. Thanks! I'll close this.
