### ISSUE TITLE
Non-zero value based patch

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/controller-runtime#665]
`Patch`es need either to provide their `[]byte` (`ConstantPatch`), use server-side apply (`Apply`) or require a deep-copy operation, modify the copied object, and provide both the original and the copy to the patch so that it can compute the differences (`MergeFrom`).

The first option is quite low-level, and while it gives the user the full control is open to bugs. The last one is an overkill for simple patches operation.

Would be quite convenient to provide another `Patch` that extracts the non-zero values and creates a patch from it. For example, to modify the number of replicas of a `Deployment`:

```
var replicas int32 = 2
patch := appsv1.Deployment{
	ObjectMeta: metav1.ObjectMeta{
		Name: "deployment-name",
		Namespace: "deployment-namespace",
	}
	Spec: appsv1.DeploymentSpec{
		Replicas: &replicas,
	},
}
r.Patch(ctx, &patch, NonZeroValue)
```

I'm not sure which values are required to identify the object. Probably `ObjectMeta.Name` and `ObjectMeta.Namespace`, but maybe some more (¿GVK? I always felt like this fields should be auto-filled when I do something as `appsv1.Deployment{}`). Those fields would obviouslly not be patchable in this way. The implementation of NonZeroValue could be pretty straightforward:

```
var (
	NonZeroValue = nonZeroValue{}
)

type nonZeroValue struct{}

// Type implements Patch.
func (p nonZeroValue) Type() types.PatchType {
	return types.MergePatchType
}

// Data implements Patch.
func (p nonZeroValue) Data(obj runtime.Object) ([]byte, error) {
	return json.Marshal(obj)
}
```

/kind feature

**Comment by DirectXMan12** [comment]
That's effectively a raw merge patch (but yeah, you'd need to set GVK in the patch logic too) -- you'd want the type to be `types.MergePatch`.  At first glance, this seems fairly reasonable, and I think we'd take it (but probably with a different name).  Just want to make sure we don't have any unforseen consequences.

**Comment by Adirio** [comment]
> That's effectively a raw merge patch (but yeah, you'd need to set GVK in the patch logic too) -- you'd want the type to be `types.MergePatch`.

I messed that up. Copy-pasted and swapped the type here in GitHub.

> At first glance, this seems fairly reasonable, and I think we'd take it (but probably with a different name).

What about `Merge`?

I really find naming a bit odd actually. `ConstantPatch` expects both the type and the raw `[]byte`. `CustomPatch` or `RawPatch` sounds more accurate. I would have used `ServerSideApply` instead of `Apply`. `MergeFrom` is pretty descriptive.

What do you think about `Merge`, `MergeFrom`, `CustomPatch` and `ServerSideApply` @DirectXMan12? I guess we would have to keep `ConstantPatch` and `Apply` as deprecated aliases for some versions.

**Comment by DirectXMan12** [comment]
> ConstantPatch ...

Yeah, the naming of constantpatch is a bit unfortunate.  It's constant because it doesn't actually do anything, it just feeds the values through (all the other patch types do computation).

`CustomPatch` or `RawPatch` seem reasonable (with a slight preference towards the latter).

> Merge ...

Merge is fine.

> ServerSideApply ...

That's a lot of typing :-P.  I'd prefer to keep Apply as-is.
