### ISSUE TITLE
Common interface for SetControllerReference

### ISSUE THREAD

**Issue by Adirio** [kubernetes-sigs/controller-runtime#666]
Is there any reason not to combine `metav1.Object` and `runtime.Object` into a single `MetaV1RuntimeObject` interface?

```
type MetaV1RuntimeObject interface {
	metav1.Object
	runtime.Object
}
```

`SetControllerReference` is casting a `metav1.Object` into a `runtime.Object` which means that if this fails it will fail at run time instead of compile time.

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil.go#L57-L89
```
func SetControllerReference(owner, object metav1.Object, scheme *runtime.Scheme) error {
	ro, ok := owner.(runtime.Object)
	if !ok {
		return fmt.Errorf("%T is not a runtime.Object, cannot call SetControllerReference", owner)
	}

	// ...
}
```
would be turned into
```
func SetControllerReference(owner MetaV1RuntimeObject, object metav1.Object, scheme *runtime.Scheme) error {
	// ...
}
```

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/controller-runtime/issues/594
