### ISSUE TITLE
workqueue filling up in all non-leader controllers when starting a manager with LeaderElection

### ISSUE THREAD

**Issue by manuelfelipe** [kubernetes-sigs/controller-runtime#668]
Was looking at creating couple of monitoring dashboards for some controllers we are working on internally. Noticed that the `workqueue_depth` metric keeps growing up in all *non-leader* pods  based on the number of resources associate with the informers managed by controller-runtime . 

In a test cluster with three resources matching the `Kind` the controller in questions is watching for:

```
for p in $(kubectl get pods --no-headers -o custom-columns=":metadata.name"); do
   echo -n $p": " ; k exec $p -- bash -c 'curl -s localhost:8080/metrics' | grep 'workqueue_depth{'
done

runtime-controller-76d6c695c9-528cj: workqueue_depth{name="runtime"} 3
runtime-controller-76d6c695c9-6rjj7: workqueue_depth{name="runtime"} 3
runtime-controller-76d6c695c9-plg82: workqueue_depth{name="runtime"} 0
```

```
k get cm runtime-controller-leader -o json | jq '.metadata.annotations["control-plane.alpha.kubernetes.io/leader"] | fromjson'
{
  "holderIdentity": "runtime-controller-76d6c695c9-plg82_0615c8bf-58a2-4bce-8cc7-13a2b8c86a17",
  "leaseDurationSeconds": 15,
  "acquireTime": "2019-10-31T18:57:44Z",
  "renewTime": "2019-10-31T19:23:47Z",
  "leaderTransitions": 12942
}
```

manager build with 
```
...
	managerOpts := ctrl.Options{
		Scheme:             scheme,
		MetricsBindAddress: c.metricsBindAddress,
		LeaderElection:     c.enableLeaderElection,
		LeaderElectionID:   c.name + "-controller-leader",
	}
...
	mgr, err := ctrl.NewManager(restConfig, managerOpts)

```
where `c.enableLeaderElection = true`

with `go.mod` looking a bit like:
```
...
	k8s.io/api v0.0.0-20190918195907-bd6ac527cfd2
	k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d
	k8s.io/client-go v0.0.0-20190918200256-06eb1244587a
	k8s.io/code-generator v0.0.0-20190912054826-cd179ad6a269 // indirect
	k8s.io/utils v0.0.0-20190801114015-581e00157fb1 // indirect
	sigs.k8s.io/controller-runtime v0.3.0
	sigs.k8s.io/controller-tools v0.2.2
...
```

**Comment by manuelfelipe** [comment]
Looking at this a bit closer, looks like the culprit is around the usage of `Builder.Complete(` when setting up the controller(s). Specifically in:

https://github.com/kubernetes-sigs/controller-runtime/blob/d21241119ea4de139f1892ba2f5bc72c96d07f3f/pkg/builder/controller.go#L150-L152

Basically, the watches are setup independently of the leader election state. 

@DirectXMan12, wondering how do you thing this can be 'fixed'?

**Comment by manuelfelipe** [comment]
oh well... after going the route trying to get PR to fix out of the latest 0.3.0 release just found out https://github.com/kubernetes-sigs/controller-runtime/pull/651 which is pretty much what I was trying to do. 

I guess this is a no issue once we have an actual release with the changes.

**Comment by DirectXMan12** [comment]
Ah, I didn't even think about that fixing this issue, but yeah, it should.  Cool.

**Comment by manuelfelipe** [comment]
tested using `40070e2a1958` rev. not an issue anymore after #651
