### ISSUE TITLE
deserializing into a runtime.RawExtension should fill in the Object if the type is known

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/controller-runtime#67]
RawExtension.Object should get either the go struct or an unstructured.Unstructured object from the client.

Steps to reproduce:

- Create a Resource with RawExtension field
  - RawExtension accepts any runtime.Object
- Create an instance of the Resource with a Deployment for the field
- In the Controller, read object and using the client into an unstructured.Unstructured object
- The unstructured should have `Object` populated with a Deployment, but it is nil.

**Comment by DirectXMan12** [comment]
err... the docs for rawextension say that it shouldn't be auto-deserialized IIRC.  What are we expecting to happen here?
