### ISSUE TITLE
Specific resource instance as source

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-sigs/controller-runtime#671]
I'd like to be able to easily create a source on a specific object rather than the whole kind.
So ideally I could write something like:
```
var obj runtime.Object
...
c.Watch(&source.Object{Object: obj},...)
```
the behavior should be that the most specific watcher would be created:
* if namespaced type:
  * if neither `namespace` nor `name` are initialized, behave like `source.Kind`
  * if only `namespace` is initialized, create a watch for that type in that namespace
  * if both `namespace` and `name` are initialized, create a watch for that specific object
* if not namespaced:
  * if `name` is not initialized behave like `source.Kind`
  * if `name` is initialized, create a watch for that specific object

this should work also with unstructured objects.

What is the best way to do this with the current controller-runtime library?

I haven't found a way to do it. It looks like the `cache.informer` interface does not allow for getting an informer on specific instances or namespace...

**Comment by DirectXMan12** [comment]
/kind feature
/priority backlog

this is a common request.  We'd need to plumb through a way to tell the list-watcher to watch a specific object.  I'm not certain it's easily doable right now w/o jumping through some hoops.

**Comment by vincepri** [comment]
This should be easier to configure in the latest version, the Watch method now takes an object

/close
