### ISSUE TITLE
[Discuss] Move sigs.k8s.io/testing_frameworks/integration to controller-runtime

### ISSUE THREAD

**Issue by hoegaarden** [kubernetes-sigs/controller-runtime#676]
Proposal: Move testing_frameworks/integration into controller-runtime (& deprecate the former)

xref: https://github.com/kubernetes-sigs/testing_frameworks/pull/68#issuecomment-536760791

Advantages:
* Some configuration and implementation gets simpler; e.g. the equivalent of "kubebuilder assets"
* Smaller change/PR overhead - changes that involve both testing_frameworks/integration and controller-runtime can be done in one place
* Until now, testing_frameworks/integration has made the decision to not vendor any k/k packages. controller-runtime, on the other hand, is using k8s.io packages. That sometimes creates friction (e.g. https://github.com/kubernetes-sigs/testing_frameworks/pull/68), which could be eliminated if the 2 lived in the same place.

Drawbacks:
* Anyone who is using testing_frameworks/integration would be forced to vendor parts of k8s.io, which might not be desirable. In practice, we have only seen references to testing_frameworks/integration as part of controller-runtime, so that should be a pretty slim possibility.
* The resulting codebase would not be able to be vendored into k/k (as is the case with controller-runtime today anyway).

Todos:
- [x] Move code to controller-runtime
- [x] Check on deprecation of repos with sig-contribex (or whoever is responsible for that)
- [x] Deprecate sigs.k8s.io/testing_frameworks

/cc @DirectXMan12 @mengqiy @apelisse 
/sig testing
/kind cleanup

**Comment by mengqiy** [comment]
We probably should be starting by moving it under `pkg/internal/testingframework` and then switch controller-runtime code to depend on that.

**Comment by DirectXMan12** [comment]
yep, sgtm.  It'll be a breaking change I believe, since we expose some bits of testing_frameworks in our public API.  Likely low impact though.

**Comment by hoegaarden** [comment]
Code has been moved over, the original repo has been archived, so we can
/close
this issue. Thanks all!

**Comment by danieldn** [comment]
@hoegaarden With `sigs.k8s.io/testing_frameworks/integration` deprecated, what is the best way for us to import this integration library if we want to use it in our projects? I just found out the following doesn't work
```
imports sigs.k8s.io/controller-runtime/pkg/internal/testing/integration: use of internal package sigs.k8s.io/controller-runtime/pkg/internal/testing/integration not allowed
```
