### ISSUE TITLE
Ability to obtain RESTClient for given type

### ISSUE THREAD

**Issue by chemikadze** [kubernetes-sigs/controller-runtime#680]
While trying to use controller-runtime client (outside of controller context), I have faced the need to create watches on objects. Doing that via utilities provided in client-go requires RESTClient to be acquired, which is not exposed by controller-runtime client, and handling creation of RESTClient just for single API call feels a bit redundant. Also, exposing RESTClient would unlock things like #452 in cases, when typed client is available.

**Comment by DirectXMan12** [comment]
https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/apiutil#RESTClientForGVK is what you're looking for.

I'm not super-keen on exposing it via the client interface, especially since not all CR clients are api clients based on RESTClient (some are cache clients or fake clients)

**Comment by DirectXMan12** [comment]
(closing for bookkeeping, but generally willing to hear counter arguments -- not trying to be rude :-) )

**Comment by chemikadze** [comment]
> especially since not all CR clients are api clients based on RESTClient

Oh I see, makes sense.

> counter arguments

Use of RESTClientForGVK somewhat suffers from same issues -- scheme, mapper, codecs should be lined up before it can be used, while controller-runtime already takes care of these things. For example, if client.New would return superset of client.Client and some new RESTClientFactory interface, it would help avoid inconsistencies between manually created and controller-runtime created clients.

**Comment by DirectXMan12** [comment]
Even with `client.New`, I'm not super-keen on tying that to RESTClient directly, since I mostly view RESTClient as an implementation detail there.

That being said, having a helper that pulled that stuff out of the manager might be helpful in making it simpler, since the correct series of calls is

```go
gvk, err := apiutil.GVKForObject(obj, mgr.GetScheme())
if err != nil { /* give yourself RSI from typing this so many times */ }
restClient, err := apiutil.RESTClientForGVK(gvk, mgr.GetConfig(), serializer.NewCodecFactory(mgr.GetScheme()))
```

which is definitely unwieldy.

**Comment by chemikadze** [comment]
Yeah, helper would be good enough if rest clients obtained in this way are more or less same as used by client.

**Comment by DirectXMan12** [comment]
/good-first-issue

a helper for this should be a relatively simple PR.  The code is above.
