### ISSUE TITLE
Expose HTTP Endpoints listeners used for metrics

### ISSUE THREAD

**Issue by salaboy** [kubernetes-sigs/controller-runtime#684]
Right now the `/metrics` endpoint is automatically created and hosted using port `8080` it will be nice for users to be able to register other HTTP endpoints using the same listener under `8080`. Today, looking at the code this is not possible.

**Comment by DirectXMan12** [comment]
/kind feature
/priority backlog

We usually just serve other things on a different port, but yeah, this could be useful.
