### ISSUE TITLE
Expose NumRequeues of work queue for user.

### ISSUE THREAD

**Issue by SimonCqk** [kubernetes-sigs/controller-runtime#686]
It's true that the well-encapsulated controller-runtime makes users more easier to develop a new controller or operator in a effective way, but I've got some case which urgently need the NumRequeues information for some items in work queue.

Imagine the implementation of `Job-like` workloads, e.g: tensorflow jobs, pytorch jobs, k8s native jobs... These jobs may failed for some reason in runtime and its controller will restart it, until the restart/retry counts reach the limit — called `BackoffLimit`. As for controller/operator, the restart/retry count can be accessed by `workqueue.NumRequeues()`, and this is critical for controller/operator develop.

So, is it possible to expose this information to user ? Or is there any way to work around with it.

**Comment by DirectXMan12** [comment]
Is backoff limit supposed to be a controller-level knob, or a object-level knob?  If the latter, that isn't preserved across controller restarts -- what happens if the controller gets restarted after every couple of requeues?  You'll never actually hit the limit.
