### ISSUE TITLE
Pass in more metadata to Validator methods

### ISSUE THREAD

**Issue by alenkacz** [kubernetes-sigs/controller-runtime#688]
Right now, if one decides to implement `admission.Validator` the methods does not provide metadata from the AdmissionRequest so one cannot e.g. figure out that it's a request to a subresource or dry run.

The easiest solution here would be to pass in whole admission request into all of those methods.

**Comment by alenkacz** [comment]
I would be happy to work on this if we agree on the direction

**Comment by DirectXMan12** [comment]
`admission.Defaulter` and `admission.Validator` are intended to fill the situation where you need to mimic the API server's built-in validation and defaulting, not as a generic mutating/validating webhook "hook", so I'm not sure we want to do this -- we probably want to use the lower-level mutating/validating webhook logic in CR for this instead.

Might I ask for the usecase here?

**Comment by alenkacz** [comment]
/close

let's actually close this one. I think in those cases people should probably fall back to implementing the validators themselves
