### ISSUE TITLE
Consider surfacing merged CRDs in envtest Environment

### ISSUE THREAD

**Issue by hasheddan** [kubernetes-sigs/controller-runtime#691]
Currently, you can add CRDs to an `envtest` Environment directly as an `*apiextensionsv1beta1.CustomResourceDefinition` or by directory path. Both of these sources are merged with any `CRDInstallOptions` and all CRDs are installed into the cluster. However, if you want to further interact with CRDs installed by directory path (e.g. if you want to clean them up before terminating connection to an existing cluster), you have to read them into structs again. It would be nice if the Environment `CRDs` field (or another new field, perhaps `InstalledCRDs`) was updated following the [install of all CRDs](https://github.com/kubernetes-sigs/controller-runtime/blob/198197fe0fd7553cadd8afcd3338f8ee4b8a7e3f/pkg/envtest/server.go#L243).

I would be happy to open a PR to enable this functionality :)

**Comment by DirectXMan12** [comment]
/kind feature
/priority backlog

this seems reasonable

**Comment by DirectXMan12** [comment]
go head
