### ISSUE TITLE
SetControllerReference incompatible with CRD version upgrade

### ISSUE THREAD

**Issue by sebgl** [kubernetes-sigs/controller-runtime#699]
I think there is a problem with the way `SetControllerReference` works and how a CRD can have multiple versions.

The problem happens if we:
- create a CRD `MyResource` with version `v1beta1`
- in the corresponding reconciliation, create another resource (eg. a Secret), with `SetControllerReference` called to set its ownerReference to `MyResource/v1beta1`
- deploy a `MyResource` sample
- add a new version for `MyResource`: `v1`. Both `v1beta1` and `v1` coexist
- run the same reconciliation again with the upgraded operator, that deals with `v1` resources (stored version)
- it will try to set the ownerReference to  `MyResource/v1` when calling `SetControllerReference`, which fails with the following error:

```
"error":"Object default/secret-with-ownerref is already owned by another MyResource controller my-resource-sample"
```

The secret has a controller reference set to `MyResource/v1beta1`, and here we try to set it to `MyResource/v1`.

This is done in `SetControllerReference()` by going through all ownerReferences to make sure the resource is not already owned by another object:

```go
for i, r := range existingRefs {
		if referSameObject(ref, r) {
			fi = i
		} else if r.Controller != nil && *r.Controller {
			return newAlreadyOwnedError(object, r)
		}
	}

```

with `referSameObject()` requiring a strict equality, including version:

```go
func referSameObject(a, b metav1.OwnerReference) bool {
	aGV, err := schema.ParseGroupVersion(a.APIVersion)
	if err != nil {
		return false
	}

	bGV, err := schema.ParseGroupVersion(b.APIVersion)
	if err != nil {
		return false
	}

	return aGV == bGV && a.Kind == b.Kind && a.Name == b.Name
}
```

Should we relax that function to allow patching the existing ownerReference if the version has changed?

**Comment by sebgl** [comment]
From this [Slack convo](https://kubernetes.slack.com/archives/C0EG7JC6T/p1575039839348100), the version of the resource in the ownerReference does not seem to be used at all for resources garbage collection.

I can think of two different ways to deal with the above problems:

1. Replace the existing ownerReference with one that has the updated `apiVersion`. The downside is users need to correctly compare their expected vs. actual ownerReferences to decide to whether they should update the corresponding resource.
2. Keep the existing ownerReference with the out-dated `apiVersion`. Which should not have any unintended impact according to the above. It does not seem very "clean" to keep resources around with old apiVersions in their ownerReferences, but [existing tools](https://github.com/kubernetes-sigs/kube-storage-version-migrator) don't seem to care either.

The second option seems simpler to me. In terms of implementation, it should just be about modifying `referSameObject()` to ignore the version in `group/version`.

**Comment by DirectXMan12** [comment]
:+1: on just having `referSameObject` ignore version.

**Comment by sebgl** [comment]
I'll work on a PR.
