### ISSUE TITLE
Reduce deleted boilerplate

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/controller-runtime#70]
Almost all Controllers have boilerplate at the top to check if the object has been deleted.  Figure out a way to reduce this.

**Comment by DirectXMan12** [comment]
perhaps a predicate?

**Comment by vincepri** [comment]
/milestone v0.5.x

/assign @alvaroaleman 
/kind design
feature should have a spec design before implementation

**Comment by alvaroaleman** [comment]
I believe a predicate would not solve the problem, because the object can get deleted while its in the workqueue, so ppl would still have to have the check if the object exists by the time  their `Reconcile` get called.

**Comment by vincepri** [comment]
/remove-lifecycle frozen
/close

Closing this as in there has been no updates on this issue for a while. If there is enough interest, we could provide an optional predicate or function that does the same, although I would assume that most controllers might want to do the check on their own, like @alvaroaleman pointed out.
