### ISSUE TITLE
Fakeclient requires types read through unstructured to be registered in the scheme

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/controller-runtime#702]
Writing a test that uses the fakeClient for code that uses `*unstructured.UnstructuredList` to list something, the test fails with a

```
failed to list ImageRegistryConfigs: non-list type *unstructured.UnstructuredList (kind "my-api/v1, Kind=Config") passed as output
```

The same code works fine when using a non-fake client.
/kind bug

**Comment by alvaroaleman** [comment]
Okay so actually it seems I should have just read the error message, because I didn't pass in the ListType which happens to work with the non-fake client.

However after fixing that, the next error is this:

```
deletion_test.go:155: Deletion failed: failed to cleanup TYPE: failed to list TYPE: no kind "TYPEList" is registered for version "APIVERSION" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:65"
```

This issue seems to be rooted in the underlying object tracker used by the fake client. Not sure if and how to fix it. Maybe register `*unstructured.Unstructured` for the given GVK?

Not being able to use `*unstructured.Unstructered` with an unregistered GVK defeats the reason of using it in the first place.

**Comment by DirectXMan12** [comment]
I think the objectracker needs to use the passed-in scheme, not the kubernetes scheme -- use `NewFakeClientWithScheme` instead of `NewFakeClient` (which totally violates our controller-runtime API conventions, but that's a whole different story...)

**Comment by alvaroaleman** [comment]
> I think the objectracker needs to use the passed-in scheme, not the kubernetes scheme -- use NewFakeClientWithScheme instead of NewFakeClient (which totally violates our controller-runtime API conventions, but that's a whole different story...)

The problem is that it requires the type I am trying to get via an `unstructured.Unstructured.` to be registered. But the reason I am using `unstructured.Unstructured` in the first place is that I do not have the go types.

**Comment by DirectXMan12** [comment]
oh, yeah, sorry, triaging too fast :-P

**Comment by DirectXMan12** [comment]
need to dig into objecttracker here probably

/help

**Comment by mittachaitu** [comment]
Is there any specific reason to add [this](https://github.com/kubernetes-sigs/controller-runtime/blob/f52b6180d515bca5f8faa551c3784fee5ce89a83/pkg/client/fake/client.go#L199) check?

**Comment by alvaroaleman** [comment]
> Is there any specific reason to add this check?

I think now that we changed the interface of `List` to  take an `client.ObjectList` as second argument instead of a `runtime.Object` we can remove that check. Alternatively, we can skip the check if the incoming type is an `*unstructured.UnstructuredList`

**Comment by kellengreen** [comment]
Hello all, Is there a workaround for this at the moment?

**Comment by alvaroaleman** [comment]
Not to my knowledge. We are happy to take a PR for this that changes the client to work with both UnstructuredList and SomeObjectList if someone is interested.

**Comment by mittachaitu** [comment]
I would like to fix this issue

**Comment by mittachaitu** [comment]
> Hello all, is there a workaround for this at the moment?

Yes, I think we have to make in the following way
```go
list := &unstructured.UnstructuredList{}
list.SetAPIVersion("apps/v1")
list.SetKind("DeploymentList")
err = cl.List(context.TODO(), list)
```
Note: We have to setAPIVersion and Kind before making call to `List func`

**Comment by xenolog** [comment]
I confirm, this workaround is good.

**Comment by alvaroaleman** [comment]
@mittachaitu @xenolog this bug report isn't about the issue you are describing, see the second message. I have retitled it to make that clearer. What you are describing is a different issue, I've opened a fix for that: https://github.com/kubernetes-sigs/controller-runtime/pull/1467

**Comment by slintes** [comment]
Hi, is anyone working on this? My team is hitting this issue and we can spend some time trying to fix it.

**Comment by alvaroaleman** [comment]
@slintes no, feel free tu pick it up!

**Comment by wbrefvem** [comment]
@mittachaitu I tried your workaround, but i still get an error. Fake client still tries to populate the UnstructuredList with objects of the underlying type. It seems to me that one of two solutions is necessary:

1.  Pass Unstructured to client-go instead of the underlying type (not sure if client-go supports this or if it even makes sense)
2.  Convert the items in the list of objects of the underlying type that client-go returns into Unstructured

**Comment by wbrefvem** [comment]
@alvaroaleman I'm not sure if this is the same issue, but I noticed that if I set the GVK for the `UnstructuredList`, fake client does fetch the correct list, but it still errors because client-go returns a list of the underlying type instead of `Unstructured`. Fake client tries to  populate the `UnstructuredList` with objects of the underlying type instead of `Unstructured`.

Again, not sure if it's related, and not sure if I know an elegant fix. Explicitly handling `UnstructuredList` as a special case in `fakeClient.List` would work (i.e., just convert the items in the list that client-go returns to `Unstructured`), but that seems clunky and brittle.

**Comment by alvaroaleman** [comment]
Sounds like a different but potentially related issue. This is about fetching objects through unstructured that are not registered in the Scheme, which implies that client-go is never going to return something other than `Unstructured{,List}`
