### ISSUE TITLE
`mergeFromPatch` does not consider the zero value as part of the patch 

### ISSUE THREAD

**Issue by enxebre** [kubernetes-sigs/controller-runtime#703]
A CRD  has a status sub-resource with a required integer field: `status.IntField`
When trying to patch the status for the first time with `status.IntField=0` the diff given by `patch.Data(obj)` does not consider the zero value as part of the patch to be applied and the request via `mergeFromPatch` `client.Status().Patch` fails with `is invalid: status.IntField: Required value`
Is the only way to go to make `IntField` a pointer?

**Comment by DirectXMan12** [comment]
/kind bug
/priority backlog

Do you want zero to be a valid value?  Or is that considered unset?

**Comment by enxebre** [comment]
>Do you want zero to be a valid value? Or is that considered unset?

A valid value.

**Comment by DirectXMan12** [comment]
is this a structural schema or a non-structural one?  I wonder if `// +default=0` would work.

**Comment by enxebre** [comment]
yeh I wanted to do that unfortunately this is non-structural yet

**Comment by DirectXMan12** [comment]
hmm... I don't think there's a good way for `MergePatchFrom` to know that the field changed -- it basically just serializes both instances and then does a diff of the raw JSON, and a field is either `omitempty` or it isn't, but in either case the value doesn't change from an empty object.  You might have to write your own patch generator that knows how to handle the case of "object doesn't exist yet" or something, or just do different behavior if the status is unset initially.

**Comment by enxebre** [comment]
Thanks for the ideas Solly, I think we can close this. I'll go by using a pointer for now and would use `//+default=0` for a structural schema
