### ISSUE TITLE
DynamicRESTMapper could cause context timeouts to be ignored

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#705]
The dynamicrestmapper doesn't support contexts (because the restmapper interface doesn't support timeouts).  This is bad.  We should fix this short-term in CR and long-term perhaps in the restmapper interface, or in a super-interface of restmapper that supports contexts (we can type-assert on it or something).

/kind feature
/priority important-longterm
/help

**Comment by alexeldeib** [comment]
Anyone have feelings about this? All of the necessary changes are fairly straightforward, but I don't love the options. Accepting context and wrapping the underlying implementation makes sense but is a break, and a super interface seems like extra fluff.

@alvaroaleman @shawn-hurley ?

**Comment by alexeldeib** [comment]
@fengzixu are you still working on this?

**Comment by fengzixu** [comment]
@alexeldeib I wrote some code for this issue. Not submit yet. Do you have any better options?

**Comment by alexeldeib** [comment]
Nope, just going through issues to pick things up. Looking forward to a PR :)

/remove-help

**Comment by shawn-hurley** [comment]
Considering the 1.18 breaks in the same context way for folks maybe it makes sense to that with the 1.18 bump release?
