### ISSUE TITLE
Allow pass vars from main function to webhook validator functions

### ISSUE THREAD

**Issue by youyongsong** [kubernetes-sigs/controller-runtime#711]
Sometimes we need more contexts than resource itself in `ValidateCreate` `ValidateUpdate` `ValidateDelete` function, for examples:
eg1:
My CR validation relays on controller's flag, so I need to access that flag inside `ValidateCreate` function.
eg2:
My CR has a reference to another resource, I need a client to get that resource inside `ValidateCreate` function.

Is there anyway or workaround to pass more contexts to validator functions?

**Comment by DirectXMan12** [comment]
Not at the moment, except by using the lower-level admission machinery (pkg/webhook/admission), or a global

**Comment by mcristina422** [comment]
I did this when building a Pod webhook that needed to check the state of PersistentVolumeClaims. Create a `admission.Handler` and register that yourself to the manager. A client can be injected for you

**Comment by youyongsong** [comment]
@DirectXMan12 @mcristina422 thanks, I'm using `admission.Handler` now, also expecting that kubuilder webhook could add dependency injection mechanism in the future.
