### ISSUE TITLE
Webhook Metric Request Total Unused

### ISSUE THREAD

**Issue by mcristina422** [kubernetes-sigs/controller-runtime#712]
The metric `controller_runtime_webhook_requests_total` is registered but never actually updated. https://github.com/kubernetes-sigs/controller-runtime/blob/a0e9c1de298fe3df44de6559b3bb6d18ae986e54/pkg/webhook/internal/metrics/metrics.go#L28-L34

It seems like it was removed in this PR
https://github.com/kubernetes-sigs/controller-runtime/pull/323/files#diff-fbc18bb07cdd05391b7081acc1dfe170R105

@DirectXMan12 left a comment and TODO to follow up on https://github.com/kubernetes-sigs/controller-runtime/pull/323#discussion_r258328895

Does the community find this metric useful to implement? If not I think it should be removed as it causes confusion by being registered in the codebase

**Comment by DirectXMan12** [comment]
yeah, it's prob fine to remove

**Comment by prafull01** [comment]
I guess this can be a good first issue. I can take it up as my first issue for controller-runtime.
