### ISSUE TITLE
envtest fails to install v1 CRDs, e.g. with defaulting

### ISSUE THREAD

**Issue by pires** [kubernetes-sigs/controller-runtime#717]
Regardless of pointing to an `USE_EXISTING_CLUSTER=true` running Kubernetes 1.16, the usage of any feature that is not included/enabled in the apimachinery imported into `envtest`, such as CRD defaulting, fails with error(s).

**Comment by DirectXMan12** [comment]
/kind bug
/priority important-soon
/help

This is because we hard-code the version that we expect of CRDs.  We'll need to fine a way around this.  Possibly using the CR client internally to avoid this happening in the future.

**Comment by droot** [comment]
>This is because we hard-code the version that we expect of CRDs. We'll need to fine a way around this. Possibly using the CR client internally to avoid this happening in the future.


Yes, you are right, we are using generated clientset https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/envtest/crd.go#L220 . We will have to move to CR client and also use `unstructured` for referring CRs in CRUD operations.

**Comment by vincepri** [comment]
/close 

This was fixed in v0.5.0, feel free to reopen if necessary
