### ISSUE TITLE
Add default readiness check for webhook server?

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/controller-runtime#723]
In the Cluster API project, we're trying to automate the following in our CI testing:

1. Create a kind cluster
1. Deploy cert-manager
1. Wait for cert-manager to be ready
1. Deploy Cluster API (CRDs, RBAC, Deployments, etc)
1. Wait for Cluster API pods to be ready (so our webhooks are ready)
1. Create a `Cluster`, `Machine`, etc.

When we're waiting for the Cluster API pods to be ready, we've noticed some test flakes because it appears the pods are ready but their webhook servers are not fully online and ready to respond to requests yet.

I've thought about adding a readiness probe to our Manager, but I believe there is still a chance that it could return a false positive; i.e., the check returns ready, but because the webhook server is technically a different server than the readiness server, the webhook server might not be ready yet.

Would it make sense to add a default readiness check for the webhook server?

**Comment by DirectXMan12** [comment]
yeah, that makes sense

**Comment by ncdc** [comment]
@DirectXMan12 I can work on this. How much flexibility would you like for the check? Should we add `AddReadyzCheck()` to `webhook.Server`? Or start simple and hard-code a simple ping response?

**Comment by ncdc** [comment]
@vincepri I'm still interested in working on this. Do you have thoughts on my question above?

**Comment by vincepri** [comment]
I'd start simple and hardcode the Readyz checks for now, we can provide a flag later. This should also be backward compatible

**Comment by ncdc** [comment]
Define backward compat here?

**Comment by vincepri** [comment]
As in, adding new endpoints for readiness is additive and doesn't impact the current behaviors of the webhook server

**Comment by phoracek** [comment]
Just curious, what is this supposed to on top of #419 ? Just to use the probe by default? It seems fairly simple to add a readiness probe in the current state of the controller-runtime.

**Comment by ncdc** [comment]
This would just be exposing checks that people could configure in their pods. Not sure there's any compat issues or impacts.

@phoracek please see the description above for the rationale.

**Comment by alenkacz** [comment]
@ncdc are you still working on this? I've just spent many hours trying to figure out a nice way how to create such readiness check from outside that I am starting to think it would be easier to implement it within controller-runtime

**Comment by ncdc** [comment]
@alenkacz not at the moment, no
