### ISSUE TITLE
Test that we don't leak goroutines on start and stop

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-runtime#724]
We should have tests for simple operations that make sure they don't leak goroutines.  Namely, `manager.Start & stop` and `controller.New`, both of which leaked in the past.

We can use the runtime package to get the goroutine count.

/good-first-issue

**Comment by knabben** [comment]
Any ideas on how to filter the goroutines from manager/controller, using the NumGoroutines from runtime returns the ones from tests ~43, do makes sense to iterate on these list and extract by file path maybe?

**Comment by alvaroaleman** [comment]
> Any ideas on how to filter only the goroutines from manager/controller?

Maybe by counting them before starting & stopping the manager or a controller, then checking if the count is back at where it was initially?

**Comment by hypnoglow** [comment]
Is there anything else to be done here? The PR is merged so I believe the issue can be closed.

**Comment by vincepri** [comment]
Closing given that #738 has been merged

/close
