### ISSUE TITLE
[feature-request][client-cache] Use sync.Map instead of sync.RWMutex

### ISSUE THREAD

**Issue by gaocegege** [kubernetes-sigs/controller-runtime#726]
In https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client_cache.go#L48

We use:

```go
	// resourceByType caches type metadata
	resourceByType map[reflect.Type]*resourceMeta
	mu             sync.RWMutex
```

to construct a thread-safe map cache. In this scenario, [sync.Map](https://golang.org/pkg/sync/#Map) should have better performance:

>  The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex. 

Should we consider it?

**Comment by DirectXMan12** [comment]
I'd like to see numbers that verify that such a change would improve things before switching.  A mutex is *often* sufficient.

**Comment by gaocegege** [comment]
@DirectXMan12 SGTM. I will evaluate it if I have time :-)
