### ISSUE TITLE
May leak memory when running controllers

### ISSUE THREAD

**Issue by kdada** [kubernetes-sigs/controller-runtime#729]
I just raise a question and does not test it.

For #424.

```
func (cm *controllerManager) Start(stop <-chan struct{}) error {
	...
	//  This method will start informers.
	go cm.startNonLeaderElectionRunnables()
	// lead election
	if cm.resourceLock != nil {
		err := cm.startLeaderElection()
		if err != nil {
			return err
		}
	} else {
		go cm.startLeaderElectionRunnables()
	}
	...
}
```
In this case, candidate controllers also can receive object events even it does not start.  All events are in controller queue and no customers.

1. It will keep deleted objects(reconcile.Request) in the queue(Of course, this case is not serious )
2. But if users redefine the event with a pointer (or other structs without equivalence), It may cause visible leakage.

**Comment by DirectXMan12** [comment]
I'm not sure I'm following what you're staying here

**Comment by answer1991** [comment]
@kdada 

commit [#0fdf465bc21be27b20c5b480a1aced84a3347d43](https://github.com/kubernetes-sigs/controller-runtime/commit/0fdf465bc21be27b20c5b480a1aced84a3347d43) fixed your issue
