### ISSUE TITLE
Client initialization doesn't use DynamicRESTMapper by default

### ISSUE THREAD

**Issue by yanniszark** [kubernetes-sigs/controller-runtime#734]
Related to issue: https://github.com/kubernetes-sigs/controller-runtime/issues/321

When using a manager, it uses the DynamicRESTMapper and everything works as expected.
However, when using just the client package, the default RESTMapper is the one from client-go, which caches the discovery endpoint result once and never retries.

I would expect it to use the DynamicRESTMapper by default, unless I am missing something.

**Comment by alvaroaleman** [comment]
> I would expect it to use the DynamicRESTMapper by default, unless I am missing something.

Yes, definitely. Want to prepare a pull for that?

**Comment by yanniszark** [comment]
@alvaroaleman absolutely!
