### ISSUE TITLE
InformerCache consistency

### ISSUE THREAD

**Issue by xinlaini** [kubernetes-sigs/controller-runtime#741]
Hello, I have made the following observations that lead me to question the caching consistency behaviors.

Observations:
O1. Start a controller with maxWorkerConcurrency=1, therefore the Reconcile() functions are going to be called serially.
O2. at the end of an earlier invocation of Reconcile(), the CRD's status subresource was updated by populating some NewData (reconciler.Status().Update(...)), and succeeded
O3. at the beginning of a subsequent invocation of Reconcile(), get the CRD resource instance, with a low probability, its Status won't contain the NewData the said earlier invocation has successfully propagated.

Analysis and Debugging:
I traced the above executions and found the following facts:
1. the reconciler.Status().Update() call in step O2 above directly calls PUT() verb via the REST client.
2. the Get() in step O3 above goes to informerCache and reads the object from client-side cache.

My understanding is that the client-side InformerCache is populated by the ListAndWatch against the API server, which is asynchronously populated, so the result of step O2's update is not guaranteed to be read from the informerCache at the time of step O3. 

I think this is also the reason of the sporadic observation of status update failures (with message like "the object has been modified; please apply your changes to the latest version and try again"), since the update is based on the outdated cached resourceVersion, which failed the optimistic concurrency control at the API server.

This is behavior looks particularly bad when we know that the only writer of the CRD is from our controller, and the worker concurrency is 1 - in this simple setting (I'd argue this is pretty common setup for operators), serial consistency is expected (i.e., I write A, then subsequently when I read, I get A).

**Comment by DirectXMan12** [comment]
This is intended behavior.  If you want to always set status, you could use a patch operation instead to ignore the resource version.

**Comment by chemikadze** [comment]
While I do agree that Update/Patch behaviors are intended and in line with k8s API behavior, I would like to clarify if lack of read-your-writes consistency in the client is intended.

It can cause quite subtle and hard-to-catch bugs, is current eventual consistency of default client something project is planning to stick with, or having stronger consistency guarantees is something that could be considered?

/cc @DirectXMan12

**Comment by shiyan2016** [comment]
Having the same problem, update crd status with some data, with the reconcile generated by update crd status, get the crd , crd's status sometimes get the old status. @DirectXMan12

**Comment by jlunaq** [comment]
Hi, Can you please point me to any example of using a patch operation to update resources and avoid this issue?
