### ISSUE TITLE
CreateOrUpdate results in forbidden error

### ISSUE THREAD

**Issue by abergmeier** [kubernetes-sigs/controller-runtime#750]
We try to use `CreateOrUpdate` to keep *Pod*s updated in our Operator.

After filling `runtime.Object`, it returns an error:

```
pods \"foo\" is forbidden: unable to validate against any security context constraint: []
```

Looking at the tests for `CreateOrUpdate`, it seems like *Pod*s are not actually tested.
So is `CreateOrUpdate` supported for *Pod*s and/or is there any guidance where this error might occur from?

CC @MichaelBrandt4994

**Comment by DirectXMan12** [comment]
Yes, createorupdate is supported for pods.  You're probably just not submitting a valid pod.  Namely, something seems to be trying to use SCCs in your cluster, and it sounds like the pod doesn't conform.
