### ISSUE TITLE
question: controller watch with a label selector

### ISSUE THREAD

**Issue by bofm** [kubernetes-sigs/controller-runtime#778]
Is there any way to pass corev1.listOption{labelSelector=...} to Controller, Manager and their underlying Informers?

**Comment by vincepri** [comment]
I don't think that's possible today, the only way you can filter on labels is to use a map function and filter on those labels

**Comment by bofm** [comment]
The possibility of passing ListOptions down to the Informers would help in cases when it is required to limit the scope of the controller to a subset of resources of a specified kind. For example, to only watch and reconcile Pods with label selector "env=test".

**Comment by vincepri** [comment]
Yeah that makes sense, although it should be pretty easy to do this in the Reconcile code, or have some building blocks on top of controller runtime.

**Comment by bofm** [comment]
The API server would have to execute queries and send events which would be ignored by the controller.

**Comment by loewenstein** [comment]
I think this is a duplicate of https://github.com/kubernetes-sigs/controller-runtime/issues/244

**Comment by vincepri** [comment]
Closing in favor of https://github.com/kubernetes-sigs/controller-runtime/issues/244

/close
