### ISSUE TITLE
Reconciler panics should not crash the manager

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/controller-runtime#797]
Currently, an unhandled panic in a reconciler will not be recovered from, and will likely cause the manager binary to crash. This is a problem, since a panic might be triggered by a single resource in an unexpected state, so that one bad resource could prevent all other resources from being processed. Since Kubernetes is likely to restart the manager pod after a crash, this can also cause the manager to DOS the Kubernetes API server as it continually restarts.

In my project, I wrote this utility function:

```go
func MakeSafe(r reconcile.Reconciler) reconcile.Reconciler {
	return safeReconciler{impl: r}
}

type safeReconciler struct {
	impl reconcile.Reconciler
}

func (r safeReconciler) Reconcile(request reconcile.Request) (result reconcile.Result, err error) {
	defer func() {
		if r := recover(); r != nil {
			result = reconcile.Result{}
			err = fmt.Errorf("panic: %v [recovered]\n\n%s", r, debug.Stack())
		}
	}()
	return r.impl.Reconcile(request)
}
```

Every time I pass a reconciler to `Complete`, I wrap it with this. It ensures that any panics raised by the reconciler are converted to normal errors.

**Comment by alvaroaleman** [comment]
Yeah, this would be great to have :)

**Comment by rajathagasthya** [comment]
Something like apimachinery's `HandleCrash` function would also work if we plug it in the right place: https://github.com/kubernetes/apimachinery/blob/3253b0a30d67e7e362b8615e463156bac729c82f/pkg/util/runtime/runtime.go#L45

**Comment by vincepri** [comment]
We can revisit the milestone if the design doesn't have breaking changes. Folks might be relying on panics to detect failures today.

/priority important-soon
/help
/kind design

**Comment by FillZpp** [comment]
@varshaprasad96 Hi, are you still pursuing this? Mind if I take a stab at it :) ?

**Comment by varshaprasad96** [comment]
@FillZpp sure, please feel free to create a PR for this.
