### ISSUE TITLE
who calls the function in metrics/workqueue.go ?

### ISSUE THREAD

**Issue by qibobo** [kubernetes-sigs/controller-runtime#803]
In https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/metrics/workqueue.go,
there are some functions in workqueueMetricsProvider, such as NewDepthMetric, NewAddsMetric. But I could not find where these functions are called? Is there an example for it?

**Comment by alvaroaleman** [comment]
@qibobo They are passed into the workqueue package here: https://github.com/kubernetes-sigs/controller-runtime/blob/37a5c612641a38e099bd4dacf9f45c58067d4548/pkg/metrics/workqueue.go#L32

There they:
* Are set as the metrics provider: https://github.com/kubernetes/client-go/blob/9346d688810d23f933041c41e8650967d639be76/util/workqueue/metrics.go#L260
* Used to create new metrics: https://github.com/kubernetes/client-go/blob/9346d688810d23f933041c41e8650967d639be76/util/workqueue/metrics.go#L236

**Comment by qibobo** [comment]
@alvaroaleman 
thank you.
