### ISSUE TITLE
The reflector metrics is empty.

### ISSUE THREAD

**Issue by qibobo** [kubernetes-sigs/controller-runtime#817]
In client_go_adapter.go, restclient and reflector metrics are registered as the following:
```
func init() {
	registerClientMetrics()
	registerReflectorMetrics()
}
```
When I import this go package, there are restclient metrics, but there is no reflector metric.
I have checked the client-go repo and found seem no one calls metricsFactory.

My question is that does reflector enable by default or it need some extra steps to enble?

https://github.com/kubernetes/client-go/blob/f772958f8a2941ad60a4bf5fb13da0acee7b2d76/tools/cache/reflector_metrics.go#L77-L89
```
var metricsFactory = struct {
	metricsProvider MetricsProvider
	setProviders    sync.Once
}{
	metricsProvider: noopMetricsProvider{},
}

// SetReflectorMetricsProvider sets the metrics provider
func SetReflectorMetricsProvider(metricsProvider MetricsProvider) {
	metricsFactory.setProviders.Do(func() {
		metricsFactory.metricsProvider = metricsProvider
	})
}
```

**Comment by djzager** [comment]
I may be missing something. But as I see it, the `registerReflectorMetrics()` function is the one calling `SetReflectorMetricsProvider` of the cache pkg from controller-runtime.

Based on my reading of https://book.kubebuilder.io/reference/metrics.html I would think that you would get reflector metrics for free without having to take extra steps.

**Comment by vincepri** [comment]
/help

needs a little bit of investigation

**Comment by charith-elastic** [comment]
Could it be because reflector metrics have been removed from Kubernetes: https://github.com/kubernetes/kubernetes/pull/74636

**Comment by logicalhan** [comment]
Trust me, you do not want reflector metrics.
