### ISSUE TITLE
Unable to get an object of a custom resource using the default client outside Reconcile() method

### ISSUE THREAD

**Issue by sophieliu15** [kubernetes-sigs/controller-runtime#822]
I am trying to get an object of a custom resource that I defined outside of Reconcile() using the default client provided by the manager. I notice that even the object exists in the cluster, the client will return an error saying the object is not found. However, the client works as expected (i.e., can find the object) when I call it in the Reconcile() method. I am wondering what might be the cause for that?

Here is a code example:

```go
type MyReconciler struct {
   client.Client
   Manager ctrl.Manager
}

func (r *MyReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
  ...
  nnm := types.NamespacedName{Namespace: "myNamespace", Name: "myName"
  inst := &api.MyCustomResource{}
  // r.Get will get the object if it exists in the cluster.
  if err := r.Get(ctx, nnm, inst); err != nil {
  ..
  }
   ...
}
```
If I call `r.Get(ctx, nnm, inst)` outside Reconcile (e.g., in or after `SetupWithManager()`), it cannot get the object even it exists.

**Comment by vincepri** [comment]
What is the error message you're getting?

When `SetupWithManager` is called, the manager/client hasn't started yet and this could cause issues.

**Comment by djzager** [comment]
Looking at the [What's In a Controller](https://book.kubebuilder.io/cronjob-tutorial/controller-overview.html?highlight=cache#whats-in-a-controller):

> Reconcile actually performs the reconciling for a single named object. Our Request just has a name, but we can use the client to fetch that object from the cache.

What you are likely running into is trying to `Get` things from the cache when they haven't been populated yet.

**Comment by djzager** [comment]
The times that I have needed to create something outside of `Reconcile()` I simply did the create and, if `err != nil` checked the error [`errors.IsAlreadyExistsError(err)`](https://godoc.org/k8s.io/apimachinery/pkg/api/errors#IsAlreadyExists).

**Comment by sophieliu15** [comment]
@vincepri I am getting errors.IsNotFound() error. The actual error message is something like {"error": "HNCConfiguration.hnc.x-k8s.io \"config\" not found"}. I assume that means the client cannot find the object?

**Comment by vincepri** [comment]
makes sense, as @djzager pointed out, it's probably because the caches haven't been populated yet

**Comment by sophieliu15** [comment]
If that is the case, is there a general practice for how long I need to wait for the cache to be populated? After calling SetupWithManager(), I tried to sleep for 5 seconds (`time.Sleep(5 * time.Second)`) before Get() from the client, but I still couldn't get the object. Does it mean the sleep time is too short?

**Comment by vincepri** [comment]
I wouldn't use `time.Sleep`, is this action something you can perform in the `Reconcile()` method instead?

**Comment by sophieliu15** [comment]
Yes, I solved the problem by enforcing the reconciliation via adding a channel to watch. I am just curious why I cannot get the object outside the Reconcile() via the client. If it is related to the cache population, is there any other way to wait for cache to be populated besides time.Sleep? BTW, why we cannot use time.Sleep?

**Comment by djzager** [comment]
> @vincepri I am getting errors.IsNotFound() error. The actual error message is something like {"error": "HNCConfiguration.hnc.x-k8s.io "config" not found"}. I assume that means the client cannot find the object? If the manager/client hasn't started, am I supposed to get a different error indicating the client hasn't started.

It would be odd for you to get an `errors.IsNotFound()` when you are doing an `r.client.Create(...)`. I was suggesting you could handle the error from `Create` and check for `errors.IsAlreadyExists()` and move on if that is the case.

> Yes, I solved the problem by enforcing the reconciliation via adding a channel to watch. 

I remember once trying to create a singleton CR in the case that it doesn't exist by doing something similar. In the end we ended up doing something like:

```
	// Create CR if it's not there
	client := mgr.GetClient()
	err = client.Create(context.TODO(), &kniv1alpha1.KNICluster{
		ObjectMeta: metav1.ObjectMeta{
			Name:      kniNamespacedName.Name,
			Namespace: kniNamespacedName.Namespace,
		},
	})
	switch {
	case err == nil:
		log.Info("Created KNICluster resource")
	case errors.IsAlreadyExists(err):
		log.Info("KNICluster resource already exists")
	default:
		log.Error(err, "Failed to create KNICluster resource")
		os.Exit(1)
	}
```

The big issue that I had with forcing the reconcile by throwing something on the queue was that the semantics for handling when the primary resource was not found was strange.

**Comment by sophieliu15** [comment]
Hi David!

Looks like I misunderstood your reply before. Yes, I got an `errors.IsAlreadyExists()` when I tried to do an `r.client.Create(...)`. I got `errors.IsNotFound()` when I did `r.client.Get(...)`, which was unexpected since the object already existed in the cluster. 

Explicitly dealing with `errors.IsAlreadyExists()` seems like a good approach to handle this problem too. Thanks for the suggestion!

Just out of curiosity... Have you tried any ways to wait for cache population outside the Reconcile() method? Was there any success?

**Comment by djzager** [comment]
> Looks like I misunderstood your reply before. Yes, I got an `errors.IsAlreadyExists()` when I tried to do an `r.client.Create(...)`. I got `errors.IsNotFound()` when I did `r.client.Get(...)`, which was unexpected since the object already existed in the cluster.

Yeah. It's surprising and my suspicion is it has to do with the unsynced cache but I just don't know enough yet to say for certain.

> Explicitly dealing with `errors.IsAlreadyExists()` seems like a good approach to handle this problem too. Thanks for the suggestion!

Happy to help out.

> Just out of curiosity... Have you tried any ways to wait for cache population outside the Reconcile() method? Was there any success?

No. It always felt as though the design of controller-runtime encouraged accessing the client (and associated caches) from inside the `Reconcile()` and as we only needed to make sure one thing was created on startup, we didn't invest any more time into it.

**Comment by alvaroaleman** [comment]
We return a different error than notFound in current c-r versions if the cache wasn't started: https://github.com/kubernetes-sigs/controller-runtime/blob/0374b8ce09672f4ef3493959860d4252d9f7e7cb/pkg/cache/informer_cache.go#L66

What version of controller-runtime are you using?

**Comment by sophieliu15** [comment]
I am using v0.2.2. Looks like the current version is v0.5.0. I guess that's why I still get a notFound error if cache is not started?

**Comment by alvaroaleman** [comment]
Yeah, that change exists froim 0.3.0 onwards: https://github.com/kubernetes-sigs/controller-runtime/commit/782b674e602e0870d9b7aab4d18cdfc1b315c28f

Can you update?

**Comment by sophieliu15** [comment]
I will try that. Thanks for the information!
