### ISSUE TITLE
Allow setting the event recorder host

### ISSUE THREAD

**Issue by rmb938** [kubernetes-sigs/controller-runtime#826]
Currently when getting the event recorder from the manager you only can specify a name.

```
mgr.GetEventRecorderFor("my-recorder")
```

The recorder provider implementation uses

```
p.eventBroadcaster.NewRecorder(p.scheme, corev1.EventSource{Component: name})
```

However `corev1.EventSource` has a `Host` field

```
// EventSource contains information for an event.
type EventSource struct {
	// Component from which the event is generated.
	// +optional
	Component string `json:"component,omitempty" protobuf:"bytes,1,opt,name=component"`
	// Node name on which the event is generated.
	// +optional
	Host string `json:"host,omitempty" protobuf:"bytes,2,opt,name=host"`
}
```

It would be nice to be able to set the host field using something like

```
mgr.GetEventRecorderFor("my-recorder", "some-host")
```

**Comment by vincepri** [comment]
@rmb938 is the use case to populate the Host field with a custom value or something we can reuse from the manager information? The latter wouldn't be a breaking change

**Comment by vincepri** [comment]
/kind feature
/priority important-soon

TBD: to investigate the Host field semantics

**Comment by rmb938** [comment]
The use case is to populate the Host field with a custom value.

**Comment by LeoLiuYan** [comment]
@vincepri  Maybe I can work for it?

**Comment by mcristina422** [comment]
I think in the new v1 API EventSource is removed. https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/383-new-event-api-ga-graduation

Replaced with `ReportingController` and `ReportingInstance`.
