### ISSUE TITLE
Doesn't appear to honour KUBECONFIG environment variable

### ISSUE THREAD

**Issue by ae-dg** [kubernetes-sigs/controller-runtime#83]
In pkg/client/config/config.go there's a check to see if KUBECONFIG is set, but then it is not used

    if len(os.Getenv("KUBECONFIG")) > 0 {
        return clientcmd.BuildConfigFromFlags(masterURL, kubeconfig)
    }

In using this from kubebuilder it worked for me when I changed the above to

    if len(os.Getenv("KUBECONFIG")) > 0 {
        return clientcmd.BuildConfigFromFlags(masterURL, os.Getenv("KUBECONFIG"))
    }

**Comment by DirectXMan12** [comment]
Closed by #84
