### ISSUE TITLE
Incorporate discovery.ServerVersion in the manager interface

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes-sigs/controller-runtime#833]
Controller-runtime manager supports majority of the `client-go` discovery interface abilities, but it does not provide a way to determine kubernetes cluster version during controller runtime without falling back to the `client-go` implementation for the feature. 

Such addition would simplify interaction with the `controller-runtime` client with use-cases like a cluster to cluster application migration (issue: https://github.com/konveyor/mig-controller/issues/432) or potentially in a hybrid cloud environment with multiple versions of kubernetes nodes being connected under a single cluster setup (if such idea makes sense). 

The application of a feature may allow to extend the support for the controllers, being utilized on a longer range of kubernetes versions and provide a way to deal with significant changes in kubernetes API more easily.  As an exampe - an exclusion of beta API version and promoting them to a stable version in v1.16 - https://github.com/kubernetes/kubernetes/pull/70672.

**Comment by DirectXMan12** [comment]
it's not clear to me from the listed use case why you actually want kubernetes version -- the information you need is better found in the discovery info we do expose.  For instance, if you want to check if v1beta1 is supported, check the RESTMapper.

Can you clarify why the existing information is insufficient?

/priority awaiting-more-evidence

**Comment by SpecialYang** [comment]
My k8s cluster version is 1.22. I use RestMapper.KindsFor method for searching ingress verison. I still got v1beta1 version.
What can i do to check the cluster whether or not support v1beta1 version?
