### ISSUE TITLE
scheme_test doesn't check for the existence of CreateOptions

### ISSUE THREAD

**Issue by Capstan** [kubernetes-sigs/controller-runtime#835]
Although it exists as a base type alongside UpdateOptions, DeleteOptions, etc., it is not explicitly tested for. Because the test only tests length of the returned list and existence of specific entries rather than a concrete set of expected entries, it seems to have been left out.

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes-sigs/controller-runtime/pull/842
/close
