### ISSUE TITLE
Delete validation for Validator interface is broken on k8s versions < 1.15

### ISSUE THREAD

**Issue by mrparkers** [kubernetes-sigs/controller-runtime#845]
Hi, I'm using controller-runtime@v0.4.0 on a local Kubernetes cluster (v1.14.7).  I'm running into an issue with implementing the Validator interface for a ValidatingAdmissionWebhook.

After implementing this interface, create/update works just fine, but delete always fails with this error message:

```
Error from server: error when deleting "crd.yaml": admission webhook "vcrd.example.com" denied the request: there is no content to decode
```

It looks like the code that consumes the Validator interface assumes that `req.OldObject` exists: https://github.com/kubernetes-sigs/controller-runtime/blob/d0de78d9f1c1de9f8570d67869f7cb47057bca37/pkg/webhook/admission/validator.go#L96

The Kubernetes PR that is referenced in the comments (https://github.com/kubernetes/kubernetes/pull/76346) adds this field to the request that the API server sends to the webhook.  This PR landed in 1.15, which is an issue for users that run local Kubernetes via Docker for Mac, which currently uses 1.14 in the stable channel, or Amazon EKS customers, which does not yet support 1.15.

If you'd like, I'd be willing to attempt a PR to fix this problem.

Thanks!

**Comment by mengqiy** [comment]
https://github.com/kubernetes-sigs/controller-runtime/blob/fc39662443b99ad0dcab22001571ccb9bc5b7960/pkg/webhook/admission/validator.go#L94-L96
https://github.com/kubernetes/kubernetes/pull/76346 this PR only started to be avavilable in 1.15+.
In <=1.14, the old object is not passed in the admission request body for delete operation.
I guess the fix is to check if `req.OldObject` is empty in the `Delete` operation. If empty, just skip it.

**Comment by YangKeao** [comment]
@mrparkers Are you working on this issue? If not, I will submit a PR to fix this :beers: .

**Comment by mrparkers** [comment]
@YangKeao this isn't something I'm worried about anymore since AWS EKS supports 1.15+ where this issue is not present.  Feel free to take this on if you'd like :+1:

**Comment by felipeweb** [comment]
I'm having this issue on `kind v0.9.0 go1.15.2 linux/amd64`

/reopen
