### ISSUE TITLE
CreateOrUpdate falsely claiming its updating resources 

### ISSUE THREAD

**Issue by mcristina422** [kubernetes-sigs/controller-runtime#847]
While using `CreateOrUpdate` with resources that get defaulted it can return `OperationResultUpdated` despite there being no updates. I'm not concerned that the call to `Update` is happening, the same values get defaulted. But I think returning `OperationResultUpdated` is wrong since nothing was actually updated. I think that `OperationResultUpdated` should only be returned when the `ResourceVersion` is not equal to the original.
https://github.com/kubernetes-sigs/controller-runtime/compare/master...mcristina422:cmpResourseVersion?expand=1#diff-4c146d38c03cf55e321de9ad53af4452R220-R238

I originally came across this issue setting ports on `Service` similar to https://github.com/kubernetes-sigs/controller-runtime/issues/464#issuecomment-499258817

I recreated the issue in a `Deployment` with my proposed fix in  https://github.com/kubernetes-sigs/controller-runtime/compare/master...mcristina422:cmpResourseVersion?expand=1

@DirectXMan12 do you think my proposal makes sense

**Comment by DirectXMan12** [comment]
I think that makes sense, off the top of my head.  I'm assuming the previous semantics were "did I submit an update", not "did an update actually occur" though.  Anyone else have thoughts?

cc @alexeldeib who touched that code last.

/kind feature
/priority awaiting-more-evidence

**Comment by mcristina422** [comment]
The reason I prefer it not to be just "did I submit an update" is that I use the result to determine if the Owned resource I am updating has been modified. If so, end the reconciliation early and let the update of the Owned object trigger a rereconcile and progress further into the reconcile logic. If this is not intended behavior thats understandable

**Comment by alexeldeib** [comment]
Seems reasonable. Currently if an object was found remotely (i.e., it's an update) but there is no difference, we no-op locally and return `OperationResultNone, nil`: https://github.com/kubernetes-sigs/controller-runtime/blob/edf717755ce2f4f6c8794c976b0184fc65676230/pkg/controller/controllerutil/controllerutil.go#L216-L218

I think this change makes our behavior consistent in OperationResultNone + no error means "the object you submitted and the object in the API server were the same". Right now we have an edge case where we tell the user that the blackbox create or update succeeded, but they have to go diff the objects themselves to figure out what happened. I personally think the important semantic is that something *changed* -- depending on using CreateOrUpdate to submit no-ops to the API server seems like something I'd discourage anyway.

**Comment by alexeldeib** [comment]
@mcristina422 can you clarify your use case slightly? You have a controller on e.g. the parent objects and when the parent tries to CreateOrUpdate a child object, you want to use the OperationResultUpdated to let the child re-trigger the parent to reconcile?

Without depending on OperationResult here, you should be able to do this by having the parent CreateOrUpdate the child, and then check for a status field on the child object.
