### ISSUE TITLE
fakeclient List does not handle nil ListOptions

### ISSUE THREAD

**Issue by displague** [kubernetes-sigs/controller-runtime#849]
It should be possible to list resources without specifying list options.
```
c.List(ctx, obj, nil)
```
The fake client does not support this, requiring an empty `&client.ListOptions{}` to be supplied.  Another approach would be to make `ListOption.ApplyOptions` `nil` safe.

The fake client line that causes this is 
https://github.com/kubernetes-sigs/controller-runtime/blob/0ea0ac5/pkg/client/fake/client.go#L152

**Comment by rajathagasthya** [comment]
See #806

**Comment by vincepri** [comment]
which version of controller runtime are you using?

/priority awaiting-more-evidence

**Comment by displague** [comment]
The commit that I tagged was In v0.6.0, but I am using v0.4.0.  

https://github.com/kubernetes-sigs/controller-runtime/blob/v0.4.0/pkg/client/fake/client.go#L145

There does not appear to be a difference between the two versions (nor v0.5.2) in terms of this expectation and the error produced.

**Comment by fabriziopandini** [comment]
I have tested this with controller runtime v0.9.5, and I can't reproduce anymore...

**Comment by joelanford** [comment]
/close

@displague If you're able to reproduce against `master`, please open a new issue.
