### ISSUE TITLE
Document controller health probes

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [kubernetes-sigs/controller-runtime#855]
Was mentioned in comments to https://github.com/kubernetes-sigs/controller-runtime/pull/419, that it's not quite clear how to set health probes for controller. 

Would be nice to add minimal example of manager with health/readiness checks.

P.S. I would gladly do that

**Comment by alexeldeib** [comment]
I really like the examples provided by controller runtime, for example the package level one: https://github.com/kubernetes-sigs/controller-runtime/blob/master/example_test.go

and the webhook specific one: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/example_test.go

perhaps we could had a runnable main.go example with healthz?

**Comment by alexeldeib** [comment]
If that's already what you meant, i'd go for it! Or are you thinking about something else like a gitbook for controller runtime?

**Comment by GrigoriyMikhalkin** [comment]
@alexeldeib Was thinking more about adding example to https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/example_test.go(please check PR).

But adding runnable example(in addition), also a good idea. Maybe we can add health probes to examples in https://github.com/kubernetes-sigs/controller-runtime/tree/master/examples, what you think?

**Comment by LeoLiuYan** [comment]
Maybe I can work for it?

**Comment by GrigoriyMikhalkin** [comment]
@LeoLiuYan There's already PR: https://github.com/kubernetes-sigs/controller-runtime/pull/856

**Comment by stevekuznetsov** [comment]
/reopen

This is not fixed and it's still entirely unclear how this works for a newcomer to this framework. Why do health and readiness probes have names? When do they start running? How do multiple interact?

**Comment by GrigoriyMikhalkin** [comment]
@stevekuznetsov There's [now] [closed PR](https://github.com/kubernetes-sigs/controller-runtime/pull/856/files) with simple probes example. Also, i could write chapter in kubebuilder on health probes if that would be helpful.

**Comment by taylormgeorge91** [comment]
> @stevekuznetsov There's [now] [closed PR](https://github.com/kubernetes-sigs/controller-runtime/pull/856/files) with simple probes example. Also, i could write chapter in kubebuilder book on health probes if that would be helpful.

That would be helpful if still an option
