### ISSUE TITLE
Fake client doesn't apply the FieldSelector options on List

### ISSUE THREAD

**Issue by TqrHsn** [kubernetes-sigs/controller-runtime#866]
Currently the fake client doesn't apply the `ListOptions.FieldSelector` to filter results when using the List function.

Here is the current fake client's List function code:

```
gvk, err := apiutil.GVKForObject(obj, c.scheme)
	if err != nil {
		return err
	}

	if !strings.HasSuffix(gvk.Kind, "List") {
		return fmt.Errorf("non-list type %T (kind %q) passed as output", obj, gvk)
	}
	// we need the non-list GVK, so chop off the "List" from the end of the kind
	gvk.Kind = gvk.Kind[:len(gvk.Kind)-4]

	listOpts := client.ListOptions{}
	listOpts.ApplyOptions(opts)

	gvr, _ := meta.UnsafeGuessKindToResource(gvk)
	o, err := c.tracker.List(gvr, gvk, listOpts.Namespace)
	if err != nil {
		return err
	}
	j, err := json.Marshal(o)
	if err != nil {
		return err
	}
	decoder := scheme.Codecs.UniversalDecoder()
	_, _, err = decoder.Decode(j, nil, obj)
	if err != nil {
		return err
	}

	if listOpts.LabelSelector != nil {
		objs, err := meta.ExtractList(obj)
		if err != nil {
			return err
		}
		filteredObjs, err := objectutil.FilterWithLabels(objs, listOpts.LabelSelector)
		if err != nil {
			return err
		}
		err = meta.SetList(obj, filteredObjs)
		if err != nil {
			return err
		}
	}
	return nil
```

**Comment by LeoLiuYan** [comment]
@vincepri  Maybe I can work for it?

**Comment by vincepri** [comment]
Go for it, @LeoLiuYan

**Comment by invidian** [comment]
This sounds useful, can somebody reopen it please?

/reopen

**Comment by coderanger** [comment]
@invidian Are you interested in implementing this? If so, please open a Pull Request and reference this issue and we'll sort it out.

**Comment by invidian** [comment]
I'm not sure if I find time to implement this, as I can workaround it by putting required information in label for now.

**Comment by imilchev** [comment]
I am also interested in this and is quite annoying for me that I cannot even inject custom behaviour in the fake client. I am willing to work on adding this feature if someone has any suggestions how to incorporate it. I saw how the kubernetes API implements this [here](https://github.com/kubernetes/kubernetes/blob/d0439d417b0563d44c65b6e400e2070964dea7d1/pkg/registry/core/pod/strategy.go#L235-L247). I think this would mean that the `fakeClient.ClientBuilder` should get a slice of `fieldIndexers`/`fieldMappers` that are able to create a map with field name and field value for objects. This would probably mean that those indexers/mappers need to be type specific. Then we should make sure those are applied when filtering.
