### ISSUE TITLE
Allow caching client to handle requests for schemas skipping the cache when the WATCH verb is unavailable.

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-runtime#870]
**Story**

I as an Operator dev, would like to be able to use the client provided by the controller to do the actions which will not use the WATCH when the operator has not permission to WACTH or the Schema is not implementing this verb. 

**Motivation**

Third-party API's/Schemas which not implemented it. 

**Example**

To get an `ImageStreamTag` resource from an OCP API. 

(main.go)

```go
import (
	....
	imagev1 "github.com/openshift/api/image/v1"
)

func main() {
	....

	// Setup Scheme for all resources
	if err := apis.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	// Setup Scheme for OpenShift imagestreams and related
	if err := imagev1.AddToScheme(mgr.GetScheme()); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

	// Setup all Controllers
	if err := controller.AddToManager(mgr); err != nil {
		log.Error(err, "")
		os.Exit(1)
	}

        ...
}
```

(controller.go)

```

import (
...
	imagev1 "github.com/openshift/api/image/v1"
)

//reconcile
....
	// Get the latest resource to prevent updating a stale status.
	img := &imagev1.ImageStreamTag{}
	err = r.client.Get(context.TODO(), types.NamespacedName{Name: fmt.Sprintf("%s:%s", "example-name", "example-tag"), Namespace: memcached.Namespace}, img)
	if err != nil {
		if errors.IsNotFound(err) {
			reqLogger.Info("worked not found")
		} else {
			reqLogger.Error(err, "unexpected error")
		}
	}
...
```

In this scenario the error faced will be:

> E0320 15:42:17.676888       1 reflector.go:280] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to watch *v1.ImageStreamTag: unknown (get imagestreamtags.image.openshift.io)

**Note**

I understand that because of the cache the WACTH permission/verb is required. However, some third-party API's may do not implement it as the above example. So, in this case, I think that we could skip the cache and perform the actions directly.

**Comment by camilamacedo86** [comment]
c/c @miguelsorianod

**Comment by DirectXMan12** [comment]
FWIW, you can either use GetAPIReader or client.New to get around this (both of which return live clients).

There's two cases where this is relevant:

1. strange resources that don't implement watch:
  * this is easy-ish to detect via discovery, but relatively uncommon.  It's unclear how the balance of complexity vs usefulness should be handled here.

2. not have permissions to watch
  * this is harder to detect, except when it happens, and is commonly a transient issue.  If transient, we don't want to sometimes go to the cache and sometimes not.  I think we want to skip automatically handling this case.
