### ISSUE TITLE
Best practice for status changes using fake client

### ISSUE THREAD

**Issue by blkperl** [kubernetes-sigs/controller-runtime#871]
I'm looking for a pattern of how to test the following in unit tests

- create a job
- wait for it to complete
- do something on job success

In PHPUnit or another mock type with expectations, I would be able to do something like

```php
     $client= $this->createMock(K8sClient::class);
     $this->client->expects(self::exactly(3))
            ->method('get')
               ->willReturnOnConsecutiveCalls(
                ['response1'],
                ['response2']
            );
```

My workaround right now is to use a Go routine to run the code I'm trying to test and after it starts change the job status. This code unfortunately has race conditions because the Go routine may not create the job and start to wait before the main thread tries to the change the status. To get around that I have to sleep for 7 seconds which is not desirable. 

```go
        // ....
        errChannel := make(chan error, 1)
	go func() {
		errChannel <- createJob(c, envName, labels)  // I'm trying to test this function
	}()

	// TODO RACE CONDITION
	time.Sleep(7 * time.Second)
	job := /// Get job code
        job.Status.Job.Succeeded = 1
	err = c.Status().Update(context.TODO(), &job)
	if err != nil {
		return err
	}
	return <- errChannel . // This is the error that my testing function returns if any
```

Thanks!

**Comment by djzager** [comment]
I have found controller-runtime itself to be a pretty good example on writing BDD type tests using ginkgo and gomega, for example [controller_test.go](https://github.com/kubernetes-sigs/controller-runtime/blob/e0b187f6cb3f905589af262e7ecf3bdeb948ebcf/pkg/internal/controller/controller_test.go). How that may be of interest to you is references to [`Eventually`](https://github.com/kubernetes-sigs/controller-runtime/blob/e0b187f6cb3f905589af262e7ecf3bdeb948ebcf/pkg/internal/controller/controller_test.go#L294-L298). However, all of the tests in this project are using envtest (at least all the ones I have interected with have been) so I'm not certain how applicable it is for your scenario.

In my experience with the fake client, I have done everything I can to limit what my test is actually doing. For example, if I were testing `createJob` I would be specifically verifying that the function correctly created the `Job`. In addition if I wanted to test what my controller did when the `Job` had `Succeeded`, I would simply call `NewFakeClient` with a `Job` that had `Succeeded` already (using `initObjs`) and then verify that my controller handled this scenario appropriately.
