### ISSUE TITLE
Also allow validation of client certificates (mTLS)

### ISSUE THREAD

**Issue by maxsmythe** [kubernetes-sigs/controller-runtime#873]
It'd be nice if we also allowed validation of client certificates.

It looks like this could be done by providing the same pattern we use for for GetCertificate to GetClientCertificate:

https://github.com/kubernetes-sigs/controller-runtime/blob/18d591ac447bed9efd60217d44509cf8ea79b5e2/pkg/webhook/server.go#L172-L175

**Comment by maxsmythe** [comment]
/reopen

still valuable

**Comment by coderanger** [comment]
This was implemented in #802 which I think was merged before this was even opened?
