### ISSUE TITLE
Update to v0.18 Kubernetes dependencies

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/controller-runtime#874]
Currently we are depending on 1.17.2 libraries. With 1.18, there are a lot of breaking changes in client-go that will block people from upgrading to newer client-go versions. It would be useful if this library is updated once 1.18 is officially published.

**Comment by alexeldeib** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/836

https://github.com/kubernetes-sigs/controller-runtime/pull/836#issuecomment-603286722

**Comment by howardjohn** [comment]
Nice, thanks! I was looking for an existing issue, didn't notice the pr
