### ISSUE TITLE
The Request to reconcile a kubernetes object is not unique.

### ISSUE THREAD

**Issue by SimonCqk** [kubernetes-sigs/controller-runtime#876]
The `Request` object defined in controller-runtime (include its Namespace and Name) can not uniquely identify the object, since UID is a more strong guarantee.

It's a fact that one NamespacedName could only maps to one object **at the same time**, however, imagine this case down below:

> We persist some pod into mysql, if the pod-id is not recorded, when this pod deleted and then
> recreated, the later-coming pod will override the persisted one in mysql tables, which is what we
> unexpected.

So I do think it's necessary to add UID filed into `Request` type definition.

**Comment by alvaroaleman** [comment]
The whole idea of the reconciliation is that you look at the object and realize what it has defined in its spec at the time of reconciliation, which may be different from the time the event was generated to due various factor such as network latency or backoff after failures. This is not a bug, its part of the design.

If you need cleanup logic that sets the object as deleted, you should use a [`finalizer`](https://book.kubebuilder.io/reference/using-finalizers.html).

If you persist objects in a third-party system and have a need to uniquely identify them there, you should just record the UID there as well.

**Comment by DerekFrank** [comment]
/reopen

@alvaroaleman I found this old issue, and I wanted to get your thoughts on Karpenter's usecase. We do a lot of in-memory tracking of objects like pods, nodes, nodepools, etc. A lot of this is for metric emission where we don't have external resources to clean up and thus don't want to add a finalizer. Some examples might be tracking total resources in a nodepool to emit a metric on it. When a new nodepool is created with the same name as the old one, we don't generally want to say that it has a bunch of resources associated with it. 

We can work around this usually by maintaining a mapping of NamespacedName -> UID to verify if the object associated with a reconcile request is a new object, but the implementation gets a lot simpler if we can uniquely identify an object anywhere in time via the reconcile Request

**Comment by alvaroaleman** [comment]
@DerekFrank adding the UID to the existing `reconcile.Request` would only be safe if its safe to assume that everyone who updates controller-runtime to a version with that change will update their code to not just check for `NotFound` but also compare the UID. If that doesn't happen, its possible that two reconciliations run in parallel for the same object which breaks the invariant that controller authors can rely on that not happening. I think the chances that everyone who upgrades c-r to a version with such a change will update their code correctly are basically zero and the situations where this matters are rare, so I am opposed to that idea.

The good news for you is that we introduced generics throughout handler/controller/reconciler, so you can define all of this downstream through a custom request type and custom handlers, see the [multiclustersync example](https://github.com/kubernetes-sigs/controller-runtime/blob/e4c1c38bcbdb6e37d85481909787891a6ffc0a67/examples/multiclustersync/main.go) for some basic idea as to how this looks.
