### ISSUE TITLE
Add `context.Context` to `Source` interface's `Start` method to make cancellable

### ISSUE THREAD

**Issue by djzager** [kubernetes-sigs/controller-runtime#879]
Do we need to add `context.Context` to the `Source` interface's `Start` method to make this cancellable?

_Originally posted by @joelanford in https://github.com/kubernetes-sigs/controller-runtime/pull/830_

**Comment by camilamacedo86** [comment]
HI @djzager and @joelanford, 

It shows done already. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/source/source.go#L57

Can we close this one?

**Comment by troy0820** [comment]
Closing as this was implemented in this PR:
https://github.com/kubernetes-sigs/controller-runtime/pull/1116

If we still need it open, we can reopen it again.
/close
