### ISSUE TITLE
Reconcile dependent custom resources

### ISSUE THREAD

**Issue by adibrastegarnia** [kubernetes-sigs/controller-runtime#887]
I am trying to implement a k8s controller that should watch two custom resources and then reconcile them by creating a deployment, service, etc. The problem is that custom resource A and custom resource B should be created first (of course we don't know the order) and then I should perform reconciling. Inside Reconcile function I can have access to one of them at a time. What is the best approach to make sure both have been created before proceeding to reconcile?

**Comment by vincepri** [comment]
You'll have to wait inside the each reconciler for the other associated resource and return a requeueAfter, or an error.

/area support
/milestone Next
