### ISSUE TITLE
Document that Mercurial must be installed

### ISSUE THREAD

**Issue by grantr** [kubernetes-sigs/controller-runtime#92]
Opening to track the remaining issue from #89. `dep ensure` works now, but Mercurial is still an undocumented dependency.

**Comment by DirectXMan12** [comment]
need to check how go modules handle this
/remove-lifecycle rotten

**Comment by DirectXMan12** [comment]
I think this is mostly resolved.  Bitbucket is shutting down mercurial support anyway, and that was the only dep we had on mercurial
