### ISSUE TITLE
Support for leader election

### ISSUE THREAD

**Issue by calind** [kubernetes-sigs/controller-runtime#93]
Currently the manager won't do any kind of leader election. I think that the manager should implement of it so that you can run highly available controllers.

**Comment by JoelSpeed** [comment]
Does anyone know of any work already done on this? If not I'm going to look into this and try to raise a PR.

The first question I have about this is that the leader election will need a unique name per kubebuilder project. I assume this will have to come from a flag unless there is a unique identifier already, any ideas?

**Comment by zhujl1991** [comment]
@JoelSpeed  When leader election is enabled, after I delete the deployment of my controller manager, the `configmap` won't be deleted automatically.
