### ISSUE TITLE
IsController flag not being taken into account

### ISSUE THREAD

**Issue by isantospardo** [kubernetes-sigs/controller-runtime#932]
I noticed some constrains when watching for the routes filtered by owner, as a quick summary :

I tried to watch only routes owned by my custom resource by doing:

```
if err := c.Watch(&source.Kind{Type: &routev1.Route{}}, &handler.EnqueueRequestForOwner{OwnerType: &webeosv1alpha1.WebeosSite{}, IsController: false}}); err != nil {
         return err
}
```

The problem I noticed was that no routes ere being watched, I added the ownerReference to the route but still the same issue

```
     15   ownerReferences:
     16   - apiVersion: webeos.webservices/v1alpha1
     17     kind: WebeosSite
     18     name: mysite
     19     uid: 00000000-0000-0000-0000-000000000
```

after investigating I found I could do it in a different and cleaner way that made it work, so the result was this:

```
if err := controllerutil.SetControllerReference(cr, route, r.scheme); err != nil {
	reqLogger.Error(err, "Failed to set controller reference for route creation", "webeossite.name", cr.Name)
	return nil
}
```

And watch the route as
```
if err := c.Watch(&source.Kind{Type: &routev1.Route{}}, &handler.EnqueueRequestForOwner{OwnerType: &webeosv1alpha1.WebeosSite{}, IsController: true}); err != nil {
	return err
}
```
The difference between those two ownerReferences is that using `SetControllerReference` it sets `blockOwnerDeletion: true` and `controller: true` to the ownerReference.

From my point of view, the IsController flag is not being taken into account

**Comment by vincepri** [comment]
`EnqueueRequestForOwner` should work correctly if you have IsController set to true or false. Did you have the `ownerReference` setup before making a change?
