### ISSUE TITLE
Multi Namespace Cache doesn't support Get for cluster scoped resources

### ISSUE THREAD

**Issue by rohandvora** [kubernetes-sigs/controller-runtime#934]
I have a requirement to watch resources in multiple namespaces as well as a cluster-scoped resource. This is how I build the cache:
```golang
cache.MultiNamespacedCacheBuilder([]string{
	"namespace-1",
        "namespace-2"
})
```
While the namespace-scoped resources work as expected, the cluster scoped resource fails at the `Get()` function. The `List()` call for multi cache namespace works fine though. In the code, I see this:
```golang
func (c *multiNamespaceCache) Get(ctx context.Context, key client.ObjectKey, obj runtime.Object) error {
	cache, ok := c.namespaceToCache[key.Namespace]
	if !ok {
		return fmt.Errorf("unable to get: %v because of unknown namespace for the cache", key)
	}
	return cache.Get(ctx, key, obj)
}
```
For a cluster scoped object, the namespace will be `""`, so this will naturally return an error. This function should check if the object is cluster-scoped and return a cache appropriately.

**Comment by morvencao** [comment]
Encountered same issue.

**Comment by Kevinma1995** [comment]
there is also some issue with list, when list cluster scoped resource, the result contains duplicate resources that come from multiple informer cache

**Comment by JAORMX** [comment]
Yep, this doesn't seem to be fixed still :/
