### ISSUE TITLE
Allow removing individual informers from the Cache

### ISSUE THREAD

**Issue by shomron** [kubernetes-sigs/controller-runtime#935]
## Overview

In a somewhat similar use-case to that described in #863, the [Gatekeeper](https://github.com/open-policy-agent/gatekeeper) project uses one set of custom resources to describe (and dynamically register) another set of CRDs. Once subordinate CRDs are created, we then use informers to register watches against resources of those types. The set of subordinate resource types change over time. 

The existing APIs in controller-runtime do not allow removal of informers once they have been created. To work around this limitation, we have [forked](https://github.com/open-policy-agent/gatekeeper/pull/490) the controller-runtime cache.

This issue tracks the effort to upstream our changes in a way that is aligned with the design goals of controller-runtime.

## Goals:

* Enable removal of individual informers from a Cache
* Support more granular lifecycle management for informers to allow them to be stopped during removal

## Non-goals

* Reference counting of informers

## Open questions

* Should existing interfaces be expanded (`Cache`, `Informers`) in a breaking manner, or should new interfaces be introduced?

**Comment by camilamacedo86** [comment]
Hi @shomron, 

Could you please let us know if it still a need? Shows that yes, 

You said that you forked controller-runtime and applied your needs on it. Why you did not push a PR against master with your suggestions? Would it be possible? Maybe it can also clarify better your need and required changes that you are asking here. 

If it is too significant changes in its design, wdyt about push a PR with a doc design proposal? See https://github.com/kubernetes-sigs/controller-runtime/tree/master/designs. 

And then, could you also provide the use cases that this RFE would address?
