### ISSUE TITLE
Internal error occurred: failed calling webhook

### ISSUE THREAD

**Issue by ifilonenko** [kubernetes-sigs/controller-runtime#943]
=====
controller-runtime: v0.6.0
k8s version: 1.15
api-machinery: v0.18.2
See an issue where, rather consistently, I get the following error:
```
Error from server (InternalError): error when creating "example.yml": 
Internal error occurred: failed calling webhook "mutating-mycrd.domain.com":
Post https://mycrd-webhook-server-service.namespace.svc:443/mutate-v1-mycrd?timeout=30s:
no service port 'ⓣ' found for service "mycrd-webhook-server-service"
```
I create the manager with the following: 
```
        c := &MyCrdConfig()
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                  scheme,
		MetricsBindAddress:      fmt.Sprintf(":%d", c.MetricsPort),
		LeaderElection:          c.LeaderElection,
		LeaderElectionNamespace: c.LeaderElectionNamespace,
		LeaderElectionID:        c.LeaderElectionId,
		Port:                    c.WebhookPort,
	})
```
and initiate the webhooks with the following as well:
```
	hookServer := mgr.GetWebhookServer()
	setupLog.Info("registering webhooks to the webhook server")
	dec, _ := admission.NewDecoder(mgr.GetScheme())
	hookServer.Register("/mutate-v1-mycrd",
		&webhook.Admission{Handler: &MyCRDDefaulter{
			Client:  mgr.GetClient(),
			Decoder: dec,
			Config:  c,}})
```
I am able to to hit the webhook fine 4/5 times with a 1/5 it return the following error with: 
```
 Internal error occurred: failed calling webhook
```
something to note: 
```
>>> ord('ⓣ')
9443
```

**Comment by vincepri** [comment]
The log message seems it was fixed in https://github.com/kubernetes/kubernetes/commit/c224a6de5e01455bcd89763f1483546496e41dcb

**Comment by ifilonenko** [comment]
Ah that is the log-message, sure. But the underlying issue is that the port is unavailable... but why so? is it being set as a port name instead of a number, maybe?

**Comment by ifilonenko** [comment]
It seems that `this` specific issue isn't present when upgrading k8s cluster to version `1.16.x`.
I specifically tested against: `1.16.7`

**Comment by liggitt** [comment]
This typically means the pod backing the admission webhook is fluttering in and out of being available. If you watch the endpoints for the `mycrd-webhook-server-service` service do they remain available?

**Comment by ifilonenko** [comment]
Agreed, it seems that this issue is a red-herring for this error: https://github.com/jetstack/cert-manager/issues/2899 that was present on my cluster. It seems to have been resolved by resolving that ca-injector annotation issue

**Comment by vincepri** [comment]
Thanks @ifilonenko, I'll close out this issue then!

/close
