### ISSUE TITLE
client.Patch got an unknown format error

### ISSUE THREAD

**Issue by allenhaozi** [kubernetes-sigs/controller-runtime#947]
`
applyOpts := []runtimeclient.PatchOption{
         runtimeclient.ForceOwnership, 
         runtimeclient.FieldOwner(component.GetName())
}
err := c.Patch(ctx, component, runtimeclient.Apply, applyOpts...)
`

the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json

k8s: version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4"

controller-runtime version : v0.6.0

**Comment by allenhaozi** [comment]
It can be resolved by upgrading k8s to v1.16.0 or v1.17

**Comment by alvaroaleman** [comment]
I believe this is because the `FieldOwner` only exists when Server Side Apply is enabled and that is only enabled by default on v1.16+: https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

**Comment by allenhaozi** [comment]
> I believe this is because the `FieldOwner` only exists when Server Side Apply is enabled and that is only enabled by default on v1.16+: https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

got it. thank u for ur reply, I close this issue
