### ISSUE TITLE
How do you get a fake EventRecorder to be used in unit tests

### ISSUE THREAD

**Issue by cscetbon** [kubernetes-sigs/controller-runtime#949]
I can't find any resource that explains how to get a fake EventRecorder along with your fakeClient. I found some examples in client-go but their fake client comes with a [FakeCoreV1](https://github.com/kubernetes/client-go/blob/master/kubernetes/fake/clientset_generated.go#L253) that gives this ability.

**Comment by davidovich** [comment]
Have you tried this?

This starts a recorder with a buffer size of 3 events. 
```
fakeRecorder := record.NewFakeRecorder(3)
```
Pass the recorder to your business logic, and then in your test,

Drain recorder the and assert messages (event messages are concatenated):
```
go func() {
	for msg := range fakeRecorder.Events {
            // assert.Equal(t, msg, "eventtype reason message args")
	}
}()
```

Synchronization is left as an exercise ;-)

**Comment by cscetbon** [comment]
@davidovich I did not but now that I have this information I'm all set.

Thanks !
