### ISSUE TITLE
Controller Runtime not invoking reconcile on request 

### ISSUE THREAD

**Issue by davesargrad** [kubernetes-sigs/controller-runtime#952]
I am watching for changes to a configmap. 

My operator detects the configmap changes and [requests](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Request) a reconciliation of the 

> NamespacedName

 _mediator_ object that uses that configmap.

```
return []reconcile.Request{
								{NamespacedName: types.NamespacedName{
									Name:      mediator.Name,
									Namespace: Namespace: configMapObject.Meta.GetNamespace(),
								}},
```

My reconcile method does not get called. I verify in delve that I make the request for reconciliation, and that the corresponding reconcile is not invoked. 

The object that is to be reconciled exists, in the appropriate namespace.

What would cause reconcile not to be invoked?

This code has worked fine in the past. I cant figure out why its not working now.

I am using version 0.4.0 of the sigs.k8s.io/controller-runtime . 

When I restarted my operator, reconcile was invoked as I expected it to be. It seems that the operator was in a partially functional state.

**Comment by vincepri** [comment]
@davesargrad Are you able to update to at least 0.5.x before we investigate this issue?

/milestone Next
/priority awaiting-more-evidence

**Comment by kshamajain99** [comment]
@vincepri We are facing the same problem, is there any update on this issue?

**Comment by vincepri** [comment]
We haven't received any updates from the original reported, and I cannot reproduce on my environments. If you're using an older version of controller runtime, I'd suggest to update to one of the latest releases.

As of today, we've only been maintaining v0.5.x and v0.6x

**Comment by kshamajain99** [comment]
@vincepri We are using controller runtime version v0.5.2. 
We were facing this issue kubernetes/kubernetes#86811 because of which we changed Timestamp to be *metav1.Time. As a result of this change, controller is able to reconcile for first update request after which it fails to reconcile for any update.

**Comment by vincepri** [comment]
Not sure if there is anything we can do from our side, it seems the CRDs with the custom ObjectMeta/timestamps need to be fixed
