### ISSUE TITLE
Make workqueue metrics available to the Reconciler

### ISSUE THREAD

**Issue by mountainhike** [kubernetes-sigs/controller-runtime#97]
Sometimes Reconciler needs workqueue related metrics for ex. numRequeues to decide the fate of the request. So it will be useful to plumb those in the `Request` object.

**Comment by DirectXMan12** [comment]
can you clarify the usecase it bit more?

**Comment by mountainhike** [comment]
For example, if my controller wants to queue a object with a delay, i.e, controller wants to check the object again in one hour, the current pkg/controller/controller.go did not have a good way to say that. 
I guess the reconcile result object can have a field called "dealy", but still I think there could be other use cases where access to the working queue is needed.

**Comment by DirectXMan12** [comment]
I'd just use a channel source to re-add the item in an hour.  The workqueue delay is really intended for backoff.

**Comment by DirectXMan12** [comment]
done a while ago

**Comment by DirectXMan12** [comment]
whoops, misinterpreted title.  As outlined above, I don't think this is something we want to support ATM
