### ISSUE TITLE
propsoal: support sharedinformer cache reader

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/controller-runtime#977]
the cache reader  contains structured and unstructured  InformersMap, assuming this case:
1.  client.Get(ctx, key, obj), obj is structured
2. client.Get(ctx, key, unstructuredObj), unstructuredObj contains the same gvk with obj in case 1.

then the InformersMap will start two informers separately  in structured and unstructured  InformersMap, which is reductant and would cause memory usage problem if the informer cache is big.

so i propose  the implementation of a sharedinformer, `shared` means structured and unstructured shared the same informerMap.

one thing need to care is in cache_reader.go[L80](https://github.com/kubernetes-sigs/controller-runtime/blob/587ca7c550ef21706453ea71793c1b26d5666836/pkg/cache/internal/cache_reader.go#L80), if  objVal is not AssignableTo the outVal, we try use the `runtime.DefaultUnstructuredConverter` to do the convention.

**Comment by xrmzju** [comment]
@DirectXMan12  what do you think? i've done a internal version of this, if you like, i would like to share it to the community

**Comment by DirectXMan12** [comment]
`client.Get` against unstructured doesn't create an informer when using the manager's default client.

My other initial thought is that there are slightly different semantics between "fetch as structured, convert to unstructured" and "fetch as unstructured", since you'll lose fields in the former.

**Comment by xrmzju** [comment]
> `client.Get` against unstructured doesn't create an informer when using the manager's default client.
the default client read directly from server, the `client` here i mean client use cache reader.

> My other initial thought is that there are slightly different semantics between "fetch as structured, convert to unstructured" and "fetch as unstructured", since you'll lose fields in the former.

lose fields may be a problem between the conversion,  but i've not met it so far..

**Comment by xrmzju** [comment]
the main thoughts is to save the memory

**Comment by wondywang** [comment]
Hi @xrmzju, I am more interested in your design. Can you make your project public so I can take a look?
