### ISSUE TITLE
add indexersByGVK  to specificInformersMap

### ISSUE THREAD

**Issue by xrmzju** [kubernetes-sigs/controller-runtime#978]
assuming this case, a client uses cacheReader as it's reader, client is used as following:
1. c.Get(ctx, key, resourceA) 
2. c.List(ctx,resourceBList, client.MatchingFields{xxxx})

usage 1 is a func would be called in every reconcile loop. usage 2 is  a rare usage, but it is heavy, so we do not want to send directly to the sever but use the cache.

in order to do list with field selector, i need to add indexers to the underlying informer of resources B before the whole Informers  calls the Start function.  but in [IndexField](https://github.com/kubernetes-sigs/controller-runtime/blob/587ca7c550ef21706453ea71793c1b26d5666836/pkg/client/interfaces.go#L125) implementation, if we call the `IndexField` method, it will add a informer to the informerMap, and the informer will start when the cache start to run. there is no way to define i need to add a indexer to the a specific informer and i want to start the informer when i call `get` or `list` method

proposal:
1.  add a map field in `specificInformersMap` to store indexers 
```go
	// indexersByGVK is the informer Indexers keyed by groupVersionKind
	indexersByGVK map[schema.GroupVersionKind]cache.Indexers
``` 
2.  implement a method AddIndexers
```
func (ip *specificInformersMap) AddIndexers(gvk schema.GroupVersionKind, new cache.Indexers) {
	ip.mu.Lock()
	defer ip.mu.Unlock()

	old, exist := ip.indexersByGVK[gvk]
	if !exist {
		old = make(cache.Indexers)
	}
	for name, indexFunc := range new {
		old[name] = indexFunc
	}
	ip.indexersByGVK[gvk] = old
}
```
3. when try to add informers to map, read from the map and pass it to the sharedindexinformer
```go
	indexers, exist := ip.indexersByGVK[gvk]
	if !exist {
		indexers = make(cache.Indexers)
	}
	indexers[cache.NamespaceIndex] = cache.MetaNamespaceIndexFunc
	ip.indexersByGVK[gvk] = indexers
	ni := cache.NewSharedIndexInformer(lw, obj, ip.resync, indexers)
	i := &MapEntry{
		Informer: ni,
		Reader:   CacheReader{indexer: ni.GetIndexer(), groupVersionKind: gvk},
	}
```

**Comment by xrmzju** [comment]
@DirectXMan12

**Comment by DirectXMan12** [comment]
I'm sorry, I'm not quite following what the problem is here -- if you don't start the given cache till you call "list", you'll end up with a large delay on your first list, and then the same behavior as if you'd called `IndexField` for the rest of the lifetime of the program.  How does this help?  What's the condition that you're hitting here that's causing issues?

**Comment by DirectXMan12** [comment]
no response from issue filer, closing
