### ISSUE TITLE
Client.Get CRD meta can not get TypeMeta

### ISSUE THREAD

**Issue by allenhaozi** [kubernetes-sigs/controller-runtime#980]
use client Get My CRD struct , but can not get Kind and APIVersion
```
var comp v1.CRD	
err := Client.Get(context.Background(), ns, &comp)
```
got:
```
(v1.TypeMeta) &TypeMeta{Kind:,APIVersion:,}
```
hope:
```
(v1.TypeMeta) &TypeMeta{Kind:CRD,APIVersion:k8s.dev/v1,}

```

**Comment by cscetbon** [comment]
@allenhaozi do you get empty annotations on your object cause it is what I see in `ObjectMeta`. I wonder if my issue relates to yours

**Comment by vincepri** [comment]
Have you registered the type in the Client's Scheme?

/milestone Next
/priority awaiting-more-evidence
/triage support
