### ISSUE TITLE
cannot update to any recent controller-runtime release (gnostic dep problem)

### ISSUE THREAD

**Issue by jaypipes** [kubernetes-sigs/controller-runtime#994]
I wanted to use some new functions in `controller-runtime/pkg/controller/controllerutil` so I did a:

```
go get -u sigs.k8s.io/controller-runtime@v0.5.5
```

Unfortunately, this fails with the following:

```
../../../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.4.2), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```

I tried pretty much all releases for the last few months but all the same.

**Comment by vincepri** [comment]
@jaypipes Have you solved this issue? You should be able to update by matching the upstream dependencies versions with https://github.com/kubernetes-sigs/controller-runtime/blob/master/go.mod#L28-L31

**Comment by jaypipes** [comment]
@vincepri haven't taken a look at it since June. Will try again shortly. Thanks for checking in!
